/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.gt.dk.dao.nghiepvu.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import vn.dtt.gt.dk.dao.nghiepvu.model.VehicleGroupSpec;
import vn.dtt.gt.dk.dao.nghiepvu.model.VehicleGroupSpecModel;
import vn.dtt.gt.dk.dao.nghiepvu.model.VehicleGroupSpecSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the VehicleGroupSpec service. Represents a row in the &quot;vr_vehiclegroupspec&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link vn.dtt.gt.dk.dao.nghiepvu.model.VehicleGroupSpecModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link VehicleGroupSpecImpl}.
 * </p>
 *
 * @author win_64
 * @see VehicleGroupSpecImpl
 * @see vn.dtt.gt.dk.dao.nghiepvu.model.VehicleGroupSpec
 * @see vn.dtt.gt.dk.dao.nghiepvu.model.VehicleGroupSpecModel
 * @generated
 */
@JSON(strict = true)
public class VehicleGroupSpecModelImpl extends BaseModelImpl<VehicleGroupSpec>
	implements VehicleGroupSpecModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a vehicle group spec model instance should use the {@link vn.dtt.gt.dk.dao.nghiepvu.model.VehicleGroupSpec} interface instead.
	 */
	public static final String TABLE_NAME = "vr_vehiclegroupspec";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id", Types.BIGINT },
			{ "vehiclegroupid", Types.BIGINT },
			{ "specificationcode", Types.VARCHAR },
			{ "specificationname", Types.VARCHAR },
			{ "specificationvalue", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table vr_vehiclegroupspec (id LONG not null primary key,vehiclegroupid LONG,specificationcode VARCHAR(75) null,specificationname VARCHAR(75) null,specificationvalue VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table vr_vehiclegroupspec";
	public static final String ORDER_BY_JPQL = " ORDER BY vehicleGroupSpec.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY vr_vehiclegroupspec.id ASC";
	public static final String DATA_SOURCE = "vrDataSource";
	public static final String SESSION_FACTORY = "vrSessionFactory";
	public static final String TX_MANAGER = "vrTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.vn.dtt.gt.dk.dao.nghiepvu.model.VehicleGroupSpec"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.vn.dtt.gt.dk.dao.nghiepvu.model.VehicleGroupSpec"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static VehicleGroupSpec toModel(VehicleGroupSpecSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		VehicleGroupSpec model = new VehicleGroupSpecImpl();

		model.setId(soapModel.getId());
		model.setVehicleGroupId(soapModel.getVehicleGroupId());
		model.setSpecificationCode(soapModel.getSpecificationCode());
		model.setSpecificationName(soapModel.getSpecificationName());
		model.setSpecificationValue(soapModel.getSpecificationValue());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<VehicleGroupSpec> toModels(
		VehicleGroupSpecSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<VehicleGroupSpec> models = new ArrayList<VehicleGroupSpec>(soapModels.length);

		for (VehicleGroupSpecSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.vn.dtt.gt.dk.dao.nghiepvu.model.VehicleGroupSpec"));

	public VehicleGroupSpecModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return VehicleGroupSpec.class;
	}

	@Override
	public String getModelClassName() {
		return VehicleGroupSpec.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("vehicleGroupId", getVehicleGroupId());
		attributes.put("specificationCode", getSpecificationCode());
		attributes.put("specificationName", getSpecificationName());
		attributes.put("specificationValue", getSpecificationValue());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id = (Long)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		Long vehicleGroupId = (Long)attributes.get("vehicleGroupId");

		if (vehicleGroupId != null) {
			setVehicleGroupId(vehicleGroupId);
		}

		String specificationCode = (String)attributes.get("specificationCode");

		if (specificationCode != null) {
			setSpecificationCode(specificationCode);
		}

		String specificationName = (String)attributes.get("specificationName");

		if (specificationName != null) {
			setSpecificationName(specificationName);
		}

		String specificationValue = (String)attributes.get("specificationValue");

		if (specificationValue != null) {
			setSpecificationValue(specificationValue);
		}
	}

	@JSON
	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		_id = id;
	}

	@JSON
	@Override
	public long getVehicleGroupId() {
		return _vehicleGroupId;
	}

	@Override
	public void setVehicleGroupId(long vehicleGroupId) {
		_vehicleGroupId = vehicleGroupId;
	}

	@JSON
	@Override
	public String getSpecificationCode() {
		if (_specificationCode == null) {
			return StringPool.BLANK;
		}
		else {
			return _specificationCode;
		}
	}

	@Override
	public void setSpecificationCode(String specificationCode) {
		_specificationCode = specificationCode;
	}

	@JSON
	@Override
	public String getSpecificationName() {
		if (_specificationName == null) {
			return StringPool.BLANK;
		}
		else {
			return _specificationName;
		}
	}

	@Override
	public void setSpecificationName(String specificationName) {
		_specificationName = specificationName;
	}

	@JSON
	@Override
	public String getSpecificationValue() {
		if (_specificationValue == null) {
			return StringPool.BLANK;
		}
		else {
			return _specificationValue;
		}
	}

	@Override
	public void setSpecificationValue(String specificationValue) {
		_specificationValue = specificationValue;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			VehicleGroupSpec.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public VehicleGroupSpec toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (VehicleGroupSpec)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		VehicleGroupSpecImpl vehicleGroupSpecImpl = new VehicleGroupSpecImpl();

		vehicleGroupSpecImpl.setId(getId());
		vehicleGroupSpecImpl.setVehicleGroupId(getVehicleGroupId());
		vehicleGroupSpecImpl.setSpecificationCode(getSpecificationCode());
		vehicleGroupSpecImpl.setSpecificationName(getSpecificationName());
		vehicleGroupSpecImpl.setSpecificationValue(getSpecificationValue());

		vehicleGroupSpecImpl.resetOriginalValues();

		return vehicleGroupSpecImpl;
	}

	@Override
	public int compareTo(VehicleGroupSpec vehicleGroupSpec) {
		int value = 0;

		if (getId() < vehicleGroupSpec.getId()) {
			value = -1;
		}
		else if (getId() > vehicleGroupSpec.getId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof VehicleGroupSpec)) {
			return false;
		}

		VehicleGroupSpec vehicleGroupSpec = (VehicleGroupSpec)obj;

		long primaryKey = vehicleGroupSpec.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<VehicleGroupSpec> toCacheModel() {
		VehicleGroupSpecCacheModel vehicleGroupSpecCacheModel = new VehicleGroupSpecCacheModel();

		vehicleGroupSpecCacheModel.id = getId();

		vehicleGroupSpecCacheModel.vehicleGroupId = getVehicleGroupId();

		vehicleGroupSpecCacheModel.specificationCode = getSpecificationCode();

		String specificationCode = vehicleGroupSpecCacheModel.specificationCode;

		if ((specificationCode != null) && (specificationCode.length() == 0)) {
			vehicleGroupSpecCacheModel.specificationCode = null;
		}

		vehicleGroupSpecCacheModel.specificationName = getSpecificationName();

		String specificationName = vehicleGroupSpecCacheModel.specificationName;

		if ((specificationName != null) && (specificationName.length() == 0)) {
			vehicleGroupSpecCacheModel.specificationName = null;
		}

		vehicleGroupSpecCacheModel.specificationValue = getSpecificationValue();

		String specificationValue = vehicleGroupSpecCacheModel.specificationValue;

		if ((specificationValue != null) && (specificationValue.length() == 0)) {
			vehicleGroupSpecCacheModel.specificationValue = null;
		}

		return vehicleGroupSpecCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(11);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", vehicleGroupId=");
		sb.append(getVehicleGroupId());
		sb.append(", specificationCode=");
		sb.append(getSpecificationCode());
		sb.append(", specificationName=");
		sb.append(getSpecificationName());
		sb.append(", specificationValue=");
		sb.append(getSpecificationValue());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(19);

		sb.append("<model><model-name>");
		sb.append("vn.dtt.gt.dk.dao.nghiepvu.model.VehicleGroupSpec");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>vehicleGroupId</column-name><column-value><![CDATA[");
		sb.append(getVehicleGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>specificationCode</column-name><column-value><![CDATA[");
		sb.append(getSpecificationCode());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>specificationName</column-name><column-value><![CDATA[");
		sb.append(getSpecificationName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>specificationValue</column-name><column-value><![CDATA[");
		sb.append(getSpecificationValue());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = VehicleGroupSpec.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			VehicleGroupSpec.class
		};
	private long _id;
	private long _vehicleGroupId;
	private String _specificationCode;
	private String _specificationName;
	private String _specificationValue;
	private VehicleGroupSpec _escapedModel;
}