/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.gt.dk.dao.nghiepvu.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import vn.dtt.gt.dk.dao.nghiepvu.model.ViewDangKiemTimKiem;
import vn.dtt.gt.dk.dao.nghiepvu.model.ViewDangKiemTimKiemModel;
import vn.dtt.gt.dk.dao.nghiepvu.model.ViewDangKiemTimKiemSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the ViewDangKiemTimKiem service. Represents a row in the &quot;view_dangkiemtimkiem&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link vn.dtt.gt.dk.dao.nghiepvu.model.ViewDangKiemTimKiemModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ViewDangKiemTimKiemImpl}.
 * </p>
 *
 * @author win_64
 * @see ViewDangKiemTimKiemImpl
 * @see vn.dtt.gt.dk.dao.nghiepvu.model.ViewDangKiemTimKiem
 * @see vn.dtt.gt.dk.dao.nghiepvu.model.ViewDangKiemTimKiemModel
 * @generated
 */
@JSON(strict = true)
public class ViewDangKiemTimKiemModelImpl extends BaseModelImpl<ViewDangKiemTimKiem>
	implements ViewDangKiemTimKiemModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a view dang kiem tim kiem model instance should use the {@link vn.dtt.gt.dk.dao.nghiepvu.model.ViewDangKiemTimKiem} interface instead.
	 */
	public static final String TABLE_NAME = "view_dangkiemtimkiem";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id", Types.BIGINT },
			{ "vehiclegroupid", Types.BIGINT },
			{ "debitnoteid", Types.BIGINT },
			{ "sequenceno", Types.BIGINT },
			{ "codenumber", Types.BIGINT },
			{ "chassisnumber", Types.VARCHAR },
			{ "enginenumber", Types.VARCHAR },
			{ "productionyear", Types.BIGINT },
			{ "vehicleenginestatus", Types.VARCHAR },
			{ "vehiclecolor", Types.VARCHAR },
			{ "unitprice", Types.DOUBLE },
			{ "currency", Types.VARCHAR },
			{ "remarks", Types.VARCHAR },
			{ "confirmedinspectionid", Types.BIGINT },
			{ "inspectionrecordid", Types.BIGINT },
			{ "draftcertificateid", Types.BIGINT },
			{ "certificaterecordid", Types.BIGINT },
			{ "markupstatus", Types.BIGINT },
			{ "safetestrequirementid", Types.BIGINT },
			{ "emissiontestrequirementid", Types.BIGINT },
			{ "controlrequirementid", Types.BIGINT },
			{ "MarkAsSample", Types.INTEGER },
			{ "inspectionrecordno", Types.VARCHAR },
			{ "inspectionrecorddate", Types.TIMESTAMP },
			{ "attachedfilebbkt", Types.BIGINT },
			{ "certificatenumber", Types.VARCHAR },
			{ "signdate", Types.TIMESTAMP },
			{ "attachedfile", Types.BIGINT },
			{ "registerednumber", Types.VARCHAR },
			{ "inspectorsigndate", Types.TIMESTAMP },
			{ "vehicleclass", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table view_dangkiemtimkiem (id LONG not null primary key,vehiclegroupid LONG,debitnoteid LONG,sequenceno LONG,codenumber LONG,chassisnumber VARCHAR(75) null,enginenumber VARCHAR(75) null,productionyear LONG,vehicleenginestatus VARCHAR(75) null,vehiclecolor VARCHAR(75) null,unitprice DOUBLE,currency VARCHAR(75) null,remarks VARCHAR(75) null,confirmedinspectionid LONG,inspectionrecordid LONG,draftcertificateid LONG,certificaterecordid LONG,markupstatus LONG,safetestrequirementid LONG,emissiontestrequirementid LONG,controlrequirementid LONG,MarkAsSample INTEGER,inspectionrecordno VARCHAR(75) null,inspectionrecorddate DATE null,attachedfilebbkt LONG,certificatenumber VARCHAR(75) null,signdate DATE null,attachedfile LONG,registerednumber VARCHAR(75) null,inspectorsigndate DATE null,vehicleclass VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table view_dangkiemtimkiem";
	public static final String ORDER_BY_JPQL = " ORDER BY viewDangKiemTimKiem.id DESC";
	public static final String ORDER_BY_SQL = " ORDER BY view_dangkiemtimkiem.id DESC";
	public static final String DATA_SOURCE = "vrDataSource";
	public static final String SESSION_FACTORY = "vrSessionFactory";
	public static final String TX_MANAGER = "vrTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.vn.dtt.gt.dk.dao.nghiepvu.model.ViewDangKiemTimKiem"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.vn.dtt.gt.dk.dao.nghiepvu.model.ViewDangKiemTimKiem"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static ViewDangKiemTimKiem toModel(ViewDangKiemTimKiemSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		ViewDangKiemTimKiem model = new ViewDangKiemTimKiemImpl();

		model.setId(soapModel.getId());
		model.setVehicleGroupId(soapModel.getVehicleGroupId());
		model.setDebitNoteId(soapModel.getDebitNoteId());
		model.setSequenceNo(soapModel.getSequenceNo());
		model.setCodeNumber(soapModel.getCodeNumber());
		model.setChassisNumber(soapModel.getChassisNumber());
		model.setEngineNumber(soapModel.getEngineNumber());
		model.setProductionYear(soapModel.getProductionYear());
		model.setVehicleEngineStatus(soapModel.getVehicleEngineStatus());
		model.setVehicleColor(soapModel.getVehicleColor());
		model.setUnitPrice(soapModel.getUnitPrice());
		model.setCurrency(soapModel.getCurrency());
		model.setRemarks(soapModel.getRemarks());
		model.setConfirmedInspectionId(soapModel.getConfirmedInspectionId());
		model.setInspectionRecordId(soapModel.getInspectionRecordId());
		model.setDraftCertificateId(soapModel.getDraftCertificateId());
		model.setCertificateRecordId(soapModel.getCertificateRecordId());
		model.setMarkUpStatus(soapModel.getMarkUpStatus());
		model.setSafeTestRequirementId(soapModel.getSafeTestRequirementId());
		model.setEmissionTestRequirementId(soapModel.getEmissionTestRequirementId());
		model.setControlRequirementId(soapModel.getControlRequirementId());
		model.setMarkAsSample(soapModel.getMarkAsSample());
		model.setInspectionrecordno(soapModel.getInspectionrecordno());
		model.setInspectionRecordDate(soapModel.getInspectionRecordDate());
		model.setAttachedFileBbkt(soapModel.getAttachedFileBbkt());
		model.setCertificateNumber(soapModel.getCertificateNumber());
		model.setSignDate(soapModel.getSignDate());
		model.setAttachedFile(soapModel.getAttachedFile());
		model.setRegisteredNumber(soapModel.getRegisteredNumber());
		model.setInspectorSignDate(soapModel.getInspectorSignDate());
		model.setVehicleClass(soapModel.getVehicleClass());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<ViewDangKiemTimKiem> toModels(
		ViewDangKiemTimKiemSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<ViewDangKiemTimKiem> models = new ArrayList<ViewDangKiemTimKiem>(soapModels.length);

		for (ViewDangKiemTimKiemSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.vn.dtt.gt.dk.dao.nghiepvu.model.ViewDangKiemTimKiem"));

	public ViewDangKiemTimKiemModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ViewDangKiemTimKiem.class;
	}

	@Override
	public String getModelClassName() {
		return ViewDangKiemTimKiem.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("vehicleGroupId", getVehicleGroupId());
		attributes.put("debitNoteId", getDebitNoteId());
		attributes.put("sequenceNo", getSequenceNo());
		attributes.put("codeNumber", getCodeNumber());
		attributes.put("chassisNumber", getChassisNumber());
		attributes.put("engineNumber", getEngineNumber());
		attributes.put("productionYear", getProductionYear());
		attributes.put("vehicleEngineStatus", getVehicleEngineStatus());
		attributes.put("vehicleColor", getVehicleColor());
		attributes.put("unitPrice", getUnitPrice());
		attributes.put("currency", getCurrency());
		attributes.put("remarks", getRemarks());
		attributes.put("confirmedInspectionId", getConfirmedInspectionId());
		attributes.put("inspectionRecordId", getInspectionRecordId());
		attributes.put("draftCertificateId", getDraftCertificateId());
		attributes.put("certificateRecordId", getCertificateRecordId());
		attributes.put("markUpStatus", getMarkUpStatus());
		attributes.put("safeTestRequirementId", getSafeTestRequirementId());
		attributes.put("emissionTestRequirementId",
			getEmissionTestRequirementId());
		attributes.put("controlRequirementId", getControlRequirementId());
		attributes.put("markAsSample", getMarkAsSample());
		attributes.put("inspectionrecordno", getInspectionrecordno());
		attributes.put("inspectionRecordDate", getInspectionRecordDate());
		attributes.put("attachedFileBbkt", getAttachedFileBbkt());
		attributes.put("certificateNumber", getCertificateNumber());
		attributes.put("signDate", getSignDate());
		attributes.put("attachedFile", getAttachedFile());
		attributes.put("registeredNumber", getRegisteredNumber());
		attributes.put("inspectorSignDate", getInspectorSignDate());
		attributes.put("vehicleClass", getVehicleClass());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id = (Long)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		Long vehicleGroupId = (Long)attributes.get("vehicleGroupId");

		if (vehicleGroupId != null) {
			setVehicleGroupId(vehicleGroupId);
		}

		Long debitNoteId = (Long)attributes.get("debitNoteId");

		if (debitNoteId != null) {
			setDebitNoteId(debitNoteId);
		}

		Long sequenceNo = (Long)attributes.get("sequenceNo");

		if (sequenceNo != null) {
			setSequenceNo(sequenceNo);
		}

		Long codeNumber = (Long)attributes.get("codeNumber");

		if (codeNumber != null) {
			setCodeNumber(codeNumber);
		}

		String chassisNumber = (String)attributes.get("chassisNumber");

		if (chassisNumber != null) {
			setChassisNumber(chassisNumber);
		}

		String engineNumber = (String)attributes.get("engineNumber");

		if (engineNumber != null) {
			setEngineNumber(engineNumber);
		}

		Long productionYear = (Long)attributes.get("productionYear");

		if (productionYear != null) {
			setProductionYear(productionYear);
		}

		String vehicleEngineStatus = (String)attributes.get(
				"vehicleEngineStatus");

		if (vehicleEngineStatus != null) {
			setVehicleEngineStatus(vehicleEngineStatus);
		}

		String vehicleColor = (String)attributes.get("vehicleColor");

		if (vehicleColor != null) {
			setVehicleColor(vehicleColor);
		}

		Double unitPrice = (Double)attributes.get("unitPrice");

		if (unitPrice != null) {
			setUnitPrice(unitPrice);
		}

		String currency = (String)attributes.get("currency");

		if (currency != null) {
			setCurrency(currency);
		}

		String remarks = (String)attributes.get("remarks");

		if (remarks != null) {
			setRemarks(remarks);
		}

		Long confirmedInspectionId = (Long)attributes.get(
				"confirmedInspectionId");

		if (confirmedInspectionId != null) {
			setConfirmedInspectionId(confirmedInspectionId);
		}

		Long inspectionRecordId = (Long)attributes.get("inspectionRecordId");

		if (inspectionRecordId != null) {
			setInspectionRecordId(inspectionRecordId);
		}

		Long draftCertificateId = (Long)attributes.get("draftCertificateId");

		if (draftCertificateId != null) {
			setDraftCertificateId(draftCertificateId);
		}

		Long certificateRecordId = (Long)attributes.get("certificateRecordId");

		if (certificateRecordId != null) {
			setCertificateRecordId(certificateRecordId);
		}

		Long markUpStatus = (Long)attributes.get("markUpStatus");

		if (markUpStatus != null) {
			setMarkUpStatus(markUpStatus);
		}

		Long safeTestRequirementId = (Long)attributes.get(
				"safeTestRequirementId");

		if (safeTestRequirementId != null) {
			setSafeTestRequirementId(safeTestRequirementId);
		}

		Long emissionTestRequirementId = (Long)attributes.get(
				"emissionTestRequirementId");

		if (emissionTestRequirementId != null) {
			setEmissionTestRequirementId(emissionTestRequirementId);
		}

		Long controlRequirementId = (Long)attributes.get("controlRequirementId");

		if (controlRequirementId != null) {
			setControlRequirementId(controlRequirementId);
		}

		Integer markAsSample = (Integer)attributes.get("markAsSample");

		if (markAsSample != null) {
			setMarkAsSample(markAsSample);
		}

		String inspectionrecordno = (String)attributes.get("inspectionrecordno");

		if (inspectionrecordno != null) {
			setInspectionrecordno(inspectionrecordno);
		}

		Date inspectionRecordDate = (Date)attributes.get("inspectionRecordDate");

		if (inspectionRecordDate != null) {
			setInspectionRecordDate(inspectionRecordDate);
		}

		Long attachedFileBbkt = (Long)attributes.get("attachedFileBbkt");

		if (attachedFileBbkt != null) {
			setAttachedFileBbkt(attachedFileBbkt);
		}

		String certificateNumber = (String)attributes.get("certificateNumber");

		if (certificateNumber != null) {
			setCertificateNumber(certificateNumber);
		}

		Date signDate = (Date)attributes.get("signDate");

		if (signDate != null) {
			setSignDate(signDate);
		}

		Long attachedFile = (Long)attributes.get("attachedFile");

		if (attachedFile != null) {
			setAttachedFile(attachedFile);
		}

		String registeredNumber = (String)attributes.get("registeredNumber");

		if (registeredNumber != null) {
			setRegisteredNumber(registeredNumber);
		}

		Date inspectorSignDate = (Date)attributes.get("inspectorSignDate");

		if (inspectorSignDate != null) {
			setInspectorSignDate(inspectorSignDate);
		}

		String vehicleClass = (String)attributes.get("vehicleClass");

		if (vehicleClass != null) {
			setVehicleClass(vehicleClass);
		}
	}

	@JSON
	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		_id = id;
	}

	@JSON
	@Override
	public long getVehicleGroupId() {
		return _vehicleGroupId;
	}

	@Override
	public void setVehicleGroupId(long vehicleGroupId) {
		_vehicleGroupId = vehicleGroupId;
	}

	@JSON
	@Override
	public long getDebitNoteId() {
		return _debitNoteId;
	}

	@Override
	public void setDebitNoteId(long debitNoteId) {
		_debitNoteId = debitNoteId;
	}

	@JSON
	@Override
	public long getSequenceNo() {
		return _sequenceNo;
	}

	@Override
	public void setSequenceNo(long sequenceNo) {
		_sequenceNo = sequenceNo;
	}

	@JSON
	@Override
	public long getCodeNumber() {
		return _codeNumber;
	}

	@Override
	public void setCodeNumber(long codeNumber) {
		_codeNumber = codeNumber;
	}

	@JSON
	@Override
	public String getChassisNumber() {
		if (_chassisNumber == null) {
			return StringPool.BLANK;
		}
		else {
			return _chassisNumber;
		}
	}

	@Override
	public void setChassisNumber(String chassisNumber) {
		_chassisNumber = chassisNumber;
	}

	@JSON
	@Override
	public String getEngineNumber() {
		if (_engineNumber == null) {
			return StringPool.BLANK;
		}
		else {
			return _engineNumber;
		}
	}

	@Override
	public void setEngineNumber(String engineNumber) {
		_engineNumber = engineNumber;
	}

	@JSON
	@Override
	public long getProductionYear() {
		return _productionYear;
	}

	@Override
	public void setProductionYear(long productionYear) {
		_productionYear = productionYear;
	}

	@JSON
	@Override
	public String getVehicleEngineStatus() {
		if (_vehicleEngineStatus == null) {
			return StringPool.BLANK;
		}
		else {
			return _vehicleEngineStatus;
		}
	}

	@Override
	public void setVehicleEngineStatus(String vehicleEngineStatus) {
		_vehicleEngineStatus = vehicleEngineStatus;
	}

	@JSON
	@Override
	public String getVehicleColor() {
		if (_vehicleColor == null) {
			return StringPool.BLANK;
		}
		else {
			return _vehicleColor;
		}
	}

	@Override
	public void setVehicleColor(String vehicleColor) {
		_vehicleColor = vehicleColor;
	}

	@JSON
	@Override
	public double getUnitPrice() {
		return _unitPrice;
	}

	@Override
	public void setUnitPrice(double unitPrice) {
		_unitPrice = unitPrice;
	}

	@JSON
	@Override
	public String getCurrency() {
		if (_currency == null) {
			return StringPool.BLANK;
		}
		else {
			return _currency;
		}
	}

	@Override
	public void setCurrency(String currency) {
		_currency = currency;
	}

	@JSON
	@Override
	public String getRemarks() {
		if (_remarks == null) {
			return StringPool.BLANK;
		}
		else {
			return _remarks;
		}
	}

	@Override
	public void setRemarks(String remarks) {
		_remarks = remarks;
	}

	@JSON
	@Override
	public long getConfirmedInspectionId() {
		return _confirmedInspectionId;
	}

	@Override
	public void setConfirmedInspectionId(long confirmedInspectionId) {
		_confirmedInspectionId = confirmedInspectionId;
	}

	@JSON
	@Override
	public long getInspectionRecordId() {
		return _inspectionRecordId;
	}

	@Override
	public void setInspectionRecordId(long inspectionRecordId) {
		_inspectionRecordId = inspectionRecordId;
	}

	@JSON
	@Override
	public long getDraftCertificateId() {
		return _draftCertificateId;
	}

	@Override
	public void setDraftCertificateId(long draftCertificateId) {
		_draftCertificateId = draftCertificateId;
	}

	@JSON
	@Override
	public long getCertificateRecordId() {
		return _certificateRecordId;
	}

	@Override
	public void setCertificateRecordId(long certificateRecordId) {
		_certificateRecordId = certificateRecordId;
	}

	@JSON
	@Override
	public long getMarkUpStatus() {
		return _markUpStatus;
	}

	@Override
	public void setMarkUpStatus(long markUpStatus) {
		_markUpStatus = markUpStatus;
	}

	@JSON
	@Override
	public long getSafeTestRequirementId() {
		return _safeTestRequirementId;
	}

	@Override
	public void setSafeTestRequirementId(long safeTestRequirementId) {
		_safeTestRequirementId = safeTestRequirementId;
	}

	@JSON
	@Override
	public long getEmissionTestRequirementId() {
		return _emissionTestRequirementId;
	}

	@Override
	public void setEmissionTestRequirementId(long emissionTestRequirementId) {
		_emissionTestRequirementId = emissionTestRequirementId;
	}

	@JSON
	@Override
	public long getControlRequirementId() {
		return _controlRequirementId;
	}

	@Override
	public void setControlRequirementId(long controlRequirementId) {
		_controlRequirementId = controlRequirementId;
	}

	@JSON
	@Override
	public int getMarkAsSample() {
		return _markAsSample;
	}

	@Override
	public void setMarkAsSample(int markAsSample) {
		_markAsSample = markAsSample;
	}

	@JSON
	@Override
	public String getInspectionrecordno() {
		if (_inspectionrecordno == null) {
			return StringPool.BLANK;
		}
		else {
			return _inspectionrecordno;
		}
	}

	@Override
	public void setInspectionrecordno(String inspectionrecordno) {
		_inspectionrecordno = inspectionrecordno;
	}

	@JSON
	@Override
	public Date getInspectionRecordDate() {
		return _inspectionRecordDate;
	}

	@Override
	public void setInspectionRecordDate(Date inspectionRecordDate) {
		_inspectionRecordDate = inspectionRecordDate;
	}

	@JSON
	@Override
	public long getAttachedFileBbkt() {
		return _attachedFileBbkt;
	}

	@Override
	public void setAttachedFileBbkt(long attachedFileBbkt) {
		_attachedFileBbkt = attachedFileBbkt;
	}

	@JSON
	@Override
	public String getCertificateNumber() {
		if (_certificateNumber == null) {
			return StringPool.BLANK;
		}
		else {
			return _certificateNumber;
		}
	}

	@Override
	public void setCertificateNumber(String certificateNumber) {
		_certificateNumber = certificateNumber;
	}

	@JSON
	@Override
	public Date getSignDate() {
		return _signDate;
	}

	@Override
	public void setSignDate(Date signDate) {
		_signDate = signDate;
	}

	@JSON
	@Override
	public long getAttachedFile() {
		return _attachedFile;
	}

	@Override
	public void setAttachedFile(long attachedFile) {
		_attachedFile = attachedFile;
	}

	@JSON
	@Override
	public String getRegisteredNumber() {
		if (_registeredNumber == null) {
			return StringPool.BLANK;
		}
		else {
			return _registeredNumber;
		}
	}

	@Override
	public void setRegisteredNumber(String registeredNumber) {
		_registeredNumber = registeredNumber;
	}

	@JSON
	@Override
	public Date getInspectorSignDate() {
		return _inspectorSignDate;
	}

	@Override
	public void setInspectorSignDate(Date inspectorSignDate) {
		_inspectorSignDate = inspectorSignDate;
	}

	@JSON
	@Override
	public String getVehicleClass() {
		if (_vehicleClass == null) {
			return StringPool.BLANK;
		}
		else {
			return _vehicleClass;
		}
	}

	@Override
	public void setVehicleClass(String vehicleClass) {
		_vehicleClass = vehicleClass;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			ViewDangKiemTimKiem.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ViewDangKiemTimKiem toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (ViewDangKiemTimKiem)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ViewDangKiemTimKiemImpl viewDangKiemTimKiemImpl = new ViewDangKiemTimKiemImpl();

		viewDangKiemTimKiemImpl.setId(getId());
		viewDangKiemTimKiemImpl.setVehicleGroupId(getVehicleGroupId());
		viewDangKiemTimKiemImpl.setDebitNoteId(getDebitNoteId());
		viewDangKiemTimKiemImpl.setSequenceNo(getSequenceNo());
		viewDangKiemTimKiemImpl.setCodeNumber(getCodeNumber());
		viewDangKiemTimKiemImpl.setChassisNumber(getChassisNumber());
		viewDangKiemTimKiemImpl.setEngineNumber(getEngineNumber());
		viewDangKiemTimKiemImpl.setProductionYear(getProductionYear());
		viewDangKiemTimKiemImpl.setVehicleEngineStatus(getVehicleEngineStatus());
		viewDangKiemTimKiemImpl.setVehicleColor(getVehicleColor());
		viewDangKiemTimKiemImpl.setUnitPrice(getUnitPrice());
		viewDangKiemTimKiemImpl.setCurrency(getCurrency());
		viewDangKiemTimKiemImpl.setRemarks(getRemarks());
		viewDangKiemTimKiemImpl.setConfirmedInspectionId(getConfirmedInspectionId());
		viewDangKiemTimKiemImpl.setInspectionRecordId(getInspectionRecordId());
		viewDangKiemTimKiemImpl.setDraftCertificateId(getDraftCertificateId());
		viewDangKiemTimKiemImpl.setCertificateRecordId(getCertificateRecordId());
		viewDangKiemTimKiemImpl.setMarkUpStatus(getMarkUpStatus());
		viewDangKiemTimKiemImpl.setSafeTestRequirementId(getSafeTestRequirementId());
		viewDangKiemTimKiemImpl.setEmissionTestRequirementId(getEmissionTestRequirementId());
		viewDangKiemTimKiemImpl.setControlRequirementId(getControlRequirementId());
		viewDangKiemTimKiemImpl.setMarkAsSample(getMarkAsSample());
		viewDangKiemTimKiemImpl.setInspectionrecordno(getInspectionrecordno());
		viewDangKiemTimKiemImpl.setInspectionRecordDate(getInspectionRecordDate());
		viewDangKiemTimKiemImpl.setAttachedFileBbkt(getAttachedFileBbkt());
		viewDangKiemTimKiemImpl.setCertificateNumber(getCertificateNumber());
		viewDangKiemTimKiemImpl.setSignDate(getSignDate());
		viewDangKiemTimKiemImpl.setAttachedFile(getAttachedFile());
		viewDangKiemTimKiemImpl.setRegisteredNumber(getRegisteredNumber());
		viewDangKiemTimKiemImpl.setInspectorSignDate(getInspectorSignDate());
		viewDangKiemTimKiemImpl.setVehicleClass(getVehicleClass());

		viewDangKiemTimKiemImpl.resetOriginalValues();

		return viewDangKiemTimKiemImpl;
	}

	@Override
	public int compareTo(ViewDangKiemTimKiem viewDangKiemTimKiem) {
		int value = 0;

		if (getId() < viewDangKiemTimKiem.getId()) {
			value = -1;
		}
		else if (getId() > viewDangKiemTimKiem.getId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof ViewDangKiemTimKiem)) {
			return false;
		}

		ViewDangKiemTimKiem viewDangKiemTimKiem = (ViewDangKiemTimKiem)obj;

		long primaryKey = viewDangKiemTimKiem.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<ViewDangKiemTimKiem> toCacheModel() {
		ViewDangKiemTimKiemCacheModel viewDangKiemTimKiemCacheModel = new ViewDangKiemTimKiemCacheModel();

		viewDangKiemTimKiemCacheModel.id = getId();

		viewDangKiemTimKiemCacheModel.vehicleGroupId = getVehicleGroupId();

		viewDangKiemTimKiemCacheModel.debitNoteId = getDebitNoteId();

		viewDangKiemTimKiemCacheModel.sequenceNo = getSequenceNo();

		viewDangKiemTimKiemCacheModel.codeNumber = getCodeNumber();

		viewDangKiemTimKiemCacheModel.chassisNumber = getChassisNumber();

		String chassisNumber = viewDangKiemTimKiemCacheModel.chassisNumber;

		if ((chassisNumber != null) && (chassisNumber.length() == 0)) {
			viewDangKiemTimKiemCacheModel.chassisNumber = null;
		}

		viewDangKiemTimKiemCacheModel.engineNumber = getEngineNumber();

		String engineNumber = viewDangKiemTimKiemCacheModel.engineNumber;

		if ((engineNumber != null) && (engineNumber.length() == 0)) {
			viewDangKiemTimKiemCacheModel.engineNumber = null;
		}

		viewDangKiemTimKiemCacheModel.productionYear = getProductionYear();

		viewDangKiemTimKiemCacheModel.vehicleEngineStatus = getVehicleEngineStatus();

		String vehicleEngineStatus = viewDangKiemTimKiemCacheModel.vehicleEngineStatus;

		if ((vehicleEngineStatus != null) &&
				(vehicleEngineStatus.length() == 0)) {
			viewDangKiemTimKiemCacheModel.vehicleEngineStatus = null;
		}

		viewDangKiemTimKiemCacheModel.vehicleColor = getVehicleColor();

		String vehicleColor = viewDangKiemTimKiemCacheModel.vehicleColor;

		if ((vehicleColor != null) && (vehicleColor.length() == 0)) {
			viewDangKiemTimKiemCacheModel.vehicleColor = null;
		}

		viewDangKiemTimKiemCacheModel.unitPrice = getUnitPrice();

		viewDangKiemTimKiemCacheModel.currency = getCurrency();

		String currency = viewDangKiemTimKiemCacheModel.currency;

		if ((currency != null) && (currency.length() == 0)) {
			viewDangKiemTimKiemCacheModel.currency = null;
		}

		viewDangKiemTimKiemCacheModel.remarks = getRemarks();

		String remarks = viewDangKiemTimKiemCacheModel.remarks;

		if ((remarks != null) && (remarks.length() == 0)) {
			viewDangKiemTimKiemCacheModel.remarks = null;
		}

		viewDangKiemTimKiemCacheModel.confirmedInspectionId = getConfirmedInspectionId();

		viewDangKiemTimKiemCacheModel.inspectionRecordId = getInspectionRecordId();

		viewDangKiemTimKiemCacheModel.draftCertificateId = getDraftCertificateId();

		viewDangKiemTimKiemCacheModel.certificateRecordId = getCertificateRecordId();

		viewDangKiemTimKiemCacheModel.markUpStatus = getMarkUpStatus();

		viewDangKiemTimKiemCacheModel.safeTestRequirementId = getSafeTestRequirementId();

		viewDangKiemTimKiemCacheModel.emissionTestRequirementId = getEmissionTestRequirementId();

		viewDangKiemTimKiemCacheModel.controlRequirementId = getControlRequirementId();

		viewDangKiemTimKiemCacheModel.markAsSample = getMarkAsSample();

		viewDangKiemTimKiemCacheModel.inspectionrecordno = getInspectionrecordno();

		String inspectionrecordno = viewDangKiemTimKiemCacheModel.inspectionrecordno;

		if ((inspectionrecordno != null) && (inspectionrecordno.length() == 0)) {
			viewDangKiemTimKiemCacheModel.inspectionrecordno = null;
		}

		Date inspectionRecordDate = getInspectionRecordDate();

		if (inspectionRecordDate != null) {
			viewDangKiemTimKiemCacheModel.inspectionRecordDate = inspectionRecordDate.getTime();
		}
		else {
			viewDangKiemTimKiemCacheModel.inspectionRecordDate = Long.MIN_VALUE;
		}

		viewDangKiemTimKiemCacheModel.attachedFileBbkt = getAttachedFileBbkt();

		viewDangKiemTimKiemCacheModel.certificateNumber = getCertificateNumber();

		String certificateNumber = viewDangKiemTimKiemCacheModel.certificateNumber;

		if ((certificateNumber != null) && (certificateNumber.length() == 0)) {
			viewDangKiemTimKiemCacheModel.certificateNumber = null;
		}

		Date signDate = getSignDate();

		if (signDate != null) {
			viewDangKiemTimKiemCacheModel.signDate = signDate.getTime();
		}
		else {
			viewDangKiemTimKiemCacheModel.signDate = Long.MIN_VALUE;
		}

		viewDangKiemTimKiemCacheModel.attachedFile = getAttachedFile();

		viewDangKiemTimKiemCacheModel.registeredNumber = getRegisteredNumber();

		String registeredNumber = viewDangKiemTimKiemCacheModel.registeredNumber;

		if ((registeredNumber != null) && (registeredNumber.length() == 0)) {
			viewDangKiemTimKiemCacheModel.registeredNumber = null;
		}

		Date inspectorSignDate = getInspectorSignDate();

		if (inspectorSignDate != null) {
			viewDangKiemTimKiemCacheModel.inspectorSignDate = inspectorSignDate.getTime();
		}
		else {
			viewDangKiemTimKiemCacheModel.inspectorSignDate = Long.MIN_VALUE;
		}

		viewDangKiemTimKiemCacheModel.vehicleClass = getVehicleClass();

		String vehicleClass = viewDangKiemTimKiemCacheModel.vehicleClass;

		if ((vehicleClass != null) && (vehicleClass.length() == 0)) {
			viewDangKiemTimKiemCacheModel.vehicleClass = null;
		}

		return viewDangKiemTimKiemCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(63);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", vehicleGroupId=");
		sb.append(getVehicleGroupId());
		sb.append(", debitNoteId=");
		sb.append(getDebitNoteId());
		sb.append(", sequenceNo=");
		sb.append(getSequenceNo());
		sb.append(", codeNumber=");
		sb.append(getCodeNumber());
		sb.append(", chassisNumber=");
		sb.append(getChassisNumber());
		sb.append(", engineNumber=");
		sb.append(getEngineNumber());
		sb.append(", productionYear=");
		sb.append(getProductionYear());
		sb.append(", vehicleEngineStatus=");
		sb.append(getVehicleEngineStatus());
		sb.append(", vehicleColor=");
		sb.append(getVehicleColor());
		sb.append(", unitPrice=");
		sb.append(getUnitPrice());
		sb.append(", currency=");
		sb.append(getCurrency());
		sb.append(", remarks=");
		sb.append(getRemarks());
		sb.append(", confirmedInspectionId=");
		sb.append(getConfirmedInspectionId());
		sb.append(", inspectionRecordId=");
		sb.append(getInspectionRecordId());
		sb.append(", draftCertificateId=");
		sb.append(getDraftCertificateId());
		sb.append(", certificateRecordId=");
		sb.append(getCertificateRecordId());
		sb.append(", markUpStatus=");
		sb.append(getMarkUpStatus());
		sb.append(", safeTestRequirementId=");
		sb.append(getSafeTestRequirementId());
		sb.append(", emissionTestRequirementId=");
		sb.append(getEmissionTestRequirementId());
		sb.append(", controlRequirementId=");
		sb.append(getControlRequirementId());
		sb.append(", markAsSample=");
		sb.append(getMarkAsSample());
		sb.append(", inspectionrecordno=");
		sb.append(getInspectionrecordno());
		sb.append(", inspectionRecordDate=");
		sb.append(getInspectionRecordDate());
		sb.append(", attachedFileBbkt=");
		sb.append(getAttachedFileBbkt());
		sb.append(", certificateNumber=");
		sb.append(getCertificateNumber());
		sb.append(", signDate=");
		sb.append(getSignDate());
		sb.append(", attachedFile=");
		sb.append(getAttachedFile());
		sb.append(", registeredNumber=");
		sb.append(getRegisteredNumber());
		sb.append(", inspectorSignDate=");
		sb.append(getInspectorSignDate());
		sb.append(", vehicleClass=");
		sb.append(getVehicleClass());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(97);

		sb.append("<model><model-name>");
		sb.append("vn.dtt.gt.dk.dao.nghiepvu.model.ViewDangKiemTimKiem");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>vehicleGroupId</column-name><column-value><![CDATA[");
		sb.append(getVehicleGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>debitNoteId</column-name><column-value><![CDATA[");
		sb.append(getDebitNoteId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>sequenceNo</column-name><column-value><![CDATA[");
		sb.append(getSequenceNo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>codeNumber</column-name><column-value><![CDATA[");
		sb.append(getCodeNumber());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>chassisNumber</column-name><column-value><![CDATA[");
		sb.append(getChassisNumber());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>engineNumber</column-name><column-value><![CDATA[");
		sb.append(getEngineNumber());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>productionYear</column-name><column-value><![CDATA[");
		sb.append(getProductionYear());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>vehicleEngineStatus</column-name><column-value><![CDATA[");
		sb.append(getVehicleEngineStatus());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>vehicleColor</column-name><column-value><![CDATA[");
		sb.append(getVehicleColor());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>unitPrice</column-name><column-value><![CDATA[");
		sb.append(getUnitPrice());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>currency</column-name><column-value><![CDATA[");
		sb.append(getCurrency());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>remarks</column-name><column-value><![CDATA[");
		sb.append(getRemarks());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>confirmedInspectionId</column-name><column-value><![CDATA[");
		sb.append(getConfirmedInspectionId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>inspectionRecordId</column-name><column-value><![CDATA[");
		sb.append(getInspectionRecordId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>draftCertificateId</column-name><column-value><![CDATA[");
		sb.append(getDraftCertificateId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>certificateRecordId</column-name><column-value><![CDATA[");
		sb.append(getCertificateRecordId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>markUpStatus</column-name><column-value><![CDATA[");
		sb.append(getMarkUpStatus());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>safeTestRequirementId</column-name><column-value><![CDATA[");
		sb.append(getSafeTestRequirementId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>emissionTestRequirementId</column-name><column-value><![CDATA[");
		sb.append(getEmissionTestRequirementId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>controlRequirementId</column-name><column-value><![CDATA[");
		sb.append(getControlRequirementId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>markAsSample</column-name><column-value><![CDATA[");
		sb.append(getMarkAsSample());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>inspectionrecordno</column-name><column-value><![CDATA[");
		sb.append(getInspectionrecordno());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>inspectionRecordDate</column-name><column-value><![CDATA[");
		sb.append(getInspectionRecordDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>attachedFileBbkt</column-name><column-value><![CDATA[");
		sb.append(getAttachedFileBbkt());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>certificateNumber</column-name><column-value><![CDATA[");
		sb.append(getCertificateNumber());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>signDate</column-name><column-value><![CDATA[");
		sb.append(getSignDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>attachedFile</column-name><column-value><![CDATA[");
		sb.append(getAttachedFile());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>registeredNumber</column-name><column-value><![CDATA[");
		sb.append(getRegisteredNumber());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>inspectorSignDate</column-name><column-value><![CDATA[");
		sb.append(getInspectorSignDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>vehicleClass</column-name><column-value><![CDATA[");
		sb.append(getVehicleClass());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = ViewDangKiemTimKiem.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			ViewDangKiemTimKiem.class
		};
	private long _id;
	private long _vehicleGroupId;
	private long _debitNoteId;
	private long _sequenceNo;
	private long _codeNumber;
	private String _chassisNumber;
	private String _engineNumber;
	private long _productionYear;
	private String _vehicleEngineStatus;
	private String _vehicleColor;
	private double _unitPrice;
	private String _currency;
	private String _remarks;
	private long _confirmedInspectionId;
	private long _inspectionRecordId;
	private long _draftCertificateId;
	private long _certificateRecordId;
	private long _markUpStatus;
	private long _safeTestRequirementId;
	private long _emissionTestRequirementId;
	private long _controlRequirementId;
	private int _markAsSample;
	private String _inspectionrecordno;
	private Date _inspectionRecordDate;
	private long _attachedFileBbkt;
	private String _certificateNumber;
	private Date _signDate;
	private long _attachedFile;
	private String _registeredNumber;
	private Date _inspectorSignDate;
	private String _vehicleClass;
	private ViewDangKiemTimKiem _escapedModel;
}