/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.gt.dk.dao.aswmsg.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the AswmsgWebservice service. Represents a row in the &quot;aswmsg_webservice&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.dtt.gt.dk.dao.aswmsg.model.impl.AswmsgWebserviceModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.dtt.gt.dk.dao.aswmsg.model.impl.AswmsgWebserviceImpl}.
 * </p>
 *
 * @author win_64
 * @see AswmsgWebservice
 * @see vn.dtt.gt.dk.dao.aswmsg.model.impl.AswmsgWebserviceImpl
 * @see vn.dtt.gt.dk.dao.aswmsg.model.impl.AswmsgWebserviceModelImpl
 * @generated
 */
public interface AswmsgWebserviceModel extends BaseModel<AswmsgWebservice> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a aswmsg webservice model instance should use the {@link AswmsgWebservice} interface instead.
	 */

	/**
	 * Returns the primary key of this aswmsg webservice.
	 *
	 * @return the primary key of this aswmsg webservice
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this aswmsg webservice.
	 *
	 * @param primaryKey the primary key of this aswmsg webservice
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this aswmsg webservice.
	 *
	 * @return the ID of this aswmsg webservice
	 */
	public long getId();

	/**
	 * Sets the ID of this aswmsg webservice.
	 *
	 * @param Id the ID of this aswmsg webservice
	 */
	public void setId(long Id);

	/**
	 * Returns the service code of this aswmsg webservice.
	 *
	 * @return the service code of this aswmsg webservice
	 */
	@AutoEscape
	public String getServiceCode();

	/**
	 * Sets the service code of this aswmsg webservice.
	 *
	 * @param ServiceCode the service code of this aswmsg webservice
	 */
	public void setServiceCode(String ServiceCode);

	/**
	 * Returns the service name of this aswmsg webservice.
	 *
	 * @return the service name of this aswmsg webservice
	 */
	@AutoEscape
	public String getServiceName();

	/**
	 * Sets the service name of this aswmsg webservice.
	 *
	 * @param ServiceName the service name of this aswmsg webservice
	 */
	public void setServiceName(String ServiceName);

	/**
	 * Returns the service u r l of this aswmsg webservice.
	 *
	 * @return the service u r l of this aswmsg webservice
	 */
	@AutoEscape
	public String getServiceURL();

	/**
	 * Sets the service u r l of this aswmsg webservice.
	 *
	 * @param ServiceURL the service u r l of this aswmsg webservice
	 */
	public void setServiceURL(String ServiceURL);

	/**
	 * Returns the user name of this aswmsg webservice.
	 *
	 * @return the user name of this aswmsg webservice
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this aswmsg webservice.
	 *
	 * @param UserName the user name of this aswmsg webservice
	 */
	public void setUserName(String UserName);

	/**
	 * Returns the password of this aswmsg webservice.
	 *
	 * @return the password of this aswmsg webservice
	 */
	@AutoEscape
	public String getPassword();

	/**
	 * Sets the password of this aswmsg webservice.
	 *
	 * @param Password the password of this aswmsg webservice
	 */
	public void setPassword(String Password);

	/**
	 * Returns the domain of this aswmsg webservice.
	 *
	 * @return the domain of this aswmsg webservice
	 */
	@AutoEscape
	public String getDomain();

	/**
	 * Sets the domain of this aswmsg webservice.
	 *
	 * @param Domain the domain of this aswmsg webservice
	 */
	public void setDomain(String Domain);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(AswmsgWebservice aswmsgWebservice);

	@Override
	public int hashCode();

	@Override
	public CacheModel<AswmsgWebservice> toCacheModel();

	@Override
	public AswmsgWebservice toEscapedModel();

	@Override
	public AswmsgWebservice toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}