/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.gt.dk.dao.aswmsg.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the AswmsgSyndatahistory service. Represents a row in the &quot;aswmsg_syndatahistory&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.dtt.gt.dk.dao.aswmsg.model.impl.AswmsgSyndatahistoryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.dtt.gt.dk.dao.aswmsg.model.impl.AswmsgSyndatahistoryImpl}.
 * </p>
 *
 * @author win_64
 * @see AswmsgSyndatahistory
 * @see vn.dtt.gt.dk.dao.aswmsg.model.impl.AswmsgSyndatahistoryImpl
 * @see vn.dtt.gt.dk.dao.aswmsg.model.impl.AswmsgSyndatahistoryModelImpl
 * @generated
 */
public interface AswmsgSyndatahistoryModel extends BaseModel<AswmsgSyndatahistory> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a aswmsg syndatahistory model instance should use the {@link AswmsgSyndatahistory} interface instead.
	 */

	/**
	 * Returns the primary key of this aswmsg syndatahistory.
	 *
	 * @return the primary key of this aswmsg syndatahistory
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this aswmsg syndatahistory.
	 *
	 * @param primaryKey the primary key of this aswmsg syndatahistory
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this aswmsg syndatahistory.
	 *
	 * @return the ID of this aswmsg syndatahistory
	 */
	public long getId();

	/**
	 * Sets the ID of this aswmsg syndatahistory.
	 *
	 * @param id the ID of this aswmsg syndatahistory
	 */
	public void setId(long id);

	/**
	 * Returns the version of this aswmsg syndatahistory.
	 *
	 * @return the version of this aswmsg syndatahistory
	 */
	@AutoEscape
	public String getVersion();

	/**
	 * Sets the version of this aswmsg syndatahistory.
	 *
	 * @param version the version of this aswmsg syndatahistory
	 */
	public void setVersion(String version);

	/**
	 * Returns the message ID of this aswmsg syndatahistory.
	 *
	 * @return the message ID of this aswmsg syndatahistory
	 */
	@AutoEscape
	public String getMessageId();

	/**
	 * Sets the message ID of this aswmsg syndatahistory.
	 *
	 * @param messageId the message ID of this aswmsg syndatahistory
	 */
	public void setMessageId(String messageId);

	/**
	 * Returns the sender name of this aswmsg syndatahistory.
	 *
	 * @return the sender name of this aswmsg syndatahistory
	 */
	@AutoEscape
	public String getSenderName();

	/**
	 * Sets the sender name of this aswmsg syndatahistory.
	 *
	 * @param senderName the sender name of this aswmsg syndatahistory
	 */
	public void setSenderName(String senderName);

	/**
	 * Returns the sender identity of this aswmsg syndatahistory.
	 *
	 * @return the sender identity of this aswmsg syndatahistory
	 */
	@AutoEscape
	public String getSenderIdentity();

	/**
	 * Sets the sender identity of this aswmsg syndatahistory.
	 *
	 * @param senderIdentity the sender identity of this aswmsg syndatahistory
	 */
	public void setSenderIdentity(String senderIdentity);

	/**
	 * Returns the sender country code of this aswmsg syndatahistory.
	 *
	 * @return the sender country code of this aswmsg syndatahistory
	 */
	@AutoEscape
	public String getSenderCountryCode();

	/**
	 * Sets the sender country code of this aswmsg syndatahistory.
	 *
	 * @param senderCountryCode the sender country code of this aswmsg syndatahistory
	 */
	public void setSenderCountryCode(String senderCountryCode);

	/**
	 * Returns the sender ministry code of this aswmsg syndatahistory.
	 *
	 * @return the sender ministry code of this aswmsg syndatahistory
	 */
	@AutoEscape
	public String getSenderMinistryCode();

	/**
	 * Sets the sender ministry code of this aswmsg syndatahistory.
	 *
	 * @param senderMinistryCode the sender ministry code of this aswmsg syndatahistory
	 */
	public void setSenderMinistryCode(String senderMinistryCode);

	/**
	 * Returns the sender organization code of this aswmsg syndatahistory.
	 *
	 * @return the sender organization code of this aswmsg syndatahistory
	 */
	@AutoEscape
	public String getSenderOrganizationCode();

	/**
	 * Sets the sender organization code of this aswmsg syndatahistory.
	 *
	 * @param senderOrganizationCode the sender organization code of this aswmsg syndatahistory
	 */
	public void setSenderOrganizationCode(String senderOrganizationCode);

	/**
	 * Returns the sender unit code of this aswmsg syndatahistory.
	 *
	 * @return the sender unit code of this aswmsg syndatahistory
	 */
	@AutoEscape
	public String getSenderUnitCode();

	/**
	 * Sets the sender unit code of this aswmsg syndatahistory.
	 *
	 * @param senderUnitCode the sender unit code of this aswmsg syndatahistory
	 */
	public void setSenderUnitCode(String senderUnitCode);

	/**
	 * Returns the receiver name of this aswmsg syndatahistory.
	 *
	 * @return the receiver name of this aswmsg syndatahistory
	 */
	@AutoEscape
	public String getReceiverName();

	/**
	 * Sets the receiver name of this aswmsg syndatahistory.
	 *
	 * @param receiverName the receiver name of this aswmsg syndatahistory
	 */
	public void setReceiverName(String receiverName);

	/**
	 * Returns the receiver identity of this aswmsg syndatahistory.
	 *
	 * @return the receiver identity of this aswmsg syndatahistory
	 */
	@AutoEscape
	public String getReceiverIdentity();

	/**
	 * Sets the receiver identity of this aswmsg syndatahistory.
	 *
	 * @param receiverIdentity the receiver identity of this aswmsg syndatahistory
	 */
	public void setReceiverIdentity(String receiverIdentity);

	/**
	 * Returns the receiver country code of this aswmsg syndatahistory.
	 *
	 * @return the receiver country code of this aswmsg syndatahistory
	 */
	@AutoEscape
	public String getReceiverCountryCode();

	/**
	 * Sets the receiver country code of this aswmsg syndatahistory.
	 *
	 * @param receiverCountryCode the receiver country code of this aswmsg syndatahistory
	 */
	public void setReceiverCountryCode(String receiverCountryCode);

	/**
	 * Returns the receiver ministry code of this aswmsg syndatahistory.
	 *
	 * @return the receiver ministry code of this aswmsg syndatahistory
	 */
	@AutoEscape
	public String getReceiverMinistryCode();

	/**
	 * Sets the receiver ministry code of this aswmsg syndatahistory.
	 *
	 * @param receiverMinistryCode the receiver ministry code of this aswmsg syndatahistory
	 */
	public void setReceiverMinistryCode(String receiverMinistryCode);

	/**
	 * Returns the receiver organization code of this aswmsg syndatahistory.
	 *
	 * @return the receiver organization code of this aswmsg syndatahistory
	 */
	@AutoEscape
	public String getReceiverOrganizationCode();

	/**
	 * Sets the receiver organization code of this aswmsg syndatahistory.
	 *
	 * @param receiverOrganizationCode the receiver organization code of this aswmsg syndatahistory
	 */
	public void setReceiverOrganizationCode(String receiverOrganizationCode);

	/**
	 * Returns the receiver unit code of this aswmsg syndatahistory.
	 *
	 * @return the receiver unit code of this aswmsg syndatahistory
	 */
	@AutoEscape
	public String getReceiverUnitCode();

	/**
	 * Sets the receiver unit code of this aswmsg syndatahistory.
	 *
	 * @param receiverUnitCode the receiver unit code of this aswmsg syndatahistory
	 */
	public void setReceiverUnitCode(String receiverUnitCode);

	/**
	 * Returns the document type of this aswmsg syndatahistory.
	 *
	 * @return the document type of this aswmsg syndatahistory
	 */
	@AutoEscape
	public String getDocumentType();

	/**
	 * Sets the document type of this aswmsg syndatahistory.
	 *
	 * @param documentType the document type of this aswmsg syndatahistory
	 */
	public void setDocumentType(String documentType);

	/**
	 * Returns the type of this aswmsg syndatahistory.
	 *
	 * @return the type of this aswmsg syndatahistory
	 */
	public int getType();

	/**
	 * Sets the type of this aswmsg syndatahistory.
	 *
	 * @param type the type of this aswmsg syndatahistory
	 */
	public void setType(int type);

	/**
	 * Returns the function of this aswmsg syndatahistory.
	 *
	 * @return the function of this aswmsg syndatahistory
	 */
	@AutoEscape
	public String getFunction();

	/**
	 * Sets the function of this aswmsg syndatahistory.
	 *
	 * @param function the function of this aswmsg syndatahistory
	 */
	public void setFunction(String function);

	/**
	 * Returns the reference of this aswmsg syndatahistory.
	 *
	 * @return the reference of this aswmsg syndatahistory
	 */
	public long getReference();

	/**
	 * Sets the reference of this aswmsg syndatahistory.
	 *
	 * @param reference the reference of this aswmsg syndatahistory
	 */
	public void setReference(long reference);

	/**
	 * Returns the pre reference of this aswmsg syndatahistory.
	 *
	 * @return the pre reference of this aswmsg syndatahistory
	 */
	public long getPreReference();

	/**
	 * Sets the pre reference of this aswmsg syndatahistory.
	 *
	 * @param preReference the pre reference of this aswmsg syndatahistory
	 */
	public void setPreReference(long preReference);

	/**
	 * Returns the document year of this aswmsg syndatahistory.
	 *
	 * @return the document year of this aswmsg syndatahistory
	 */
	public int getDocumentYear();

	/**
	 * Sets the document year of this aswmsg syndatahistory.
	 *
	 * @param documentYear the document year of this aswmsg syndatahistory
	 */
	public void setDocumentYear(int documentYear);

	/**
	 * Returns the send date of this aswmsg syndatahistory.
	 *
	 * @return the send date of this aswmsg syndatahistory
	 */
	public Date getSendDate();

	/**
	 * Sets the send date of this aswmsg syndatahistory.
	 *
	 * @param sendDate the send date of this aswmsg syndatahistory
	 */
	public void setSendDate(Date sendDate);

	/**
	 * Returns the signature of this aswmsg syndatahistory.
	 *
	 * @return the signature of this aswmsg syndatahistory
	 */
	@AutoEscape
	public String getSignature();

	/**
	 * Sets the signature of this aswmsg syndatahistory.
	 *
	 * @param signature the signature of this aswmsg syndatahistory
	 */
	public void setSignature(String signature);

	/**
	 * Returns the system signature of this aswmsg syndatahistory.
	 *
	 * @return the system signature of this aswmsg syndatahistory
	 */
	@AutoEscape
	public String getSystemSignature();

	/**
	 * Sets the system signature of this aswmsg syndatahistory.
	 *
	 * @param systemSignature the system signature of this aswmsg syndatahistory
	 */
	public void setSystemSignature(String systemSignature);

	/**
	 * Returns the all content of this aswmsg syndatahistory.
	 *
	 * @return the all content of this aswmsg syndatahistory
	 */
	@AutoEscape
	public String getAllContent();

	/**
	 * Sets the all content of this aswmsg syndatahistory.
	 *
	 * @param allContent the all content of this aswmsg syndatahistory
	 */
	public void setAllContent(String allContent);

	/**
	 * Returns the created time of this aswmsg syndatahistory.
	 *
	 * @return the created time of this aswmsg syndatahistory
	 */
	public Date getCreatedTime();

	/**
	 * Sets the created time of this aswmsg syndatahistory.
	 *
	 * @param createdTime the created time of this aswmsg syndatahistory
	 */
	public void setCreatedTime(Date createdTime);

	/**
	 * Returns the webservice of this aswmsg syndatahistory.
	 *
	 * @return the webservice of this aswmsg syndatahistory
	 */
	public int getWebservice();

	/**
	 * Sets the webservice of this aswmsg syndatahistory.
	 *
	 * @param webservice the webservice of this aswmsg syndatahistory
	 */
	public void setWebservice(int webservice);

	/**
	 * Returns the validated of this aswmsg syndatahistory.
	 *
	 * @return the validated of this aswmsg syndatahistory
	 */
	public int getValidated();

	/**
	 * Sets the validated of this aswmsg syndatahistory.
	 *
	 * @param validated the validated of this aswmsg syndatahistory
	 */
	public void setValidated(int validated);

	/**
	 * Returns the priority of this aswmsg syndatahistory.
	 *
	 * @return the priority of this aswmsg syndatahistory
	 */
	public int getPriority();

	/**
	 * Sets the priority of this aswmsg syndatahistory.
	 *
	 * @param priority the priority of this aswmsg syndatahistory
	 */
	public void setPriority(int priority);

	/**
	 * Returns the description of this aswmsg syndatahistory.
	 *
	 * @return the description of this aswmsg syndatahistory
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this aswmsg syndatahistory.
	 *
	 * @param description the description of this aswmsg syndatahistory
	 */
	public void setDescription(String description);

	/**
	 * Returns the validation code of this aswmsg syndatahistory.
	 *
	 * @return the validation code of this aswmsg syndatahistory
	 */
	@AutoEscape
	public String getValidationCode();

	/**
	 * Sets the validation code of this aswmsg syndatahistory.
	 *
	 * @param validationCode the validation code of this aswmsg syndatahistory
	 */
	public void setValidationCode(String validationCode);

	/**
	 * Returns the so lan gui of this aswmsg syndatahistory.
	 *
	 * @return the so lan gui of this aswmsg syndatahistory
	 */
	public int getSoLanGui();

	/**
	 * Sets the so lan gui of this aswmsg syndatahistory.
	 *
	 * @param soLanGui the so lan gui of this aswmsg syndatahistory
	 */
	public void setSoLanGui(int soLanGui);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(AswmsgSyndatahistory aswmsgSyndatahistory);

	@Override
	public int hashCode();

	@Override
	public CacheModel<AswmsgSyndatahistory> toCacheModel();

	@Override
	public AswmsgSyndatahistory toEscapedModel();

	@Override
	public AswmsgSyndatahistory toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}