/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.gt.dk.dao.motcua.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import vn.dtt.gt.dk.dao.motcua.model.MotCuaPhieuXuLyChinh;
import vn.dtt.gt.dk.dao.motcua.model.MotCuaPhieuXuLyChinhModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the MotCuaPhieuXuLyChinh service. Represents a row in the &quot;motcua_phieuxulychinh&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link vn.dtt.gt.dk.dao.motcua.model.MotCuaPhieuXuLyChinhModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MotCuaPhieuXuLyChinhImpl}.
 * </p>
 *
 * @author huymq
 * @see MotCuaPhieuXuLyChinhImpl
 * @see vn.dtt.gt.dk.dao.motcua.model.MotCuaPhieuXuLyChinh
 * @see vn.dtt.gt.dk.dao.motcua.model.MotCuaPhieuXuLyChinhModel
 * @generated
 */
public class MotCuaPhieuXuLyChinhModelImpl extends BaseModelImpl<MotCuaPhieuXuLyChinh>
	implements MotCuaPhieuXuLyChinhModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a mot cua phieu xu ly chinh model instance should use the {@link vn.dtt.gt.dk.dao.motcua.model.MotCuaPhieuXuLyChinh} interface instead.
	 */
	public static final String TABLE_NAME = "motcua_phieuxulychinh";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id", Types.BIGINT },
			{ "hosothutucid", Types.BIGINT },
			{ "quytrinhthutucid", Types.BIGINT },
			{ "tennguoinop", Types.VARCHAR },
			{ "cmndnguoinop", Types.VARCHAR },
			{ "diachinguoinop", Types.VARCHAR },
			{ "sodtddnguoinop", Types.VARCHAR },
			{ "emailnguoinop", Types.VARCHAR },
			{ "ghichu", Types.VARCHAR },
			{ "trangthaihientaiid", Types.BIGINT },
			{ "hethosocon", Types.BIGINT },
			{ "chiemquyenxuly", Types.BIGINT },
			{ "ngaytaophieu", Types.TIMESTAMP },
			{ "nguoitaophieu", Types.BIGINT },
			{ "sodtcdnguoinop", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table motcua_phieuxulychinh (id LONG not null primary key,hosothutucid LONG,quytrinhthutucid LONG,tennguoinop VARCHAR(75) null,cmndnguoinop VARCHAR(75) null,diachinguoinop VARCHAR(75) null,sodtddnguoinop VARCHAR(75) null,emailnguoinop VARCHAR(75) null,ghichu VARCHAR(75) null,trangthaihientaiid LONG,hethosocon LONG,chiemquyenxuly LONG,ngaytaophieu DATE null,nguoitaophieu LONG,sodtcdnguoinop VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table motcua_phieuxulychinh";
	public static final String ORDER_BY_JPQL = " ORDER BY motCuaPhieuXuLyChinh.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY motcua_phieuxulychinh.id ASC";
	public static final String DATA_SOURCE = "tthcDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.vn.dtt.gt.dk.dao.motcua.model.MotCuaPhieuXuLyChinh"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.vn.dtt.gt.dk.dao.motcua.model.MotCuaPhieuXuLyChinh"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.vn.dtt.gt.dk.dao.motcua.model.MotCuaPhieuXuLyChinh"),
			true);
	public static long HOSOTHUTUCID_COLUMN_BITMASK = 1L;
	public static long QUYTRINHTHUTUCID_COLUMN_BITMASK = 2L;
	public static long ID_COLUMN_BITMASK = 4L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.vn.dtt.gt.dk.dao.motcua.model.MotCuaPhieuXuLyChinh"));

	public MotCuaPhieuXuLyChinhModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return MotCuaPhieuXuLyChinh.class;
	}

	@Override
	public String getModelClassName() {
		return MotCuaPhieuXuLyChinh.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("hoSoThuTucId", getHoSoThuTucId());
		attributes.put("quyTrinhThuTucId", getQuyTrinhThuTucId());
		attributes.put("tenNguoiNop", getTenNguoiNop());
		attributes.put("cmndNguoiNop", getCmndNguoiNop());
		attributes.put("diaChiNguoiNop", getDiaChiNguoiNop());
		attributes.put("soDtddNguoiNop", getSoDtddNguoiNop());
		attributes.put("emailNguoiNop", getEmailNguoiNop());
		attributes.put("ghiChu", getGhiChu());
		attributes.put("trangThaiHienTaiId", getTrangThaiHienTaiId());
		attributes.put("hetHoSoCon", getHetHoSoCon());
		attributes.put("chiemQuyenXuLy", getChiemQuyenXuLy());
		attributes.put("ngayTaoPhieu", getNgayTaoPhieu());
		attributes.put("nguoiTaoPhieu", getNguoiTaoPhieu());
		attributes.put("soDtcdNguoiNop", getSoDtcdNguoiNop());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id = (Long)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		Long hoSoThuTucId = (Long)attributes.get("hoSoThuTucId");

		if (hoSoThuTucId != null) {
			setHoSoThuTucId(hoSoThuTucId);
		}

		Long quyTrinhThuTucId = (Long)attributes.get("quyTrinhThuTucId");

		if (quyTrinhThuTucId != null) {
			setQuyTrinhThuTucId(quyTrinhThuTucId);
		}

		String tenNguoiNop = (String)attributes.get("tenNguoiNop");

		if (tenNguoiNop != null) {
			setTenNguoiNop(tenNguoiNop);
		}

		String cmndNguoiNop = (String)attributes.get("cmndNguoiNop");

		if (cmndNguoiNop != null) {
			setCmndNguoiNop(cmndNguoiNop);
		}

		String diaChiNguoiNop = (String)attributes.get("diaChiNguoiNop");

		if (diaChiNguoiNop != null) {
			setDiaChiNguoiNop(diaChiNguoiNop);
		}

		String soDtddNguoiNop = (String)attributes.get("soDtddNguoiNop");

		if (soDtddNguoiNop != null) {
			setSoDtddNguoiNop(soDtddNguoiNop);
		}

		String emailNguoiNop = (String)attributes.get("emailNguoiNop");

		if (emailNguoiNop != null) {
			setEmailNguoiNop(emailNguoiNop);
		}

		String ghiChu = (String)attributes.get("ghiChu");

		if (ghiChu != null) {
			setGhiChu(ghiChu);
		}

		Long trangThaiHienTaiId = (Long)attributes.get("trangThaiHienTaiId");

		if (trangThaiHienTaiId != null) {
			setTrangThaiHienTaiId(trangThaiHienTaiId);
		}

		Long hetHoSoCon = (Long)attributes.get("hetHoSoCon");

		if (hetHoSoCon != null) {
			setHetHoSoCon(hetHoSoCon);
		}

		Long chiemQuyenXuLy = (Long)attributes.get("chiemQuyenXuLy");

		if (chiemQuyenXuLy != null) {
			setChiemQuyenXuLy(chiemQuyenXuLy);
		}

		Date ngayTaoPhieu = (Date)attributes.get("ngayTaoPhieu");

		if (ngayTaoPhieu != null) {
			setNgayTaoPhieu(ngayTaoPhieu);
		}

		Long nguoiTaoPhieu = (Long)attributes.get("nguoiTaoPhieu");

		if (nguoiTaoPhieu != null) {
			setNguoiTaoPhieu(nguoiTaoPhieu);
		}

		String soDtcdNguoiNop = (String)attributes.get("soDtcdNguoiNop");

		if (soDtcdNguoiNop != null) {
			setSoDtcdNguoiNop(soDtcdNguoiNop);
		}
	}

	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		_columnBitmask = -1L;

		_id = id;
	}

	@Override
	public long getHoSoThuTucId() {
		return _hoSoThuTucId;
	}

	@Override
	public void setHoSoThuTucId(long hoSoThuTucId) {
		_columnBitmask |= HOSOTHUTUCID_COLUMN_BITMASK;

		if (!_setOriginalHoSoThuTucId) {
			_setOriginalHoSoThuTucId = true;

			_originalHoSoThuTucId = _hoSoThuTucId;
		}

		_hoSoThuTucId = hoSoThuTucId;
	}

	public long getOriginalHoSoThuTucId() {
		return _originalHoSoThuTucId;
	}

	@Override
	public long getQuyTrinhThuTucId() {
		return _quyTrinhThuTucId;
	}

	@Override
	public void setQuyTrinhThuTucId(long quyTrinhThuTucId) {
		_columnBitmask |= QUYTRINHTHUTUCID_COLUMN_BITMASK;

		if (!_setOriginalQuyTrinhThuTucId) {
			_setOriginalQuyTrinhThuTucId = true;

			_originalQuyTrinhThuTucId = _quyTrinhThuTucId;
		}

		_quyTrinhThuTucId = quyTrinhThuTucId;
	}

	public long getOriginalQuyTrinhThuTucId() {
		return _originalQuyTrinhThuTucId;
	}

	@Override
	public String getTenNguoiNop() {
		if (_tenNguoiNop == null) {
			return StringPool.BLANK;
		}
		else {
			return _tenNguoiNop;
		}
	}

	@Override
	public void setTenNguoiNop(String tenNguoiNop) {
		_tenNguoiNop = tenNguoiNop;
	}

	@Override
	public String getCmndNguoiNop() {
		if (_cmndNguoiNop == null) {
			return StringPool.BLANK;
		}
		else {
			return _cmndNguoiNop;
		}
	}

	@Override
	public void setCmndNguoiNop(String cmndNguoiNop) {
		_cmndNguoiNop = cmndNguoiNop;
	}

	@Override
	public String getDiaChiNguoiNop() {
		if (_diaChiNguoiNop == null) {
			return StringPool.BLANK;
		}
		else {
			return _diaChiNguoiNop;
		}
	}

	@Override
	public void setDiaChiNguoiNop(String diaChiNguoiNop) {
		_diaChiNguoiNop = diaChiNguoiNop;
	}

	@Override
	public String getSoDtddNguoiNop() {
		if (_soDtddNguoiNop == null) {
			return StringPool.BLANK;
		}
		else {
			return _soDtddNguoiNop;
		}
	}

	@Override
	public void setSoDtddNguoiNop(String soDtddNguoiNop) {
		_soDtddNguoiNop = soDtddNguoiNop;
	}

	@Override
	public String getEmailNguoiNop() {
		if (_emailNguoiNop == null) {
			return StringPool.BLANK;
		}
		else {
			return _emailNguoiNop;
		}
	}

	@Override
	public void setEmailNguoiNop(String emailNguoiNop) {
		_emailNguoiNop = emailNguoiNop;
	}

	@Override
	public String getGhiChu() {
		if (_ghiChu == null) {
			return StringPool.BLANK;
		}
		else {
			return _ghiChu;
		}
	}

	@Override
	public void setGhiChu(String ghiChu) {
		_ghiChu = ghiChu;
	}

	@Override
	public long getTrangThaiHienTaiId() {
		return _trangThaiHienTaiId;
	}

	@Override
	public void setTrangThaiHienTaiId(long trangThaiHienTaiId) {
		_trangThaiHienTaiId = trangThaiHienTaiId;
	}

	@Override
	public long getHetHoSoCon() {
		return _hetHoSoCon;
	}

	@Override
	public void setHetHoSoCon(long hetHoSoCon) {
		_hetHoSoCon = hetHoSoCon;
	}

	@Override
	public long getChiemQuyenXuLy() {
		return _chiemQuyenXuLy;
	}

	@Override
	public void setChiemQuyenXuLy(long chiemQuyenXuLy) {
		_chiemQuyenXuLy = chiemQuyenXuLy;
	}

	@Override
	public Date getNgayTaoPhieu() {
		return _ngayTaoPhieu;
	}

	@Override
	public void setNgayTaoPhieu(Date ngayTaoPhieu) {
		_ngayTaoPhieu = ngayTaoPhieu;
	}

	@Override
	public long getNguoiTaoPhieu() {
		return _nguoiTaoPhieu;
	}

	@Override
	public void setNguoiTaoPhieu(long nguoiTaoPhieu) {
		_nguoiTaoPhieu = nguoiTaoPhieu;
	}

	@Override
	public String getSoDtcdNguoiNop() {
		if (_soDtcdNguoiNop == null) {
			return StringPool.BLANK;
		}
		else {
			return _soDtcdNguoiNop;
		}
	}

	@Override
	public void setSoDtcdNguoiNop(String soDtcdNguoiNop) {
		_soDtcdNguoiNop = soDtcdNguoiNop;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			MotCuaPhieuXuLyChinh.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public MotCuaPhieuXuLyChinh toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (MotCuaPhieuXuLyChinh)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		MotCuaPhieuXuLyChinhImpl motCuaPhieuXuLyChinhImpl = new MotCuaPhieuXuLyChinhImpl();

		motCuaPhieuXuLyChinhImpl.setId(getId());
		motCuaPhieuXuLyChinhImpl.setHoSoThuTucId(getHoSoThuTucId());
		motCuaPhieuXuLyChinhImpl.setQuyTrinhThuTucId(getQuyTrinhThuTucId());
		motCuaPhieuXuLyChinhImpl.setTenNguoiNop(getTenNguoiNop());
		motCuaPhieuXuLyChinhImpl.setCmndNguoiNop(getCmndNguoiNop());
		motCuaPhieuXuLyChinhImpl.setDiaChiNguoiNop(getDiaChiNguoiNop());
		motCuaPhieuXuLyChinhImpl.setSoDtddNguoiNop(getSoDtddNguoiNop());
		motCuaPhieuXuLyChinhImpl.setEmailNguoiNop(getEmailNguoiNop());
		motCuaPhieuXuLyChinhImpl.setGhiChu(getGhiChu());
		motCuaPhieuXuLyChinhImpl.setTrangThaiHienTaiId(getTrangThaiHienTaiId());
		motCuaPhieuXuLyChinhImpl.setHetHoSoCon(getHetHoSoCon());
		motCuaPhieuXuLyChinhImpl.setChiemQuyenXuLy(getChiemQuyenXuLy());
		motCuaPhieuXuLyChinhImpl.setNgayTaoPhieu(getNgayTaoPhieu());
		motCuaPhieuXuLyChinhImpl.setNguoiTaoPhieu(getNguoiTaoPhieu());
		motCuaPhieuXuLyChinhImpl.setSoDtcdNguoiNop(getSoDtcdNguoiNop());

		motCuaPhieuXuLyChinhImpl.resetOriginalValues();

		return motCuaPhieuXuLyChinhImpl;
	}

	@Override
	public int compareTo(MotCuaPhieuXuLyChinh motCuaPhieuXuLyChinh) {
		int value = 0;

		if (getId() < motCuaPhieuXuLyChinh.getId()) {
			value = -1;
		}
		else if (getId() > motCuaPhieuXuLyChinh.getId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof MotCuaPhieuXuLyChinh)) {
			return false;
		}

		MotCuaPhieuXuLyChinh motCuaPhieuXuLyChinh = (MotCuaPhieuXuLyChinh)obj;

		long primaryKey = motCuaPhieuXuLyChinh.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		MotCuaPhieuXuLyChinhModelImpl motCuaPhieuXuLyChinhModelImpl = this;

		motCuaPhieuXuLyChinhModelImpl._originalHoSoThuTucId = motCuaPhieuXuLyChinhModelImpl._hoSoThuTucId;

		motCuaPhieuXuLyChinhModelImpl._setOriginalHoSoThuTucId = false;

		motCuaPhieuXuLyChinhModelImpl._originalQuyTrinhThuTucId = motCuaPhieuXuLyChinhModelImpl._quyTrinhThuTucId;

		motCuaPhieuXuLyChinhModelImpl._setOriginalQuyTrinhThuTucId = false;

		motCuaPhieuXuLyChinhModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<MotCuaPhieuXuLyChinh> toCacheModel() {
		MotCuaPhieuXuLyChinhCacheModel motCuaPhieuXuLyChinhCacheModel = new MotCuaPhieuXuLyChinhCacheModel();

		motCuaPhieuXuLyChinhCacheModel.id = getId();

		motCuaPhieuXuLyChinhCacheModel.hoSoThuTucId = getHoSoThuTucId();

		motCuaPhieuXuLyChinhCacheModel.quyTrinhThuTucId = getQuyTrinhThuTucId();

		motCuaPhieuXuLyChinhCacheModel.tenNguoiNop = getTenNguoiNop();

		String tenNguoiNop = motCuaPhieuXuLyChinhCacheModel.tenNguoiNop;

		if ((tenNguoiNop != null) && (tenNguoiNop.length() == 0)) {
			motCuaPhieuXuLyChinhCacheModel.tenNguoiNop = null;
		}

		motCuaPhieuXuLyChinhCacheModel.cmndNguoiNop = getCmndNguoiNop();

		String cmndNguoiNop = motCuaPhieuXuLyChinhCacheModel.cmndNguoiNop;

		if ((cmndNguoiNop != null) && (cmndNguoiNop.length() == 0)) {
			motCuaPhieuXuLyChinhCacheModel.cmndNguoiNop = null;
		}

		motCuaPhieuXuLyChinhCacheModel.diaChiNguoiNop = getDiaChiNguoiNop();

		String diaChiNguoiNop = motCuaPhieuXuLyChinhCacheModel.diaChiNguoiNop;

		if ((diaChiNguoiNop != null) && (diaChiNguoiNop.length() == 0)) {
			motCuaPhieuXuLyChinhCacheModel.diaChiNguoiNop = null;
		}

		motCuaPhieuXuLyChinhCacheModel.soDtddNguoiNop = getSoDtddNguoiNop();

		String soDtddNguoiNop = motCuaPhieuXuLyChinhCacheModel.soDtddNguoiNop;

		if ((soDtddNguoiNop != null) && (soDtddNguoiNop.length() == 0)) {
			motCuaPhieuXuLyChinhCacheModel.soDtddNguoiNop = null;
		}

		motCuaPhieuXuLyChinhCacheModel.emailNguoiNop = getEmailNguoiNop();

		String emailNguoiNop = motCuaPhieuXuLyChinhCacheModel.emailNguoiNop;

		if ((emailNguoiNop != null) && (emailNguoiNop.length() == 0)) {
			motCuaPhieuXuLyChinhCacheModel.emailNguoiNop = null;
		}

		motCuaPhieuXuLyChinhCacheModel.ghiChu = getGhiChu();

		String ghiChu = motCuaPhieuXuLyChinhCacheModel.ghiChu;

		if ((ghiChu != null) && (ghiChu.length() == 0)) {
			motCuaPhieuXuLyChinhCacheModel.ghiChu = null;
		}

		motCuaPhieuXuLyChinhCacheModel.trangThaiHienTaiId = getTrangThaiHienTaiId();

		motCuaPhieuXuLyChinhCacheModel.hetHoSoCon = getHetHoSoCon();

		motCuaPhieuXuLyChinhCacheModel.chiemQuyenXuLy = getChiemQuyenXuLy();

		Date ngayTaoPhieu = getNgayTaoPhieu();

		if (ngayTaoPhieu != null) {
			motCuaPhieuXuLyChinhCacheModel.ngayTaoPhieu = ngayTaoPhieu.getTime();
		}
		else {
			motCuaPhieuXuLyChinhCacheModel.ngayTaoPhieu = Long.MIN_VALUE;
		}

		motCuaPhieuXuLyChinhCacheModel.nguoiTaoPhieu = getNguoiTaoPhieu();

		motCuaPhieuXuLyChinhCacheModel.soDtcdNguoiNop = getSoDtcdNguoiNop();

		String soDtcdNguoiNop = motCuaPhieuXuLyChinhCacheModel.soDtcdNguoiNop;

		if ((soDtcdNguoiNop != null) && (soDtcdNguoiNop.length() == 0)) {
			motCuaPhieuXuLyChinhCacheModel.soDtcdNguoiNop = null;
		}

		return motCuaPhieuXuLyChinhCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(31);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", hoSoThuTucId=");
		sb.append(getHoSoThuTucId());
		sb.append(", quyTrinhThuTucId=");
		sb.append(getQuyTrinhThuTucId());
		sb.append(", tenNguoiNop=");
		sb.append(getTenNguoiNop());
		sb.append(", cmndNguoiNop=");
		sb.append(getCmndNguoiNop());
		sb.append(", diaChiNguoiNop=");
		sb.append(getDiaChiNguoiNop());
		sb.append(", soDtddNguoiNop=");
		sb.append(getSoDtddNguoiNop());
		sb.append(", emailNguoiNop=");
		sb.append(getEmailNguoiNop());
		sb.append(", ghiChu=");
		sb.append(getGhiChu());
		sb.append(", trangThaiHienTaiId=");
		sb.append(getTrangThaiHienTaiId());
		sb.append(", hetHoSoCon=");
		sb.append(getHetHoSoCon());
		sb.append(", chiemQuyenXuLy=");
		sb.append(getChiemQuyenXuLy());
		sb.append(", ngayTaoPhieu=");
		sb.append(getNgayTaoPhieu());
		sb.append(", nguoiTaoPhieu=");
		sb.append(getNguoiTaoPhieu());
		sb.append(", soDtcdNguoiNop=");
		sb.append(getSoDtcdNguoiNop());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(49);

		sb.append("<model><model-name>");
		sb.append("vn.dtt.gt.dk.dao.motcua.model.MotCuaPhieuXuLyChinh");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>hoSoThuTucId</column-name><column-value><![CDATA[");
		sb.append(getHoSoThuTucId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>quyTrinhThuTucId</column-name><column-value><![CDATA[");
		sb.append(getQuyTrinhThuTucId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tenNguoiNop</column-name><column-value><![CDATA[");
		sb.append(getTenNguoiNop());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>cmndNguoiNop</column-name><column-value><![CDATA[");
		sb.append(getCmndNguoiNop());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>diaChiNguoiNop</column-name><column-value><![CDATA[");
		sb.append(getDiaChiNguoiNop());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>soDtddNguoiNop</column-name><column-value><![CDATA[");
		sb.append(getSoDtddNguoiNop());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>emailNguoiNop</column-name><column-value><![CDATA[");
		sb.append(getEmailNguoiNop());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ghiChu</column-name><column-value><![CDATA[");
		sb.append(getGhiChu());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>trangThaiHienTaiId</column-name><column-value><![CDATA[");
		sb.append(getTrangThaiHienTaiId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>hetHoSoCon</column-name><column-value><![CDATA[");
		sb.append(getHetHoSoCon());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>chiemQuyenXuLy</column-name><column-value><![CDATA[");
		sb.append(getChiemQuyenXuLy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayTaoPhieu</column-name><column-value><![CDATA[");
		sb.append(getNgayTaoPhieu());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nguoiTaoPhieu</column-name><column-value><![CDATA[");
		sb.append(getNguoiTaoPhieu());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>soDtcdNguoiNop</column-name><column-value><![CDATA[");
		sb.append(getSoDtcdNguoiNop());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = MotCuaPhieuXuLyChinh.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			MotCuaPhieuXuLyChinh.class
		};
	private long _id;
	private long _hoSoThuTucId;
	private long _originalHoSoThuTucId;
	private boolean _setOriginalHoSoThuTucId;
	private long _quyTrinhThuTucId;
	private long _originalQuyTrinhThuTucId;
	private boolean _setOriginalQuyTrinhThuTucId;
	private String _tenNguoiNop;
	private String _cmndNguoiNop;
	private String _diaChiNguoiNop;
	private String _soDtddNguoiNop;
	private String _emailNguoiNop;
	private String _ghiChu;
	private long _trangThaiHienTaiId;
	private long _hetHoSoCon;
	private long _chiemQuyenXuLy;
	private Date _ngayTaoPhieu;
	private long _nguoiTaoPhieu;
	private String _soDtcdNguoiNop;
	private long _columnBitmask;
	private MotCuaPhieuXuLyChinh _escapedModel;
}