/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.gt.dk.dao.motcua.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the MotCuaKetQuaDienBien service. Represents a row in the &quot;motcua_ketquadienbien&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.dtt.gt.dk.dao.motcua.model.impl.MotCuaKetQuaDienBienModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.dtt.gt.dk.dao.motcua.model.impl.MotCuaKetQuaDienBienImpl}.
 * </p>
 *
 * @author huymq
 * @see MotCuaKetQuaDienBien
 * @see vn.dtt.gt.dk.dao.motcua.model.impl.MotCuaKetQuaDienBienImpl
 * @see vn.dtt.gt.dk.dao.motcua.model.impl.MotCuaKetQuaDienBienModelImpl
 * @generated
 */
public interface MotCuaKetQuaDienBienModel extends BaseModel<MotCuaKetQuaDienBien> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a mot cua ket qua dien bien model instance should use the {@link MotCuaKetQuaDienBien} interface instead.
	 */

	/**
	 * Returns the primary key of this mot cua ket qua dien bien.
	 *
	 * @return the primary key of this mot cua ket qua dien bien
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this mot cua ket qua dien bien.
	 *
	 * @param primaryKey the primary key of this mot cua ket qua dien bien
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this mot cua ket qua dien bien.
	 *
	 * @return the ID of this mot cua ket qua dien bien
	 */
	public long getId();

	/**
	 * Sets the ID of this mot cua ket qua dien bien.
	 *
	 * @param id the ID of this mot cua ket qua dien bien
	 */
	public void setId(long id);

	/**
	 * Returns the dien bien ho so ID of this mot cua ket qua dien bien.
	 *
	 * @return the dien bien ho so ID of this mot cua ket qua dien bien
	 */
	public long getDienBienHoSoId();

	/**
	 * Sets the dien bien ho so ID of this mot cua ket qua dien bien.
	 *
	 * @param dienBienHoSoId the dien bien ho so ID of this mot cua ket qua dien bien
	 */
	public void setDienBienHoSoId(long dienBienHoSoId);

	/**
	 * Returns the noi dung ho so ID of this mot cua ket qua dien bien.
	 *
	 * @return the noi dung ho so ID of this mot cua ket qua dien bien
	 */
	public long getNoiDungHoSoId();

	/**
	 * Sets the noi dung ho so ID of this mot cua ket qua dien bien.
	 *
	 * @param noiDungHoSoId the noi dung ho so ID of this mot cua ket qua dien bien
	 */
	public void setNoiDungHoSoId(long noiDungHoSoId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(MotCuaKetQuaDienBien motCuaKetQuaDienBien);

	@Override
	public int hashCode();

	@Override
	public CacheModel<MotCuaKetQuaDienBien> toCacheModel();

	@Override
	public MotCuaKetQuaDienBien toEscapedModel();

	@Override
	public MotCuaKetQuaDienBien toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}