/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.gt.dk.dao.motcua.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the ThamSoHeThong service. Represents a row in the &quot;cmon_thamsohethong&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.dtt.gt.dk.dao.motcua.model.impl.ThamSoHeThongModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.dtt.gt.dk.dao.motcua.model.impl.ThamSoHeThongImpl}.
 * </p>
 *
 * @author huymq
 * @see ThamSoHeThong
 * @see vn.dtt.gt.dk.dao.motcua.model.impl.ThamSoHeThongImpl
 * @see vn.dtt.gt.dk.dao.motcua.model.impl.ThamSoHeThongModelImpl
 * @generated
 */
public interface ThamSoHeThongModel extends BaseModel<ThamSoHeThong> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a tham so he thong model instance should use the {@link ThamSoHeThong} interface instead.
	 */

	/**
	 * Returns the primary key of this tham so he thong.
	 *
	 * @return the primary key of this tham so he thong
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this tham so he thong.
	 *
	 * @param primaryKey the primary key of this tham so he thong
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this tham so he thong.
	 *
	 * @return the ID of this tham so he thong
	 */
	public long getId();

	/**
	 * Sets the ID of this tham so he thong.
	 *
	 * @param id the ID of this tham so he thong
	 */
	public void setId(long id);

	/**
	 * Returns the value data of this tham so he thong.
	 *
	 * @return the value data of this tham so he thong
	 */
	@AutoEscape
	public String getValueData();

	/**
	 * Sets the value data of this tham so he thong.
	 *
	 * @param valueData the value data of this tham so he thong
	 */
	public void setValueData(String valueData);

	/**
	 * Returns the key data of this tham so he thong.
	 *
	 * @return the key data of this tham so he thong
	 */
	@AutoEscape
	public String getKeyData();

	/**
	 * Sets the key data of this tham so he thong.
	 *
	 * @param keyData the key data of this tham so he thong
	 */
	public void setKeyData(String keyData);

	/**
	 * Returns the description of this tham so he thong.
	 *
	 * @return the description of this tham so he thong
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this tham so he thong.
	 *
	 * @param description the description of this tham so he thong
	 */
	public void setDescription(String description);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ThamSoHeThong thamSoHeThong);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ThamSoHeThong> toCacheModel();

	@Override
	public ThamSoHeThong toEscapedModel();

	@Override
	public ThamSoHeThong toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}