/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.gt.dk.dao.common.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import vn.dtt.gt.dk.dao.common.model.TthcPhanNhomHoSoVaiTro;
import vn.dtt.gt.dk.dao.common.service.TthcPhanNhomHoSoVaiTroLocalServiceUtil;

/**
 * The extended model base implementation for the TthcPhanNhomHoSoVaiTro service. Represents a row in the &quot;tthc_phannhomhoso_vaitro&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TthcPhanNhomHoSoVaiTroImpl}.
 * </p>
 *
 * @author huymq
 * @see TthcPhanNhomHoSoVaiTroImpl
 * @see vn.dtt.gt.dk.dao.common.model.TthcPhanNhomHoSoVaiTro
 * @generated
 */
public abstract class TthcPhanNhomHoSoVaiTroBaseImpl
	extends TthcPhanNhomHoSoVaiTroModelImpl implements TthcPhanNhomHoSoVaiTro {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a tthc phan nhom ho so vai tro model instance should use the {@link TthcPhanNhomHoSoVaiTro} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			TthcPhanNhomHoSoVaiTroLocalServiceUtil.addTthcPhanNhomHoSoVaiTro(this);
		}
		else {
			TthcPhanNhomHoSoVaiTroLocalServiceUtil.updateTthcPhanNhomHoSoVaiTro(this);
		}
	}
}