/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.gt.dk.dao.common.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import vn.dtt.gt.dk.dao.common.model.TthcDonViThucHien;
import vn.dtt.gt.dk.dao.common.model.TthcDonViThucHienModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the TthcDonViThucHien service. Represents a row in the &quot;tthc_donvithuchien&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link vn.dtt.gt.dk.dao.common.model.TthcDonViThucHienModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TthcDonViThucHienImpl}.
 * </p>
 *
 * @author win_64
 * @see TthcDonViThucHienImpl
 * @see vn.dtt.gt.dk.dao.common.model.TthcDonViThucHien
 * @see vn.dtt.gt.dk.dao.common.model.TthcDonViThucHienModel
 * @generated
 */
public class TthcDonViThucHienModelImpl extends BaseModelImpl<TthcDonViThucHien>
	implements TthcDonViThucHienModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a tthc don vi thuc hien model instance should use the {@link vn.dtt.gt.dk.dao.common.model.TthcDonViThucHien} interface instead.
	 */
	public static final String TABLE_NAME = "tthc_donvithuchien";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id", Types.BIGINT },
			{ "thutuchanhchinhid", Types.BIGINT },
			{ "madvth", Types.VARCHAR },
			{ "tendvth", Types.VARCHAR },
			{ "tentienganh", Types.VARCHAR },
			{ "tochuc", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table tthc_donvithuchien (id LONG not null primary key,thutuchanhchinhid LONG,madvth VARCHAR(75) null,tendvth VARCHAR(75) null,tentienganh VARCHAR(75) null,tochuc LONG)";
	public static final String TABLE_SQL_DROP = "drop table tthc_donvithuchien";
	public static final String ORDER_BY_JPQL = " ORDER BY tthcDonViThucHien.Id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY tthc_donvithuchien.id ASC";
	public static final String DATA_SOURCE = "tthcDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.vn.dtt.gt.dk.dao.common.model.TthcDonViThucHien"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.vn.dtt.gt.dk.dao.common.model.TthcDonViThucHien"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.vn.dtt.gt.dk.dao.common.model.TthcDonViThucHien"));

	public TthcDonViThucHienModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _Id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _Id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return TthcDonViThucHien.class;
	}

	@Override
	public String getModelClassName() {
		return TthcDonViThucHien.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("Id", getId());
		attributes.put("ThuTucHanhChinhId", getThuTucHanhChinhId());
		attributes.put("MaDvth", getMaDvth());
		attributes.put("TenDvth", getTenDvth());
		attributes.put("TenTiengAnh", getTenTiengAnh());
		attributes.put("ToChuc", getToChuc());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long Id = (Long)attributes.get("Id");

		if (Id != null) {
			setId(Id);
		}

		Long ThuTucHanhChinhId = (Long)attributes.get("ThuTucHanhChinhId");

		if (ThuTucHanhChinhId != null) {
			setThuTucHanhChinhId(ThuTucHanhChinhId);
		}

		String MaDvth = (String)attributes.get("MaDvth");

		if (MaDvth != null) {
			setMaDvth(MaDvth);
		}

		String TenDvth = (String)attributes.get("TenDvth");

		if (TenDvth != null) {
			setTenDvth(TenDvth);
		}

		String TenTiengAnh = (String)attributes.get("TenTiengAnh");

		if (TenTiengAnh != null) {
			setTenTiengAnh(TenTiengAnh);
		}

		Long ToChuc = (Long)attributes.get("ToChuc");

		if (ToChuc != null) {
			setToChuc(ToChuc);
		}
	}

	@Override
	public long getId() {
		return _Id;
	}

	@Override
	public void setId(long Id) {
		_Id = Id;
	}

	@Override
	public long getThuTucHanhChinhId() {
		return _ThuTucHanhChinhId;
	}

	@Override
	public void setThuTucHanhChinhId(long ThuTucHanhChinhId) {
		_ThuTucHanhChinhId = ThuTucHanhChinhId;
	}

	@Override
	public String getMaDvth() {
		if (_MaDvth == null) {
			return StringPool.BLANK;
		}
		else {
			return _MaDvth;
		}
	}

	@Override
	public void setMaDvth(String MaDvth) {
		_MaDvth = MaDvth;
	}

	@Override
	public String getTenDvth() {
		if (_TenDvth == null) {
			return StringPool.BLANK;
		}
		else {
			return _TenDvth;
		}
	}

	@Override
	public void setTenDvth(String TenDvth) {
		_TenDvth = TenDvth;
	}

	@Override
	public String getTenTiengAnh() {
		if (_TenTiengAnh == null) {
			return StringPool.BLANK;
		}
		else {
			return _TenTiengAnh;
		}
	}

	@Override
	public void setTenTiengAnh(String TenTiengAnh) {
		_TenTiengAnh = TenTiengAnh;
	}

	@Override
	public long getToChuc() {
		return _ToChuc;
	}

	@Override
	public void setToChuc(long ToChuc) {
		_ToChuc = ToChuc;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			TthcDonViThucHien.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public TthcDonViThucHien toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (TthcDonViThucHien)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		TthcDonViThucHienImpl tthcDonViThucHienImpl = new TthcDonViThucHienImpl();

		tthcDonViThucHienImpl.setId(getId());
		tthcDonViThucHienImpl.setThuTucHanhChinhId(getThuTucHanhChinhId());
		tthcDonViThucHienImpl.setMaDvth(getMaDvth());
		tthcDonViThucHienImpl.setTenDvth(getTenDvth());
		tthcDonViThucHienImpl.setTenTiengAnh(getTenTiengAnh());
		tthcDonViThucHienImpl.setToChuc(getToChuc());

		tthcDonViThucHienImpl.resetOriginalValues();

		return tthcDonViThucHienImpl;
	}

	@Override
	public int compareTo(TthcDonViThucHien tthcDonViThucHien) {
		int value = 0;

		if (getId() < tthcDonViThucHien.getId()) {
			value = -1;
		}
		else if (getId() > tthcDonViThucHien.getId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof TthcDonViThucHien)) {
			return false;
		}

		TthcDonViThucHien tthcDonViThucHien = (TthcDonViThucHien)obj;

		long primaryKey = tthcDonViThucHien.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<TthcDonViThucHien> toCacheModel() {
		TthcDonViThucHienCacheModel tthcDonViThucHienCacheModel = new TthcDonViThucHienCacheModel();

		tthcDonViThucHienCacheModel.Id = getId();

		tthcDonViThucHienCacheModel.ThuTucHanhChinhId = getThuTucHanhChinhId();

		tthcDonViThucHienCacheModel.MaDvth = getMaDvth();

		String MaDvth = tthcDonViThucHienCacheModel.MaDvth;

		if ((MaDvth != null) && (MaDvth.length() == 0)) {
			tthcDonViThucHienCacheModel.MaDvth = null;
		}

		tthcDonViThucHienCacheModel.TenDvth = getTenDvth();

		String TenDvth = tthcDonViThucHienCacheModel.TenDvth;

		if ((TenDvth != null) && (TenDvth.length() == 0)) {
			tthcDonViThucHienCacheModel.TenDvth = null;
		}

		tthcDonViThucHienCacheModel.TenTiengAnh = getTenTiengAnh();

		String TenTiengAnh = tthcDonViThucHienCacheModel.TenTiengAnh;

		if ((TenTiengAnh != null) && (TenTiengAnh.length() == 0)) {
			tthcDonViThucHienCacheModel.TenTiengAnh = null;
		}

		tthcDonViThucHienCacheModel.ToChuc = getToChuc();

		return tthcDonViThucHienCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(13);

		sb.append("{Id=");
		sb.append(getId());
		sb.append(", ThuTucHanhChinhId=");
		sb.append(getThuTucHanhChinhId());
		sb.append(", MaDvth=");
		sb.append(getMaDvth());
		sb.append(", TenDvth=");
		sb.append(getTenDvth());
		sb.append(", TenTiengAnh=");
		sb.append(getTenTiengAnh());
		sb.append(", ToChuc=");
		sb.append(getToChuc());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(22);

		sb.append("<model><model-name>");
		sb.append("vn.dtt.gt.dk.dao.common.model.TthcDonViThucHien");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>Id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ThuTucHanhChinhId</column-name><column-value><![CDATA[");
		sb.append(getThuTucHanhChinhId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>MaDvth</column-name><column-value><![CDATA[");
		sb.append(getMaDvth());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>TenDvth</column-name><column-value><![CDATA[");
		sb.append(getTenDvth());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>TenTiengAnh</column-name><column-value><![CDATA[");
		sb.append(getTenTiengAnh());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ToChuc</column-name><column-value><![CDATA[");
		sb.append(getToChuc());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = TthcDonViThucHien.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			TthcDonViThucHien.class
		};
	private long _Id;
	private long _ThuTucHanhChinhId;
	private String _MaDvth;
	private String _TenDvth;
	private String _TenTiengAnh;
	private long _ToChuc;
	private TthcDonViThucHien _escapedModel;
}