/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.gt.dk.dao.common.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import vn.dtt.gt.dk.dao.common.model.TthcCoQuanQltt;
import vn.dtt.gt.dk.dao.common.service.TthcCoQuanQlttLocalServiceUtil;

/**
 * The extended model base implementation for the TthcCoQuanQltt service. Represents a row in the &quot;tthc_coquanqltt&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TthcCoQuanQlttImpl}.
 * </p>
 *
 * @author win_64
 * @see TthcCoQuanQlttImpl
 * @see vn.dtt.gt.dk.dao.common.model.TthcCoQuanQltt
 * @generated
 */
public abstract class TthcCoQuanQlttBaseImpl extends TthcCoQuanQlttModelImpl
	implements TthcCoQuanQltt {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a tthc co quan qltt model instance should use the {@link TthcCoQuanQltt} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			TthcCoQuanQlttLocalServiceUtil.addTthcCoQuanQltt(this);
		}
		else {
			TthcCoQuanQlttLocalServiceUtil.updateTthcCoQuanQltt(this);
		}
	}
}