/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.gt.dk.dao.report.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the DocumentStatistics service. Represents a row in the &quot;rp_documentstatistics&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.dtt.gt.dk.dao.report.model.impl.DocumentStatisticsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.dtt.gt.dk.dao.report.model.impl.DocumentStatisticsImpl}.
 * </p>
 *
 * @author win_64
 * @see DocumentStatistics
 * @see vn.dtt.gt.dk.dao.report.model.impl.DocumentStatisticsImpl
 * @see vn.dtt.gt.dk.dao.report.model.impl.DocumentStatisticsModelImpl
 * @generated
 */
public interface DocumentStatisticsModel extends BaseModel<DocumentStatistics> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a document statistics model instance should use the {@link DocumentStatistics} interface instead.
	 */

	/**
	 * Returns the primary key of this document statistics.
	 *
	 * @return the primary key of this document statistics
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this document statistics.
	 *
	 * @param primaryKey the primary key of this document statistics
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this document statistics.
	 *
	 * @return the ID of this document statistics
	 */
	public long getId();

	/**
	 * Sets the ID of this document statistics.
	 *
	 * @param id the ID of this document statistics
	 */
	public void setId(long id);

	/**
	 * Returns the create date of this document statistics.
	 *
	 * @return the create date of this document statistics
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this document statistics.
	 *
	 * @param createDate the create date of this document statistics
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this document statistics.
	 *
	 * @return the modified date of this document statistics
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this document statistics.
	 *
	 * @param modifiedDate the modified date of this document statistics
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the document type code of this document statistics.
	 *
	 * @return the document type code of this document statistics
	 */
	@AutoEscape
	public String getDocumentTypeCode();

	/**
	 * Sets the document type code of this document statistics.
	 *
	 * @param documentTypeCode the document type code of this document statistics
	 */
	public void setDocumentTypeCode(String documentTypeCode);

	/**
	 * Returns the remaining number of this document statistics.
	 *
	 * @return the remaining number of this document statistics
	 */
	public long getRemainingNumber();

	/**
	 * Sets the remaining number of this document statistics.
	 *
	 * @param remainingNumber the remaining number of this document statistics
	 */
	public void setRemainingNumber(long remainingNumber);

	/**
	 * Returns the received number of this document statistics.
	 *
	 * @return the received number of this document statistics
	 */
	public long getReceivedNumber();

	/**
	 * Sets the received number of this document statistics.
	 *
	 * @param receivedNumber the received number of this document statistics
	 */
	public void setReceivedNumber(long receivedNumber);

	/**
	 * Returns the ontime number of this document statistics.
	 *
	 * @return the ontime number of this document statistics
	 */
	public long getOntimeNumber();

	/**
	 * Sets the ontime number of this document statistics.
	 *
	 * @param ontimeNumber the ontime number of this document statistics
	 */
	public void setOntimeNumber(long ontimeNumber);

	/**
	 * Returns the overtime number of this document statistics.
	 *
	 * @return the overtime number of this document statistics
	 */
	public long getOvertimeNumber();

	/**
	 * Sets the overtime number of this document statistics.
	 *
	 * @param overtimeNumber the overtime number of this document statistics
	 */
	public void setOvertimeNumber(long overtimeNumber);

	/**
	 * Returns the processing number of this document statistics.
	 *
	 * @return the processing number of this document statistics
	 */
	public long getProcessingNumber();

	/**
	 * Sets the processing number of this document statistics.
	 *
	 * @param processingNumber the processing number of this document statistics
	 */
	public void setProcessingNumber(long processingNumber);

	/**
	 * Returns the delaying number of this document statistics.
	 *
	 * @return the delaying number of this document statistics
	 */
	public long getDelayingNumber();

	/**
	 * Sets the delaying number of this document statistics.
	 *
	 * @param delayingNumber the delaying number of this document statistics
	 */
	public void setDelayingNumber(long delayingNumber);

	/**
	 * Returns the month of this document statistics.
	 *
	 * @return the month of this document statistics
	 */
	public int getMonth();

	/**
	 * Sets the month of this document statistics.
	 *
	 * @param month the month of this document statistics
	 */
	public void setMonth(int month);

	/**
	 * Returns the year of this document statistics.
	 *
	 * @return the year of this document statistics
	 */
	public int getYear();

	/**
	 * Sets the year of this document statistics.
	 *
	 * @param year the year of this document statistics
	 */
	public void setYear(int year);

	/**
	 * Returns the status of this document statistics.
	 *
	 * @return the status of this document statistics
	 */
	public int getStatus();

	/**
	 * Sets the status of this document statistics.
	 *
	 * @param status the status of this document statistics
	 */
	public void setStatus(int status);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(DocumentStatistics documentStatistics);

	@Override
	public int hashCode();

	@Override
	public CacheModel<DocumentStatistics> toCacheModel();

	@Override
	public DocumentStatistics toEscapedModel();

	@Override
	public DocumentStatistics toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}