/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.gt.dk.dao.common.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the TthcCoQuanQltt service. Represents a row in the &quot;tthc_coquanqltt&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.dtt.gt.dk.dao.common.model.impl.TthcCoQuanQlttModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.dtt.gt.dk.dao.common.model.impl.TthcCoQuanQlttImpl}.
 * </p>
 *
 * @author win_64
 * @see TthcCoQuanQltt
 * @see vn.dtt.gt.dk.dao.common.model.impl.TthcCoQuanQlttImpl
 * @see vn.dtt.gt.dk.dao.common.model.impl.TthcCoQuanQlttModelImpl
 * @generated
 */
public interface TthcCoQuanQlttModel extends BaseModel<TthcCoQuanQltt> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a tthc co quan qltt model instance should use the {@link TthcCoQuanQltt} interface instead.
	 */

	/**
	 * Returns the primary key of this tthc co quan qltt.
	 *
	 * @return the primary key of this tthc co quan qltt
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this tthc co quan qltt.
	 *
	 * @param primaryKey the primary key of this tthc co quan qltt
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this tthc co quan qltt.
	 *
	 * @return the ID of this tthc co quan qltt
	 */
	public long getId();

	/**
	 * Sets the ID of this tthc co quan qltt.
	 *
	 * @param Id the ID of this tthc co quan qltt
	 */
	public void setId(long Id);

	/**
	 * Returns the ten co quan qltt of this tthc co quan qltt.
	 *
	 * @return the ten co quan qltt of this tthc co quan qltt
	 */
	@AutoEscape
	public String getTenCoQuanQltt();

	/**
	 * Sets the ten co quan qltt of this tthc co quan qltt.
	 *
	 * @param TenCoQuanQltt the ten co quan qltt of this tthc co quan qltt
	 */
	public void setTenCoQuanQltt(String TenCoQuanQltt);

	/**
	 * Returns the ten tieng anh of this tthc co quan qltt.
	 *
	 * @return the ten tieng anh of this tthc co quan qltt
	 */
	@AutoEscape
	public String getTenTiengAnh();

	/**
	 * Sets the ten tieng anh of this tthc co quan qltt.
	 *
	 * @param TenTiengAnh the ten tieng anh of this tthc co quan qltt
	 */
	public void setTenTiengAnh(String TenTiengAnh);

	/**
	 * Returns the id cha of this tthc co quan qltt.
	 *
	 * @return the id cha of this tthc co quan qltt
	 */
	public long getIdCha();

	/**
	 * Sets the id cha of this tthc co quan qltt.
	 *
	 * @param IdCha the id cha of this tthc co quan qltt
	 */
	public void setIdCha(long IdCha);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		vn.dtt.gt.dk.dao.common.model.TthcCoQuanQltt tthcCoQuanQltt);

	@Override
	public int hashCode();

	@Override
	public CacheModel<vn.dtt.gt.dk.dao.common.model.TthcCoQuanQltt> toCacheModel();

	@Override
	public vn.dtt.gt.dk.dao.common.model.TthcCoQuanQltt toEscapedModel();

	@Override
	public vn.dtt.gt.dk.dao.common.model.TthcCoQuanQltt toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}