/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.gt.dk.dao.common.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the TthcBieuMauHoSo service. Represents a row in the &quot;tthc_bieumauhoso&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.dtt.gt.dk.dao.common.model.impl.TthcBieuMauHoSoModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.dtt.gt.dk.dao.common.model.impl.TthcBieuMauHoSoImpl}.
 * </p>
 *
 * @author win_64
 * @see TthcBieuMauHoSo
 * @see vn.dtt.gt.dk.dao.common.model.impl.TthcBieuMauHoSoImpl
 * @see vn.dtt.gt.dk.dao.common.model.impl.TthcBieuMauHoSoModelImpl
 * @generated
 */
public interface TthcBieuMauHoSoModel extends BaseModel<TthcBieuMauHoSo> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a tthc bieu mau ho so model instance should use the {@link TthcBieuMauHoSo} interface instead.
	 */

	/**
	 * Returns the primary key of this tthc bieu mau ho so.
	 *
	 * @return the primary key of this tthc bieu mau ho so
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this tthc bieu mau ho so.
	 *
	 * @param primaryKey the primary key of this tthc bieu mau ho so
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this tthc bieu mau ho so.
	 *
	 * @return the ID of this tthc bieu mau ho so
	 */
	public long getId();

	/**
	 * Sets the ID of this tthc bieu mau ho so.
	 *
	 * @param Id the ID of this tthc bieu mau ho so
	 */
	public void setId(long Id);

	/**
	 * Returns the ma bieu mau of this tthc bieu mau ho so.
	 *
	 * @return the ma bieu mau of this tthc bieu mau ho so
	 */
	@AutoEscape
	public String getMaBieuMau();

	/**
	 * Sets the ma bieu mau of this tthc bieu mau ho so.
	 *
	 * @param MaBieuMau the ma bieu mau of this tthc bieu mau ho so
	 */
	public void setMaBieuMau(String MaBieuMau);

	/**
	 * Returns the ten bieu mau of this tthc bieu mau ho so.
	 *
	 * @return the ten bieu mau of this tthc bieu mau ho so
	 */
	@AutoEscape
	public String getTenBieuMau();

	/**
	 * Sets the ten bieu mau of this tthc bieu mau ho so.
	 *
	 * @param TenBieuMau the ten bieu mau of this tthc bieu mau ho so
	 */
	public void setTenBieuMau(String TenBieuMau);

	/**
	 * Returns the ten tieng anh of this tthc bieu mau ho so.
	 *
	 * @return the ten tieng anh of this tthc bieu mau ho so
	 */
	@AutoEscape
	public String getTenTiengAnh();

	/**
	 * Sets the ten tieng anh of this tthc bieu mau ho so.
	 *
	 * @param TenTiengAnh the ten tieng anh of this tthc bieu mau ho so
	 */
	public void setTenTiengAnh(String TenTiengAnh);

	/**
	 * Returns the tai lieu mau of this tthc bieu mau ho so.
	 *
	 * @return the tai lieu mau of this tthc bieu mau ho so
	 */
	public long getTaiLieuMau();

	/**
	 * Sets the tai lieu mau of this tthc bieu mau ho so.
	 *
	 * @param TaiLieuMau the tai lieu mau of this tthc bieu mau ho so
	 */
	public void setTaiLieuMau(long TaiLieuMau);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		vn.dtt.gt.dk.dao.common.model.TthcBieuMauHoSo tthcBieuMauHoSo);

	@Override
	public int hashCode();

	@Override
	public CacheModel<vn.dtt.gt.dk.dao.common.model.TthcBieuMauHoSo> toCacheModel();

	@Override
	public vn.dtt.gt.dk.dao.common.model.TthcBieuMauHoSo toEscapedModel();

	@Override
	public vn.dtt.gt.dk.dao.common.model.TthcBieuMauHoSo toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}