/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.gt.dk.dao.common.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the TthcPhanNhomHoSoVaiTro service. Represents a row in the &quot;tthc_phannhomhoso_vaitro&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.dtt.gt.dk.dao.common.model.impl.TthcPhanNhomHoSoVaiTroModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.dtt.gt.dk.dao.common.model.impl.TthcPhanNhomHoSoVaiTroImpl}.
 * </p>
 *
 * @author win_64
 * @see TthcPhanNhomHoSoVaiTro
 * @see vn.dtt.gt.dk.dao.common.model.impl.TthcPhanNhomHoSoVaiTroImpl
 * @see vn.dtt.gt.dk.dao.common.model.impl.TthcPhanNhomHoSoVaiTroModelImpl
 * @generated
 */
public interface TthcPhanNhomHoSoVaiTroModel extends BaseModel<TthcPhanNhomHoSoVaiTro> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a tthc phan nhom ho so vai tro model instance should use the {@link TthcPhanNhomHoSoVaiTro} interface instead.
	 */

	/**
	 * Returns the primary key of this tthc phan nhom ho so vai tro.
	 *
	 * @return the primary key of this tthc phan nhom ho so vai tro
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this tthc phan nhom ho so vai tro.
	 *
	 * @param primaryKey the primary key of this tthc phan nhom ho so vai tro
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this tthc phan nhom ho so vai tro.
	 *
	 * @return the ID of this tthc phan nhom ho so vai tro
	 */
	public long getId();

	/**
	 * Sets the ID of this tthc phan nhom ho so vai tro.
	 *
	 * @param Id the ID of this tthc phan nhom ho so vai tro
	 */
	public void setId(long Id);

	/**
	 * Returns the phan nhom ho so ID of this tthc phan nhom ho so vai tro.
	 *
	 * @return the phan nhom ho so ID of this tthc phan nhom ho so vai tro
	 */
	public long getPhanNhomHoSoId();

	/**
	 * Sets the phan nhom ho so ID of this tthc phan nhom ho so vai tro.
	 *
	 * @param PhanNhomHoSoId the phan nhom ho so ID of this tthc phan nhom ho so vai tro
	 */
	public void setPhanNhomHoSoId(long PhanNhomHoSoId);

	/**
	 * Returns the vai tro xu ly of this tthc phan nhom ho so vai tro.
	 *
	 * @return the vai tro xu ly of this tthc phan nhom ho so vai tro
	 */
	public long getVaiTroXuLy();

	/**
	 * Sets the vai tro xu ly of this tthc phan nhom ho so vai tro.
	 *
	 * @param VaiTroXuLy the vai tro xu ly of this tthc phan nhom ho so vai tro
	 */
	public void setVaiTroXuLy(long VaiTroXuLy);

	/**
	 * Returns the nhom phieu xu ly of this tthc phan nhom ho so vai tro.
	 *
	 * @return the nhom phieu xu ly of this tthc phan nhom ho so vai tro
	 */
	@AutoEscape
	public String getNhomPhieuXuLy();

	/**
	 * Sets the nhom phieu xu ly of this tthc phan nhom ho so vai tro.
	 *
	 * @param nhomPhieuXuLy the nhom phieu xu ly of this tthc phan nhom ho so vai tro
	 */
	public void setNhomPhieuXuLy(String nhomPhieuXuLy);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(TthcPhanNhomHoSoVaiTro tthcPhanNhomHoSoVaiTro);

	@Override
	public int hashCode();

	@Override
	public CacheModel<TthcPhanNhomHoSoVaiTro> toCacheModel();

	@Override
	public TthcPhanNhomHoSoVaiTro toEscapedModel();

	@Override
	public TthcPhanNhomHoSoVaiTro toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}