/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.gt.dk.dao.nghiepvu.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import vn.dtt.gt.dk.dao.nghiepvu.model.EmissionTestRequest;
import vn.dtt.gt.dk.dao.nghiepvu.model.EmissionTestRequestModel;
import vn.dtt.gt.dk.dao.nghiepvu.model.EmissionTestRequestSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the EmissionTestRequest service. Represents a row in the &quot;vr_emissiontestrequest&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link vn.dtt.gt.dk.dao.nghiepvu.model.EmissionTestRequestModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EmissionTestRequestImpl}.
 * </p>
 *
 * @author huymq
 * @see EmissionTestRequestImpl
 * @see vn.dtt.gt.dk.dao.nghiepvu.model.EmissionTestRequest
 * @see vn.dtt.gt.dk.dao.nghiepvu.model.EmissionTestRequestModel
 * @generated
 */
@JSON(strict = true)
public class EmissionTestRequestModelImpl extends BaseModelImpl<EmissionTestRequest>
	implements EmissionTestRequestModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a emission test request model instance should use the {@link vn.dtt.gt.dk.dao.nghiepvu.model.EmissionTestRequest} interface instead.
	 */
	public static final String TABLE_NAME = "vr_emissiontestrequest";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id", Types.BIGINT },
			{ "confirmedinspectionid", Types.BIGINT },
			{ "requestnumber", Types.VARCHAR },
			{ "testtimeandplace", Types.VARCHAR },
			{ "testpayment", Types.VARCHAR },
			{ "remarks", Types.VARCHAR },
			{ "corporationname", Types.VARCHAR },
			{ "attachedfile", Types.BIGINT },
			{ "signname", Types.VARCHAR },
			{ "signtitle", Types.VARCHAR },
			{ "signplace", Types.VARCHAR },
			{ "signdate", Types.TIMESTAMP },
			{ "synchdate", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table vr_emissiontestrequest (id LONG not null primary key,confirmedinspectionid LONG,requestnumber VARCHAR(75) null,testtimeandplace VARCHAR(75) null,testpayment VARCHAR(75) null,remarks VARCHAR(75) null,corporationname VARCHAR(75) null,attachedfile LONG,signname VARCHAR(75) null,signtitle VARCHAR(75) null,signplace VARCHAR(75) null,signdate DATE null,synchdate DATE null)";
	public static final String TABLE_SQL_DROP = "drop table vr_emissiontestrequest";
	public static final String ORDER_BY_JPQL = " ORDER BY emissionTestRequest.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY vr_emissiontestrequest.id ASC";
	public static final String DATA_SOURCE = "vrDataSource";
	public static final String SESSION_FACTORY = "vrSessionFactory";
	public static final String TX_MANAGER = "vrTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.vn.dtt.gt.dk.dao.nghiepvu.model.EmissionTestRequest"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.vn.dtt.gt.dk.dao.nghiepvu.model.EmissionTestRequest"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static EmissionTestRequest toModel(EmissionTestRequestSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		EmissionTestRequest model = new EmissionTestRequestImpl();

		model.setId(soapModel.getId());
		model.setConfirmedInspectionId(soapModel.getConfirmedInspectionId());
		model.setRequestNumber(soapModel.getRequestNumber());
		model.setTestTimeAndPlace(soapModel.getTestTimeAndPlace());
		model.setTestPayment(soapModel.getTestPayment());
		model.setRemarks(soapModel.getRemarks());
		model.setCorporationName(soapModel.getCorporationName());
		model.setAttachedFile(soapModel.getAttachedFile());
		model.setSignName(soapModel.getSignName());
		model.setSignTitle(soapModel.getSignTitle());
		model.setSignPlace(soapModel.getSignPlace());
		model.setSignDate(soapModel.getSignDate());
		model.setSynchdate(soapModel.getSynchdate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<EmissionTestRequest> toModels(
		EmissionTestRequestSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<EmissionTestRequest> models = new ArrayList<EmissionTestRequest>(soapModels.length);

		for (EmissionTestRequestSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.vn.dtt.gt.dk.dao.nghiepvu.model.EmissionTestRequest"));

	public EmissionTestRequestModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return EmissionTestRequest.class;
	}

	@Override
	public String getModelClassName() {
		return EmissionTestRequest.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("confirmedInspectionId", getConfirmedInspectionId());
		attributes.put("requestNumber", getRequestNumber());
		attributes.put("testTimeAndPlace", getTestTimeAndPlace());
		attributes.put("testPayment", getTestPayment());
		attributes.put("remarks", getRemarks());
		attributes.put("corporationName", getCorporationName());
		attributes.put("attachedFile", getAttachedFile());
		attributes.put("signName", getSignName());
		attributes.put("signTitle", getSignTitle());
		attributes.put("signPlace", getSignPlace());
		attributes.put("signDate", getSignDate());
		attributes.put("synchdate", getSynchdate());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id = (Long)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		Long confirmedInspectionId = (Long)attributes.get(
				"confirmedInspectionId");

		if (confirmedInspectionId != null) {
			setConfirmedInspectionId(confirmedInspectionId);
		}

		String requestNumber = (String)attributes.get("requestNumber");

		if (requestNumber != null) {
			setRequestNumber(requestNumber);
		}

		String testTimeAndPlace = (String)attributes.get("testTimeAndPlace");

		if (testTimeAndPlace != null) {
			setTestTimeAndPlace(testTimeAndPlace);
		}

		String testPayment = (String)attributes.get("testPayment");

		if (testPayment != null) {
			setTestPayment(testPayment);
		}

		String remarks = (String)attributes.get("remarks");

		if (remarks != null) {
			setRemarks(remarks);
		}

		String corporationName = (String)attributes.get("corporationName");

		if (corporationName != null) {
			setCorporationName(corporationName);
		}

		Long attachedFile = (Long)attributes.get("attachedFile");

		if (attachedFile != null) {
			setAttachedFile(attachedFile);
		}

		String signName = (String)attributes.get("signName");

		if (signName != null) {
			setSignName(signName);
		}

		String signTitle = (String)attributes.get("signTitle");

		if (signTitle != null) {
			setSignTitle(signTitle);
		}

		String signPlace = (String)attributes.get("signPlace");

		if (signPlace != null) {
			setSignPlace(signPlace);
		}

		Date signDate = (Date)attributes.get("signDate");

		if (signDate != null) {
			setSignDate(signDate);
		}

		Date synchdate = (Date)attributes.get("synchdate");

		if (synchdate != null) {
			setSynchdate(synchdate);
		}
	}

	@JSON
	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		_id = id;
	}

	@JSON
	@Override
	public long getConfirmedInspectionId() {
		return _confirmedInspectionId;
	}

	@Override
	public void setConfirmedInspectionId(long confirmedInspectionId) {
		_confirmedInspectionId = confirmedInspectionId;
	}

	@JSON
	@Override
	public String getRequestNumber() {
		if (_requestNumber == null) {
			return StringPool.BLANK;
		}
		else {
			return _requestNumber;
		}
	}

	@Override
	public void setRequestNumber(String requestNumber) {
		_requestNumber = requestNumber;
	}

	@JSON
	@Override
	public String getTestTimeAndPlace() {
		if (_testTimeAndPlace == null) {
			return StringPool.BLANK;
		}
		else {
			return _testTimeAndPlace;
		}
	}

	@Override
	public void setTestTimeAndPlace(String testTimeAndPlace) {
		_testTimeAndPlace = testTimeAndPlace;
	}

	@JSON
	@Override
	public String getTestPayment() {
		if (_testPayment == null) {
			return StringPool.BLANK;
		}
		else {
			return _testPayment;
		}
	}

	@Override
	public void setTestPayment(String testPayment) {
		_testPayment = testPayment;
	}

	@JSON
	@Override
	public String getRemarks() {
		if (_remarks == null) {
			return StringPool.BLANK;
		}
		else {
			return _remarks;
		}
	}

	@Override
	public void setRemarks(String remarks) {
		_remarks = remarks;
	}

	@JSON
	@Override
	public String getCorporationName() {
		if (_corporationName == null) {
			return StringPool.BLANK;
		}
		else {
			return _corporationName;
		}
	}

	@Override
	public void setCorporationName(String corporationName) {
		_corporationName = corporationName;
	}

	@JSON
	@Override
	public long getAttachedFile() {
		return _attachedFile;
	}

	@Override
	public void setAttachedFile(long attachedFile) {
		_attachedFile = attachedFile;
	}

	@JSON
	@Override
	public String getSignName() {
		if (_signName == null) {
			return StringPool.BLANK;
		}
		else {
			return _signName;
		}
	}

	@Override
	public void setSignName(String signName) {
		_signName = signName;
	}

	@JSON
	@Override
	public String getSignTitle() {
		if (_signTitle == null) {
			return StringPool.BLANK;
		}
		else {
			return _signTitle;
		}
	}

	@Override
	public void setSignTitle(String signTitle) {
		_signTitle = signTitle;
	}

	@JSON
	@Override
	public String getSignPlace() {
		if (_signPlace == null) {
			return StringPool.BLANK;
		}
		else {
			return _signPlace;
		}
	}

	@Override
	public void setSignPlace(String signPlace) {
		_signPlace = signPlace;
	}

	@JSON
	@Override
	public Date getSignDate() {
		return _signDate;
	}

	@Override
	public void setSignDate(Date signDate) {
		_signDate = signDate;
	}

	@JSON
	@Override
	public Date getSynchdate() {
		return _synchdate;
	}

	@Override
	public void setSynchdate(Date synchdate) {
		_synchdate = synchdate;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			EmissionTestRequest.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public EmissionTestRequest toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (EmissionTestRequest)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		EmissionTestRequestImpl emissionTestRequestImpl = new EmissionTestRequestImpl();

		emissionTestRequestImpl.setId(getId());
		emissionTestRequestImpl.setConfirmedInspectionId(getConfirmedInspectionId());
		emissionTestRequestImpl.setRequestNumber(getRequestNumber());
		emissionTestRequestImpl.setTestTimeAndPlace(getTestTimeAndPlace());
		emissionTestRequestImpl.setTestPayment(getTestPayment());
		emissionTestRequestImpl.setRemarks(getRemarks());
		emissionTestRequestImpl.setCorporationName(getCorporationName());
		emissionTestRequestImpl.setAttachedFile(getAttachedFile());
		emissionTestRequestImpl.setSignName(getSignName());
		emissionTestRequestImpl.setSignTitle(getSignTitle());
		emissionTestRequestImpl.setSignPlace(getSignPlace());
		emissionTestRequestImpl.setSignDate(getSignDate());
		emissionTestRequestImpl.setSynchdate(getSynchdate());

		emissionTestRequestImpl.resetOriginalValues();

		return emissionTestRequestImpl;
	}

	@Override
	public int compareTo(EmissionTestRequest emissionTestRequest) {
		int value = 0;

		if (getId() < emissionTestRequest.getId()) {
			value = -1;
		}
		else if (getId() > emissionTestRequest.getId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof EmissionTestRequest)) {
			return false;
		}

		EmissionTestRequest emissionTestRequest = (EmissionTestRequest)obj;

		long primaryKey = emissionTestRequest.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<EmissionTestRequest> toCacheModel() {
		EmissionTestRequestCacheModel emissionTestRequestCacheModel = new EmissionTestRequestCacheModel();

		emissionTestRequestCacheModel.id = getId();

		emissionTestRequestCacheModel.confirmedInspectionId = getConfirmedInspectionId();

		emissionTestRequestCacheModel.requestNumber = getRequestNumber();

		String requestNumber = emissionTestRequestCacheModel.requestNumber;

		if ((requestNumber != null) && (requestNumber.length() == 0)) {
			emissionTestRequestCacheModel.requestNumber = null;
		}

		emissionTestRequestCacheModel.testTimeAndPlace = getTestTimeAndPlace();

		String testTimeAndPlace = emissionTestRequestCacheModel.testTimeAndPlace;

		if ((testTimeAndPlace != null) && (testTimeAndPlace.length() == 0)) {
			emissionTestRequestCacheModel.testTimeAndPlace = null;
		}

		emissionTestRequestCacheModel.testPayment = getTestPayment();

		String testPayment = emissionTestRequestCacheModel.testPayment;

		if ((testPayment != null) && (testPayment.length() == 0)) {
			emissionTestRequestCacheModel.testPayment = null;
		}

		emissionTestRequestCacheModel.remarks = getRemarks();

		String remarks = emissionTestRequestCacheModel.remarks;

		if ((remarks != null) && (remarks.length() == 0)) {
			emissionTestRequestCacheModel.remarks = null;
		}

		emissionTestRequestCacheModel.corporationName = getCorporationName();

		String corporationName = emissionTestRequestCacheModel.corporationName;

		if ((corporationName != null) && (corporationName.length() == 0)) {
			emissionTestRequestCacheModel.corporationName = null;
		}

		emissionTestRequestCacheModel.attachedFile = getAttachedFile();

		emissionTestRequestCacheModel.signName = getSignName();

		String signName = emissionTestRequestCacheModel.signName;

		if ((signName != null) && (signName.length() == 0)) {
			emissionTestRequestCacheModel.signName = null;
		}

		emissionTestRequestCacheModel.signTitle = getSignTitle();

		String signTitle = emissionTestRequestCacheModel.signTitle;

		if ((signTitle != null) && (signTitle.length() == 0)) {
			emissionTestRequestCacheModel.signTitle = null;
		}

		emissionTestRequestCacheModel.signPlace = getSignPlace();

		String signPlace = emissionTestRequestCacheModel.signPlace;

		if ((signPlace != null) && (signPlace.length() == 0)) {
			emissionTestRequestCacheModel.signPlace = null;
		}

		Date signDate = getSignDate();

		if (signDate != null) {
			emissionTestRequestCacheModel.signDate = signDate.getTime();
		}
		else {
			emissionTestRequestCacheModel.signDate = Long.MIN_VALUE;
		}

		Date synchdate = getSynchdate();

		if (synchdate != null) {
			emissionTestRequestCacheModel.synchdate = synchdate.getTime();
		}
		else {
			emissionTestRequestCacheModel.synchdate = Long.MIN_VALUE;
		}

		return emissionTestRequestCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(27);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", confirmedInspectionId=");
		sb.append(getConfirmedInspectionId());
		sb.append(", requestNumber=");
		sb.append(getRequestNumber());
		sb.append(", testTimeAndPlace=");
		sb.append(getTestTimeAndPlace());
		sb.append(", testPayment=");
		sb.append(getTestPayment());
		sb.append(", remarks=");
		sb.append(getRemarks());
		sb.append(", corporationName=");
		sb.append(getCorporationName());
		sb.append(", attachedFile=");
		sb.append(getAttachedFile());
		sb.append(", signName=");
		sb.append(getSignName());
		sb.append(", signTitle=");
		sb.append(getSignTitle());
		sb.append(", signPlace=");
		sb.append(getSignPlace());
		sb.append(", signDate=");
		sb.append(getSignDate());
		sb.append(", synchdate=");
		sb.append(getSynchdate());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(43);

		sb.append("<model><model-name>");
		sb.append("vn.dtt.gt.dk.dao.nghiepvu.model.EmissionTestRequest");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>confirmedInspectionId</column-name><column-value><![CDATA[");
		sb.append(getConfirmedInspectionId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>requestNumber</column-name><column-value><![CDATA[");
		sb.append(getRequestNumber());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>testTimeAndPlace</column-name><column-value><![CDATA[");
		sb.append(getTestTimeAndPlace());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>testPayment</column-name><column-value><![CDATA[");
		sb.append(getTestPayment());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>remarks</column-name><column-value><![CDATA[");
		sb.append(getRemarks());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>corporationName</column-name><column-value><![CDATA[");
		sb.append(getCorporationName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>attachedFile</column-name><column-value><![CDATA[");
		sb.append(getAttachedFile());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>signName</column-name><column-value><![CDATA[");
		sb.append(getSignName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>signTitle</column-name><column-value><![CDATA[");
		sb.append(getSignTitle());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>signPlace</column-name><column-value><![CDATA[");
		sb.append(getSignPlace());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>signDate</column-name><column-value><![CDATA[");
		sb.append(getSignDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>synchdate</column-name><column-value><![CDATA[");
		sb.append(getSynchdate());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = EmissionTestRequest.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			EmissionTestRequest.class
		};
	private long _id;
	private long _confirmedInspectionId;
	private String _requestNumber;
	private String _testTimeAndPlace;
	private String _testPayment;
	private String _remarks;
	private String _corporationName;
	private long _attachedFile;
	private String _signName;
	private String _signTitle;
	private String _signPlace;
	private Date _signDate;
	private Date _synchdate;
	private EmissionTestRequest _escapedModel;
}