/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.gt.dk.dao.nghiepvu.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import vn.dtt.gt.dk.dao.nghiepvu.model.ActionLog;
import vn.dtt.gt.dk.dao.nghiepvu.model.ActionLogModel;
import vn.dtt.gt.dk.dao.nghiepvu.model.ActionLogSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the ActionLog service. Represents a row in the &quot;vr_action_log&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link vn.dtt.gt.dk.dao.nghiepvu.model.ActionLogModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ActionLogImpl}.
 * </p>
 *
 * @author win_64
 * @see ActionLogImpl
 * @see vn.dtt.gt.dk.dao.nghiepvu.model.ActionLog
 * @see vn.dtt.gt.dk.dao.nghiepvu.model.ActionLogModel
 * @generated
 */
@JSON(strict = true)
public class ActionLogModelImpl extends BaseModelImpl<ActionLog>
	implements ActionLogModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a action log model instance should use the {@link vn.dtt.gt.dk.dao.nghiepvu.model.ActionLog} interface instead.
	 */
	public static final String TABLE_NAME = "vr_action_log";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id", Types.BIGINT },
			{ "hosothutucid", Types.BIGINT },
			{ "masohoso", Types.VARCHAR },
			{ "mabiennhan", Types.VARCHAR },
			{ "ngayxemhoso", Types.TIMESTAMP },
			{ "noidungmanhinh", Types.VARCHAR },
			{ "importername", Types.VARCHAR },
			{ "corporationid", Types.VARCHAR },
			{ "inspectorid", Types.BIGINT },
			{ "inspectorname", Types.VARCHAR },
			{ "inspectorphone", Types.VARCHAR },
			{ "inspectoremail", Types.VARCHAR },
			{ "title", Types.VARCHAR },
			{ "contactcode", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table vr_action_log (id LONG not null primary key,hosothutucid LONG,masohoso VARCHAR(75) null,mabiennhan VARCHAR(75) null,ngayxemhoso DATE null,noidungmanhinh VARCHAR(75) null,importername VARCHAR(75) null,corporationid VARCHAR(75) null,inspectorid LONG,inspectorname VARCHAR(75) null,inspectorphone VARCHAR(75) null,inspectoremail VARCHAR(75) null,title VARCHAR(75) null,contactcode VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table vr_action_log";
	public static final String ORDER_BY_JPQL = " ORDER BY actionLog.id DESC";
	public static final String ORDER_BY_SQL = " ORDER BY vr_action_log.id DESC";
	public static final String DATA_SOURCE = "vrDataSource";
	public static final String SESSION_FACTORY = "vrSessionFactory";
	public static final String TX_MANAGER = "vrTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.vn.dtt.gt.dk.dao.nghiepvu.model.ActionLog"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.vn.dtt.gt.dk.dao.nghiepvu.model.ActionLog"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.vn.dtt.gt.dk.dao.nghiepvu.model.ActionLog"),
			true);
	public static long CONTACTCODE_COLUMN_BITMASK = 1L;
	public static long CORPORATIONID_COLUMN_BITMASK = 2L;
	public static long HOSOTHUTUCID_COLUMN_BITMASK = 4L;
	public static long IMPORTERNAME_COLUMN_BITMASK = 8L;
	public static long INSPECTORID_COLUMN_BITMASK = 16L;
	public static long MABIENNHAN_COLUMN_BITMASK = 32L;
	public static long MASOHOSO_COLUMN_BITMASK = 64L;
	public static long ID_COLUMN_BITMASK = 128L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static ActionLog toModel(ActionLogSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		ActionLog model = new ActionLogImpl();

		model.setId(soapModel.getId());
		model.setHosothutucid(soapModel.getHosothutucid());
		model.setMasohoso(soapModel.getMasohoso());
		model.setMabiennhan(soapModel.getMabiennhan());
		model.setNgayxemhoso(soapModel.getNgayxemhoso());
		model.setNoidungmanhinh(soapModel.getNoidungmanhinh());
		model.setImportername(soapModel.getImportername());
		model.setCorporationid(soapModel.getCorporationid());
		model.setInspectorid(soapModel.getInspectorid());
		model.setInspectorname(soapModel.getInspectorname());
		model.setInspectorphone(soapModel.getInspectorphone());
		model.setInspectoremail(soapModel.getInspectoremail());
		model.setTitle(soapModel.getTitle());
		model.setContactcode(soapModel.getContactcode());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<ActionLog> toModels(ActionLogSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<ActionLog> models = new ArrayList<ActionLog>(soapModels.length);

		for (ActionLogSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.vn.dtt.gt.dk.dao.nghiepvu.model.ActionLog"));

	public ActionLogModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ActionLog.class;
	}

	@Override
	public String getModelClassName() {
		return ActionLog.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("hosothutucid", getHosothutucid());
		attributes.put("masohoso", getMasohoso());
		attributes.put("mabiennhan", getMabiennhan());
		attributes.put("ngayxemhoso", getNgayxemhoso());
		attributes.put("noidungmanhinh", getNoidungmanhinh());
		attributes.put("importername", getImportername());
		attributes.put("corporationid", getCorporationid());
		attributes.put("inspectorid", getInspectorid());
		attributes.put("inspectorname", getInspectorname());
		attributes.put("inspectorphone", getInspectorphone());
		attributes.put("inspectoremail", getInspectoremail());
		attributes.put("title", getTitle());
		attributes.put("contactcode", getContactcode());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id = (Long)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		Long hosothutucid = (Long)attributes.get("hosothutucid");

		if (hosothutucid != null) {
			setHosothutucid(hosothutucid);
		}

		String masohoso = (String)attributes.get("masohoso");

		if (masohoso != null) {
			setMasohoso(masohoso);
		}

		String mabiennhan = (String)attributes.get("mabiennhan");

		if (mabiennhan != null) {
			setMabiennhan(mabiennhan);
		}

		Date ngayxemhoso = (Date)attributes.get("ngayxemhoso");

		if (ngayxemhoso != null) {
			setNgayxemhoso(ngayxemhoso);
		}

		String noidungmanhinh = (String)attributes.get("noidungmanhinh");

		if (noidungmanhinh != null) {
			setNoidungmanhinh(noidungmanhinh);
		}

		String importername = (String)attributes.get("importername");

		if (importername != null) {
			setImportername(importername);
		}

		String corporationid = (String)attributes.get("corporationid");

		if (corporationid != null) {
			setCorporationid(corporationid);
		}

		Long inspectorid = (Long)attributes.get("inspectorid");

		if (inspectorid != null) {
			setInspectorid(inspectorid);
		}

		String inspectorname = (String)attributes.get("inspectorname");

		if (inspectorname != null) {
			setInspectorname(inspectorname);
		}

		String inspectorphone = (String)attributes.get("inspectorphone");

		if (inspectorphone != null) {
			setInspectorphone(inspectorphone);
		}

		String inspectoremail = (String)attributes.get("inspectoremail");

		if (inspectoremail != null) {
			setInspectoremail(inspectoremail);
		}

		String title = (String)attributes.get("title");

		if (title != null) {
			setTitle(title);
		}

		String contactcode = (String)attributes.get("contactcode");

		if (contactcode != null) {
			setContactcode(contactcode);
		}
	}

	@JSON
	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		_columnBitmask = -1L;

		_id = id;
	}

	@JSON
	@Override
	public long getHosothutucid() {
		return _hosothutucid;
	}

	@Override
	public void setHosothutucid(long hosothutucid) {
		_columnBitmask |= HOSOTHUTUCID_COLUMN_BITMASK;

		if (!_setOriginalHosothutucid) {
			_setOriginalHosothutucid = true;

			_originalHosothutucid = _hosothutucid;
		}

		_hosothutucid = hosothutucid;
	}

	public long getOriginalHosothutucid() {
		return _originalHosothutucid;
	}

	@JSON
	@Override
	public String getMasohoso() {
		if (_masohoso == null) {
			return StringPool.BLANK;
		}
		else {
			return _masohoso;
		}
	}

	@Override
	public void setMasohoso(String masohoso) {
		_columnBitmask |= MASOHOSO_COLUMN_BITMASK;

		if (_originalMasohoso == null) {
			_originalMasohoso = _masohoso;
		}

		_masohoso = masohoso;
	}

	public String getOriginalMasohoso() {
		return GetterUtil.getString(_originalMasohoso);
	}

	@JSON
	@Override
	public String getMabiennhan() {
		if (_mabiennhan == null) {
			return StringPool.BLANK;
		}
		else {
			return _mabiennhan;
		}
	}

	@Override
	public void setMabiennhan(String mabiennhan) {
		_columnBitmask |= MABIENNHAN_COLUMN_BITMASK;

		if (_originalMabiennhan == null) {
			_originalMabiennhan = _mabiennhan;
		}

		_mabiennhan = mabiennhan;
	}

	public String getOriginalMabiennhan() {
		return GetterUtil.getString(_originalMabiennhan);
	}

	@JSON
	@Override
	public Date getNgayxemhoso() {
		return _ngayxemhoso;
	}

	@Override
	public void setNgayxemhoso(Date ngayxemhoso) {
		_ngayxemhoso = ngayxemhoso;
	}

	@JSON
	@Override
	public String getNoidungmanhinh() {
		if (_noidungmanhinh == null) {
			return StringPool.BLANK;
		}
		else {
			return _noidungmanhinh;
		}
	}

	@Override
	public void setNoidungmanhinh(String noidungmanhinh) {
		_noidungmanhinh = noidungmanhinh;
	}

	@JSON
	@Override
	public String getImportername() {
		if (_importername == null) {
			return StringPool.BLANK;
		}
		else {
			return _importername;
		}
	}

	@Override
	public void setImportername(String importername) {
		_columnBitmask |= IMPORTERNAME_COLUMN_BITMASK;

		if (_originalImportername == null) {
			_originalImportername = _importername;
		}

		_importername = importername;
	}

	public String getOriginalImportername() {
		return GetterUtil.getString(_originalImportername);
	}

	@JSON
	@Override
	public String getCorporationid() {
		if (_corporationid == null) {
			return StringPool.BLANK;
		}
		else {
			return _corporationid;
		}
	}

	@Override
	public void setCorporationid(String corporationid) {
		_columnBitmask |= CORPORATIONID_COLUMN_BITMASK;

		if (_originalCorporationid == null) {
			_originalCorporationid = _corporationid;
		}

		_corporationid = corporationid;
	}

	public String getOriginalCorporationid() {
		return GetterUtil.getString(_originalCorporationid);
	}

	@JSON
	@Override
	public long getInspectorid() {
		return _inspectorid;
	}

	@Override
	public void setInspectorid(long inspectorid) {
		_columnBitmask |= INSPECTORID_COLUMN_BITMASK;

		if (!_setOriginalInspectorid) {
			_setOriginalInspectorid = true;

			_originalInspectorid = _inspectorid;
		}

		_inspectorid = inspectorid;
	}

	public long getOriginalInspectorid() {
		return _originalInspectorid;
	}

	@JSON
	@Override
	public String getInspectorname() {
		if (_inspectorname == null) {
			return StringPool.BLANK;
		}
		else {
			return _inspectorname;
		}
	}

	@Override
	public void setInspectorname(String inspectorname) {
		_inspectorname = inspectorname;
	}

	@JSON
	@Override
	public String getInspectorphone() {
		if (_inspectorphone == null) {
			return StringPool.BLANK;
		}
		else {
			return _inspectorphone;
		}
	}

	@Override
	public void setInspectorphone(String inspectorphone) {
		_inspectorphone = inspectorphone;
	}

	@JSON
	@Override
	public String getInspectoremail() {
		if (_inspectoremail == null) {
			return StringPool.BLANK;
		}
		else {
			return _inspectoremail;
		}
	}

	@Override
	public void setInspectoremail(String inspectoremail) {
		_inspectoremail = inspectoremail;
	}

	@JSON
	@Override
	public String getTitle() {
		if (_title == null) {
			return StringPool.BLANK;
		}
		else {
			return _title;
		}
	}

	@Override
	public void setTitle(String title) {
		_title = title;
	}

	@JSON
	@Override
	public String getContactcode() {
		if (_contactcode == null) {
			return StringPool.BLANK;
		}
		else {
			return _contactcode;
		}
	}

	@Override
	public void setContactcode(String contactcode) {
		_columnBitmask |= CONTACTCODE_COLUMN_BITMASK;

		if (_originalContactcode == null) {
			_originalContactcode = _contactcode;
		}

		_contactcode = contactcode;
	}

	public String getOriginalContactcode() {
		return GetterUtil.getString(_originalContactcode);
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			ActionLog.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ActionLog toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (ActionLog)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ActionLogImpl actionLogImpl = new ActionLogImpl();

		actionLogImpl.setId(getId());
		actionLogImpl.setHosothutucid(getHosothutucid());
		actionLogImpl.setMasohoso(getMasohoso());
		actionLogImpl.setMabiennhan(getMabiennhan());
		actionLogImpl.setNgayxemhoso(getNgayxemhoso());
		actionLogImpl.setNoidungmanhinh(getNoidungmanhinh());
		actionLogImpl.setImportername(getImportername());
		actionLogImpl.setCorporationid(getCorporationid());
		actionLogImpl.setInspectorid(getInspectorid());
		actionLogImpl.setInspectorname(getInspectorname());
		actionLogImpl.setInspectorphone(getInspectorphone());
		actionLogImpl.setInspectoremail(getInspectoremail());
		actionLogImpl.setTitle(getTitle());
		actionLogImpl.setContactcode(getContactcode());

		actionLogImpl.resetOriginalValues();

		return actionLogImpl;
	}

	@Override
	public int compareTo(ActionLog actionLog) {
		int value = 0;

		if (getId() < actionLog.getId()) {
			value = -1;
		}
		else if (getId() > actionLog.getId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof ActionLog)) {
			return false;
		}

		ActionLog actionLog = (ActionLog)obj;

		long primaryKey = actionLog.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		ActionLogModelImpl actionLogModelImpl = this;

		actionLogModelImpl._originalHosothutucid = actionLogModelImpl._hosothutucid;

		actionLogModelImpl._setOriginalHosothutucid = false;

		actionLogModelImpl._originalMasohoso = actionLogModelImpl._masohoso;

		actionLogModelImpl._originalMabiennhan = actionLogModelImpl._mabiennhan;

		actionLogModelImpl._originalImportername = actionLogModelImpl._importername;

		actionLogModelImpl._originalCorporationid = actionLogModelImpl._corporationid;

		actionLogModelImpl._originalInspectorid = actionLogModelImpl._inspectorid;

		actionLogModelImpl._setOriginalInspectorid = false;

		actionLogModelImpl._originalContactcode = actionLogModelImpl._contactcode;

		actionLogModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<ActionLog> toCacheModel() {
		ActionLogCacheModel actionLogCacheModel = new ActionLogCacheModel();

		actionLogCacheModel.id = getId();

		actionLogCacheModel.hosothutucid = getHosothutucid();

		actionLogCacheModel.masohoso = getMasohoso();

		String masohoso = actionLogCacheModel.masohoso;

		if ((masohoso != null) && (masohoso.length() == 0)) {
			actionLogCacheModel.masohoso = null;
		}

		actionLogCacheModel.mabiennhan = getMabiennhan();

		String mabiennhan = actionLogCacheModel.mabiennhan;

		if ((mabiennhan != null) && (mabiennhan.length() == 0)) {
			actionLogCacheModel.mabiennhan = null;
		}

		Date ngayxemhoso = getNgayxemhoso();

		if (ngayxemhoso != null) {
			actionLogCacheModel.ngayxemhoso = ngayxemhoso.getTime();
		}
		else {
			actionLogCacheModel.ngayxemhoso = Long.MIN_VALUE;
		}

		actionLogCacheModel.noidungmanhinh = getNoidungmanhinh();

		String noidungmanhinh = actionLogCacheModel.noidungmanhinh;

		if ((noidungmanhinh != null) && (noidungmanhinh.length() == 0)) {
			actionLogCacheModel.noidungmanhinh = null;
		}

		actionLogCacheModel.importername = getImportername();

		String importername = actionLogCacheModel.importername;

		if ((importername != null) && (importername.length() == 0)) {
			actionLogCacheModel.importername = null;
		}

		actionLogCacheModel.corporationid = getCorporationid();

		String corporationid = actionLogCacheModel.corporationid;

		if ((corporationid != null) && (corporationid.length() == 0)) {
			actionLogCacheModel.corporationid = null;
		}

		actionLogCacheModel.inspectorid = getInspectorid();

		actionLogCacheModel.inspectorname = getInspectorname();

		String inspectorname = actionLogCacheModel.inspectorname;

		if ((inspectorname != null) && (inspectorname.length() == 0)) {
			actionLogCacheModel.inspectorname = null;
		}

		actionLogCacheModel.inspectorphone = getInspectorphone();

		String inspectorphone = actionLogCacheModel.inspectorphone;

		if ((inspectorphone != null) && (inspectorphone.length() == 0)) {
			actionLogCacheModel.inspectorphone = null;
		}

		actionLogCacheModel.inspectoremail = getInspectoremail();

		String inspectoremail = actionLogCacheModel.inspectoremail;

		if ((inspectoremail != null) && (inspectoremail.length() == 0)) {
			actionLogCacheModel.inspectoremail = null;
		}

		actionLogCacheModel.title = getTitle();

		String title = actionLogCacheModel.title;

		if ((title != null) && (title.length() == 0)) {
			actionLogCacheModel.title = null;
		}

		actionLogCacheModel.contactcode = getContactcode();

		String contactcode = actionLogCacheModel.contactcode;

		if ((contactcode != null) && (contactcode.length() == 0)) {
			actionLogCacheModel.contactcode = null;
		}

		return actionLogCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(29);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", hosothutucid=");
		sb.append(getHosothutucid());
		sb.append(", masohoso=");
		sb.append(getMasohoso());
		sb.append(", mabiennhan=");
		sb.append(getMabiennhan());
		sb.append(", ngayxemhoso=");
		sb.append(getNgayxemhoso());
		sb.append(", noidungmanhinh=");
		sb.append(getNoidungmanhinh());
		sb.append(", importername=");
		sb.append(getImportername());
		sb.append(", corporationid=");
		sb.append(getCorporationid());
		sb.append(", inspectorid=");
		sb.append(getInspectorid());
		sb.append(", inspectorname=");
		sb.append(getInspectorname());
		sb.append(", inspectorphone=");
		sb.append(getInspectorphone());
		sb.append(", inspectoremail=");
		sb.append(getInspectoremail());
		sb.append(", title=");
		sb.append(getTitle());
		sb.append(", contactcode=");
		sb.append(getContactcode());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(46);

		sb.append("<model><model-name>");
		sb.append("vn.dtt.gt.dk.dao.nghiepvu.model.ActionLog");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>hosothutucid</column-name><column-value><![CDATA[");
		sb.append(getHosothutucid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>masohoso</column-name><column-value><![CDATA[");
		sb.append(getMasohoso());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>mabiennhan</column-name><column-value><![CDATA[");
		sb.append(getMabiennhan());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayxemhoso</column-name><column-value><![CDATA[");
		sb.append(getNgayxemhoso());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>noidungmanhinh</column-name><column-value><![CDATA[");
		sb.append(getNoidungmanhinh());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>importername</column-name><column-value><![CDATA[");
		sb.append(getImportername());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>corporationid</column-name><column-value><![CDATA[");
		sb.append(getCorporationid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>inspectorid</column-name><column-value><![CDATA[");
		sb.append(getInspectorid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>inspectorname</column-name><column-value><![CDATA[");
		sb.append(getInspectorname());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>inspectorphone</column-name><column-value><![CDATA[");
		sb.append(getInspectorphone());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>inspectoremail</column-name><column-value><![CDATA[");
		sb.append(getInspectoremail());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>title</column-name><column-value><![CDATA[");
		sb.append(getTitle());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>contactcode</column-name><column-value><![CDATA[");
		sb.append(getContactcode());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = ActionLog.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			ActionLog.class
		};
	private long _id;
	private long _hosothutucid;
	private long _originalHosothutucid;
	private boolean _setOriginalHosothutucid;
	private String _masohoso;
	private String _originalMasohoso;
	private String _mabiennhan;
	private String _originalMabiennhan;
	private Date _ngayxemhoso;
	private String _noidungmanhinh;
	private String _importername;
	private String _originalImportername;
	private String _corporationid;
	private String _originalCorporationid;
	private long _inspectorid;
	private long _originalInspectorid;
	private boolean _setOriginalInspectorid;
	private String _inspectorname;
	private String _inspectorphone;
	private String _inspectoremail;
	private String _title;
	private String _contactcode;
	private String _originalContactcode;
	private long _columnBitmask;
	private ActionLog _escapedModel;
}