/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.gt.dk.dao.nghiepvu.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import vn.dtt.gt.dk.dao.nghiepvu.model.CertificateRecordSpec;
import vn.dtt.gt.dk.dao.nghiepvu.model.CertificateRecordSpecModel;
import vn.dtt.gt.dk.dao.nghiepvu.model.CertificateRecordSpecSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the CertificateRecordSpec service. Represents a row in the &quot;vr_certificaterecordspec&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link vn.dtt.gt.dk.dao.nghiepvu.model.CertificateRecordSpecModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CertificateRecordSpecImpl}.
 * </p>
 *
 * @author win_64
 * @see CertificateRecordSpecImpl
 * @see vn.dtt.gt.dk.dao.nghiepvu.model.CertificateRecordSpec
 * @see vn.dtt.gt.dk.dao.nghiepvu.model.CertificateRecordSpecModel
 * @generated
 */
@JSON(strict = true)
public class CertificateRecordSpecModelImpl extends BaseModelImpl<CertificateRecordSpec>
	implements CertificateRecordSpecModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a certificate record spec model instance should use the {@link vn.dtt.gt.dk.dao.nghiepvu.model.CertificateRecordSpec} interface instead.
	 */
	public static final String TABLE_NAME = "vr_certificaterecordspec";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id", Types.BIGINT },
			{ "certificaterecordid", Types.BIGINT },
			{ "specificationcode", Types.VARCHAR },
			{ "specificationname", Types.VARCHAR },
			{ "specificationvalue", Types.VARCHAR },
			{ "version", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table vr_certificaterecordspec (id LONG not null primary key,certificaterecordid LONG,specificationcode VARCHAR(75) null,specificationname VARCHAR(75) null,specificationvalue VARCHAR(75) null,version LONG)";
	public static final String TABLE_SQL_DROP = "drop table vr_certificaterecordspec";
	public static final String ORDER_BY_JPQL = " ORDER BY certificateRecordSpec.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY vr_certificaterecordspec.id ASC";
	public static final String DATA_SOURCE = "vrDataSource";
	public static final String SESSION_FACTORY = "vrSessionFactory";
	public static final String TX_MANAGER = "vrTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.vn.dtt.gt.dk.dao.nghiepvu.model.CertificateRecordSpec"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.vn.dtt.gt.dk.dao.nghiepvu.model.CertificateRecordSpec"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.vn.dtt.gt.dk.dao.nghiepvu.model.CertificateRecordSpec"),
			true);
	public static long CERTIFICATERECORDID_COLUMN_BITMASK = 1L;
	public static long SPECIFICATIONCODE_COLUMN_BITMASK = 2L;
	public static long ID_COLUMN_BITMASK = 4L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static CertificateRecordSpec toModel(
		CertificateRecordSpecSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		CertificateRecordSpec model = new CertificateRecordSpecImpl();

		model.setId(soapModel.getId());
		model.setCertificateRecordId(soapModel.getCertificateRecordId());
		model.setSpecificationCode(soapModel.getSpecificationCode());
		model.setSpecificationName(soapModel.getSpecificationName());
		model.setSpecificationValue(soapModel.getSpecificationValue());
		model.setVersion(soapModel.getVersion());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<CertificateRecordSpec> toModels(
		CertificateRecordSpecSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<CertificateRecordSpec> models = new ArrayList<CertificateRecordSpec>(soapModels.length);

		for (CertificateRecordSpecSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.vn.dtt.gt.dk.dao.nghiepvu.model.CertificateRecordSpec"));

	public CertificateRecordSpecModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return CertificateRecordSpec.class;
	}

	@Override
	public String getModelClassName() {
		return CertificateRecordSpec.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("certificateRecordId", getCertificateRecordId());
		attributes.put("specificationCode", getSpecificationCode());
		attributes.put("specificationName", getSpecificationName());
		attributes.put("specificationValue", getSpecificationValue());
		attributes.put("version", getVersion());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id = (Long)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		Long certificateRecordId = (Long)attributes.get("certificateRecordId");

		if (certificateRecordId != null) {
			setCertificateRecordId(certificateRecordId);
		}

		String specificationCode = (String)attributes.get("specificationCode");

		if (specificationCode != null) {
			setSpecificationCode(specificationCode);
		}

		String specificationName = (String)attributes.get("specificationName");

		if (specificationName != null) {
			setSpecificationName(specificationName);
		}

		String specificationValue = (String)attributes.get("specificationValue");

		if (specificationValue != null) {
			setSpecificationValue(specificationValue);
		}

		Long version = (Long)attributes.get("version");

		if (version != null) {
			setVersion(version);
		}
	}

	@JSON
	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		_columnBitmask = -1L;

		_id = id;
	}

	@JSON
	@Override
	public long getCertificateRecordId() {
		return _certificateRecordId;
	}

	@Override
	public void setCertificateRecordId(long certificateRecordId) {
		_columnBitmask |= CERTIFICATERECORDID_COLUMN_BITMASK;

		if (!_setOriginalCertificateRecordId) {
			_setOriginalCertificateRecordId = true;

			_originalCertificateRecordId = _certificateRecordId;
		}

		_certificateRecordId = certificateRecordId;
	}

	public long getOriginalCertificateRecordId() {
		return _originalCertificateRecordId;
	}

	@JSON
	@Override
	public String getSpecificationCode() {
		if (_specificationCode == null) {
			return StringPool.BLANK;
		}
		else {
			return _specificationCode;
		}
	}

	@Override
	public void setSpecificationCode(String specificationCode) {
		_columnBitmask |= SPECIFICATIONCODE_COLUMN_BITMASK;

		if (_originalSpecificationCode == null) {
			_originalSpecificationCode = _specificationCode;
		}

		_specificationCode = specificationCode;
	}

	public String getOriginalSpecificationCode() {
		return GetterUtil.getString(_originalSpecificationCode);
	}

	@JSON
	@Override
	public String getSpecificationName() {
		if (_specificationName == null) {
			return StringPool.BLANK;
		}
		else {
			return _specificationName;
		}
	}

	@Override
	public void setSpecificationName(String specificationName) {
		_specificationName = specificationName;
	}

	@JSON
	@Override
	public String getSpecificationValue() {
		if (_specificationValue == null) {
			return StringPool.BLANK;
		}
		else {
			return _specificationValue;
		}
	}

	@Override
	public void setSpecificationValue(String specificationValue) {
		_specificationValue = specificationValue;
	}

	@JSON
	@Override
	public long getVersion() {
		return _version;
	}

	@Override
	public void setVersion(long version) {
		_version = version;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			CertificateRecordSpec.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public CertificateRecordSpec toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (CertificateRecordSpec)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CertificateRecordSpecImpl certificateRecordSpecImpl = new CertificateRecordSpecImpl();

		certificateRecordSpecImpl.setId(getId());
		certificateRecordSpecImpl.setCertificateRecordId(getCertificateRecordId());
		certificateRecordSpecImpl.setSpecificationCode(getSpecificationCode());
		certificateRecordSpecImpl.setSpecificationName(getSpecificationName());
		certificateRecordSpecImpl.setSpecificationValue(getSpecificationValue());
		certificateRecordSpecImpl.setVersion(getVersion());

		certificateRecordSpecImpl.resetOriginalValues();

		return certificateRecordSpecImpl;
	}

	@Override
	public int compareTo(CertificateRecordSpec certificateRecordSpec) {
		int value = 0;

		if (getId() < certificateRecordSpec.getId()) {
			value = -1;
		}
		else if (getId() > certificateRecordSpec.getId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof CertificateRecordSpec)) {
			return false;
		}

		CertificateRecordSpec certificateRecordSpec = (CertificateRecordSpec)obj;

		long primaryKey = certificateRecordSpec.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		CertificateRecordSpecModelImpl certificateRecordSpecModelImpl = this;

		certificateRecordSpecModelImpl._originalCertificateRecordId = certificateRecordSpecModelImpl._certificateRecordId;

		certificateRecordSpecModelImpl._setOriginalCertificateRecordId = false;

		certificateRecordSpecModelImpl._originalSpecificationCode = certificateRecordSpecModelImpl._specificationCode;

		certificateRecordSpecModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<CertificateRecordSpec> toCacheModel() {
		CertificateRecordSpecCacheModel certificateRecordSpecCacheModel = new CertificateRecordSpecCacheModel();

		certificateRecordSpecCacheModel.id = getId();

		certificateRecordSpecCacheModel.certificateRecordId = getCertificateRecordId();

		certificateRecordSpecCacheModel.specificationCode = getSpecificationCode();

		String specificationCode = certificateRecordSpecCacheModel.specificationCode;

		if ((specificationCode != null) && (specificationCode.length() == 0)) {
			certificateRecordSpecCacheModel.specificationCode = null;
		}

		certificateRecordSpecCacheModel.specificationName = getSpecificationName();

		String specificationName = certificateRecordSpecCacheModel.specificationName;

		if ((specificationName != null) && (specificationName.length() == 0)) {
			certificateRecordSpecCacheModel.specificationName = null;
		}

		certificateRecordSpecCacheModel.specificationValue = getSpecificationValue();

		String specificationValue = certificateRecordSpecCacheModel.specificationValue;

		if ((specificationValue != null) && (specificationValue.length() == 0)) {
			certificateRecordSpecCacheModel.specificationValue = null;
		}

		certificateRecordSpecCacheModel.version = getVersion();

		return certificateRecordSpecCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(13);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", certificateRecordId=");
		sb.append(getCertificateRecordId());
		sb.append(", specificationCode=");
		sb.append(getSpecificationCode());
		sb.append(", specificationName=");
		sb.append(getSpecificationName());
		sb.append(", specificationValue=");
		sb.append(getSpecificationValue());
		sb.append(", version=");
		sb.append(getVersion());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(22);

		sb.append("<model><model-name>");
		sb.append("vn.dtt.gt.dk.dao.nghiepvu.model.CertificateRecordSpec");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>certificateRecordId</column-name><column-value><![CDATA[");
		sb.append(getCertificateRecordId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>specificationCode</column-name><column-value><![CDATA[");
		sb.append(getSpecificationCode());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>specificationName</column-name><column-value><![CDATA[");
		sb.append(getSpecificationName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>specificationValue</column-name><column-value><![CDATA[");
		sb.append(getSpecificationValue());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>version</column-name><column-value><![CDATA[");
		sb.append(getVersion());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = CertificateRecordSpec.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			CertificateRecordSpec.class
		};
	private long _id;
	private long _certificateRecordId;
	private long _originalCertificateRecordId;
	private boolean _setOriginalCertificateRecordId;
	private String _specificationCode;
	private String _originalSpecificationCode;
	private String _specificationName;
	private String _specificationValue;
	private long _version;
	private long _columnBitmask;
	private CertificateRecordSpec _escapedModel;
}