/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.gt.dk.dao.nghiepvu.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import vn.dtt.gt.dk.dao.nghiepvu.model.SafetyTestReport;
import vn.dtt.gt.dk.dao.nghiepvu.model.SafetyTestReportModel;
import vn.dtt.gt.dk.dao.nghiepvu.model.SafetyTestReportSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the SafetyTestReport service. Represents a row in the &quot;vr_safetytestreport&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link vn.dtt.gt.dk.dao.nghiepvu.model.SafetyTestReportModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SafetyTestReportImpl}.
 * </p>
 *
 * @author win_64
 * @see SafetyTestReportImpl
 * @see vn.dtt.gt.dk.dao.nghiepvu.model.SafetyTestReport
 * @see vn.dtt.gt.dk.dao.nghiepvu.model.SafetyTestReportModel
 * @generated
 */
@JSON(strict = true)
public class SafetyTestReportModelImpl extends BaseModelImpl<SafetyTestReport>
	implements SafetyTestReportModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a safety test report model instance should use the {@link vn.dtt.gt.dk.dao.nghiepvu.model.SafetyTestReport} interface instead.
	 */
	public static final String TABLE_NAME = "vr_safetytestreport";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id", Types.BIGINT },
			{ "registeredinspectionid", Types.BIGINT },
			{ "inspectionrecordid", Types.BIGINT },
			{ "hosothutucid", Types.BIGINT },
			{ "safetestrequirementid", Types.BIGINT },
			{ "corporationid", Types.BIGINT },
			{ "requirementnumber", Types.VARCHAR },
			{ "reportnumber", Types.VARCHAR },
			{ "description", Types.VARCHAR },
			{ "confirmedresult", Types.BIGINT },
			{ "attachedfile", Types.BIGINT },
			{ "phieuxulyphuid", Types.BIGINT },
			{ "signname", Types.VARCHAR },
			{ "signtitle", Types.VARCHAR },
			{ "signplace", Types.VARCHAR },
			{ "signdate", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table vr_safetytestreport (id LONG not null primary key,registeredinspectionid LONG,inspectionrecordid LONG,hosothutucid LONG,safetestrequirementid LONG,corporationid LONG,requirementnumber VARCHAR(75) null,reportnumber VARCHAR(75) null,description VARCHAR(75) null,confirmedresult LONG,attachedfile LONG,phieuxulyphuid LONG,signname VARCHAR(75) null,signtitle VARCHAR(75) null,signplace VARCHAR(75) null,signdate DATE null)";
	public static final String TABLE_SQL_DROP = "drop table vr_safetytestreport";
	public static final String ORDER_BY_JPQL = " ORDER BY safetyTestReport.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY vr_safetytestreport.id ASC";
	public static final String DATA_SOURCE = "vrDataSource";
	public static final String SESSION_FACTORY = "vrSessionFactory";
	public static final String TX_MANAGER = "vrTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.vn.dtt.gt.dk.dao.nghiepvu.model.SafetyTestReport"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.vn.dtt.gt.dk.dao.nghiepvu.model.SafetyTestReport"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.vn.dtt.gt.dk.dao.nghiepvu.model.SafetyTestReport"),
			true);
	public static long SAFETESTREQUIREMENTID_COLUMN_BITMASK = 1L;
	public static long ID_COLUMN_BITMASK = 2L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static SafetyTestReport toModel(SafetyTestReportSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		SafetyTestReport model = new SafetyTestReportImpl();

		model.setId(soapModel.getId());
		model.setRegisteredInspectionId(soapModel.getRegisteredInspectionId());
		model.setInspectionrecordId(soapModel.getInspectionrecordId());
		model.setHosothutucId(soapModel.getHosothutucId());
		model.setSafetestRequirementId(soapModel.getSafetestRequirementId());
		model.setCorporationId(soapModel.getCorporationId());
		model.setRequirementNumber(soapModel.getRequirementNumber());
		model.setReportNumber(soapModel.getReportNumber());
		model.setDescription(soapModel.getDescription());
		model.setConfirmedResult(soapModel.getConfirmedResult());
		model.setAttachedFile(soapModel.getAttachedFile());
		model.setPhieuxulyphuId(soapModel.getPhieuxulyphuId());
		model.setSignName(soapModel.getSignName());
		model.setSignTitle(soapModel.getSignTitle());
		model.setSignPlace(soapModel.getSignPlace());
		model.setSignDate(soapModel.getSignDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<SafetyTestReport> toModels(
		SafetyTestReportSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<SafetyTestReport> models = new ArrayList<SafetyTestReport>(soapModels.length);

		for (SafetyTestReportSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.vn.dtt.gt.dk.dao.nghiepvu.model.SafetyTestReport"));

	public SafetyTestReportModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return SafetyTestReport.class;
	}

	@Override
	public String getModelClassName() {
		return SafetyTestReport.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("registeredInspectionId", getRegisteredInspectionId());
		attributes.put("inspectionrecordId", getInspectionrecordId());
		attributes.put("hosothutucId", getHosothutucId());
		attributes.put("safetestRequirementId", getSafetestRequirementId());
		attributes.put("corporationId", getCorporationId());
		attributes.put("requirementNumber", getRequirementNumber());
		attributes.put("reportNumber", getReportNumber());
		attributes.put("description", getDescription());
		attributes.put("confirmedResult", getConfirmedResult());
		attributes.put("attachedFile", getAttachedFile());
		attributes.put("phieuxulyphuId", getPhieuxulyphuId());
		attributes.put("signName", getSignName());
		attributes.put("signTitle", getSignTitle());
		attributes.put("signPlace", getSignPlace());
		attributes.put("signDate", getSignDate());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id = (Long)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		Long registeredInspectionId = (Long)attributes.get(
				"registeredInspectionId");

		if (registeredInspectionId != null) {
			setRegisteredInspectionId(registeredInspectionId);
		}

		Long inspectionrecordId = (Long)attributes.get("inspectionrecordId");

		if (inspectionrecordId != null) {
			setInspectionrecordId(inspectionrecordId);
		}

		Long hosothutucId = (Long)attributes.get("hosothutucId");

		if (hosothutucId != null) {
			setHosothutucId(hosothutucId);
		}

		Long safetestRequirementId = (Long)attributes.get(
				"safetestRequirementId");

		if (safetestRequirementId != null) {
			setSafetestRequirementId(safetestRequirementId);
		}

		Long corporationId = (Long)attributes.get("corporationId");

		if (corporationId != null) {
			setCorporationId(corporationId);
		}

		String requirementNumber = (String)attributes.get("requirementNumber");

		if (requirementNumber != null) {
			setRequirementNumber(requirementNumber);
		}

		String reportNumber = (String)attributes.get("reportNumber");

		if (reportNumber != null) {
			setReportNumber(reportNumber);
		}

		String description = (String)attributes.get("description");

		if (description != null) {
			setDescription(description);
		}

		Long confirmedResult = (Long)attributes.get("confirmedResult");

		if (confirmedResult != null) {
			setConfirmedResult(confirmedResult);
		}

		Long attachedFile = (Long)attributes.get("attachedFile");

		if (attachedFile != null) {
			setAttachedFile(attachedFile);
		}

		Long phieuxulyphuId = (Long)attributes.get("phieuxulyphuId");

		if (phieuxulyphuId != null) {
			setPhieuxulyphuId(phieuxulyphuId);
		}

		String signName = (String)attributes.get("signName");

		if (signName != null) {
			setSignName(signName);
		}

		String signTitle = (String)attributes.get("signTitle");

		if (signTitle != null) {
			setSignTitle(signTitle);
		}

		String signPlace = (String)attributes.get("signPlace");

		if (signPlace != null) {
			setSignPlace(signPlace);
		}

		Date signDate = (Date)attributes.get("signDate");

		if (signDate != null) {
			setSignDate(signDate);
		}
	}

	@JSON
	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		_columnBitmask = -1L;

		_id = id;
	}

	@JSON
	@Override
	public long getRegisteredInspectionId() {
		return _registeredInspectionId;
	}

	@Override
	public void setRegisteredInspectionId(long registeredInspectionId) {
		_registeredInspectionId = registeredInspectionId;
	}

	@JSON
	@Override
	public long getInspectionrecordId() {
		return _inspectionrecordId;
	}

	@Override
	public void setInspectionrecordId(long inspectionrecordId) {
		_inspectionrecordId = inspectionrecordId;
	}

	@JSON
	@Override
	public long getHosothutucId() {
		return _hosothutucId;
	}

	@Override
	public void setHosothutucId(long hosothutucId) {
		_hosothutucId = hosothutucId;
	}

	@JSON
	@Override
	public long getSafetestRequirementId() {
		return _safetestRequirementId;
	}

	@Override
	public void setSafetestRequirementId(long safetestRequirementId) {
		_columnBitmask |= SAFETESTREQUIREMENTID_COLUMN_BITMASK;

		if (!_setOriginalSafetestRequirementId) {
			_setOriginalSafetestRequirementId = true;

			_originalSafetestRequirementId = _safetestRequirementId;
		}

		_safetestRequirementId = safetestRequirementId;
	}

	public long getOriginalSafetestRequirementId() {
		return _originalSafetestRequirementId;
	}

	@JSON
	@Override
	public long getCorporationId() {
		return _corporationId;
	}

	@Override
	public void setCorporationId(long corporationId) {
		_corporationId = corporationId;
	}

	@JSON
	@Override
	public String getRequirementNumber() {
		if (_requirementNumber == null) {
			return StringPool.BLANK;
		}
		else {
			return _requirementNumber;
		}
	}

	@Override
	public void setRequirementNumber(String requirementNumber) {
		_requirementNumber = requirementNumber;
	}

	@JSON
	@Override
	public String getReportNumber() {
		if (_reportNumber == null) {
			return StringPool.BLANK;
		}
		else {
			return _reportNumber;
		}
	}

	@Override
	public void setReportNumber(String reportNumber) {
		_reportNumber = reportNumber;
	}

	@JSON
	@Override
	public String getDescription() {
		if (_description == null) {
			return StringPool.BLANK;
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		_description = description;
	}

	@JSON
	@Override
	public long getConfirmedResult() {
		return _confirmedResult;
	}

	@Override
	public void setConfirmedResult(long confirmedResult) {
		_confirmedResult = confirmedResult;
	}

	@JSON
	@Override
	public long getAttachedFile() {
		return _attachedFile;
	}

	@Override
	public void setAttachedFile(long attachedFile) {
		_attachedFile = attachedFile;
	}

	@JSON
	@Override
	public long getPhieuxulyphuId() {
		return _phieuxulyphuId;
	}

	@Override
	public void setPhieuxulyphuId(long phieuxulyphuId) {
		_phieuxulyphuId = phieuxulyphuId;
	}

	@JSON
	@Override
	public String getSignName() {
		if (_signName == null) {
			return StringPool.BLANK;
		}
		else {
			return _signName;
		}
	}

	@Override
	public void setSignName(String signName) {
		_signName = signName;
	}

	@JSON
	@Override
	public String getSignTitle() {
		if (_signTitle == null) {
			return StringPool.BLANK;
		}
		else {
			return _signTitle;
		}
	}

	@Override
	public void setSignTitle(String signTitle) {
		_signTitle = signTitle;
	}

	@JSON
	@Override
	public String getSignPlace() {
		if (_signPlace == null) {
			return StringPool.BLANK;
		}
		else {
			return _signPlace;
		}
	}

	@Override
	public void setSignPlace(String signPlace) {
		_signPlace = signPlace;
	}

	@JSON
	@Override
	public Date getSignDate() {
		return _signDate;
	}

	@Override
	public void setSignDate(Date signDate) {
		_signDate = signDate;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			SafetyTestReport.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public SafetyTestReport toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (SafetyTestReport)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		SafetyTestReportImpl safetyTestReportImpl = new SafetyTestReportImpl();

		safetyTestReportImpl.setId(getId());
		safetyTestReportImpl.setRegisteredInspectionId(getRegisteredInspectionId());
		safetyTestReportImpl.setInspectionrecordId(getInspectionrecordId());
		safetyTestReportImpl.setHosothutucId(getHosothutucId());
		safetyTestReportImpl.setSafetestRequirementId(getSafetestRequirementId());
		safetyTestReportImpl.setCorporationId(getCorporationId());
		safetyTestReportImpl.setRequirementNumber(getRequirementNumber());
		safetyTestReportImpl.setReportNumber(getReportNumber());
		safetyTestReportImpl.setDescription(getDescription());
		safetyTestReportImpl.setConfirmedResult(getConfirmedResult());
		safetyTestReportImpl.setAttachedFile(getAttachedFile());
		safetyTestReportImpl.setPhieuxulyphuId(getPhieuxulyphuId());
		safetyTestReportImpl.setSignName(getSignName());
		safetyTestReportImpl.setSignTitle(getSignTitle());
		safetyTestReportImpl.setSignPlace(getSignPlace());
		safetyTestReportImpl.setSignDate(getSignDate());

		safetyTestReportImpl.resetOriginalValues();

		return safetyTestReportImpl;
	}

	@Override
	public int compareTo(SafetyTestReport safetyTestReport) {
		int value = 0;

		if (getId() < safetyTestReport.getId()) {
			value = -1;
		}
		else if (getId() > safetyTestReport.getId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof SafetyTestReport)) {
			return false;
		}

		SafetyTestReport safetyTestReport = (SafetyTestReport)obj;

		long primaryKey = safetyTestReport.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		SafetyTestReportModelImpl safetyTestReportModelImpl = this;

		safetyTestReportModelImpl._originalSafetestRequirementId = safetyTestReportModelImpl._safetestRequirementId;

		safetyTestReportModelImpl._setOriginalSafetestRequirementId = false;

		safetyTestReportModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<SafetyTestReport> toCacheModel() {
		SafetyTestReportCacheModel safetyTestReportCacheModel = new SafetyTestReportCacheModel();

		safetyTestReportCacheModel.id = getId();

		safetyTestReportCacheModel.registeredInspectionId = getRegisteredInspectionId();

		safetyTestReportCacheModel.inspectionrecordId = getInspectionrecordId();

		safetyTestReportCacheModel.hosothutucId = getHosothutucId();

		safetyTestReportCacheModel.safetestRequirementId = getSafetestRequirementId();

		safetyTestReportCacheModel.corporationId = getCorporationId();

		safetyTestReportCacheModel.requirementNumber = getRequirementNumber();

		String requirementNumber = safetyTestReportCacheModel.requirementNumber;

		if ((requirementNumber != null) && (requirementNumber.length() == 0)) {
			safetyTestReportCacheModel.requirementNumber = null;
		}

		safetyTestReportCacheModel.reportNumber = getReportNumber();

		String reportNumber = safetyTestReportCacheModel.reportNumber;

		if ((reportNumber != null) && (reportNumber.length() == 0)) {
			safetyTestReportCacheModel.reportNumber = null;
		}

		safetyTestReportCacheModel.description = getDescription();

		String description = safetyTestReportCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			safetyTestReportCacheModel.description = null;
		}

		safetyTestReportCacheModel.confirmedResult = getConfirmedResult();

		safetyTestReportCacheModel.attachedFile = getAttachedFile();

		safetyTestReportCacheModel.phieuxulyphuId = getPhieuxulyphuId();

		safetyTestReportCacheModel.signName = getSignName();

		String signName = safetyTestReportCacheModel.signName;

		if ((signName != null) && (signName.length() == 0)) {
			safetyTestReportCacheModel.signName = null;
		}

		safetyTestReportCacheModel.signTitle = getSignTitle();

		String signTitle = safetyTestReportCacheModel.signTitle;

		if ((signTitle != null) && (signTitle.length() == 0)) {
			safetyTestReportCacheModel.signTitle = null;
		}

		safetyTestReportCacheModel.signPlace = getSignPlace();

		String signPlace = safetyTestReportCacheModel.signPlace;

		if ((signPlace != null) && (signPlace.length() == 0)) {
			safetyTestReportCacheModel.signPlace = null;
		}

		Date signDate = getSignDate();

		if (signDate != null) {
			safetyTestReportCacheModel.signDate = signDate.getTime();
		}
		else {
			safetyTestReportCacheModel.signDate = Long.MIN_VALUE;
		}

		return safetyTestReportCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(33);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", registeredInspectionId=");
		sb.append(getRegisteredInspectionId());
		sb.append(", inspectionrecordId=");
		sb.append(getInspectionrecordId());
		sb.append(", hosothutucId=");
		sb.append(getHosothutucId());
		sb.append(", safetestRequirementId=");
		sb.append(getSafetestRequirementId());
		sb.append(", corporationId=");
		sb.append(getCorporationId());
		sb.append(", requirementNumber=");
		sb.append(getRequirementNumber());
		sb.append(", reportNumber=");
		sb.append(getReportNumber());
		sb.append(", description=");
		sb.append(getDescription());
		sb.append(", confirmedResult=");
		sb.append(getConfirmedResult());
		sb.append(", attachedFile=");
		sb.append(getAttachedFile());
		sb.append(", phieuxulyphuId=");
		sb.append(getPhieuxulyphuId());
		sb.append(", signName=");
		sb.append(getSignName());
		sb.append(", signTitle=");
		sb.append(getSignTitle());
		sb.append(", signPlace=");
		sb.append(getSignPlace());
		sb.append(", signDate=");
		sb.append(getSignDate());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(52);

		sb.append("<model><model-name>");
		sb.append("vn.dtt.gt.dk.dao.nghiepvu.model.SafetyTestReport");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>registeredInspectionId</column-name><column-value><![CDATA[");
		sb.append(getRegisteredInspectionId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>inspectionrecordId</column-name><column-value><![CDATA[");
		sb.append(getInspectionrecordId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>hosothutucId</column-name><column-value><![CDATA[");
		sb.append(getHosothutucId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>safetestRequirementId</column-name><column-value><![CDATA[");
		sb.append(getSafetestRequirementId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>corporationId</column-name><column-value><![CDATA[");
		sb.append(getCorporationId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>requirementNumber</column-name><column-value><![CDATA[");
		sb.append(getRequirementNumber());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>reportNumber</column-name><column-value><![CDATA[");
		sb.append(getReportNumber());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>description</column-name><column-value><![CDATA[");
		sb.append(getDescription());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>confirmedResult</column-name><column-value><![CDATA[");
		sb.append(getConfirmedResult());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>attachedFile</column-name><column-value><![CDATA[");
		sb.append(getAttachedFile());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>phieuxulyphuId</column-name><column-value><![CDATA[");
		sb.append(getPhieuxulyphuId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>signName</column-name><column-value><![CDATA[");
		sb.append(getSignName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>signTitle</column-name><column-value><![CDATA[");
		sb.append(getSignTitle());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>signPlace</column-name><column-value><![CDATA[");
		sb.append(getSignPlace());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>signDate</column-name><column-value><![CDATA[");
		sb.append(getSignDate());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = SafetyTestReport.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			SafetyTestReport.class
		};
	private long _id;
	private long _registeredInspectionId;
	private long _inspectionrecordId;
	private long _hosothutucId;
	private long _safetestRequirementId;
	private long _originalSafetestRequirementId;
	private boolean _setOriginalSafetestRequirementId;
	private long _corporationId;
	private String _requirementNumber;
	private String _reportNumber;
	private String _description;
	private long _confirmedResult;
	private long _attachedFile;
	private long _phieuxulyphuId;
	private String _signName;
	private String _signTitle;
	private String _signPlace;
	private Date _signDate;
	private long _columnBitmask;
	private SafetyTestReport _escapedModel;
}