/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.gt.dk.dao.nghiepvu.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import vn.dtt.gt.dk.dao.nghiepvu.model.THONGSOCHUNGCHIDONGCO;
import vn.dtt.gt.dk.dao.nghiepvu.model.THONGSOCHUNGCHIDONGCOModel;
import vn.dtt.gt.dk.dao.nghiepvu.model.THONGSOCHUNGCHIDONGCOSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the THONGSOCHUNGCHIDONGCO service. Represents a row in the &quot;thongsochungchi_dongco&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link vn.dtt.gt.dk.dao.nghiepvu.model.THONGSOCHUNGCHIDONGCOModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link THONGSOCHUNGCHIDONGCOImpl}.
 * </p>
 *
 * @author win_64
 * @see THONGSOCHUNGCHIDONGCOImpl
 * @see vn.dtt.gt.dk.dao.nghiepvu.model.THONGSOCHUNGCHIDONGCO
 * @see vn.dtt.gt.dk.dao.nghiepvu.model.THONGSOCHUNGCHIDONGCOModel
 * @generated
 */
@JSON(strict = true)
public class THONGSOCHUNGCHIDONGCOModelImpl extends BaseModelImpl<THONGSOCHUNGCHIDONGCO>
	implements THONGSOCHUNGCHIDONGCOModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a t h o n g s o c h u n g c h i d o n g c o model instance should use the {@link vn.dtt.gt.dk.dao.nghiepvu.model.THONGSOCHUNGCHIDONGCO} interface instead.
	 */
	public static final String TABLE_NAME = "thongsochungchi_dongco";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id", Types.BIGINT },
			{ "hoSoThuTucId", Types.BIGINT },
			{ "certificateRecordId", Types.BIGINT },
			{ "vehicleGroupId", Types.BIGINT },
			{ "SynchDate", Types.TIMESTAMP },
			{ "DCX0007", Types.VARCHAR },
			{ "DCX0008", Types.VARCHAR },
			{ "DCX0010", Types.VARCHAR },
			{ "DCX0011", Types.VARCHAR },
			{ "DCX0012", Types.VARCHAR },
			{ "DCX1012", Types.VARCHAR },
			{ "DCX0013", Types.VARCHAR },
			{ "DCX1013", Types.VARCHAR },
			{ "DCX0014", Types.VARCHAR },
			{ "DCX0015", Types.VARCHAR },
			{ "DCX0016", Types.VARCHAR },
			{ "DCX0017", Types.VARCHAR },
			{ "DCX0018", Types.VARCHAR },
			{ "DCX0019", Types.VARCHAR },
			{ "DCX0021", Types.VARCHAR },
			{ "DCX0022", Types.VARCHAR },
			{ "DCX0023", Types.VARCHAR },
			{ "DCX0024", Types.VARCHAR },
			{ "DCX0006", Types.VARCHAR },
			{ "DCX0025", Types.VARCHAR },
			{ "DCX0026", Types.VARCHAR },
			{ "DCX0027", Types.VARCHAR },
			{ "DCX0028", Types.VARCHAR },
			{ "DCX0029", Types.VARCHAR },
			{ "DCX0030", Types.VARCHAR },
			{ "DCX0031", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table thongsochungchi_dongco (id LONG not null primary key,hoSoThuTucId LONG,certificateRecordId LONG,vehicleGroupId LONG,SynchDate DATE null,DCX0007 VARCHAR(75) null,DCX0008 VARCHAR(75) null,DCX0010 VARCHAR(75) null,DCX0011 VARCHAR(75) null,DCX0012 VARCHAR(75) null,DCX1012 VARCHAR(75) null,DCX0013 VARCHAR(75) null,DCX1013 VARCHAR(75) null,DCX0014 VARCHAR(75) null,DCX0015 VARCHAR(75) null,DCX0016 VARCHAR(75) null,DCX0017 VARCHAR(75) null,DCX0018 VARCHAR(75) null,DCX0019 VARCHAR(75) null,DCX0021 VARCHAR(75) null,DCX0022 VARCHAR(75) null,DCX0023 VARCHAR(75) null,DCX0024 VARCHAR(75) null,DCX0006 VARCHAR(75) null,DCX0025 VARCHAR(75) null,DCX0026 VARCHAR(75) null,DCX0027 VARCHAR(75) null,DCX0028 VARCHAR(75) null,DCX0029 VARCHAR(75) null,DCX0030 VARCHAR(75) null,DCX0031 VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table thongsochungchi_dongco";
	public static final String ORDER_BY_JPQL = " ORDER BY thongsochungchidongco.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY thongsochungchi_dongco.id ASC";
	public static final String DATA_SOURCE = "vrDataSource";
	public static final String SESSION_FACTORY = "vrSessionFactory";
	public static final String TX_MANAGER = "vrTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.vn.dtt.gt.dk.dao.nghiepvu.model.THONGSOCHUNGCHIDONGCO"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.vn.dtt.gt.dk.dao.nghiepvu.model.THONGSOCHUNGCHIDONGCO"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.vn.dtt.gt.dk.dao.nghiepvu.model.THONGSOCHUNGCHIDONGCO"),
			true);
	public static long CERTIFICATERECORDID_COLUMN_BITMASK = 1L;
	public static long HOSOTHUTUCID_COLUMN_BITMASK = 2L;
	public static long VEHICLEGROUPID_COLUMN_BITMASK = 4L;
	public static long ID_COLUMN_BITMASK = 8L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static THONGSOCHUNGCHIDONGCO toModel(
		THONGSOCHUNGCHIDONGCOSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		THONGSOCHUNGCHIDONGCO model = new THONGSOCHUNGCHIDONGCOImpl();

		model.setId(soapModel.getId());
		model.setHoSoThuTucId(soapModel.getHoSoThuTucId());
		model.setCertificateRecordId(soapModel.getCertificateRecordId());
		model.setVehicleGroupId(soapModel.getVehicleGroupId());
		model.setSynchDate(soapModel.getSynchDate());
		model.setDCX0007(soapModel.getDCX0007());
		model.setDCX0008(soapModel.getDCX0008());
		model.setDCX0010(soapModel.getDCX0010());
		model.setDCX0011(soapModel.getDCX0011());
		model.setDCX0012(soapModel.getDCX0012());
		model.setDCX1012(soapModel.getDCX1012());
		model.setDCX0013(soapModel.getDCX0013());
		model.setDCX1013(soapModel.getDCX1013());
		model.setDCX0014(soapModel.getDCX0014());
		model.setDCX0015(soapModel.getDCX0015());
		model.setDCX0016(soapModel.getDCX0016());
		model.setDCX0017(soapModel.getDCX0017());
		model.setDCX0018(soapModel.getDCX0018());
		model.setDCX0019(soapModel.getDCX0019());
		model.setDCX0021(soapModel.getDCX0021());
		model.setDCX0022(soapModel.getDCX0022());
		model.setDCX0023(soapModel.getDCX0023());
		model.setDCX0024(soapModel.getDCX0024());
		model.setDCX0006(soapModel.getDCX0006());
		model.setDCX0025(soapModel.getDCX0025());
		model.setDCX0026(soapModel.getDCX0026());
		model.setDCX0027(soapModel.getDCX0027());
		model.setDCX0028(soapModel.getDCX0028());
		model.setDCX0029(soapModel.getDCX0029());
		model.setDCX0030(soapModel.getDCX0030());
		model.setDCX0031(soapModel.getDCX0031());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<THONGSOCHUNGCHIDONGCO> toModels(
		THONGSOCHUNGCHIDONGCOSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<THONGSOCHUNGCHIDONGCO> models = new ArrayList<THONGSOCHUNGCHIDONGCO>(soapModels.length);

		for (THONGSOCHUNGCHIDONGCOSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.vn.dtt.gt.dk.dao.nghiepvu.model.THONGSOCHUNGCHIDONGCO"));

	public THONGSOCHUNGCHIDONGCOModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return THONGSOCHUNGCHIDONGCO.class;
	}

	@Override
	public String getModelClassName() {
		return THONGSOCHUNGCHIDONGCO.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("hoSoThuTucId", getHoSoThuTucId());
		attributes.put("certificateRecordId", getCertificateRecordId());
		attributes.put("vehicleGroupId", getVehicleGroupId());
		attributes.put("SynchDate", getSynchDate());
		attributes.put("DCX0007", getDCX0007());
		attributes.put("DCX0008", getDCX0008());
		attributes.put("DCX0010", getDCX0010());
		attributes.put("DCX0011", getDCX0011());
		attributes.put("DCX0012", getDCX0012());
		attributes.put("DCX1012", getDCX1012());
		attributes.put("DCX0013", getDCX0013());
		attributes.put("DCX1013", getDCX1013());
		attributes.put("DCX0014", getDCX0014());
		attributes.put("DCX0015", getDCX0015());
		attributes.put("DCX0016", getDCX0016());
		attributes.put("DCX0017", getDCX0017());
		attributes.put("DCX0018", getDCX0018());
		attributes.put("DCX0019", getDCX0019());
		attributes.put("DCX0021", getDCX0021());
		attributes.put("DCX0022", getDCX0022());
		attributes.put("DCX0023", getDCX0023());
		attributes.put("DCX0024", getDCX0024());
		attributes.put("DCX0006", getDCX0006());
		attributes.put("DCX0025", getDCX0025());
		attributes.put("DCX0026", getDCX0026());
		attributes.put("DCX0027", getDCX0027());
		attributes.put("DCX0028", getDCX0028());
		attributes.put("DCX0029", getDCX0029());
		attributes.put("DCX0030", getDCX0030());
		attributes.put("DCX0031", getDCX0031());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id = (Long)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		Long hoSoThuTucId = (Long)attributes.get("hoSoThuTucId");

		if (hoSoThuTucId != null) {
			setHoSoThuTucId(hoSoThuTucId);
		}

		Long certificateRecordId = (Long)attributes.get("certificateRecordId");

		if (certificateRecordId != null) {
			setCertificateRecordId(certificateRecordId);
		}

		Long vehicleGroupId = (Long)attributes.get("vehicleGroupId");

		if (vehicleGroupId != null) {
			setVehicleGroupId(vehicleGroupId);
		}

		Date SynchDate = (Date)attributes.get("SynchDate");

		if (SynchDate != null) {
			setSynchDate(SynchDate);
		}

		String DCX0007 = (String)attributes.get("DCX0007");

		if (DCX0007 != null) {
			setDCX0007(DCX0007);
		}

		String DCX0008 = (String)attributes.get("DCX0008");

		if (DCX0008 != null) {
			setDCX0008(DCX0008);
		}

		String DCX0010 = (String)attributes.get("DCX0010");

		if (DCX0010 != null) {
			setDCX0010(DCX0010);
		}

		String DCX0011 = (String)attributes.get("DCX0011");

		if (DCX0011 != null) {
			setDCX0011(DCX0011);
		}

		String DCX0012 = (String)attributes.get("DCX0012");

		if (DCX0012 != null) {
			setDCX0012(DCX0012);
		}

		String DCX1012 = (String)attributes.get("DCX1012");

		if (DCX1012 != null) {
			setDCX1012(DCX1012);
		}

		String DCX0013 = (String)attributes.get("DCX0013");

		if (DCX0013 != null) {
			setDCX0013(DCX0013);
		}

		String DCX1013 = (String)attributes.get("DCX1013");

		if (DCX1013 != null) {
			setDCX1013(DCX1013);
		}

		String DCX0014 = (String)attributes.get("DCX0014");

		if (DCX0014 != null) {
			setDCX0014(DCX0014);
		}

		String DCX0015 = (String)attributes.get("DCX0015");

		if (DCX0015 != null) {
			setDCX0015(DCX0015);
		}

		String DCX0016 = (String)attributes.get("DCX0016");

		if (DCX0016 != null) {
			setDCX0016(DCX0016);
		}

		String DCX0017 = (String)attributes.get("DCX0017");

		if (DCX0017 != null) {
			setDCX0017(DCX0017);
		}

		String DCX0018 = (String)attributes.get("DCX0018");

		if (DCX0018 != null) {
			setDCX0018(DCX0018);
		}

		String DCX0019 = (String)attributes.get("DCX0019");

		if (DCX0019 != null) {
			setDCX0019(DCX0019);
		}

		String DCX0021 = (String)attributes.get("DCX0021");

		if (DCX0021 != null) {
			setDCX0021(DCX0021);
		}

		String DCX0022 = (String)attributes.get("DCX0022");

		if (DCX0022 != null) {
			setDCX0022(DCX0022);
		}

		String DCX0023 = (String)attributes.get("DCX0023");

		if (DCX0023 != null) {
			setDCX0023(DCX0023);
		}

		String DCX0024 = (String)attributes.get("DCX0024");

		if (DCX0024 != null) {
			setDCX0024(DCX0024);
		}

		String DCX0006 = (String)attributes.get("DCX0006");

		if (DCX0006 != null) {
			setDCX0006(DCX0006);
		}

		String DCX0025 = (String)attributes.get("DCX0025");

		if (DCX0025 != null) {
			setDCX0025(DCX0025);
		}

		String DCX0026 = (String)attributes.get("DCX0026");

		if (DCX0026 != null) {
			setDCX0026(DCX0026);
		}

		String DCX0027 = (String)attributes.get("DCX0027");

		if (DCX0027 != null) {
			setDCX0027(DCX0027);
		}

		String DCX0028 = (String)attributes.get("DCX0028");

		if (DCX0028 != null) {
			setDCX0028(DCX0028);
		}

		String DCX0029 = (String)attributes.get("DCX0029");

		if (DCX0029 != null) {
			setDCX0029(DCX0029);
		}

		String DCX0030 = (String)attributes.get("DCX0030");

		if (DCX0030 != null) {
			setDCX0030(DCX0030);
		}

		String DCX0031 = (String)attributes.get("DCX0031");

		if (DCX0031 != null) {
			setDCX0031(DCX0031);
		}
	}

	@JSON
	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		_columnBitmask = -1L;

		_id = id;
	}

	@JSON
	@Override
	public long getHoSoThuTucId() {
		return _hoSoThuTucId;
	}

	@Override
	public void setHoSoThuTucId(long hoSoThuTucId) {
		_columnBitmask |= HOSOTHUTUCID_COLUMN_BITMASK;

		if (!_setOriginalHoSoThuTucId) {
			_setOriginalHoSoThuTucId = true;

			_originalHoSoThuTucId = _hoSoThuTucId;
		}

		_hoSoThuTucId = hoSoThuTucId;
	}

	public long getOriginalHoSoThuTucId() {
		return _originalHoSoThuTucId;
	}

	@JSON
	@Override
	public long getCertificateRecordId() {
		return _certificateRecordId;
	}

	@Override
	public void setCertificateRecordId(long certificateRecordId) {
		_columnBitmask |= CERTIFICATERECORDID_COLUMN_BITMASK;

		if (!_setOriginalCertificateRecordId) {
			_setOriginalCertificateRecordId = true;

			_originalCertificateRecordId = _certificateRecordId;
		}

		_certificateRecordId = certificateRecordId;
	}

	public long getOriginalCertificateRecordId() {
		return _originalCertificateRecordId;
	}

	@JSON
	@Override
	public long getVehicleGroupId() {
		return _vehicleGroupId;
	}

	@Override
	public void setVehicleGroupId(long vehicleGroupId) {
		_columnBitmask |= VEHICLEGROUPID_COLUMN_BITMASK;

		if (!_setOriginalVehicleGroupId) {
			_setOriginalVehicleGroupId = true;

			_originalVehicleGroupId = _vehicleGroupId;
		}

		_vehicleGroupId = vehicleGroupId;
	}

	public long getOriginalVehicleGroupId() {
		return _originalVehicleGroupId;
	}

	@JSON
	@Override
	public Date getSynchDate() {
		return _SynchDate;
	}

	@Override
	public void setSynchDate(Date SynchDate) {
		_SynchDate = SynchDate;
	}

	@JSON
	@Override
	public String getDCX0007() {
		if (_DCX0007 == null) {
			return StringPool.BLANK;
		}
		else {
			return _DCX0007;
		}
	}

	@Override
	public void setDCX0007(String DCX0007) {
		_DCX0007 = DCX0007;
	}

	@JSON
	@Override
	public String getDCX0008() {
		if (_DCX0008 == null) {
			return StringPool.BLANK;
		}
		else {
			return _DCX0008;
		}
	}

	@Override
	public void setDCX0008(String DCX0008) {
		_DCX0008 = DCX0008;
	}

	@JSON
	@Override
	public String getDCX0010() {
		if (_DCX0010 == null) {
			return StringPool.BLANK;
		}
		else {
			return _DCX0010;
		}
	}

	@Override
	public void setDCX0010(String DCX0010) {
		_DCX0010 = DCX0010;
	}

	@JSON
	@Override
	public String getDCX0011() {
		if (_DCX0011 == null) {
			return StringPool.BLANK;
		}
		else {
			return _DCX0011;
		}
	}

	@Override
	public void setDCX0011(String DCX0011) {
		_DCX0011 = DCX0011;
	}

	@JSON
	@Override
	public String getDCX0012() {
		if (_DCX0012 == null) {
			return StringPool.BLANK;
		}
		else {
			return _DCX0012;
		}
	}

	@Override
	public void setDCX0012(String DCX0012) {
		_DCX0012 = DCX0012;
	}

	@JSON
	@Override
	public String getDCX1012() {
		if (_DCX1012 == null) {
			return StringPool.BLANK;
		}
		else {
			return _DCX1012;
		}
	}

	@Override
	public void setDCX1012(String DCX1012) {
		_DCX1012 = DCX1012;
	}

	@JSON
	@Override
	public String getDCX0013() {
		if (_DCX0013 == null) {
			return StringPool.BLANK;
		}
		else {
			return _DCX0013;
		}
	}

	@Override
	public void setDCX0013(String DCX0013) {
		_DCX0013 = DCX0013;
	}

	@JSON
	@Override
	public String getDCX1013() {
		if (_DCX1013 == null) {
			return StringPool.BLANK;
		}
		else {
			return _DCX1013;
		}
	}

	@Override
	public void setDCX1013(String DCX1013) {
		_DCX1013 = DCX1013;
	}

	@JSON
	@Override
	public String getDCX0014() {
		if (_DCX0014 == null) {
			return StringPool.BLANK;
		}
		else {
			return _DCX0014;
		}
	}

	@Override
	public void setDCX0014(String DCX0014) {
		_DCX0014 = DCX0014;
	}

	@JSON
	@Override
	public String getDCX0015() {
		if (_DCX0015 == null) {
			return StringPool.BLANK;
		}
		else {
			return _DCX0015;
		}
	}

	@Override
	public void setDCX0015(String DCX0015) {
		_DCX0015 = DCX0015;
	}

	@JSON
	@Override
	public String getDCX0016() {
		if (_DCX0016 == null) {
			return StringPool.BLANK;
		}
		else {
			return _DCX0016;
		}
	}

	@Override
	public void setDCX0016(String DCX0016) {
		_DCX0016 = DCX0016;
	}

	@JSON
	@Override
	public String getDCX0017() {
		if (_DCX0017 == null) {
			return StringPool.BLANK;
		}
		else {
			return _DCX0017;
		}
	}

	@Override
	public void setDCX0017(String DCX0017) {
		_DCX0017 = DCX0017;
	}

	@JSON
	@Override
	public String getDCX0018() {
		if (_DCX0018 == null) {
			return StringPool.BLANK;
		}
		else {
			return _DCX0018;
		}
	}

	@Override
	public void setDCX0018(String DCX0018) {
		_DCX0018 = DCX0018;
	}

	@JSON
	@Override
	public String getDCX0019() {
		if (_DCX0019 == null) {
			return StringPool.BLANK;
		}
		else {
			return _DCX0019;
		}
	}

	@Override
	public void setDCX0019(String DCX0019) {
		_DCX0019 = DCX0019;
	}

	@JSON
	@Override
	public String getDCX0021() {
		if (_DCX0021 == null) {
			return StringPool.BLANK;
		}
		else {
			return _DCX0021;
		}
	}

	@Override
	public void setDCX0021(String DCX0021) {
		_DCX0021 = DCX0021;
	}

	@JSON
	@Override
	public String getDCX0022() {
		if (_DCX0022 == null) {
			return StringPool.BLANK;
		}
		else {
			return _DCX0022;
		}
	}

	@Override
	public void setDCX0022(String DCX0022) {
		_DCX0022 = DCX0022;
	}

	@JSON
	@Override
	public String getDCX0023() {
		if (_DCX0023 == null) {
			return StringPool.BLANK;
		}
		else {
			return _DCX0023;
		}
	}

	@Override
	public void setDCX0023(String DCX0023) {
		_DCX0023 = DCX0023;
	}

	@JSON
	@Override
	public String getDCX0024() {
		if (_DCX0024 == null) {
			return StringPool.BLANK;
		}
		else {
			return _DCX0024;
		}
	}

	@Override
	public void setDCX0024(String DCX0024) {
		_DCX0024 = DCX0024;
	}

	@JSON
	@Override
	public String getDCX0006() {
		if (_DCX0006 == null) {
			return StringPool.BLANK;
		}
		else {
			return _DCX0006;
		}
	}

	@Override
	public void setDCX0006(String DCX0006) {
		_DCX0006 = DCX0006;
	}

	@JSON
	@Override
	public String getDCX0025() {
		if (_DCX0025 == null) {
			return StringPool.BLANK;
		}
		else {
			return _DCX0025;
		}
	}

	@Override
	public void setDCX0025(String DCX0025) {
		_DCX0025 = DCX0025;
	}

	@JSON
	@Override
	public String getDCX0026() {
		if (_DCX0026 == null) {
			return StringPool.BLANK;
		}
		else {
			return _DCX0026;
		}
	}

	@Override
	public void setDCX0026(String DCX0026) {
		_DCX0026 = DCX0026;
	}

	@JSON
	@Override
	public String getDCX0027() {
		if (_DCX0027 == null) {
			return StringPool.BLANK;
		}
		else {
			return _DCX0027;
		}
	}

	@Override
	public void setDCX0027(String DCX0027) {
		_DCX0027 = DCX0027;
	}

	@JSON
	@Override
	public String getDCX0028() {
		if (_DCX0028 == null) {
			return StringPool.BLANK;
		}
		else {
			return _DCX0028;
		}
	}

	@Override
	public void setDCX0028(String DCX0028) {
		_DCX0028 = DCX0028;
	}

	@JSON
	@Override
	public String getDCX0029() {
		if (_DCX0029 == null) {
			return StringPool.BLANK;
		}
		else {
			return _DCX0029;
		}
	}

	@Override
	public void setDCX0029(String DCX0029) {
		_DCX0029 = DCX0029;
	}

	@JSON
	@Override
	public String getDCX0030() {
		if (_DCX0030 == null) {
			return StringPool.BLANK;
		}
		else {
			return _DCX0030;
		}
	}

	@Override
	public void setDCX0030(String DCX0030) {
		_DCX0030 = DCX0030;
	}

	@JSON
	@Override
	public String getDCX0031() {
		if (_DCX0031 == null) {
			return StringPool.BLANK;
		}
		else {
			return _DCX0031;
		}
	}

	@Override
	public void setDCX0031(String DCX0031) {
		_DCX0031 = DCX0031;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			THONGSOCHUNGCHIDONGCO.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public THONGSOCHUNGCHIDONGCO toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (THONGSOCHUNGCHIDONGCO)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		THONGSOCHUNGCHIDONGCOImpl thongsochungchidongcoImpl = new THONGSOCHUNGCHIDONGCOImpl();

		thongsochungchidongcoImpl.setId(getId());
		thongsochungchidongcoImpl.setHoSoThuTucId(getHoSoThuTucId());
		thongsochungchidongcoImpl.setCertificateRecordId(getCertificateRecordId());
		thongsochungchidongcoImpl.setVehicleGroupId(getVehicleGroupId());
		thongsochungchidongcoImpl.setSynchDate(getSynchDate());
		thongsochungchidongcoImpl.setDCX0007(getDCX0007());
		thongsochungchidongcoImpl.setDCX0008(getDCX0008());
		thongsochungchidongcoImpl.setDCX0010(getDCX0010());
		thongsochungchidongcoImpl.setDCX0011(getDCX0011());
		thongsochungchidongcoImpl.setDCX0012(getDCX0012());
		thongsochungchidongcoImpl.setDCX1012(getDCX1012());
		thongsochungchidongcoImpl.setDCX0013(getDCX0013());
		thongsochungchidongcoImpl.setDCX1013(getDCX1013());
		thongsochungchidongcoImpl.setDCX0014(getDCX0014());
		thongsochungchidongcoImpl.setDCX0015(getDCX0015());
		thongsochungchidongcoImpl.setDCX0016(getDCX0016());
		thongsochungchidongcoImpl.setDCX0017(getDCX0017());
		thongsochungchidongcoImpl.setDCX0018(getDCX0018());
		thongsochungchidongcoImpl.setDCX0019(getDCX0019());
		thongsochungchidongcoImpl.setDCX0021(getDCX0021());
		thongsochungchidongcoImpl.setDCX0022(getDCX0022());
		thongsochungchidongcoImpl.setDCX0023(getDCX0023());
		thongsochungchidongcoImpl.setDCX0024(getDCX0024());
		thongsochungchidongcoImpl.setDCX0006(getDCX0006());
		thongsochungchidongcoImpl.setDCX0025(getDCX0025());
		thongsochungchidongcoImpl.setDCX0026(getDCX0026());
		thongsochungchidongcoImpl.setDCX0027(getDCX0027());
		thongsochungchidongcoImpl.setDCX0028(getDCX0028());
		thongsochungchidongcoImpl.setDCX0029(getDCX0029());
		thongsochungchidongcoImpl.setDCX0030(getDCX0030());
		thongsochungchidongcoImpl.setDCX0031(getDCX0031());

		thongsochungchidongcoImpl.resetOriginalValues();

		return thongsochungchidongcoImpl;
	}

	@Override
	public int compareTo(THONGSOCHUNGCHIDONGCO thongsochungchidongco) {
		int value = 0;

		if (getId() < thongsochungchidongco.getId()) {
			value = -1;
		}
		else if (getId() > thongsochungchidongco.getId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof THONGSOCHUNGCHIDONGCO)) {
			return false;
		}

		THONGSOCHUNGCHIDONGCO thongsochungchidongco = (THONGSOCHUNGCHIDONGCO)obj;

		long primaryKey = thongsochungchidongco.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		THONGSOCHUNGCHIDONGCOModelImpl thongsochungchidongcoModelImpl = this;

		thongsochungchidongcoModelImpl._originalHoSoThuTucId = thongsochungchidongcoModelImpl._hoSoThuTucId;

		thongsochungchidongcoModelImpl._setOriginalHoSoThuTucId = false;

		thongsochungchidongcoModelImpl._originalCertificateRecordId = thongsochungchidongcoModelImpl._certificateRecordId;

		thongsochungchidongcoModelImpl._setOriginalCertificateRecordId = false;

		thongsochungchidongcoModelImpl._originalVehicleGroupId = thongsochungchidongcoModelImpl._vehicleGroupId;

		thongsochungchidongcoModelImpl._setOriginalVehicleGroupId = false;

		thongsochungchidongcoModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<THONGSOCHUNGCHIDONGCO> toCacheModel() {
		THONGSOCHUNGCHIDONGCOCacheModel thongsochungchidongcoCacheModel = new THONGSOCHUNGCHIDONGCOCacheModel();

		thongsochungchidongcoCacheModel.id = getId();

		thongsochungchidongcoCacheModel.hoSoThuTucId = getHoSoThuTucId();

		thongsochungchidongcoCacheModel.certificateRecordId = getCertificateRecordId();

		thongsochungchidongcoCacheModel.vehicleGroupId = getVehicleGroupId();

		Date SynchDate = getSynchDate();

		if (SynchDate != null) {
			thongsochungchidongcoCacheModel.SynchDate = SynchDate.getTime();
		}
		else {
			thongsochungchidongcoCacheModel.SynchDate = Long.MIN_VALUE;
		}

		thongsochungchidongcoCacheModel.DCX0007 = getDCX0007();

		String DCX0007 = thongsochungchidongcoCacheModel.DCX0007;

		if ((DCX0007 != null) && (DCX0007.length() == 0)) {
			thongsochungchidongcoCacheModel.DCX0007 = null;
		}

		thongsochungchidongcoCacheModel.DCX0008 = getDCX0008();

		String DCX0008 = thongsochungchidongcoCacheModel.DCX0008;

		if ((DCX0008 != null) && (DCX0008.length() == 0)) {
			thongsochungchidongcoCacheModel.DCX0008 = null;
		}

		thongsochungchidongcoCacheModel.DCX0010 = getDCX0010();

		String DCX0010 = thongsochungchidongcoCacheModel.DCX0010;

		if ((DCX0010 != null) && (DCX0010.length() == 0)) {
			thongsochungchidongcoCacheModel.DCX0010 = null;
		}

		thongsochungchidongcoCacheModel.DCX0011 = getDCX0011();

		String DCX0011 = thongsochungchidongcoCacheModel.DCX0011;

		if ((DCX0011 != null) && (DCX0011.length() == 0)) {
			thongsochungchidongcoCacheModel.DCX0011 = null;
		}

		thongsochungchidongcoCacheModel.DCX0012 = getDCX0012();

		String DCX0012 = thongsochungchidongcoCacheModel.DCX0012;

		if ((DCX0012 != null) && (DCX0012.length() == 0)) {
			thongsochungchidongcoCacheModel.DCX0012 = null;
		}

		thongsochungchidongcoCacheModel.DCX1012 = getDCX1012();

		String DCX1012 = thongsochungchidongcoCacheModel.DCX1012;

		if ((DCX1012 != null) && (DCX1012.length() == 0)) {
			thongsochungchidongcoCacheModel.DCX1012 = null;
		}

		thongsochungchidongcoCacheModel.DCX0013 = getDCX0013();

		String DCX0013 = thongsochungchidongcoCacheModel.DCX0013;

		if ((DCX0013 != null) && (DCX0013.length() == 0)) {
			thongsochungchidongcoCacheModel.DCX0013 = null;
		}

		thongsochungchidongcoCacheModel.DCX1013 = getDCX1013();

		String DCX1013 = thongsochungchidongcoCacheModel.DCX1013;

		if ((DCX1013 != null) && (DCX1013.length() == 0)) {
			thongsochungchidongcoCacheModel.DCX1013 = null;
		}

		thongsochungchidongcoCacheModel.DCX0014 = getDCX0014();

		String DCX0014 = thongsochungchidongcoCacheModel.DCX0014;

		if ((DCX0014 != null) && (DCX0014.length() == 0)) {
			thongsochungchidongcoCacheModel.DCX0014 = null;
		}

		thongsochungchidongcoCacheModel.DCX0015 = getDCX0015();

		String DCX0015 = thongsochungchidongcoCacheModel.DCX0015;

		if ((DCX0015 != null) && (DCX0015.length() == 0)) {
			thongsochungchidongcoCacheModel.DCX0015 = null;
		}

		thongsochungchidongcoCacheModel.DCX0016 = getDCX0016();

		String DCX0016 = thongsochungchidongcoCacheModel.DCX0016;

		if ((DCX0016 != null) && (DCX0016.length() == 0)) {
			thongsochungchidongcoCacheModel.DCX0016 = null;
		}

		thongsochungchidongcoCacheModel.DCX0017 = getDCX0017();

		String DCX0017 = thongsochungchidongcoCacheModel.DCX0017;

		if ((DCX0017 != null) && (DCX0017.length() == 0)) {
			thongsochungchidongcoCacheModel.DCX0017 = null;
		}

		thongsochungchidongcoCacheModel.DCX0018 = getDCX0018();

		String DCX0018 = thongsochungchidongcoCacheModel.DCX0018;

		if ((DCX0018 != null) && (DCX0018.length() == 0)) {
			thongsochungchidongcoCacheModel.DCX0018 = null;
		}

		thongsochungchidongcoCacheModel.DCX0019 = getDCX0019();

		String DCX0019 = thongsochungchidongcoCacheModel.DCX0019;

		if ((DCX0019 != null) && (DCX0019.length() == 0)) {
			thongsochungchidongcoCacheModel.DCX0019 = null;
		}

		thongsochungchidongcoCacheModel.DCX0021 = getDCX0021();

		String DCX0021 = thongsochungchidongcoCacheModel.DCX0021;

		if ((DCX0021 != null) && (DCX0021.length() == 0)) {
			thongsochungchidongcoCacheModel.DCX0021 = null;
		}

		thongsochungchidongcoCacheModel.DCX0022 = getDCX0022();

		String DCX0022 = thongsochungchidongcoCacheModel.DCX0022;

		if ((DCX0022 != null) && (DCX0022.length() == 0)) {
			thongsochungchidongcoCacheModel.DCX0022 = null;
		}

		thongsochungchidongcoCacheModel.DCX0023 = getDCX0023();

		String DCX0023 = thongsochungchidongcoCacheModel.DCX0023;

		if ((DCX0023 != null) && (DCX0023.length() == 0)) {
			thongsochungchidongcoCacheModel.DCX0023 = null;
		}

		thongsochungchidongcoCacheModel.DCX0024 = getDCX0024();

		String DCX0024 = thongsochungchidongcoCacheModel.DCX0024;

		if ((DCX0024 != null) && (DCX0024.length() == 0)) {
			thongsochungchidongcoCacheModel.DCX0024 = null;
		}

		thongsochungchidongcoCacheModel.DCX0006 = getDCX0006();

		String DCX0006 = thongsochungchidongcoCacheModel.DCX0006;

		if ((DCX0006 != null) && (DCX0006.length() == 0)) {
			thongsochungchidongcoCacheModel.DCX0006 = null;
		}

		thongsochungchidongcoCacheModel.DCX0025 = getDCX0025();

		String DCX0025 = thongsochungchidongcoCacheModel.DCX0025;

		if ((DCX0025 != null) && (DCX0025.length() == 0)) {
			thongsochungchidongcoCacheModel.DCX0025 = null;
		}

		thongsochungchidongcoCacheModel.DCX0026 = getDCX0026();

		String DCX0026 = thongsochungchidongcoCacheModel.DCX0026;

		if ((DCX0026 != null) && (DCX0026.length() == 0)) {
			thongsochungchidongcoCacheModel.DCX0026 = null;
		}

		thongsochungchidongcoCacheModel.DCX0027 = getDCX0027();

		String DCX0027 = thongsochungchidongcoCacheModel.DCX0027;

		if ((DCX0027 != null) && (DCX0027.length() == 0)) {
			thongsochungchidongcoCacheModel.DCX0027 = null;
		}

		thongsochungchidongcoCacheModel.DCX0028 = getDCX0028();

		String DCX0028 = thongsochungchidongcoCacheModel.DCX0028;

		if ((DCX0028 != null) && (DCX0028.length() == 0)) {
			thongsochungchidongcoCacheModel.DCX0028 = null;
		}

		thongsochungchidongcoCacheModel.DCX0029 = getDCX0029();

		String DCX0029 = thongsochungchidongcoCacheModel.DCX0029;

		if ((DCX0029 != null) && (DCX0029.length() == 0)) {
			thongsochungchidongcoCacheModel.DCX0029 = null;
		}

		thongsochungchidongcoCacheModel.DCX0030 = getDCX0030();

		String DCX0030 = thongsochungchidongcoCacheModel.DCX0030;

		if ((DCX0030 != null) && (DCX0030.length() == 0)) {
			thongsochungchidongcoCacheModel.DCX0030 = null;
		}

		thongsochungchidongcoCacheModel.DCX0031 = getDCX0031();

		String DCX0031 = thongsochungchidongcoCacheModel.DCX0031;

		if ((DCX0031 != null) && (DCX0031.length() == 0)) {
			thongsochungchidongcoCacheModel.DCX0031 = null;
		}

		return thongsochungchidongcoCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(63);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", hoSoThuTucId=");
		sb.append(getHoSoThuTucId());
		sb.append(", certificateRecordId=");
		sb.append(getCertificateRecordId());
		sb.append(", vehicleGroupId=");
		sb.append(getVehicleGroupId());
		sb.append(", SynchDate=");
		sb.append(getSynchDate());
		sb.append(", DCX0007=");
		sb.append(getDCX0007());
		sb.append(", DCX0008=");
		sb.append(getDCX0008());
		sb.append(", DCX0010=");
		sb.append(getDCX0010());
		sb.append(", DCX0011=");
		sb.append(getDCX0011());
		sb.append(", DCX0012=");
		sb.append(getDCX0012());
		sb.append(", DCX1012=");
		sb.append(getDCX1012());
		sb.append(", DCX0013=");
		sb.append(getDCX0013());
		sb.append(", DCX1013=");
		sb.append(getDCX1013());
		sb.append(", DCX0014=");
		sb.append(getDCX0014());
		sb.append(", DCX0015=");
		sb.append(getDCX0015());
		sb.append(", DCX0016=");
		sb.append(getDCX0016());
		sb.append(", DCX0017=");
		sb.append(getDCX0017());
		sb.append(", DCX0018=");
		sb.append(getDCX0018());
		sb.append(", DCX0019=");
		sb.append(getDCX0019());
		sb.append(", DCX0021=");
		sb.append(getDCX0021());
		sb.append(", DCX0022=");
		sb.append(getDCX0022());
		sb.append(", DCX0023=");
		sb.append(getDCX0023());
		sb.append(", DCX0024=");
		sb.append(getDCX0024());
		sb.append(", DCX0006=");
		sb.append(getDCX0006());
		sb.append(", DCX0025=");
		sb.append(getDCX0025());
		sb.append(", DCX0026=");
		sb.append(getDCX0026());
		sb.append(", DCX0027=");
		sb.append(getDCX0027());
		sb.append(", DCX0028=");
		sb.append(getDCX0028());
		sb.append(", DCX0029=");
		sb.append(getDCX0029());
		sb.append(", DCX0030=");
		sb.append(getDCX0030());
		sb.append(", DCX0031=");
		sb.append(getDCX0031());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(97);

		sb.append("<model><model-name>");
		sb.append("vn.dtt.gt.dk.dao.nghiepvu.model.THONGSOCHUNGCHIDONGCO");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>hoSoThuTucId</column-name><column-value><![CDATA[");
		sb.append(getHoSoThuTucId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>certificateRecordId</column-name><column-value><![CDATA[");
		sb.append(getCertificateRecordId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>vehicleGroupId</column-name><column-value><![CDATA[");
		sb.append(getVehicleGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>SynchDate</column-name><column-value><![CDATA[");
		sb.append(getSynchDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>DCX0007</column-name><column-value><![CDATA[");
		sb.append(getDCX0007());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>DCX0008</column-name><column-value><![CDATA[");
		sb.append(getDCX0008());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>DCX0010</column-name><column-value><![CDATA[");
		sb.append(getDCX0010());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>DCX0011</column-name><column-value><![CDATA[");
		sb.append(getDCX0011());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>DCX0012</column-name><column-value><![CDATA[");
		sb.append(getDCX0012());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>DCX1012</column-name><column-value><![CDATA[");
		sb.append(getDCX1012());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>DCX0013</column-name><column-value><![CDATA[");
		sb.append(getDCX0013());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>DCX1013</column-name><column-value><![CDATA[");
		sb.append(getDCX1013());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>DCX0014</column-name><column-value><![CDATA[");
		sb.append(getDCX0014());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>DCX0015</column-name><column-value><![CDATA[");
		sb.append(getDCX0015());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>DCX0016</column-name><column-value><![CDATA[");
		sb.append(getDCX0016());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>DCX0017</column-name><column-value><![CDATA[");
		sb.append(getDCX0017());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>DCX0018</column-name><column-value><![CDATA[");
		sb.append(getDCX0018());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>DCX0019</column-name><column-value><![CDATA[");
		sb.append(getDCX0019());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>DCX0021</column-name><column-value><![CDATA[");
		sb.append(getDCX0021());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>DCX0022</column-name><column-value><![CDATA[");
		sb.append(getDCX0022());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>DCX0023</column-name><column-value><![CDATA[");
		sb.append(getDCX0023());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>DCX0024</column-name><column-value><![CDATA[");
		sb.append(getDCX0024());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>DCX0006</column-name><column-value><![CDATA[");
		sb.append(getDCX0006());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>DCX0025</column-name><column-value><![CDATA[");
		sb.append(getDCX0025());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>DCX0026</column-name><column-value><![CDATA[");
		sb.append(getDCX0026());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>DCX0027</column-name><column-value><![CDATA[");
		sb.append(getDCX0027());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>DCX0028</column-name><column-value><![CDATA[");
		sb.append(getDCX0028());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>DCX0029</column-name><column-value><![CDATA[");
		sb.append(getDCX0029());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>DCX0030</column-name><column-value><![CDATA[");
		sb.append(getDCX0030());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>DCX0031</column-name><column-value><![CDATA[");
		sb.append(getDCX0031());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = THONGSOCHUNGCHIDONGCO.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			THONGSOCHUNGCHIDONGCO.class
		};
	private long _id;
	private long _hoSoThuTucId;
	private long _originalHoSoThuTucId;
	private boolean _setOriginalHoSoThuTucId;
	private long _certificateRecordId;
	private long _originalCertificateRecordId;
	private boolean _setOriginalCertificateRecordId;
	private long _vehicleGroupId;
	private long _originalVehicleGroupId;
	private boolean _setOriginalVehicleGroupId;
	private Date _SynchDate;
	private String _DCX0007;
	private String _DCX0008;
	private String _DCX0010;
	private String _DCX0011;
	private String _DCX0012;
	private String _DCX1012;
	private String _DCX0013;
	private String _DCX1013;
	private String _DCX0014;
	private String _DCX0015;
	private String _DCX0016;
	private String _DCX0017;
	private String _DCX0018;
	private String _DCX0019;
	private String _DCX0021;
	private String _DCX0022;
	private String _DCX0023;
	private String _DCX0024;
	private String _DCX0006;
	private String _DCX0025;
	private String _DCX0026;
	private String _DCX0027;
	private String _DCX0028;
	private String _DCX0029;
	private String _DCX0030;
	private String _DCX0031;
	private long _columnBitmask;
	private THONGSOCHUNGCHIDONGCO _escapedModel;
}