/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.gt.dk.dao.nghiepvu.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import vn.dtt.gt.dk.dao.nghiepvu.model.THONGSOCHUNGCHIXEDAPDIEN;
import vn.dtt.gt.dk.dao.nghiepvu.model.THONGSOCHUNGCHIXEDAPDIENModel;
import vn.dtt.gt.dk.dao.nghiepvu.model.THONGSOCHUNGCHIXEDAPDIENSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the THONGSOCHUNGCHIXEDAPDIEN service. Represents a row in the &quot;thongsochungchi_xedapdien&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link vn.dtt.gt.dk.dao.nghiepvu.model.THONGSOCHUNGCHIXEDAPDIENModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link THONGSOCHUNGCHIXEDAPDIENImpl}.
 * </p>
 *
 * @author win_64
 * @see THONGSOCHUNGCHIXEDAPDIENImpl
 * @see vn.dtt.gt.dk.dao.nghiepvu.model.THONGSOCHUNGCHIXEDAPDIEN
 * @see vn.dtt.gt.dk.dao.nghiepvu.model.THONGSOCHUNGCHIXEDAPDIENModel
 * @generated
 */
@JSON(strict = true)
public class THONGSOCHUNGCHIXEDAPDIENModelImpl extends BaseModelImpl<THONGSOCHUNGCHIXEDAPDIEN>
	implements THONGSOCHUNGCHIXEDAPDIENModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a t h o n g s o c h u n g c h i x e d a p d i e n model instance should use the {@link vn.dtt.gt.dk.dao.nghiepvu.model.THONGSOCHUNGCHIXEDAPDIEN} interface instead.
	 */
	public static final String TABLE_NAME = "thongsochungchi_xedapdien";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id", Types.BIGINT },
			{ "hoSoThuTucId", Types.BIGINT },
			{ "certificateRecordId", Types.BIGINT },
			{ "vehicleGroupId", Types.BIGINT },
			{ "SynchDate", Types.TIMESTAMP },
			{ "XDD0008", Types.VARCHAR },
			{ "XDD0009", Types.VARCHAR },
			{ "XDD0010", Types.VARCHAR },
			{ "XDD0011", Types.VARCHAR },
			{ "XDD0012", Types.VARCHAR },
			{ "XDD0013", Types.VARCHAR },
			{ "XDD0014", Types.VARCHAR },
			{ "XDD0015", Types.VARCHAR },
			{ "XDD0016", Types.VARCHAR },
			{ "XDD0017", Types.VARCHAR },
			{ "XDD0018", Types.VARCHAR },
			{ "XDD0019", Types.VARCHAR },
			{ "XDD0020", Types.VARCHAR },
			{ "XDD0021", Types.VARCHAR },
			{ "XDD0022", Types.VARCHAR },
			{ "XDD0023", Types.VARCHAR },
			{ "XDD0024", Types.VARCHAR },
			{ "XDD0025", Types.VARCHAR },
			{ "XDD0026", Types.VARCHAR },
			{ "XDD0027", Types.VARCHAR },
			{ "XDD1027", Types.VARCHAR },
			{ "XDD0028", Types.VARCHAR },
			{ "XDD1028", Types.VARCHAR },
			{ "XDD1128", Types.VARCHAR },
			{ "XDD0029", Types.VARCHAR },
			{ "XDD1029", Types.VARCHAR },
			{ "XDD1129", Types.VARCHAR },
			{ "XDD0030", Types.VARCHAR },
			{ "XDD0031", Types.VARCHAR },
			{ "XDD0032", Types.VARCHAR },
			{ "XDD0033", Types.VARCHAR },
			{ "XDD0034", Types.VARCHAR },
			{ "XDD1034", Types.VARCHAR },
			{ "XDD0035", Types.VARCHAR },
			{ "XDD1035", Types.VARCHAR },
			{ "XDD0036", Types.VARCHAR },
			{ "XDD0037", Types.VARCHAR },
			{ "XDD0038", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table thongsochungchi_xedapdien (id LONG not null primary key,hoSoThuTucId LONG,certificateRecordId LONG,vehicleGroupId LONG,SynchDate DATE null,XDD0008 VARCHAR(75) null,XDD0009 VARCHAR(75) null,XDD0010 VARCHAR(75) null,XDD0011 VARCHAR(75) null,XDD0012 VARCHAR(75) null,XDD0013 VARCHAR(75) null,XDD0014 VARCHAR(75) null,XDD0015 VARCHAR(75) null,XDD0016 VARCHAR(75) null,XDD0017 VARCHAR(75) null,XDD0018 VARCHAR(75) null,XDD0019 VARCHAR(75) null,XDD0020 VARCHAR(75) null,XDD0021 VARCHAR(75) null,XDD0022 VARCHAR(75) null,XDD0023 VARCHAR(75) null,XDD0024 VARCHAR(75) null,XDD0025 VARCHAR(75) null,XDD0026 VARCHAR(75) null,XDD0027 VARCHAR(75) null,XDD1027 VARCHAR(75) null,XDD0028 VARCHAR(75) null,XDD1028 VARCHAR(75) null,XDD1128 VARCHAR(75) null,XDD0029 VARCHAR(75) null,XDD1029 VARCHAR(75) null,XDD1129 VARCHAR(75) null,XDD0030 VARCHAR(75) null,XDD0031 VARCHAR(75) null,XDD0032 VARCHAR(75) null,XDD0033 VARCHAR(75) null,XDD0034 VARCHAR(75) null,XDD1034 VARCHAR(75) null,XDD0035 VARCHAR(75) null,XDD1035 VARCHAR(75) null,XDD0036 VARCHAR(75) null,XDD0037 VARCHAR(75) null,XDD0038 VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table thongsochungchi_xedapdien";
	public static final String ORDER_BY_JPQL = " ORDER BY thongsochungchixedapdien.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY thongsochungchi_xedapdien.id ASC";
	public static final String DATA_SOURCE = "vrDataSource";
	public static final String SESSION_FACTORY = "vrSessionFactory";
	public static final String TX_MANAGER = "vrTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.vn.dtt.gt.dk.dao.nghiepvu.model.THONGSOCHUNGCHIXEDAPDIEN"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.vn.dtt.gt.dk.dao.nghiepvu.model.THONGSOCHUNGCHIXEDAPDIEN"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.vn.dtt.gt.dk.dao.nghiepvu.model.THONGSOCHUNGCHIXEDAPDIEN"),
			true);
	public static long CERTIFICATERECORDID_COLUMN_BITMASK = 1L;
	public static long HOSOTHUTUCID_COLUMN_BITMASK = 2L;
	public static long VEHICLEGROUPID_COLUMN_BITMASK = 4L;
	public static long ID_COLUMN_BITMASK = 8L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static THONGSOCHUNGCHIXEDAPDIEN toModel(
		THONGSOCHUNGCHIXEDAPDIENSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		THONGSOCHUNGCHIXEDAPDIEN model = new THONGSOCHUNGCHIXEDAPDIENImpl();

		model.setId(soapModel.getId());
		model.setHoSoThuTucId(soapModel.getHoSoThuTucId());
		model.setCertificateRecordId(soapModel.getCertificateRecordId());
		model.setVehicleGroupId(soapModel.getVehicleGroupId());
		model.setSynchDate(soapModel.getSynchDate());
		model.setXDD0008(soapModel.getXDD0008());
		model.setXDD0009(soapModel.getXDD0009());
		model.setXDD0010(soapModel.getXDD0010());
		model.setXDD0011(soapModel.getXDD0011());
		model.setXDD0012(soapModel.getXDD0012());
		model.setXDD0013(soapModel.getXDD0013());
		model.setXDD0014(soapModel.getXDD0014());
		model.setXDD0015(soapModel.getXDD0015());
		model.setXDD0016(soapModel.getXDD0016());
		model.setXDD0017(soapModel.getXDD0017());
		model.setXDD0018(soapModel.getXDD0018());
		model.setXDD0019(soapModel.getXDD0019());
		model.setXDD0020(soapModel.getXDD0020());
		model.setXDD0021(soapModel.getXDD0021());
		model.setXDD0022(soapModel.getXDD0022());
		model.setXDD0023(soapModel.getXDD0023());
		model.setXDD0024(soapModel.getXDD0024());
		model.setXDD0025(soapModel.getXDD0025());
		model.setXDD0026(soapModel.getXDD0026());
		model.setXDD0027(soapModel.getXDD0027());
		model.setXDD1027(soapModel.getXDD1027());
		model.setXDD0028(soapModel.getXDD0028());
		model.setXDD1028(soapModel.getXDD1028());
		model.setXDD1128(soapModel.getXDD1128());
		model.setXDD0029(soapModel.getXDD0029());
		model.setXDD1029(soapModel.getXDD1029());
		model.setXDD1129(soapModel.getXDD1129());
		model.setXDD0030(soapModel.getXDD0030());
		model.setXDD0031(soapModel.getXDD0031());
		model.setXDD0032(soapModel.getXDD0032());
		model.setXDD0033(soapModel.getXDD0033());
		model.setXDD0034(soapModel.getXDD0034());
		model.setXDD1034(soapModel.getXDD1034());
		model.setXDD0035(soapModel.getXDD0035());
		model.setXDD1035(soapModel.getXDD1035());
		model.setXDD0036(soapModel.getXDD0036());
		model.setXDD0037(soapModel.getXDD0037());
		model.setXDD0038(soapModel.getXDD0038());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<THONGSOCHUNGCHIXEDAPDIEN> toModels(
		THONGSOCHUNGCHIXEDAPDIENSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<THONGSOCHUNGCHIXEDAPDIEN> models = new ArrayList<THONGSOCHUNGCHIXEDAPDIEN>(soapModels.length);

		for (THONGSOCHUNGCHIXEDAPDIENSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.vn.dtt.gt.dk.dao.nghiepvu.model.THONGSOCHUNGCHIXEDAPDIEN"));

	public THONGSOCHUNGCHIXEDAPDIENModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return THONGSOCHUNGCHIXEDAPDIEN.class;
	}

	@Override
	public String getModelClassName() {
		return THONGSOCHUNGCHIXEDAPDIEN.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("hoSoThuTucId", getHoSoThuTucId());
		attributes.put("certificateRecordId", getCertificateRecordId());
		attributes.put("vehicleGroupId", getVehicleGroupId());
		attributes.put("SynchDate", getSynchDate());
		attributes.put("XDD0008", getXDD0008());
		attributes.put("XDD0009", getXDD0009());
		attributes.put("XDD0010", getXDD0010());
		attributes.put("XDD0011", getXDD0011());
		attributes.put("XDD0012", getXDD0012());
		attributes.put("XDD0013", getXDD0013());
		attributes.put("XDD0014", getXDD0014());
		attributes.put("XDD0015", getXDD0015());
		attributes.put("XDD0016", getXDD0016());
		attributes.put("XDD0017", getXDD0017());
		attributes.put("XDD0018", getXDD0018());
		attributes.put("XDD0019", getXDD0019());
		attributes.put("XDD0020", getXDD0020());
		attributes.put("XDD0021", getXDD0021());
		attributes.put("XDD0022", getXDD0022());
		attributes.put("XDD0023", getXDD0023());
		attributes.put("XDD0024", getXDD0024());
		attributes.put("XDD0025", getXDD0025());
		attributes.put("XDD0026", getXDD0026());
		attributes.put("XDD0027", getXDD0027());
		attributes.put("XDD1027", getXDD1027());
		attributes.put("XDD0028", getXDD0028());
		attributes.put("XDD1028", getXDD1028());
		attributes.put("XDD1128", getXDD1128());
		attributes.put("XDD0029", getXDD0029());
		attributes.put("XDD1029", getXDD1029());
		attributes.put("XDD1129", getXDD1129());
		attributes.put("XDD0030", getXDD0030());
		attributes.put("XDD0031", getXDD0031());
		attributes.put("XDD0032", getXDD0032());
		attributes.put("XDD0033", getXDD0033());
		attributes.put("XDD0034", getXDD0034());
		attributes.put("XDD1034", getXDD1034());
		attributes.put("XDD0035", getXDD0035());
		attributes.put("XDD1035", getXDD1035());
		attributes.put("XDD0036", getXDD0036());
		attributes.put("XDD0037", getXDD0037());
		attributes.put("XDD0038", getXDD0038());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id = (Long)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		Long hoSoThuTucId = (Long)attributes.get("hoSoThuTucId");

		if (hoSoThuTucId != null) {
			setHoSoThuTucId(hoSoThuTucId);
		}

		Long certificateRecordId = (Long)attributes.get("certificateRecordId");

		if (certificateRecordId != null) {
			setCertificateRecordId(certificateRecordId);
		}

		Long vehicleGroupId = (Long)attributes.get("vehicleGroupId");

		if (vehicleGroupId != null) {
			setVehicleGroupId(vehicleGroupId);
		}

		Date SynchDate = (Date)attributes.get("SynchDate");

		if (SynchDate != null) {
			setSynchDate(SynchDate);
		}

		String XDD0008 = (String)attributes.get("XDD0008");

		if (XDD0008 != null) {
			setXDD0008(XDD0008);
		}

		String XDD0009 = (String)attributes.get("XDD0009");

		if (XDD0009 != null) {
			setXDD0009(XDD0009);
		}

		String XDD0010 = (String)attributes.get("XDD0010");

		if (XDD0010 != null) {
			setXDD0010(XDD0010);
		}

		String XDD0011 = (String)attributes.get("XDD0011");

		if (XDD0011 != null) {
			setXDD0011(XDD0011);
		}

		String XDD0012 = (String)attributes.get("XDD0012");

		if (XDD0012 != null) {
			setXDD0012(XDD0012);
		}

		String XDD0013 = (String)attributes.get("XDD0013");

		if (XDD0013 != null) {
			setXDD0013(XDD0013);
		}

		String XDD0014 = (String)attributes.get("XDD0014");

		if (XDD0014 != null) {
			setXDD0014(XDD0014);
		}

		String XDD0015 = (String)attributes.get("XDD0015");

		if (XDD0015 != null) {
			setXDD0015(XDD0015);
		}

		String XDD0016 = (String)attributes.get("XDD0016");

		if (XDD0016 != null) {
			setXDD0016(XDD0016);
		}

		String XDD0017 = (String)attributes.get("XDD0017");

		if (XDD0017 != null) {
			setXDD0017(XDD0017);
		}

		String XDD0018 = (String)attributes.get("XDD0018");

		if (XDD0018 != null) {
			setXDD0018(XDD0018);
		}

		String XDD0019 = (String)attributes.get("XDD0019");

		if (XDD0019 != null) {
			setXDD0019(XDD0019);
		}

		String XDD0020 = (String)attributes.get("XDD0020");

		if (XDD0020 != null) {
			setXDD0020(XDD0020);
		}

		String XDD0021 = (String)attributes.get("XDD0021");

		if (XDD0021 != null) {
			setXDD0021(XDD0021);
		}

		String XDD0022 = (String)attributes.get("XDD0022");

		if (XDD0022 != null) {
			setXDD0022(XDD0022);
		}

		String XDD0023 = (String)attributes.get("XDD0023");

		if (XDD0023 != null) {
			setXDD0023(XDD0023);
		}

		String XDD0024 = (String)attributes.get("XDD0024");

		if (XDD0024 != null) {
			setXDD0024(XDD0024);
		}

		String XDD0025 = (String)attributes.get("XDD0025");

		if (XDD0025 != null) {
			setXDD0025(XDD0025);
		}

		String XDD0026 = (String)attributes.get("XDD0026");

		if (XDD0026 != null) {
			setXDD0026(XDD0026);
		}

		String XDD0027 = (String)attributes.get("XDD0027");

		if (XDD0027 != null) {
			setXDD0027(XDD0027);
		}

		String XDD1027 = (String)attributes.get("XDD1027");

		if (XDD1027 != null) {
			setXDD1027(XDD1027);
		}

		String XDD0028 = (String)attributes.get("XDD0028");

		if (XDD0028 != null) {
			setXDD0028(XDD0028);
		}

		String XDD1028 = (String)attributes.get("XDD1028");

		if (XDD1028 != null) {
			setXDD1028(XDD1028);
		}

		String XDD1128 = (String)attributes.get("XDD1128");

		if (XDD1128 != null) {
			setXDD1128(XDD1128);
		}

		String XDD0029 = (String)attributes.get("XDD0029");

		if (XDD0029 != null) {
			setXDD0029(XDD0029);
		}

		String XDD1029 = (String)attributes.get("XDD1029");

		if (XDD1029 != null) {
			setXDD1029(XDD1029);
		}

		String XDD1129 = (String)attributes.get("XDD1129");

		if (XDD1129 != null) {
			setXDD1129(XDD1129);
		}

		String XDD0030 = (String)attributes.get("XDD0030");

		if (XDD0030 != null) {
			setXDD0030(XDD0030);
		}

		String XDD0031 = (String)attributes.get("XDD0031");

		if (XDD0031 != null) {
			setXDD0031(XDD0031);
		}

		String XDD0032 = (String)attributes.get("XDD0032");

		if (XDD0032 != null) {
			setXDD0032(XDD0032);
		}

		String XDD0033 = (String)attributes.get("XDD0033");

		if (XDD0033 != null) {
			setXDD0033(XDD0033);
		}

		String XDD0034 = (String)attributes.get("XDD0034");

		if (XDD0034 != null) {
			setXDD0034(XDD0034);
		}

		String XDD1034 = (String)attributes.get("XDD1034");

		if (XDD1034 != null) {
			setXDD1034(XDD1034);
		}

		String XDD0035 = (String)attributes.get("XDD0035");

		if (XDD0035 != null) {
			setXDD0035(XDD0035);
		}

		String XDD1035 = (String)attributes.get("XDD1035");

		if (XDD1035 != null) {
			setXDD1035(XDD1035);
		}

		String XDD0036 = (String)attributes.get("XDD0036");

		if (XDD0036 != null) {
			setXDD0036(XDD0036);
		}

		String XDD0037 = (String)attributes.get("XDD0037");

		if (XDD0037 != null) {
			setXDD0037(XDD0037);
		}

		String XDD0038 = (String)attributes.get("XDD0038");

		if (XDD0038 != null) {
			setXDD0038(XDD0038);
		}
	}

	@JSON
	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		_columnBitmask = -1L;

		_id = id;
	}

	@JSON
	@Override
	public long getHoSoThuTucId() {
		return _hoSoThuTucId;
	}

	@Override
	public void setHoSoThuTucId(long hoSoThuTucId) {
		_columnBitmask |= HOSOTHUTUCID_COLUMN_BITMASK;

		if (!_setOriginalHoSoThuTucId) {
			_setOriginalHoSoThuTucId = true;

			_originalHoSoThuTucId = _hoSoThuTucId;
		}

		_hoSoThuTucId = hoSoThuTucId;
	}

	public long getOriginalHoSoThuTucId() {
		return _originalHoSoThuTucId;
	}

	@JSON
	@Override
	public long getCertificateRecordId() {
		return _certificateRecordId;
	}

	@Override
	public void setCertificateRecordId(long certificateRecordId) {
		_columnBitmask |= CERTIFICATERECORDID_COLUMN_BITMASK;

		if (!_setOriginalCertificateRecordId) {
			_setOriginalCertificateRecordId = true;

			_originalCertificateRecordId = _certificateRecordId;
		}

		_certificateRecordId = certificateRecordId;
	}

	public long getOriginalCertificateRecordId() {
		return _originalCertificateRecordId;
	}

	@JSON
	@Override
	public long getVehicleGroupId() {
		return _vehicleGroupId;
	}

	@Override
	public void setVehicleGroupId(long vehicleGroupId) {
		_columnBitmask |= VEHICLEGROUPID_COLUMN_BITMASK;

		if (!_setOriginalVehicleGroupId) {
			_setOriginalVehicleGroupId = true;

			_originalVehicleGroupId = _vehicleGroupId;
		}

		_vehicleGroupId = vehicleGroupId;
	}

	public long getOriginalVehicleGroupId() {
		return _originalVehicleGroupId;
	}

	@JSON
	@Override
	public Date getSynchDate() {
		return _SynchDate;
	}

	@Override
	public void setSynchDate(Date SynchDate) {
		_SynchDate = SynchDate;
	}

	@JSON
	@Override
	public String getXDD0008() {
		if (_XDD0008 == null) {
			return StringPool.BLANK;
		}
		else {
			return _XDD0008;
		}
	}

	@Override
	public void setXDD0008(String XDD0008) {
		_XDD0008 = XDD0008;
	}

	@JSON
	@Override
	public String getXDD0009() {
		if (_XDD0009 == null) {
			return StringPool.BLANK;
		}
		else {
			return _XDD0009;
		}
	}

	@Override
	public void setXDD0009(String XDD0009) {
		_XDD0009 = XDD0009;
	}

	@JSON
	@Override
	public String getXDD0010() {
		if (_XDD0010 == null) {
			return StringPool.BLANK;
		}
		else {
			return _XDD0010;
		}
	}

	@Override
	public void setXDD0010(String XDD0010) {
		_XDD0010 = XDD0010;
	}

	@JSON
	@Override
	public String getXDD0011() {
		if (_XDD0011 == null) {
			return StringPool.BLANK;
		}
		else {
			return _XDD0011;
		}
	}

	@Override
	public void setXDD0011(String XDD0011) {
		_XDD0011 = XDD0011;
	}

	@JSON
	@Override
	public String getXDD0012() {
		if (_XDD0012 == null) {
			return StringPool.BLANK;
		}
		else {
			return _XDD0012;
		}
	}

	@Override
	public void setXDD0012(String XDD0012) {
		_XDD0012 = XDD0012;
	}

	@JSON
	@Override
	public String getXDD0013() {
		if (_XDD0013 == null) {
			return StringPool.BLANK;
		}
		else {
			return _XDD0013;
		}
	}

	@Override
	public void setXDD0013(String XDD0013) {
		_XDD0013 = XDD0013;
	}

	@JSON
	@Override
	public String getXDD0014() {
		if (_XDD0014 == null) {
			return StringPool.BLANK;
		}
		else {
			return _XDD0014;
		}
	}

	@Override
	public void setXDD0014(String XDD0014) {
		_XDD0014 = XDD0014;
	}

	@JSON
	@Override
	public String getXDD0015() {
		if (_XDD0015 == null) {
			return StringPool.BLANK;
		}
		else {
			return _XDD0015;
		}
	}

	@Override
	public void setXDD0015(String XDD0015) {
		_XDD0015 = XDD0015;
	}

	@JSON
	@Override
	public String getXDD0016() {
		if (_XDD0016 == null) {
			return StringPool.BLANK;
		}
		else {
			return _XDD0016;
		}
	}

	@Override
	public void setXDD0016(String XDD0016) {
		_XDD0016 = XDD0016;
	}

	@JSON
	@Override
	public String getXDD0017() {
		if (_XDD0017 == null) {
			return StringPool.BLANK;
		}
		else {
			return _XDD0017;
		}
	}

	@Override
	public void setXDD0017(String XDD0017) {
		_XDD0017 = XDD0017;
	}

	@JSON
	@Override
	public String getXDD0018() {
		if (_XDD0018 == null) {
			return StringPool.BLANK;
		}
		else {
			return _XDD0018;
		}
	}

	@Override
	public void setXDD0018(String XDD0018) {
		_XDD0018 = XDD0018;
	}

	@JSON
	@Override
	public String getXDD0019() {
		if (_XDD0019 == null) {
			return StringPool.BLANK;
		}
		else {
			return _XDD0019;
		}
	}

	@Override
	public void setXDD0019(String XDD0019) {
		_XDD0019 = XDD0019;
	}

	@JSON
	@Override
	public String getXDD0020() {
		if (_XDD0020 == null) {
			return StringPool.BLANK;
		}
		else {
			return _XDD0020;
		}
	}

	@Override
	public void setXDD0020(String XDD0020) {
		_XDD0020 = XDD0020;
	}

	@JSON
	@Override
	public String getXDD0021() {
		if (_XDD0021 == null) {
			return StringPool.BLANK;
		}
		else {
			return _XDD0021;
		}
	}

	@Override
	public void setXDD0021(String XDD0021) {
		_XDD0021 = XDD0021;
	}

	@JSON
	@Override
	public String getXDD0022() {
		if (_XDD0022 == null) {
			return StringPool.BLANK;
		}
		else {
			return _XDD0022;
		}
	}

	@Override
	public void setXDD0022(String XDD0022) {
		_XDD0022 = XDD0022;
	}

	@JSON
	@Override
	public String getXDD0023() {
		if (_XDD0023 == null) {
			return StringPool.BLANK;
		}
		else {
			return _XDD0023;
		}
	}

	@Override
	public void setXDD0023(String XDD0023) {
		_XDD0023 = XDD0023;
	}

	@JSON
	@Override
	public String getXDD0024() {
		if (_XDD0024 == null) {
			return StringPool.BLANK;
		}
		else {
			return _XDD0024;
		}
	}

	@Override
	public void setXDD0024(String XDD0024) {
		_XDD0024 = XDD0024;
	}

	@JSON
	@Override
	public String getXDD0025() {
		if (_XDD0025 == null) {
			return StringPool.BLANK;
		}
		else {
			return _XDD0025;
		}
	}

	@Override
	public void setXDD0025(String XDD0025) {
		_XDD0025 = XDD0025;
	}

	@JSON
	@Override
	public String getXDD0026() {
		if (_XDD0026 == null) {
			return StringPool.BLANK;
		}
		else {
			return _XDD0026;
		}
	}

	@Override
	public void setXDD0026(String XDD0026) {
		_XDD0026 = XDD0026;
	}

	@JSON
	@Override
	public String getXDD0027() {
		if (_XDD0027 == null) {
			return StringPool.BLANK;
		}
		else {
			return _XDD0027;
		}
	}

	@Override
	public void setXDD0027(String XDD0027) {
		_XDD0027 = XDD0027;
	}

	@JSON
	@Override
	public String getXDD1027() {
		if (_XDD1027 == null) {
			return StringPool.BLANK;
		}
		else {
			return _XDD1027;
		}
	}

	@Override
	public void setXDD1027(String XDD1027) {
		_XDD1027 = XDD1027;
	}

	@JSON
	@Override
	public String getXDD0028() {
		if (_XDD0028 == null) {
			return StringPool.BLANK;
		}
		else {
			return _XDD0028;
		}
	}

	@Override
	public void setXDD0028(String XDD0028) {
		_XDD0028 = XDD0028;
	}

	@JSON
	@Override
	public String getXDD1028() {
		if (_XDD1028 == null) {
			return StringPool.BLANK;
		}
		else {
			return _XDD1028;
		}
	}

	@Override
	public void setXDD1028(String XDD1028) {
		_XDD1028 = XDD1028;
	}

	@JSON
	@Override
	public String getXDD1128() {
		if (_XDD1128 == null) {
			return StringPool.BLANK;
		}
		else {
			return _XDD1128;
		}
	}

	@Override
	public void setXDD1128(String XDD1128) {
		_XDD1128 = XDD1128;
	}

	@JSON
	@Override
	public String getXDD0029() {
		if (_XDD0029 == null) {
			return StringPool.BLANK;
		}
		else {
			return _XDD0029;
		}
	}

	@Override
	public void setXDD0029(String XDD0029) {
		_XDD0029 = XDD0029;
	}

	@JSON
	@Override
	public String getXDD1029() {
		if (_XDD1029 == null) {
			return StringPool.BLANK;
		}
		else {
			return _XDD1029;
		}
	}

	@Override
	public void setXDD1029(String XDD1029) {
		_XDD1029 = XDD1029;
	}

	@JSON
	@Override
	public String getXDD1129() {
		if (_XDD1129 == null) {
			return StringPool.BLANK;
		}
		else {
			return _XDD1129;
		}
	}

	@Override
	public void setXDD1129(String XDD1129) {
		_XDD1129 = XDD1129;
	}

	@JSON
	@Override
	public String getXDD0030() {
		if (_XDD0030 == null) {
			return StringPool.BLANK;
		}
		else {
			return _XDD0030;
		}
	}

	@Override
	public void setXDD0030(String XDD0030) {
		_XDD0030 = XDD0030;
	}

	@JSON
	@Override
	public String getXDD0031() {
		if (_XDD0031 == null) {
			return StringPool.BLANK;
		}
		else {
			return _XDD0031;
		}
	}

	@Override
	public void setXDD0031(String XDD0031) {
		_XDD0031 = XDD0031;
	}

	@JSON
	@Override
	public String getXDD0032() {
		if (_XDD0032 == null) {
			return StringPool.BLANK;
		}
		else {
			return _XDD0032;
		}
	}

	@Override
	public void setXDD0032(String XDD0032) {
		_XDD0032 = XDD0032;
	}

	@JSON
	@Override
	public String getXDD0033() {
		if (_XDD0033 == null) {
			return StringPool.BLANK;
		}
		else {
			return _XDD0033;
		}
	}

	@Override
	public void setXDD0033(String XDD0033) {
		_XDD0033 = XDD0033;
	}

	@JSON
	@Override
	public String getXDD0034() {
		if (_XDD0034 == null) {
			return StringPool.BLANK;
		}
		else {
			return _XDD0034;
		}
	}

	@Override
	public void setXDD0034(String XDD0034) {
		_XDD0034 = XDD0034;
	}

	@JSON
	@Override
	public String getXDD1034() {
		if (_XDD1034 == null) {
			return StringPool.BLANK;
		}
		else {
			return _XDD1034;
		}
	}

	@Override
	public void setXDD1034(String XDD1034) {
		_XDD1034 = XDD1034;
	}

	@JSON
	@Override
	public String getXDD0035() {
		if (_XDD0035 == null) {
			return StringPool.BLANK;
		}
		else {
			return _XDD0035;
		}
	}

	@Override
	public void setXDD0035(String XDD0035) {
		_XDD0035 = XDD0035;
	}

	@JSON
	@Override
	public String getXDD1035() {
		if (_XDD1035 == null) {
			return StringPool.BLANK;
		}
		else {
			return _XDD1035;
		}
	}

	@Override
	public void setXDD1035(String XDD1035) {
		_XDD1035 = XDD1035;
	}

	@JSON
	@Override
	public String getXDD0036() {
		if (_XDD0036 == null) {
			return StringPool.BLANK;
		}
		else {
			return _XDD0036;
		}
	}

	@Override
	public void setXDD0036(String XDD0036) {
		_XDD0036 = XDD0036;
	}

	@JSON
	@Override
	public String getXDD0037() {
		if (_XDD0037 == null) {
			return StringPool.BLANK;
		}
		else {
			return _XDD0037;
		}
	}

	@Override
	public void setXDD0037(String XDD0037) {
		_XDD0037 = XDD0037;
	}

	@JSON
	@Override
	public String getXDD0038() {
		if (_XDD0038 == null) {
			return StringPool.BLANK;
		}
		else {
			return _XDD0038;
		}
	}

	@Override
	public void setXDD0038(String XDD0038) {
		_XDD0038 = XDD0038;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			THONGSOCHUNGCHIXEDAPDIEN.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public THONGSOCHUNGCHIXEDAPDIEN toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (THONGSOCHUNGCHIXEDAPDIEN)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		THONGSOCHUNGCHIXEDAPDIENImpl thongsochungchixedapdienImpl = new THONGSOCHUNGCHIXEDAPDIENImpl();

		thongsochungchixedapdienImpl.setId(getId());
		thongsochungchixedapdienImpl.setHoSoThuTucId(getHoSoThuTucId());
		thongsochungchixedapdienImpl.setCertificateRecordId(getCertificateRecordId());
		thongsochungchixedapdienImpl.setVehicleGroupId(getVehicleGroupId());
		thongsochungchixedapdienImpl.setSynchDate(getSynchDate());
		thongsochungchixedapdienImpl.setXDD0008(getXDD0008());
		thongsochungchixedapdienImpl.setXDD0009(getXDD0009());
		thongsochungchixedapdienImpl.setXDD0010(getXDD0010());
		thongsochungchixedapdienImpl.setXDD0011(getXDD0011());
		thongsochungchixedapdienImpl.setXDD0012(getXDD0012());
		thongsochungchixedapdienImpl.setXDD0013(getXDD0013());
		thongsochungchixedapdienImpl.setXDD0014(getXDD0014());
		thongsochungchixedapdienImpl.setXDD0015(getXDD0015());
		thongsochungchixedapdienImpl.setXDD0016(getXDD0016());
		thongsochungchixedapdienImpl.setXDD0017(getXDD0017());
		thongsochungchixedapdienImpl.setXDD0018(getXDD0018());
		thongsochungchixedapdienImpl.setXDD0019(getXDD0019());
		thongsochungchixedapdienImpl.setXDD0020(getXDD0020());
		thongsochungchixedapdienImpl.setXDD0021(getXDD0021());
		thongsochungchixedapdienImpl.setXDD0022(getXDD0022());
		thongsochungchixedapdienImpl.setXDD0023(getXDD0023());
		thongsochungchixedapdienImpl.setXDD0024(getXDD0024());
		thongsochungchixedapdienImpl.setXDD0025(getXDD0025());
		thongsochungchixedapdienImpl.setXDD0026(getXDD0026());
		thongsochungchixedapdienImpl.setXDD0027(getXDD0027());
		thongsochungchixedapdienImpl.setXDD1027(getXDD1027());
		thongsochungchixedapdienImpl.setXDD0028(getXDD0028());
		thongsochungchixedapdienImpl.setXDD1028(getXDD1028());
		thongsochungchixedapdienImpl.setXDD1128(getXDD1128());
		thongsochungchixedapdienImpl.setXDD0029(getXDD0029());
		thongsochungchixedapdienImpl.setXDD1029(getXDD1029());
		thongsochungchixedapdienImpl.setXDD1129(getXDD1129());
		thongsochungchixedapdienImpl.setXDD0030(getXDD0030());
		thongsochungchixedapdienImpl.setXDD0031(getXDD0031());
		thongsochungchixedapdienImpl.setXDD0032(getXDD0032());
		thongsochungchixedapdienImpl.setXDD0033(getXDD0033());
		thongsochungchixedapdienImpl.setXDD0034(getXDD0034());
		thongsochungchixedapdienImpl.setXDD1034(getXDD1034());
		thongsochungchixedapdienImpl.setXDD0035(getXDD0035());
		thongsochungchixedapdienImpl.setXDD1035(getXDD1035());
		thongsochungchixedapdienImpl.setXDD0036(getXDD0036());
		thongsochungchixedapdienImpl.setXDD0037(getXDD0037());
		thongsochungchixedapdienImpl.setXDD0038(getXDD0038());

		thongsochungchixedapdienImpl.resetOriginalValues();

		return thongsochungchixedapdienImpl;
	}

	@Override
	public int compareTo(THONGSOCHUNGCHIXEDAPDIEN thongsochungchixedapdien) {
		int value = 0;

		if (getId() < thongsochungchixedapdien.getId()) {
			value = -1;
		}
		else if (getId() > thongsochungchixedapdien.getId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof THONGSOCHUNGCHIXEDAPDIEN)) {
			return false;
		}

		THONGSOCHUNGCHIXEDAPDIEN thongsochungchixedapdien = (THONGSOCHUNGCHIXEDAPDIEN)obj;

		long primaryKey = thongsochungchixedapdien.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		THONGSOCHUNGCHIXEDAPDIENModelImpl thongsochungchixedapdienModelImpl = this;

		thongsochungchixedapdienModelImpl._originalHoSoThuTucId = thongsochungchixedapdienModelImpl._hoSoThuTucId;

		thongsochungchixedapdienModelImpl._setOriginalHoSoThuTucId = false;

		thongsochungchixedapdienModelImpl._originalCertificateRecordId = thongsochungchixedapdienModelImpl._certificateRecordId;

		thongsochungchixedapdienModelImpl._setOriginalCertificateRecordId = false;

		thongsochungchixedapdienModelImpl._originalVehicleGroupId = thongsochungchixedapdienModelImpl._vehicleGroupId;

		thongsochungchixedapdienModelImpl._setOriginalVehicleGroupId = false;

		thongsochungchixedapdienModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<THONGSOCHUNGCHIXEDAPDIEN> toCacheModel() {
		THONGSOCHUNGCHIXEDAPDIENCacheModel thongsochungchixedapdienCacheModel = new THONGSOCHUNGCHIXEDAPDIENCacheModel();

		thongsochungchixedapdienCacheModel.id = getId();

		thongsochungchixedapdienCacheModel.hoSoThuTucId = getHoSoThuTucId();

		thongsochungchixedapdienCacheModel.certificateRecordId = getCertificateRecordId();

		thongsochungchixedapdienCacheModel.vehicleGroupId = getVehicleGroupId();

		Date SynchDate = getSynchDate();

		if (SynchDate != null) {
			thongsochungchixedapdienCacheModel.SynchDate = SynchDate.getTime();
		}
		else {
			thongsochungchixedapdienCacheModel.SynchDate = Long.MIN_VALUE;
		}

		thongsochungchixedapdienCacheModel.XDD0008 = getXDD0008();

		String XDD0008 = thongsochungchixedapdienCacheModel.XDD0008;

		if ((XDD0008 != null) && (XDD0008.length() == 0)) {
			thongsochungchixedapdienCacheModel.XDD0008 = null;
		}

		thongsochungchixedapdienCacheModel.XDD0009 = getXDD0009();

		String XDD0009 = thongsochungchixedapdienCacheModel.XDD0009;

		if ((XDD0009 != null) && (XDD0009.length() == 0)) {
			thongsochungchixedapdienCacheModel.XDD0009 = null;
		}

		thongsochungchixedapdienCacheModel.XDD0010 = getXDD0010();

		String XDD0010 = thongsochungchixedapdienCacheModel.XDD0010;

		if ((XDD0010 != null) && (XDD0010.length() == 0)) {
			thongsochungchixedapdienCacheModel.XDD0010 = null;
		}

		thongsochungchixedapdienCacheModel.XDD0011 = getXDD0011();

		String XDD0011 = thongsochungchixedapdienCacheModel.XDD0011;

		if ((XDD0011 != null) && (XDD0011.length() == 0)) {
			thongsochungchixedapdienCacheModel.XDD0011 = null;
		}

		thongsochungchixedapdienCacheModel.XDD0012 = getXDD0012();

		String XDD0012 = thongsochungchixedapdienCacheModel.XDD0012;

		if ((XDD0012 != null) && (XDD0012.length() == 0)) {
			thongsochungchixedapdienCacheModel.XDD0012 = null;
		}

		thongsochungchixedapdienCacheModel.XDD0013 = getXDD0013();

		String XDD0013 = thongsochungchixedapdienCacheModel.XDD0013;

		if ((XDD0013 != null) && (XDD0013.length() == 0)) {
			thongsochungchixedapdienCacheModel.XDD0013 = null;
		}

		thongsochungchixedapdienCacheModel.XDD0014 = getXDD0014();

		String XDD0014 = thongsochungchixedapdienCacheModel.XDD0014;

		if ((XDD0014 != null) && (XDD0014.length() == 0)) {
			thongsochungchixedapdienCacheModel.XDD0014 = null;
		}

		thongsochungchixedapdienCacheModel.XDD0015 = getXDD0015();

		String XDD0015 = thongsochungchixedapdienCacheModel.XDD0015;

		if ((XDD0015 != null) && (XDD0015.length() == 0)) {
			thongsochungchixedapdienCacheModel.XDD0015 = null;
		}

		thongsochungchixedapdienCacheModel.XDD0016 = getXDD0016();

		String XDD0016 = thongsochungchixedapdienCacheModel.XDD0016;

		if ((XDD0016 != null) && (XDD0016.length() == 0)) {
			thongsochungchixedapdienCacheModel.XDD0016 = null;
		}

		thongsochungchixedapdienCacheModel.XDD0017 = getXDD0017();

		String XDD0017 = thongsochungchixedapdienCacheModel.XDD0017;

		if ((XDD0017 != null) && (XDD0017.length() == 0)) {
			thongsochungchixedapdienCacheModel.XDD0017 = null;
		}

		thongsochungchixedapdienCacheModel.XDD0018 = getXDD0018();

		String XDD0018 = thongsochungchixedapdienCacheModel.XDD0018;

		if ((XDD0018 != null) && (XDD0018.length() == 0)) {
			thongsochungchixedapdienCacheModel.XDD0018 = null;
		}

		thongsochungchixedapdienCacheModel.XDD0019 = getXDD0019();

		String XDD0019 = thongsochungchixedapdienCacheModel.XDD0019;

		if ((XDD0019 != null) && (XDD0019.length() == 0)) {
			thongsochungchixedapdienCacheModel.XDD0019 = null;
		}

		thongsochungchixedapdienCacheModel.XDD0020 = getXDD0020();

		String XDD0020 = thongsochungchixedapdienCacheModel.XDD0020;

		if ((XDD0020 != null) && (XDD0020.length() == 0)) {
			thongsochungchixedapdienCacheModel.XDD0020 = null;
		}

		thongsochungchixedapdienCacheModel.XDD0021 = getXDD0021();

		String XDD0021 = thongsochungchixedapdienCacheModel.XDD0021;

		if ((XDD0021 != null) && (XDD0021.length() == 0)) {
			thongsochungchixedapdienCacheModel.XDD0021 = null;
		}

		thongsochungchixedapdienCacheModel.XDD0022 = getXDD0022();

		String XDD0022 = thongsochungchixedapdienCacheModel.XDD0022;

		if ((XDD0022 != null) && (XDD0022.length() == 0)) {
			thongsochungchixedapdienCacheModel.XDD0022 = null;
		}

		thongsochungchixedapdienCacheModel.XDD0023 = getXDD0023();

		String XDD0023 = thongsochungchixedapdienCacheModel.XDD0023;

		if ((XDD0023 != null) && (XDD0023.length() == 0)) {
			thongsochungchixedapdienCacheModel.XDD0023 = null;
		}

		thongsochungchixedapdienCacheModel.XDD0024 = getXDD0024();

		String XDD0024 = thongsochungchixedapdienCacheModel.XDD0024;

		if ((XDD0024 != null) && (XDD0024.length() == 0)) {
			thongsochungchixedapdienCacheModel.XDD0024 = null;
		}

		thongsochungchixedapdienCacheModel.XDD0025 = getXDD0025();

		String XDD0025 = thongsochungchixedapdienCacheModel.XDD0025;

		if ((XDD0025 != null) && (XDD0025.length() == 0)) {
			thongsochungchixedapdienCacheModel.XDD0025 = null;
		}

		thongsochungchixedapdienCacheModel.XDD0026 = getXDD0026();

		String XDD0026 = thongsochungchixedapdienCacheModel.XDD0026;

		if ((XDD0026 != null) && (XDD0026.length() == 0)) {
			thongsochungchixedapdienCacheModel.XDD0026 = null;
		}

		thongsochungchixedapdienCacheModel.XDD0027 = getXDD0027();

		String XDD0027 = thongsochungchixedapdienCacheModel.XDD0027;

		if ((XDD0027 != null) && (XDD0027.length() == 0)) {
			thongsochungchixedapdienCacheModel.XDD0027 = null;
		}

		thongsochungchixedapdienCacheModel.XDD1027 = getXDD1027();

		String XDD1027 = thongsochungchixedapdienCacheModel.XDD1027;

		if ((XDD1027 != null) && (XDD1027.length() == 0)) {
			thongsochungchixedapdienCacheModel.XDD1027 = null;
		}

		thongsochungchixedapdienCacheModel.XDD0028 = getXDD0028();

		String XDD0028 = thongsochungchixedapdienCacheModel.XDD0028;

		if ((XDD0028 != null) && (XDD0028.length() == 0)) {
			thongsochungchixedapdienCacheModel.XDD0028 = null;
		}

		thongsochungchixedapdienCacheModel.XDD1028 = getXDD1028();

		String XDD1028 = thongsochungchixedapdienCacheModel.XDD1028;

		if ((XDD1028 != null) && (XDD1028.length() == 0)) {
			thongsochungchixedapdienCacheModel.XDD1028 = null;
		}

		thongsochungchixedapdienCacheModel.XDD1128 = getXDD1128();

		String XDD1128 = thongsochungchixedapdienCacheModel.XDD1128;

		if ((XDD1128 != null) && (XDD1128.length() == 0)) {
			thongsochungchixedapdienCacheModel.XDD1128 = null;
		}

		thongsochungchixedapdienCacheModel.XDD0029 = getXDD0029();

		String XDD0029 = thongsochungchixedapdienCacheModel.XDD0029;

		if ((XDD0029 != null) && (XDD0029.length() == 0)) {
			thongsochungchixedapdienCacheModel.XDD0029 = null;
		}

		thongsochungchixedapdienCacheModel.XDD1029 = getXDD1029();

		String XDD1029 = thongsochungchixedapdienCacheModel.XDD1029;

		if ((XDD1029 != null) && (XDD1029.length() == 0)) {
			thongsochungchixedapdienCacheModel.XDD1029 = null;
		}

		thongsochungchixedapdienCacheModel.XDD1129 = getXDD1129();

		String XDD1129 = thongsochungchixedapdienCacheModel.XDD1129;

		if ((XDD1129 != null) && (XDD1129.length() == 0)) {
			thongsochungchixedapdienCacheModel.XDD1129 = null;
		}

		thongsochungchixedapdienCacheModel.XDD0030 = getXDD0030();

		String XDD0030 = thongsochungchixedapdienCacheModel.XDD0030;

		if ((XDD0030 != null) && (XDD0030.length() == 0)) {
			thongsochungchixedapdienCacheModel.XDD0030 = null;
		}

		thongsochungchixedapdienCacheModel.XDD0031 = getXDD0031();

		String XDD0031 = thongsochungchixedapdienCacheModel.XDD0031;

		if ((XDD0031 != null) && (XDD0031.length() == 0)) {
			thongsochungchixedapdienCacheModel.XDD0031 = null;
		}

		thongsochungchixedapdienCacheModel.XDD0032 = getXDD0032();

		String XDD0032 = thongsochungchixedapdienCacheModel.XDD0032;

		if ((XDD0032 != null) && (XDD0032.length() == 0)) {
			thongsochungchixedapdienCacheModel.XDD0032 = null;
		}

		thongsochungchixedapdienCacheModel.XDD0033 = getXDD0033();

		String XDD0033 = thongsochungchixedapdienCacheModel.XDD0033;

		if ((XDD0033 != null) && (XDD0033.length() == 0)) {
			thongsochungchixedapdienCacheModel.XDD0033 = null;
		}

		thongsochungchixedapdienCacheModel.XDD0034 = getXDD0034();

		String XDD0034 = thongsochungchixedapdienCacheModel.XDD0034;

		if ((XDD0034 != null) && (XDD0034.length() == 0)) {
			thongsochungchixedapdienCacheModel.XDD0034 = null;
		}

		thongsochungchixedapdienCacheModel.XDD1034 = getXDD1034();

		String XDD1034 = thongsochungchixedapdienCacheModel.XDD1034;

		if ((XDD1034 != null) && (XDD1034.length() == 0)) {
			thongsochungchixedapdienCacheModel.XDD1034 = null;
		}

		thongsochungchixedapdienCacheModel.XDD0035 = getXDD0035();

		String XDD0035 = thongsochungchixedapdienCacheModel.XDD0035;

		if ((XDD0035 != null) && (XDD0035.length() == 0)) {
			thongsochungchixedapdienCacheModel.XDD0035 = null;
		}

		thongsochungchixedapdienCacheModel.XDD1035 = getXDD1035();

		String XDD1035 = thongsochungchixedapdienCacheModel.XDD1035;

		if ((XDD1035 != null) && (XDD1035.length() == 0)) {
			thongsochungchixedapdienCacheModel.XDD1035 = null;
		}

		thongsochungchixedapdienCacheModel.XDD0036 = getXDD0036();

		String XDD0036 = thongsochungchixedapdienCacheModel.XDD0036;

		if ((XDD0036 != null) && (XDD0036.length() == 0)) {
			thongsochungchixedapdienCacheModel.XDD0036 = null;
		}

		thongsochungchixedapdienCacheModel.XDD0037 = getXDD0037();

		String XDD0037 = thongsochungchixedapdienCacheModel.XDD0037;

		if ((XDD0037 != null) && (XDD0037.length() == 0)) {
			thongsochungchixedapdienCacheModel.XDD0037 = null;
		}

		thongsochungchixedapdienCacheModel.XDD0038 = getXDD0038();

		String XDD0038 = thongsochungchixedapdienCacheModel.XDD0038;

		if ((XDD0038 != null) && (XDD0038.length() == 0)) {
			thongsochungchixedapdienCacheModel.XDD0038 = null;
		}

		return thongsochungchixedapdienCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(87);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", hoSoThuTucId=");
		sb.append(getHoSoThuTucId());
		sb.append(", certificateRecordId=");
		sb.append(getCertificateRecordId());
		sb.append(", vehicleGroupId=");
		sb.append(getVehicleGroupId());
		sb.append(", SynchDate=");
		sb.append(getSynchDate());
		sb.append(", XDD0008=");
		sb.append(getXDD0008());
		sb.append(", XDD0009=");
		sb.append(getXDD0009());
		sb.append(", XDD0010=");
		sb.append(getXDD0010());
		sb.append(", XDD0011=");
		sb.append(getXDD0011());
		sb.append(", XDD0012=");
		sb.append(getXDD0012());
		sb.append(", XDD0013=");
		sb.append(getXDD0013());
		sb.append(", XDD0014=");
		sb.append(getXDD0014());
		sb.append(", XDD0015=");
		sb.append(getXDD0015());
		sb.append(", XDD0016=");
		sb.append(getXDD0016());
		sb.append(", XDD0017=");
		sb.append(getXDD0017());
		sb.append(", XDD0018=");
		sb.append(getXDD0018());
		sb.append(", XDD0019=");
		sb.append(getXDD0019());
		sb.append(", XDD0020=");
		sb.append(getXDD0020());
		sb.append(", XDD0021=");
		sb.append(getXDD0021());
		sb.append(", XDD0022=");
		sb.append(getXDD0022());
		sb.append(", XDD0023=");
		sb.append(getXDD0023());
		sb.append(", XDD0024=");
		sb.append(getXDD0024());
		sb.append(", XDD0025=");
		sb.append(getXDD0025());
		sb.append(", XDD0026=");
		sb.append(getXDD0026());
		sb.append(", XDD0027=");
		sb.append(getXDD0027());
		sb.append(", XDD1027=");
		sb.append(getXDD1027());
		sb.append(", XDD0028=");
		sb.append(getXDD0028());
		sb.append(", XDD1028=");
		sb.append(getXDD1028());
		sb.append(", XDD1128=");
		sb.append(getXDD1128());
		sb.append(", XDD0029=");
		sb.append(getXDD0029());
		sb.append(", XDD1029=");
		sb.append(getXDD1029());
		sb.append(", XDD1129=");
		sb.append(getXDD1129());
		sb.append(", XDD0030=");
		sb.append(getXDD0030());
		sb.append(", XDD0031=");
		sb.append(getXDD0031());
		sb.append(", XDD0032=");
		sb.append(getXDD0032());
		sb.append(", XDD0033=");
		sb.append(getXDD0033());
		sb.append(", XDD0034=");
		sb.append(getXDD0034());
		sb.append(", XDD1034=");
		sb.append(getXDD1034());
		sb.append(", XDD0035=");
		sb.append(getXDD0035());
		sb.append(", XDD1035=");
		sb.append(getXDD1035());
		sb.append(", XDD0036=");
		sb.append(getXDD0036());
		sb.append(", XDD0037=");
		sb.append(getXDD0037());
		sb.append(", XDD0038=");
		sb.append(getXDD0038());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(133);

		sb.append("<model><model-name>");
		sb.append("vn.dtt.gt.dk.dao.nghiepvu.model.THONGSOCHUNGCHIXEDAPDIEN");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>hoSoThuTucId</column-name><column-value><![CDATA[");
		sb.append(getHoSoThuTucId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>certificateRecordId</column-name><column-value><![CDATA[");
		sb.append(getCertificateRecordId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>vehicleGroupId</column-name><column-value><![CDATA[");
		sb.append(getVehicleGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>SynchDate</column-name><column-value><![CDATA[");
		sb.append(getSynchDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>XDD0008</column-name><column-value><![CDATA[");
		sb.append(getXDD0008());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>XDD0009</column-name><column-value><![CDATA[");
		sb.append(getXDD0009());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>XDD0010</column-name><column-value><![CDATA[");
		sb.append(getXDD0010());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>XDD0011</column-name><column-value><![CDATA[");
		sb.append(getXDD0011());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>XDD0012</column-name><column-value><![CDATA[");
		sb.append(getXDD0012());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>XDD0013</column-name><column-value><![CDATA[");
		sb.append(getXDD0013());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>XDD0014</column-name><column-value><![CDATA[");
		sb.append(getXDD0014());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>XDD0015</column-name><column-value><![CDATA[");
		sb.append(getXDD0015());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>XDD0016</column-name><column-value><![CDATA[");
		sb.append(getXDD0016());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>XDD0017</column-name><column-value><![CDATA[");
		sb.append(getXDD0017());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>XDD0018</column-name><column-value><![CDATA[");
		sb.append(getXDD0018());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>XDD0019</column-name><column-value><![CDATA[");
		sb.append(getXDD0019());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>XDD0020</column-name><column-value><![CDATA[");
		sb.append(getXDD0020());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>XDD0021</column-name><column-value><![CDATA[");
		sb.append(getXDD0021());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>XDD0022</column-name><column-value><![CDATA[");
		sb.append(getXDD0022());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>XDD0023</column-name><column-value><![CDATA[");
		sb.append(getXDD0023());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>XDD0024</column-name><column-value><![CDATA[");
		sb.append(getXDD0024());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>XDD0025</column-name><column-value><![CDATA[");
		sb.append(getXDD0025());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>XDD0026</column-name><column-value><![CDATA[");
		sb.append(getXDD0026());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>XDD0027</column-name><column-value><![CDATA[");
		sb.append(getXDD0027());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>XDD1027</column-name><column-value><![CDATA[");
		sb.append(getXDD1027());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>XDD0028</column-name><column-value><![CDATA[");
		sb.append(getXDD0028());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>XDD1028</column-name><column-value><![CDATA[");
		sb.append(getXDD1028());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>XDD1128</column-name><column-value><![CDATA[");
		sb.append(getXDD1128());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>XDD0029</column-name><column-value><![CDATA[");
		sb.append(getXDD0029());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>XDD1029</column-name><column-value><![CDATA[");
		sb.append(getXDD1029());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>XDD1129</column-name><column-value><![CDATA[");
		sb.append(getXDD1129());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>XDD0030</column-name><column-value><![CDATA[");
		sb.append(getXDD0030());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>XDD0031</column-name><column-value><![CDATA[");
		sb.append(getXDD0031());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>XDD0032</column-name><column-value><![CDATA[");
		sb.append(getXDD0032());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>XDD0033</column-name><column-value><![CDATA[");
		sb.append(getXDD0033());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>XDD0034</column-name><column-value><![CDATA[");
		sb.append(getXDD0034());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>XDD1034</column-name><column-value><![CDATA[");
		sb.append(getXDD1034());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>XDD0035</column-name><column-value><![CDATA[");
		sb.append(getXDD0035());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>XDD1035</column-name><column-value><![CDATA[");
		sb.append(getXDD1035());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>XDD0036</column-name><column-value><![CDATA[");
		sb.append(getXDD0036());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>XDD0037</column-name><column-value><![CDATA[");
		sb.append(getXDD0037());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>XDD0038</column-name><column-value><![CDATA[");
		sb.append(getXDD0038());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = THONGSOCHUNGCHIXEDAPDIEN.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			THONGSOCHUNGCHIXEDAPDIEN.class
		};
	private long _id;
	private long _hoSoThuTucId;
	private long _originalHoSoThuTucId;
	private boolean _setOriginalHoSoThuTucId;
	private long _certificateRecordId;
	private long _originalCertificateRecordId;
	private boolean _setOriginalCertificateRecordId;
	private long _vehicleGroupId;
	private long _originalVehicleGroupId;
	private boolean _setOriginalVehicleGroupId;
	private Date _SynchDate;
	private String _XDD0008;
	private String _XDD0009;
	private String _XDD0010;
	private String _XDD0011;
	private String _XDD0012;
	private String _XDD0013;
	private String _XDD0014;
	private String _XDD0015;
	private String _XDD0016;
	private String _XDD0017;
	private String _XDD0018;
	private String _XDD0019;
	private String _XDD0020;
	private String _XDD0021;
	private String _XDD0022;
	private String _XDD0023;
	private String _XDD0024;
	private String _XDD0025;
	private String _XDD0026;
	private String _XDD0027;
	private String _XDD1027;
	private String _XDD0028;
	private String _XDD1028;
	private String _XDD1128;
	private String _XDD0029;
	private String _XDD1029;
	private String _XDD1129;
	private String _XDD0030;
	private String _XDD0031;
	private String _XDD0032;
	private String _XDD0033;
	private String _XDD0034;
	private String _XDD1034;
	private String _XDD0035;
	private String _XDD1035;
	private String _XDD0036;
	private String _XDD0037;
	private String _XDD0038;
	private long _columnBitmask;
	private THONGSOCHUNGCHIXEDAPDIEN _escapedModel;
}