/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.gt.dk.dao.common.service.base;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.model.PersistedModel;
import com.liferay.portal.service.BaseLocalServiceImpl;
import com.liferay.portal.service.PersistedModelLocalServiceRegistryUtil;
import com.liferay.portal.service.persistence.UserPersistence;

import vn.dtt.gt.dk.dao.common.model.TthcThuTucHanhChinh;
import vn.dtt.gt.dk.dao.common.service.TthcThuTucHanhChinhLocalService;
import vn.dtt.gt.dk.dao.common.service.persistence.DmDataGroupPersistence;
import vn.dtt.gt.dk.dao.common.service.persistence.DmDataItemFinder;
import vn.dtt.gt.dk.dao.common.service.persistence.DmDataItemPersistence;
import vn.dtt.gt.dk.dao.common.service.persistence.TthcBieuMauHoSoPersistence;
import vn.dtt.gt.dk.dao.common.service.persistence.TthcHoSoThuTucPersistence;
import vn.dtt.gt.dk.dao.common.service.persistence.TthcKeHoachChuyenDichFinder;
import vn.dtt.gt.dk.dao.common.service.persistence.TthcKeHoachChuyenDichPersistence;
import vn.dtt.gt.dk.dao.common.service.persistence.TthcNoidungHoSoFinder;
import vn.dtt.gt.dk.dao.common.service.persistence.TthcNoidungHoSoPersistence;
import vn.dtt.gt.dk.dao.common.service.persistence.TthcNoidungHoSoReadPersistence;
import vn.dtt.gt.dk.dao.common.service.persistence.TthcPhanNhomHoSoFinder;
import vn.dtt.gt.dk.dao.common.service.persistence.TthcPhanNhomHoSoPersistence;
import vn.dtt.gt.dk.dao.common.service.persistence.TthcPhanNhomHoSoVaiTroFinder;
import vn.dtt.gt.dk.dao.common.service.persistence.TthcPhanNhomHoSoVaiTroPersistence;
import vn.dtt.gt.dk.dao.common.service.persistence.TthcThanhPhanHoSoFinder;
import vn.dtt.gt.dk.dao.common.service.persistence.TthcThanhPhanHoSoPersistence;
import vn.dtt.gt.dk.dao.common.service.persistence.TthcThuTucHanhChinhPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the tthc thu tuc hanh chinh local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link vn.dtt.gt.dk.dao.common.service.impl.TthcThuTucHanhChinhLocalServiceImpl}.
 * </p>
 *
 * @author huymq
 * @see vn.dtt.gt.dk.dao.common.service.impl.TthcThuTucHanhChinhLocalServiceImpl
 * @see vn.dtt.gt.dk.dao.common.service.TthcThuTucHanhChinhLocalServiceUtil
 * @generated
 */
public abstract class TthcThuTucHanhChinhLocalServiceBaseImpl
	extends BaseLocalServiceImpl implements TthcThuTucHanhChinhLocalService,
		IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link vn.dtt.gt.dk.dao.common.service.TthcThuTucHanhChinhLocalServiceUtil} to access the tthc thu tuc hanh chinh local service.
	 */

	/**
	 * Adds the tthc thu tuc hanh chinh to the database. Also notifies the appropriate model listeners.
	 *
	 * @param tthcThuTucHanhChinh the tthc thu tuc hanh chinh
	 * @return the tthc thu tuc hanh chinh that was added
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public TthcThuTucHanhChinh addTthcThuTucHanhChinh(
		TthcThuTucHanhChinh tthcThuTucHanhChinh) throws SystemException {
		tthcThuTucHanhChinh.setNew(true);

		return tthcThuTucHanhChinhPersistence.update(tthcThuTucHanhChinh);
	}

	/**
	 * Creates a new tthc thu tuc hanh chinh with the primary key. Does not add the tthc thu tuc hanh chinh to the database.
	 *
	 * @param Id the primary key for the new tthc thu tuc hanh chinh
	 * @return the new tthc thu tuc hanh chinh
	 */
	@Override
	public TthcThuTucHanhChinh createTthcThuTucHanhChinh(long Id) {
		return tthcThuTucHanhChinhPersistence.create(Id);
	}

	/**
	 * Deletes the tthc thu tuc hanh chinh with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param Id the primary key of the tthc thu tuc hanh chinh
	 * @return the tthc thu tuc hanh chinh that was removed
	 * @throws PortalException if a tthc thu tuc hanh chinh with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public TthcThuTucHanhChinh deleteTthcThuTucHanhChinh(long Id)
		throws PortalException, SystemException {
		return tthcThuTucHanhChinhPersistence.remove(Id);
	}

	/**
	 * Deletes the tthc thu tuc hanh chinh from the database. Also notifies the appropriate model listeners.
	 *
	 * @param tthcThuTucHanhChinh the tthc thu tuc hanh chinh
	 * @return the tthc thu tuc hanh chinh that was removed
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public TthcThuTucHanhChinh deleteTthcThuTucHanhChinh(
		TthcThuTucHanhChinh tthcThuTucHanhChinh) throws SystemException {
		return tthcThuTucHanhChinhPersistence.remove(tthcThuTucHanhChinh);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(TthcThuTucHanhChinh.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery)
		throws SystemException {
		return tthcThuTucHanhChinhPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link vn.dtt.gt.dk.dao.common.model.impl.TthcThuTucHanhChinhModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
		throws SystemException {
		return tthcThuTucHanhChinhPersistence.findWithDynamicQuery(dynamicQuery,
			start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link vn.dtt.gt.dk.dao.common.model.impl.TthcThuTucHanhChinhModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator orderByComparator) throws SystemException {
		return tthcThuTucHanhChinhPersistence.findWithDynamicQuery(dynamicQuery,
			start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery)
		throws SystemException {
		return tthcThuTucHanhChinhPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery,
		Projection projection) throws SystemException {
		return tthcThuTucHanhChinhPersistence.countWithDynamicQuery(dynamicQuery,
			projection);
	}

	@Override
	public TthcThuTucHanhChinh fetchTthcThuTucHanhChinh(long Id)
		throws SystemException {
		return tthcThuTucHanhChinhPersistence.fetchByPrimaryKey(Id);
	}

	/**
	 * Returns the tthc thu tuc hanh chinh with the primary key.
	 *
	 * @param Id the primary key of the tthc thu tuc hanh chinh
	 * @return the tthc thu tuc hanh chinh
	 * @throws PortalException if a tthc thu tuc hanh chinh with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public TthcThuTucHanhChinh getTthcThuTucHanhChinh(long Id)
		throws PortalException, SystemException {
		return tthcThuTucHanhChinhPersistence.findByPrimaryKey(Id);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException, SystemException {
		return tthcThuTucHanhChinhPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the tthc thu tuc hanh chinhs.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link vn.dtt.gt.dk.dao.common.model.impl.TthcThuTucHanhChinhModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param start the lower bound of the range of tthc thu tuc hanh chinhs
	 * @param end the upper bound of the range of tthc thu tuc hanh chinhs (not inclusive)
	 * @return the range of tthc thu tuc hanh chinhs
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public List<TthcThuTucHanhChinh> getTthcThuTucHanhChinhs(int start, int end)
		throws SystemException {
		return tthcThuTucHanhChinhPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of tthc thu tuc hanh chinhs.
	 *
	 * @return the number of tthc thu tuc hanh chinhs
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public int getTthcThuTucHanhChinhsCount() throws SystemException {
		return tthcThuTucHanhChinhPersistence.countAll();
	}

	/**
	 * Updates the tthc thu tuc hanh chinh in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param tthcThuTucHanhChinh the tthc thu tuc hanh chinh
	 * @return the tthc thu tuc hanh chinh that was updated
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public TthcThuTucHanhChinh updateTthcThuTucHanhChinh(
		TthcThuTucHanhChinh tthcThuTucHanhChinh) throws SystemException {
		return tthcThuTucHanhChinhPersistence.update(tthcThuTucHanhChinh);
	}

	/**
	 * Returns the dm data group remote service.
	 *
	 * @return the dm data group remote service
	 */
	public vn.dtt.gt.dk.dao.common.service.DmDataGroupService getDmDataGroupService() {
		return dmDataGroupService;
	}

	/**
	 * Sets the dm data group remote service.
	 *
	 * @param dmDataGroupService the dm data group remote service
	 */
	public void setDmDataGroupService(
		vn.dtt.gt.dk.dao.common.service.DmDataGroupService dmDataGroupService) {
		this.dmDataGroupService = dmDataGroupService;
	}

	/**
	 * Returns the dm data group persistence.
	 *
	 * @return the dm data group persistence
	 */
	public DmDataGroupPersistence getDmDataGroupPersistence() {
		return dmDataGroupPersistence;
	}

	/**
	 * Sets the dm data group persistence.
	 *
	 * @param dmDataGroupPersistence the dm data group persistence
	 */
	public void setDmDataGroupPersistence(
		DmDataGroupPersistence dmDataGroupPersistence) {
		this.dmDataGroupPersistence = dmDataGroupPersistence;
	}

	/**
	 * Returns the dm data item local service.
	 *
	 * @return the dm data item local service
	 */
	public vn.dtt.gt.dk.dao.common.service.DmDataItemLocalService getDmDataItemLocalService() {
		return dmDataItemLocalService;
	}

	/**
	 * Sets the dm data item local service.
	 *
	 * @param dmDataItemLocalService the dm data item local service
	 */
	public void setDmDataItemLocalService(
		vn.dtt.gt.dk.dao.common.service.DmDataItemLocalService dmDataItemLocalService) {
		this.dmDataItemLocalService = dmDataItemLocalService;
	}

	/**
	 * Returns the dm data item remote service.
	 *
	 * @return the dm data item remote service
	 */
	public vn.dtt.gt.dk.dao.common.service.DmDataItemService getDmDataItemService() {
		return dmDataItemService;
	}

	/**
	 * Sets the dm data item remote service.
	 *
	 * @param dmDataItemService the dm data item remote service
	 */
	public void setDmDataItemService(
		vn.dtt.gt.dk.dao.common.service.DmDataItemService dmDataItemService) {
		this.dmDataItemService = dmDataItemService;
	}

	/**
	 * Returns the dm data item persistence.
	 *
	 * @return the dm data item persistence
	 */
	public DmDataItemPersistence getDmDataItemPersistence() {
		return dmDataItemPersistence;
	}

	/**
	 * Sets the dm data item persistence.
	 *
	 * @param dmDataItemPersistence the dm data item persistence
	 */
	public void setDmDataItemPersistence(
		DmDataItemPersistence dmDataItemPersistence) {
		this.dmDataItemPersistence = dmDataItemPersistence;
	}

	/**
	 * Returns the dm data item finder.
	 *
	 * @return the dm data item finder
	 */
	public DmDataItemFinder getDmDataItemFinder() {
		return dmDataItemFinder;
	}

	/**
	 * Sets the dm data item finder.
	 *
	 * @param dmDataItemFinder the dm data item finder
	 */
	public void setDmDataItemFinder(DmDataItemFinder dmDataItemFinder) {
		this.dmDataItemFinder = dmDataItemFinder;
	}

	/**
	 * Returns the tthc bieu mau ho so local service.
	 *
	 * @return the tthc bieu mau ho so local service
	 */
	public vn.dtt.gt.dk.dao.common.service.TthcBieuMauHoSoLocalService getTthcBieuMauHoSoLocalService() {
		return tthcBieuMauHoSoLocalService;
	}

	/**
	 * Sets the tthc bieu mau ho so local service.
	 *
	 * @param tthcBieuMauHoSoLocalService the tthc bieu mau ho so local service
	 */
	public void setTthcBieuMauHoSoLocalService(
		vn.dtt.gt.dk.dao.common.service.TthcBieuMauHoSoLocalService tthcBieuMauHoSoLocalService) {
		this.tthcBieuMauHoSoLocalService = tthcBieuMauHoSoLocalService;
	}

	/**
	 * Returns the tthc bieu mau ho so remote service.
	 *
	 * @return the tthc bieu mau ho so remote service
	 */
	public vn.dtt.gt.dk.dao.common.service.TthcBieuMauHoSoService getTthcBieuMauHoSoService() {
		return tthcBieuMauHoSoService;
	}

	/**
	 * Sets the tthc bieu mau ho so remote service.
	 *
	 * @param tthcBieuMauHoSoService the tthc bieu mau ho so remote service
	 */
	public void setTthcBieuMauHoSoService(
		vn.dtt.gt.dk.dao.common.service.TthcBieuMauHoSoService tthcBieuMauHoSoService) {
		this.tthcBieuMauHoSoService = tthcBieuMauHoSoService;
	}

	/**
	 * Returns the tthc bieu mau ho so persistence.
	 *
	 * @return the tthc bieu mau ho so persistence
	 */
	public TthcBieuMauHoSoPersistence getTthcBieuMauHoSoPersistence() {
		return tthcBieuMauHoSoPersistence;
	}

	/**
	 * Sets the tthc bieu mau ho so persistence.
	 *
	 * @param tthcBieuMauHoSoPersistence the tthc bieu mau ho so persistence
	 */
	public void setTthcBieuMauHoSoPersistence(
		TthcBieuMauHoSoPersistence tthcBieuMauHoSoPersistence) {
		this.tthcBieuMauHoSoPersistence = tthcBieuMauHoSoPersistence;
	}

	/**
	 * Returns the tthc ho so thu tuc local service.
	 *
	 * @return the tthc ho so thu tuc local service
	 */
	public vn.dtt.gt.dk.dao.common.service.TthcHoSoThuTucLocalService getTthcHoSoThuTucLocalService() {
		return tthcHoSoThuTucLocalService;
	}

	/**
	 * Sets the tthc ho so thu tuc local service.
	 *
	 * @param tthcHoSoThuTucLocalService the tthc ho so thu tuc local service
	 */
	public void setTthcHoSoThuTucLocalService(
		vn.dtt.gt.dk.dao.common.service.TthcHoSoThuTucLocalService tthcHoSoThuTucLocalService) {
		this.tthcHoSoThuTucLocalService = tthcHoSoThuTucLocalService;
	}

	/**
	 * Returns the tthc ho so thu tuc remote service.
	 *
	 * @return the tthc ho so thu tuc remote service
	 */
	public vn.dtt.gt.dk.dao.common.service.TthcHoSoThuTucService getTthcHoSoThuTucService() {
		return tthcHoSoThuTucService;
	}

	/**
	 * Sets the tthc ho so thu tuc remote service.
	 *
	 * @param tthcHoSoThuTucService the tthc ho so thu tuc remote service
	 */
	public void setTthcHoSoThuTucService(
		vn.dtt.gt.dk.dao.common.service.TthcHoSoThuTucService tthcHoSoThuTucService) {
		this.tthcHoSoThuTucService = tthcHoSoThuTucService;
	}

	/**
	 * Returns the tthc ho so thu tuc persistence.
	 *
	 * @return the tthc ho so thu tuc persistence
	 */
	public TthcHoSoThuTucPersistence getTthcHoSoThuTucPersistence() {
		return tthcHoSoThuTucPersistence;
	}

	/**
	 * Sets the tthc ho so thu tuc persistence.
	 *
	 * @param tthcHoSoThuTucPersistence the tthc ho so thu tuc persistence
	 */
	public void setTthcHoSoThuTucPersistence(
		TthcHoSoThuTucPersistence tthcHoSoThuTucPersistence) {
		this.tthcHoSoThuTucPersistence = tthcHoSoThuTucPersistence;
	}

	/**
	 * Returns the tthc ke hoach chuyen dich local service.
	 *
	 * @return the tthc ke hoach chuyen dich local service
	 */
	public vn.dtt.gt.dk.dao.common.service.TthcKeHoachChuyenDichLocalService getTthcKeHoachChuyenDichLocalService() {
		return tthcKeHoachChuyenDichLocalService;
	}

	/**
	 * Sets the tthc ke hoach chuyen dich local service.
	 *
	 * @param tthcKeHoachChuyenDichLocalService the tthc ke hoach chuyen dich local service
	 */
	public void setTthcKeHoachChuyenDichLocalService(
		vn.dtt.gt.dk.dao.common.service.TthcKeHoachChuyenDichLocalService tthcKeHoachChuyenDichLocalService) {
		this.tthcKeHoachChuyenDichLocalService = tthcKeHoachChuyenDichLocalService;
	}

	/**
	 * Returns the tthc ke hoach chuyen dich persistence.
	 *
	 * @return the tthc ke hoach chuyen dich persistence
	 */
	public TthcKeHoachChuyenDichPersistence getTthcKeHoachChuyenDichPersistence() {
		return tthcKeHoachChuyenDichPersistence;
	}

	/**
	 * Sets the tthc ke hoach chuyen dich persistence.
	 *
	 * @param tthcKeHoachChuyenDichPersistence the tthc ke hoach chuyen dich persistence
	 */
	public void setTthcKeHoachChuyenDichPersistence(
		TthcKeHoachChuyenDichPersistence tthcKeHoachChuyenDichPersistence) {
		this.tthcKeHoachChuyenDichPersistence = tthcKeHoachChuyenDichPersistence;
	}

	/**
	 * Returns the tthc ke hoach chuyen dich finder.
	 *
	 * @return the tthc ke hoach chuyen dich finder
	 */
	public TthcKeHoachChuyenDichFinder getTthcKeHoachChuyenDichFinder() {
		return tthcKeHoachChuyenDichFinder;
	}

	/**
	 * Sets the tthc ke hoach chuyen dich finder.
	 *
	 * @param tthcKeHoachChuyenDichFinder the tthc ke hoach chuyen dich finder
	 */
	public void setTthcKeHoachChuyenDichFinder(
		TthcKeHoachChuyenDichFinder tthcKeHoachChuyenDichFinder) {
		this.tthcKeHoachChuyenDichFinder = tthcKeHoachChuyenDichFinder;
	}

	/**
	 * Returns the tthc noidung ho so local service.
	 *
	 * @return the tthc noidung ho so local service
	 */
	public vn.dtt.gt.dk.dao.common.service.TthcNoidungHoSoLocalService getTthcNoidungHoSoLocalService() {
		return tthcNoidungHoSoLocalService;
	}

	/**
	 * Sets the tthc noidung ho so local service.
	 *
	 * @param tthcNoidungHoSoLocalService the tthc noidung ho so local service
	 */
	public void setTthcNoidungHoSoLocalService(
		vn.dtt.gt.dk.dao.common.service.TthcNoidungHoSoLocalService tthcNoidungHoSoLocalService) {
		this.tthcNoidungHoSoLocalService = tthcNoidungHoSoLocalService;
	}

	/**
	 * Returns the tthc noidung ho so remote service.
	 *
	 * @return the tthc noidung ho so remote service
	 */
	public vn.dtt.gt.dk.dao.common.service.TthcNoidungHoSoService getTthcNoidungHoSoService() {
		return tthcNoidungHoSoService;
	}

	/**
	 * Sets the tthc noidung ho so remote service.
	 *
	 * @param tthcNoidungHoSoService the tthc noidung ho so remote service
	 */
	public void setTthcNoidungHoSoService(
		vn.dtt.gt.dk.dao.common.service.TthcNoidungHoSoService tthcNoidungHoSoService) {
		this.tthcNoidungHoSoService = tthcNoidungHoSoService;
	}

	/**
	 * Returns the tthc noidung ho so persistence.
	 *
	 * @return the tthc noidung ho so persistence
	 */
	public TthcNoidungHoSoPersistence getTthcNoidungHoSoPersistence() {
		return tthcNoidungHoSoPersistence;
	}

	/**
	 * Sets the tthc noidung ho so persistence.
	 *
	 * @param tthcNoidungHoSoPersistence the tthc noidung ho so persistence
	 */
	public void setTthcNoidungHoSoPersistence(
		TthcNoidungHoSoPersistence tthcNoidungHoSoPersistence) {
		this.tthcNoidungHoSoPersistence = tthcNoidungHoSoPersistence;
	}

	/**
	 * Returns the tthc noidung ho so finder.
	 *
	 * @return the tthc noidung ho so finder
	 */
	public TthcNoidungHoSoFinder getTthcNoidungHoSoFinder() {
		return tthcNoidungHoSoFinder;
	}

	/**
	 * Sets the tthc noidung ho so finder.
	 *
	 * @param tthcNoidungHoSoFinder the tthc noidung ho so finder
	 */
	public void setTthcNoidungHoSoFinder(
		TthcNoidungHoSoFinder tthcNoidungHoSoFinder) {
		this.tthcNoidungHoSoFinder = tthcNoidungHoSoFinder;
	}

	/**
	 * Returns the tthc noidung ho so read local service.
	 *
	 * @return the tthc noidung ho so read local service
	 */
	public vn.dtt.gt.dk.dao.common.service.TthcNoidungHoSoReadLocalService getTthcNoidungHoSoReadLocalService() {
		return tthcNoidungHoSoReadLocalService;
	}

	/**
	 * Sets the tthc noidung ho so read local service.
	 *
	 * @param tthcNoidungHoSoReadLocalService the tthc noidung ho so read local service
	 */
	public void setTthcNoidungHoSoReadLocalService(
		vn.dtt.gt.dk.dao.common.service.TthcNoidungHoSoReadLocalService tthcNoidungHoSoReadLocalService) {
		this.tthcNoidungHoSoReadLocalService = tthcNoidungHoSoReadLocalService;
	}

	/**
	 * Returns the tthc noidung ho so read remote service.
	 *
	 * @return the tthc noidung ho so read remote service
	 */
	public vn.dtt.gt.dk.dao.common.service.TthcNoidungHoSoReadService getTthcNoidungHoSoReadService() {
		return tthcNoidungHoSoReadService;
	}

	/**
	 * Sets the tthc noidung ho so read remote service.
	 *
	 * @param tthcNoidungHoSoReadService the tthc noidung ho so read remote service
	 */
	public void setTthcNoidungHoSoReadService(
		vn.dtt.gt.dk.dao.common.service.TthcNoidungHoSoReadService tthcNoidungHoSoReadService) {
		this.tthcNoidungHoSoReadService = tthcNoidungHoSoReadService;
	}

	/**
	 * Returns the tthc noidung ho so read persistence.
	 *
	 * @return the tthc noidung ho so read persistence
	 */
	public TthcNoidungHoSoReadPersistence getTthcNoidungHoSoReadPersistence() {
		return tthcNoidungHoSoReadPersistence;
	}

	/**
	 * Sets the tthc noidung ho so read persistence.
	 *
	 * @param tthcNoidungHoSoReadPersistence the tthc noidung ho so read persistence
	 */
	public void setTthcNoidungHoSoReadPersistence(
		TthcNoidungHoSoReadPersistence tthcNoidungHoSoReadPersistence) {
		this.tthcNoidungHoSoReadPersistence = tthcNoidungHoSoReadPersistence;
	}

	/**
	 * Returns the tthc phan nhom ho so local service.
	 *
	 * @return the tthc phan nhom ho so local service
	 */
	public vn.dtt.gt.dk.dao.common.service.TthcPhanNhomHoSoLocalService getTthcPhanNhomHoSoLocalService() {
		return tthcPhanNhomHoSoLocalService;
	}

	/**
	 * Sets the tthc phan nhom ho so local service.
	 *
	 * @param tthcPhanNhomHoSoLocalService the tthc phan nhom ho so local service
	 */
	public void setTthcPhanNhomHoSoLocalService(
		vn.dtt.gt.dk.dao.common.service.TthcPhanNhomHoSoLocalService tthcPhanNhomHoSoLocalService) {
		this.tthcPhanNhomHoSoLocalService = tthcPhanNhomHoSoLocalService;
	}

	/**
	 * Returns the tthc phan nhom ho so remote service.
	 *
	 * @return the tthc phan nhom ho so remote service
	 */
	public vn.dtt.gt.dk.dao.common.service.TthcPhanNhomHoSoService getTthcPhanNhomHoSoService() {
		return tthcPhanNhomHoSoService;
	}

	/**
	 * Sets the tthc phan nhom ho so remote service.
	 *
	 * @param tthcPhanNhomHoSoService the tthc phan nhom ho so remote service
	 */
	public void setTthcPhanNhomHoSoService(
		vn.dtt.gt.dk.dao.common.service.TthcPhanNhomHoSoService tthcPhanNhomHoSoService) {
		this.tthcPhanNhomHoSoService = tthcPhanNhomHoSoService;
	}

	/**
	 * Returns the tthc phan nhom ho so persistence.
	 *
	 * @return the tthc phan nhom ho so persistence
	 */
	public TthcPhanNhomHoSoPersistence getTthcPhanNhomHoSoPersistence() {
		return tthcPhanNhomHoSoPersistence;
	}

	/**
	 * Sets the tthc phan nhom ho so persistence.
	 *
	 * @param tthcPhanNhomHoSoPersistence the tthc phan nhom ho so persistence
	 */
	public void setTthcPhanNhomHoSoPersistence(
		TthcPhanNhomHoSoPersistence tthcPhanNhomHoSoPersistence) {
		this.tthcPhanNhomHoSoPersistence = tthcPhanNhomHoSoPersistence;
	}

	/**
	 * Returns the tthc phan nhom ho so finder.
	 *
	 * @return the tthc phan nhom ho so finder
	 */
	public TthcPhanNhomHoSoFinder getTthcPhanNhomHoSoFinder() {
		return tthcPhanNhomHoSoFinder;
	}

	/**
	 * Sets the tthc phan nhom ho so finder.
	 *
	 * @param tthcPhanNhomHoSoFinder the tthc phan nhom ho so finder
	 */
	public void setTthcPhanNhomHoSoFinder(
		TthcPhanNhomHoSoFinder tthcPhanNhomHoSoFinder) {
		this.tthcPhanNhomHoSoFinder = tthcPhanNhomHoSoFinder;
	}

	/**
	 * Returns the tthc phan nhom ho so vai tro local service.
	 *
	 * @return the tthc phan nhom ho so vai tro local service
	 */
	public vn.dtt.gt.dk.dao.common.service.TthcPhanNhomHoSoVaiTroLocalService getTthcPhanNhomHoSoVaiTroLocalService() {
		return tthcPhanNhomHoSoVaiTroLocalService;
	}

	/**
	 * Sets the tthc phan nhom ho so vai tro local service.
	 *
	 * @param tthcPhanNhomHoSoVaiTroLocalService the tthc phan nhom ho so vai tro local service
	 */
	public void setTthcPhanNhomHoSoVaiTroLocalService(
		vn.dtt.gt.dk.dao.common.service.TthcPhanNhomHoSoVaiTroLocalService tthcPhanNhomHoSoVaiTroLocalService) {
		this.tthcPhanNhomHoSoVaiTroLocalService = tthcPhanNhomHoSoVaiTroLocalService;
	}

	/**
	 * Returns the tthc phan nhom ho so vai tro persistence.
	 *
	 * @return the tthc phan nhom ho so vai tro persistence
	 */
	public TthcPhanNhomHoSoVaiTroPersistence getTthcPhanNhomHoSoVaiTroPersistence() {
		return tthcPhanNhomHoSoVaiTroPersistence;
	}

	/**
	 * Sets the tthc phan nhom ho so vai tro persistence.
	 *
	 * @param tthcPhanNhomHoSoVaiTroPersistence the tthc phan nhom ho so vai tro persistence
	 */
	public void setTthcPhanNhomHoSoVaiTroPersistence(
		TthcPhanNhomHoSoVaiTroPersistence tthcPhanNhomHoSoVaiTroPersistence) {
		this.tthcPhanNhomHoSoVaiTroPersistence = tthcPhanNhomHoSoVaiTroPersistence;
	}

	/**
	 * Returns the tthc phan nhom ho so vai tro finder.
	 *
	 * @return the tthc phan nhom ho so vai tro finder
	 */
	public TthcPhanNhomHoSoVaiTroFinder getTthcPhanNhomHoSoVaiTroFinder() {
		return tthcPhanNhomHoSoVaiTroFinder;
	}

	/**
	 * Sets the tthc phan nhom ho so vai tro finder.
	 *
	 * @param tthcPhanNhomHoSoVaiTroFinder the tthc phan nhom ho so vai tro finder
	 */
	public void setTthcPhanNhomHoSoVaiTroFinder(
		TthcPhanNhomHoSoVaiTroFinder tthcPhanNhomHoSoVaiTroFinder) {
		this.tthcPhanNhomHoSoVaiTroFinder = tthcPhanNhomHoSoVaiTroFinder;
	}

	/**
	 * Returns the tthc thanh phan ho so local service.
	 *
	 * @return the tthc thanh phan ho so local service
	 */
	public vn.dtt.gt.dk.dao.common.service.TthcThanhPhanHoSoLocalService getTthcThanhPhanHoSoLocalService() {
		return tthcThanhPhanHoSoLocalService;
	}

	/**
	 * Sets the tthc thanh phan ho so local service.
	 *
	 * @param tthcThanhPhanHoSoLocalService the tthc thanh phan ho so local service
	 */
	public void setTthcThanhPhanHoSoLocalService(
		vn.dtt.gt.dk.dao.common.service.TthcThanhPhanHoSoLocalService tthcThanhPhanHoSoLocalService) {
		this.tthcThanhPhanHoSoLocalService = tthcThanhPhanHoSoLocalService;
	}

	/**
	 * Returns the tthc thanh phan ho so persistence.
	 *
	 * @return the tthc thanh phan ho so persistence
	 */
	public TthcThanhPhanHoSoPersistence getTthcThanhPhanHoSoPersistence() {
		return tthcThanhPhanHoSoPersistence;
	}

	/**
	 * Sets the tthc thanh phan ho so persistence.
	 *
	 * @param tthcThanhPhanHoSoPersistence the tthc thanh phan ho so persistence
	 */
	public void setTthcThanhPhanHoSoPersistence(
		TthcThanhPhanHoSoPersistence tthcThanhPhanHoSoPersistence) {
		this.tthcThanhPhanHoSoPersistence = tthcThanhPhanHoSoPersistence;
	}

	/**
	 * Returns the tthc thanh phan ho so finder.
	 *
	 * @return the tthc thanh phan ho so finder
	 */
	public TthcThanhPhanHoSoFinder getTthcThanhPhanHoSoFinder() {
		return tthcThanhPhanHoSoFinder;
	}

	/**
	 * Sets the tthc thanh phan ho so finder.
	 *
	 * @param tthcThanhPhanHoSoFinder the tthc thanh phan ho so finder
	 */
	public void setTthcThanhPhanHoSoFinder(
		TthcThanhPhanHoSoFinder tthcThanhPhanHoSoFinder) {
		this.tthcThanhPhanHoSoFinder = tthcThanhPhanHoSoFinder;
	}

	/**
	 * Returns the tthc thu tuc hanh chinh local service.
	 *
	 * @return the tthc thu tuc hanh chinh local service
	 */
	public vn.dtt.gt.dk.dao.common.service.TthcThuTucHanhChinhLocalService getTthcThuTucHanhChinhLocalService() {
		return tthcThuTucHanhChinhLocalService;
	}

	/**
	 * Sets the tthc thu tuc hanh chinh local service.
	 *
	 * @param tthcThuTucHanhChinhLocalService the tthc thu tuc hanh chinh local service
	 */
	public void setTthcThuTucHanhChinhLocalService(
		vn.dtt.gt.dk.dao.common.service.TthcThuTucHanhChinhLocalService tthcThuTucHanhChinhLocalService) {
		this.tthcThuTucHanhChinhLocalService = tthcThuTucHanhChinhLocalService;
	}

	/**
	 * Returns the tthc thu tuc hanh chinh remote service.
	 *
	 * @return the tthc thu tuc hanh chinh remote service
	 */
	public vn.dtt.gt.dk.dao.common.service.TthcThuTucHanhChinhService getTthcThuTucHanhChinhService() {
		return tthcThuTucHanhChinhService;
	}

	/**
	 * Sets the tthc thu tuc hanh chinh remote service.
	 *
	 * @param tthcThuTucHanhChinhService the tthc thu tuc hanh chinh remote service
	 */
	public void setTthcThuTucHanhChinhService(
		vn.dtt.gt.dk.dao.common.service.TthcThuTucHanhChinhService tthcThuTucHanhChinhService) {
		this.tthcThuTucHanhChinhService = tthcThuTucHanhChinhService;
	}

	/**
	 * Returns the tthc thu tuc hanh chinh persistence.
	 *
	 * @return the tthc thu tuc hanh chinh persistence
	 */
	public TthcThuTucHanhChinhPersistence getTthcThuTucHanhChinhPersistence() {
		return tthcThuTucHanhChinhPersistence;
	}

	/**
	 * Sets the tthc thu tuc hanh chinh persistence.
	 *
	 * @param tthcThuTucHanhChinhPersistence the tthc thu tuc hanh chinh persistence
	 */
	public void setTthcThuTucHanhChinhPersistence(
		TthcThuTucHanhChinhPersistence tthcThuTucHanhChinhPersistence) {
		this.tthcThuTucHanhChinhPersistence = tthcThuTucHanhChinhPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.service.UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		Class<?> clazz = getClass();

		_classLoader = clazz.getClassLoader();

		PersistedModelLocalServiceRegistryUtil.register("vn.dtt.gt.dk.dao.common.model.TthcThuTucHanhChinh",
			tthcThuTucHanhChinhLocalService);
	}

	public void destroy() {
		PersistedModelLocalServiceRegistryUtil.unregister(
			"vn.dtt.gt.dk.dao.common.model.TthcThuTucHanhChinh");
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	@Override
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	@Override
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	@Override
	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		Thread currentThread = Thread.currentThread();

		ClassLoader contextClassLoader = currentThread.getContextClassLoader();

		if (contextClassLoader != _classLoader) {
			currentThread.setContextClassLoader(_classLoader);
		}

		try {
			return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
		}
		finally {
			if (contextClassLoader != _classLoader) {
				currentThread.setContextClassLoader(contextClassLoader);
			}
		}
	}

	protected Class<?> getModelClass() {
		return TthcThuTucHanhChinh.class;
	}

	protected String getModelClassName() {
		return TthcThuTucHanhChinh.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = tthcThuTucHanhChinhPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = vn.dtt.gt.dk.dao.common.service.DmDataGroupService.class)
	protected vn.dtt.gt.dk.dao.common.service.DmDataGroupService dmDataGroupService;
	@BeanReference(type = DmDataGroupPersistence.class)
	protected DmDataGroupPersistence dmDataGroupPersistence;
	@BeanReference(type = vn.dtt.gt.dk.dao.common.service.DmDataItemLocalService.class)
	protected vn.dtt.gt.dk.dao.common.service.DmDataItemLocalService dmDataItemLocalService;
	@BeanReference(type = vn.dtt.gt.dk.dao.common.service.DmDataItemService.class)
	protected vn.dtt.gt.dk.dao.common.service.DmDataItemService dmDataItemService;
	@BeanReference(type = DmDataItemPersistence.class)
	protected DmDataItemPersistence dmDataItemPersistence;
	@BeanReference(type = DmDataItemFinder.class)
	protected DmDataItemFinder dmDataItemFinder;
	@BeanReference(type = vn.dtt.gt.dk.dao.common.service.TthcBieuMauHoSoLocalService.class)
	protected vn.dtt.gt.dk.dao.common.service.TthcBieuMauHoSoLocalService tthcBieuMauHoSoLocalService;
	@BeanReference(type = vn.dtt.gt.dk.dao.common.service.TthcBieuMauHoSoService.class)
	protected vn.dtt.gt.dk.dao.common.service.TthcBieuMauHoSoService tthcBieuMauHoSoService;
	@BeanReference(type = TthcBieuMauHoSoPersistence.class)
	protected TthcBieuMauHoSoPersistence tthcBieuMauHoSoPersistence;
	@BeanReference(type = vn.dtt.gt.dk.dao.common.service.TthcHoSoThuTucLocalService.class)
	protected vn.dtt.gt.dk.dao.common.service.TthcHoSoThuTucLocalService tthcHoSoThuTucLocalService;
	@BeanReference(type = vn.dtt.gt.dk.dao.common.service.TthcHoSoThuTucService.class)
	protected vn.dtt.gt.dk.dao.common.service.TthcHoSoThuTucService tthcHoSoThuTucService;
	@BeanReference(type = TthcHoSoThuTucPersistence.class)
	protected TthcHoSoThuTucPersistence tthcHoSoThuTucPersistence;
	@BeanReference(type = vn.dtt.gt.dk.dao.common.service.TthcKeHoachChuyenDichLocalService.class)
	protected vn.dtt.gt.dk.dao.common.service.TthcKeHoachChuyenDichLocalService tthcKeHoachChuyenDichLocalService;
	@BeanReference(type = TthcKeHoachChuyenDichPersistence.class)
	protected TthcKeHoachChuyenDichPersistence tthcKeHoachChuyenDichPersistence;
	@BeanReference(type = TthcKeHoachChuyenDichFinder.class)
	protected TthcKeHoachChuyenDichFinder tthcKeHoachChuyenDichFinder;
	@BeanReference(type = vn.dtt.gt.dk.dao.common.service.TthcNoidungHoSoLocalService.class)
	protected vn.dtt.gt.dk.dao.common.service.TthcNoidungHoSoLocalService tthcNoidungHoSoLocalService;
	@BeanReference(type = vn.dtt.gt.dk.dao.common.service.TthcNoidungHoSoService.class)
	protected vn.dtt.gt.dk.dao.common.service.TthcNoidungHoSoService tthcNoidungHoSoService;
	@BeanReference(type = TthcNoidungHoSoPersistence.class)
	protected TthcNoidungHoSoPersistence tthcNoidungHoSoPersistence;
	@BeanReference(type = TthcNoidungHoSoFinder.class)
	protected TthcNoidungHoSoFinder tthcNoidungHoSoFinder;
	@BeanReference(type = vn.dtt.gt.dk.dao.common.service.TthcNoidungHoSoReadLocalService.class)
	protected vn.dtt.gt.dk.dao.common.service.TthcNoidungHoSoReadLocalService tthcNoidungHoSoReadLocalService;
	@BeanReference(type = vn.dtt.gt.dk.dao.common.service.TthcNoidungHoSoReadService.class)
	protected vn.dtt.gt.dk.dao.common.service.TthcNoidungHoSoReadService tthcNoidungHoSoReadService;
	@BeanReference(type = TthcNoidungHoSoReadPersistence.class)
	protected TthcNoidungHoSoReadPersistence tthcNoidungHoSoReadPersistence;
	@BeanReference(type = vn.dtt.gt.dk.dao.common.service.TthcPhanNhomHoSoLocalService.class)
	protected vn.dtt.gt.dk.dao.common.service.TthcPhanNhomHoSoLocalService tthcPhanNhomHoSoLocalService;
	@BeanReference(type = vn.dtt.gt.dk.dao.common.service.TthcPhanNhomHoSoService.class)
	protected vn.dtt.gt.dk.dao.common.service.TthcPhanNhomHoSoService tthcPhanNhomHoSoService;
	@BeanReference(type = TthcPhanNhomHoSoPersistence.class)
	protected TthcPhanNhomHoSoPersistence tthcPhanNhomHoSoPersistence;
	@BeanReference(type = TthcPhanNhomHoSoFinder.class)
	protected TthcPhanNhomHoSoFinder tthcPhanNhomHoSoFinder;
	@BeanReference(type = vn.dtt.gt.dk.dao.common.service.TthcPhanNhomHoSoVaiTroLocalService.class)
	protected vn.dtt.gt.dk.dao.common.service.TthcPhanNhomHoSoVaiTroLocalService tthcPhanNhomHoSoVaiTroLocalService;
	@BeanReference(type = TthcPhanNhomHoSoVaiTroPersistence.class)
	protected TthcPhanNhomHoSoVaiTroPersistence tthcPhanNhomHoSoVaiTroPersistence;
	@BeanReference(type = TthcPhanNhomHoSoVaiTroFinder.class)
	protected TthcPhanNhomHoSoVaiTroFinder tthcPhanNhomHoSoVaiTroFinder;
	@BeanReference(type = vn.dtt.gt.dk.dao.common.service.TthcThanhPhanHoSoLocalService.class)
	protected vn.dtt.gt.dk.dao.common.service.TthcThanhPhanHoSoLocalService tthcThanhPhanHoSoLocalService;
	@BeanReference(type = TthcThanhPhanHoSoPersistence.class)
	protected TthcThanhPhanHoSoPersistence tthcThanhPhanHoSoPersistence;
	@BeanReference(type = TthcThanhPhanHoSoFinder.class)
	protected TthcThanhPhanHoSoFinder tthcThanhPhanHoSoFinder;
	@BeanReference(type = vn.dtt.gt.dk.dao.common.service.TthcThuTucHanhChinhLocalService.class)
	protected vn.dtt.gt.dk.dao.common.service.TthcThuTucHanhChinhLocalService tthcThuTucHanhChinhLocalService;
	@BeanReference(type = vn.dtt.gt.dk.dao.common.service.TthcThuTucHanhChinhService.class)
	protected vn.dtt.gt.dk.dao.common.service.TthcThuTucHanhChinhService tthcThuTucHanhChinhService;
	@BeanReference(type = TthcThuTucHanhChinhPersistence.class)
	protected TthcThuTucHanhChinhPersistence tthcThuTucHanhChinhPersistence;
	@BeanReference(type = com.liferay.counter.service.CounterLocalService.class)
	protected com.liferay.counter.service.CounterLocalService counterLocalService;
	@BeanReference(type = com.liferay.portal.service.ResourceLocalService.class)
	protected com.liferay.portal.service.ResourceLocalService resourceLocalService;
	@BeanReference(type = com.liferay.portal.service.UserLocalService.class)
	protected com.liferay.portal.service.UserLocalService userLocalService;
	@BeanReference(type = com.liferay.portal.service.UserService.class)
	protected com.liferay.portal.service.UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
	private ClassLoader _classLoader;
	private TthcThuTucHanhChinhLocalServiceClpInvoker _clpInvoker = new TthcThuTucHanhChinhLocalServiceClpInvoker();
}