/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.gt.dk.dao.api.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Api service. Represents a row in the &quot;api_log&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.dtt.gt.dk.dao.api.model.impl.ApiModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.dtt.gt.dk.dao.api.model.impl.ApiImpl}.
 * </p>
 *
 * @author huymq
 * @see Api
 * @see vn.dtt.gt.dk.dao.api.model.impl.ApiImpl
 * @see vn.dtt.gt.dk.dao.api.model.impl.ApiModelImpl
 * @generated
 */
public interface ApiModel extends BaseModel<Api> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a api model instance should use the {@link Api} interface instead.
	 */

	/**
	 * Returns the primary key of this api.
	 *
	 * @return the primary key of this api
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this api.
	 *
	 * @param primaryKey the primary key of this api
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this api.
	 *
	 * @return the ID of this api
	 */
	public long getId();

	/**
	 * Sets the ID of this api.
	 *
	 * @param id the ID of this api
	 */
	public void setId(long id);

	/**
	 * Returns the create date of this api.
	 *
	 * @return the create date of this api
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this api.
	 *
	 * @param createDate the create date of this api
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this api.
	 *
	 * @return the modified date of this api
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this api.
	 *
	 * @param modifiedDate the modified date of this api
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the user agent of this api.
	 *
	 * @return the user agent of this api
	 */
	@AutoEscape
	public String getUserAgent();

	/**
	 * Sets the user agent of this api.
	 *
	 * @param userAgent the user agent of this api
	 */
	public void setUserAgent(String userAgent);

	/**
	 * Returns the ip of this api.
	 *
	 * @return the ip of this api
	 */
	@AutoEscape
	public String getIp();

	/**
	 * Sets the ip of this api.
	 *
	 * @param ip the ip of this api
	 */
	public void setIp(String ip);

	/**
	 * Returns the code of this api.
	 *
	 * @return the code of this api
	 */
	@AutoEscape
	public String getCode();

	/**
	 * Sets the code of this api.
	 *
	 * @param code the code of this api
	 */
	public void setCode(String code);

	/**
	 * Returns the registered number of this api.
	 *
	 * @return the registered number of this api
	 */
	@AutoEscape
	public String getRegisteredNumber();

	/**
	 * Sets the registered number of this api.
	 *
	 * @param registeredNumber the registered number of this api
	 */
	public void setRegisteredNumber(String registeredNumber);

	/**
	 * Returns the request of this api.
	 *
	 * @return the request of this api
	 */
	@AutoEscape
	public String getRequest();

	/**
	 * Sets the request of this api.
	 *
	 * @param request the request of this api
	 */
	public void setRequest(String request);

	/**
	 * Returns the response of this api.
	 *
	 * @return the response of this api
	 */
	@AutoEscape
	public String getResponse();

	/**
	 * Sets the response of this api.
	 *
	 * @param response the response of this api
	 */
	public void setResponse(String response);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Api api);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Api> toCacheModel();

	@Override
	public Api toEscapedModel();

	@Override
	public Api toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}