//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.06 at 04:05:36 PM ICT 
//


package vn.dtt.gt.dk.nsw.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RequestDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Organization" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Division" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ReasonOfInquiry" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CertificateDetails" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="CertificateNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="VehicleEngineStatus" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="Importer">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="ImporterCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ImporterName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ImporterAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="TradeMark" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ModelType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ProductionCountry">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="CountryCode" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="ProductionYear" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="MarkAsVehicle" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="VehicleType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="EngineType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ChassisNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="EngineNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="CustomDeclaration" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="ImportCustomDeclareNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ImportCustomDeclareDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="RegisteredNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "requestDate",
    "organization",
    "division",
    "name",
    "reasonOfInquiry",
    "certificateDetails"
})
@XmlRootElement(name = "InquiryImportedVehicleReference")
public class InquiryImportedVehicleReference {

    @XmlElement(name = "RequestDate", required = true)
    protected String requestDate;
    @XmlElement(name = "Organization", required = true)
    protected String organization;
    @XmlElement(name = "Division", required = true)
    protected String division;
    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "ReasonOfInquiry", required = true)
    protected String reasonOfInquiry;
    @XmlElement(name = "CertificateDetails", required = true)
    protected List<InquiryImportedVehicleReference.CertificateDetails> certificateDetails;

    /**
     * Gets the value of the requestDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestDate() {
        return requestDate;
    }

    /**
     * Sets the value of the requestDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestDate(String value) {
        this.requestDate = value;
    }

    /**
     * Gets the value of the organization property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrganization() {
        return organization;
    }

    /**
     * Sets the value of the organization property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrganization(String value) {
        this.organization = value;
    }

    /**
     * Gets the value of the division property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDivision() {
        return division;
    }

    /**
     * Sets the value of the division property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDivision(String value) {
        this.division = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the reasonOfInquiry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReasonOfInquiry() {
        return reasonOfInquiry;
    }

    /**
     * Sets the value of the reasonOfInquiry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReasonOfInquiry(String value) {
        this.reasonOfInquiry = value;
    }

    /**
     * Gets the value of the certificateDetails property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the certificateDetails property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCertificateDetails().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InquiryImportedVehicleReference.CertificateDetails }
     * 
     * 
     */
    public List<InquiryImportedVehicleReference.CertificateDetails> getCertificateDetails() {
        if (certificateDetails == null) {
            certificateDetails = new ArrayList<InquiryImportedVehicleReference.CertificateDetails>();
        }
        return this.certificateDetails;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="CertificateNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="VehicleEngineStatus" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="Importer">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="ImporterCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ImporterName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ImporterAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="TradeMark" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ModelType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ProductionCountry">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="CountryCode" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="ProductionYear" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="MarkAsVehicle" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="VehicleType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="EngineType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ChassisNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="EngineNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="CustomDeclaration" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="ImportCustomDeclareNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ImportCustomDeclareDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="RegisteredNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "certificateNumber",
        "vehicleEngineStatus",
        "importer",
        "tradeMark",
        "modelType",
        "productionCountry",
        "productionYear",
        "markAsVehicle",
        "vehicleType",
        "engineType",
        "chassisNumber",
        "engineNumber",
        "customDeclaration",
        "registeredNumber"
    })
    public static class CertificateDetails {

        @XmlElement(name = "CertificateNumber", required = true)
        protected String certificateNumber;
        @XmlElement(name = "VehicleEngineStatus")
        protected int vehicleEngineStatus;
        @XmlElement(name = "Importer", required = true)
        protected InquiryImportedVehicleReference.CertificateDetails.Importer importer;
        @XmlElement(name = "TradeMark", required = true)
        protected String tradeMark;
        @XmlElement(name = "ModelType", required = true)
        protected String modelType;
        @XmlElement(name = "ProductionCountry", required = true)
        protected InquiryImportedVehicleReference.CertificateDetails.ProductionCountry productionCountry;
        @XmlElement(name = "ProductionYear", required = true)
        protected String productionYear;
        @XmlElement(name = "MarkAsVehicle")
        protected int markAsVehicle;
        @XmlElement(name = "VehicleType", required = true)
        protected String vehicleType;
        @XmlElement(name = "EngineType", required = true)
        protected String engineType;
        @XmlElement(name = "ChassisNumber", required = true)
        protected String chassisNumber;
        @XmlElement(name = "EngineNumber", required = true)
        protected String engineNumber;
        @XmlElement(name = "CustomDeclaration", required = true)
        protected List<InquiryImportedVehicleReference.CertificateDetails.CustomDeclaration> customDeclaration;
        @XmlElement(name = "RegisteredNumber", required = true)
        protected String registeredNumber;

        /**
         * Gets the value of the certificateNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCertificateNumber() {
            return certificateNumber;
        }

        /**
         * Sets the value of the certificateNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCertificateNumber(String value) {
            this.certificateNumber = value;
        }

        /**
         * Gets the value of the vehicleEngineStatus property.
         * 
         */
        public int getVehicleEngineStatus() {
            return vehicleEngineStatus;
        }

        /**
         * Sets the value of the vehicleEngineStatus property.
         * 
         */
        public void setVehicleEngineStatus(int value) {
            this.vehicleEngineStatus = value;
        }

        /**
         * Gets the value of the importer property.
         * 
         * @return
         *     possible object is
         *     {@link InquiryImportedVehicleReference.CertificateDetails.Importer }
         *     
         */
        public InquiryImportedVehicleReference.CertificateDetails.Importer getImporter() {
            return importer;
        }

        /**
         * Sets the value of the importer property.
         * 
         * @param value
         *     allowed object is
         *     {@link InquiryImportedVehicleReference.CertificateDetails.Importer }
         *     
         */
        public void setImporter(InquiryImportedVehicleReference.CertificateDetails.Importer value) {
            this.importer = value;
        }

        /**
         * Gets the value of the tradeMark property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTradeMark() {
            return tradeMark;
        }

        /**
         * Sets the value of the tradeMark property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTradeMark(String value) {
            this.tradeMark = value;
        }

        /**
         * Gets the value of the modelType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getModelType() {
            return modelType;
        }

        /**
         * Sets the value of the modelType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setModelType(String value) {
            this.modelType = value;
        }

        /**
         * Gets the value of the productionCountry property.
         * 
         * @return
         *     possible object is
         *     {@link InquiryImportedVehicleReference.CertificateDetails.ProductionCountry }
         *     
         */
        public InquiryImportedVehicleReference.CertificateDetails.ProductionCountry getProductionCountry() {
            return productionCountry;
        }

        /**
         * Sets the value of the productionCountry property.
         * 
         * @param value
         *     allowed object is
         *     {@link InquiryImportedVehicleReference.CertificateDetails.ProductionCountry }
         *     
         */
        public void setProductionCountry(InquiryImportedVehicleReference.CertificateDetails.ProductionCountry value) {
            this.productionCountry = value;
        }

        /**
         * Gets the value of the productionYear property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProductionYear() {
            return productionYear;
        }

        /**
         * Sets the value of the productionYear property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProductionYear(String value) {
            this.productionYear = value;
        }

        /**
         * Gets the value of the markAsVehicle property.
         * 
         */
        public int getMarkAsVehicle() {
            return markAsVehicle;
        }

        /**
         * Sets the value of the markAsVehicle property.
         * 
         */
        public void setMarkAsVehicle(int value) {
            this.markAsVehicle = value;
        }

        /**
         * Gets the value of the vehicleType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVehicleType() {
            return vehicleType;
        }

        /**
         * Sets the value of the vehicleType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVehicleType(String value) {
            this.vehicleType = value;
        }

        /**
         * Gets the value of the engineType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEngineType() {
            return engineType;
        }

        /**
         * Sets the value of the engineType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEngineType(String value) {
            this.engineType = value;
        }

        /**
         * Gets the value of the chassisNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getChassisNumber() {
            return chassisNumber;
        }

        /**
         * Sets the value of the chassisNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setChassisNumber(String value) {
            this.chassisNumber = value;
        }

        /**
         * Gets the value of the engineNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEngineNumber() {
            return engineNumber;
        }

        /**
         * Sets the value of the engineNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEngineNumber(String value) {
            this.engineNumber = value;
        }

        /**
         * Gets the value of the customDeclaration property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the customDeclaration property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCustomDeclaration().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link InquiryImportedVehicleReference.CertificateDetails.CustomDeclaration }
         * 
         * 
         */
        public List<InquiryImportedVehicleReference.CertificateDetails.CustomDeclaration> getCustomDeclaration() {
            if (customDeclaration == null) {
                customDeclaration = new ArrayList<InquiryImportedVehicleReference.CertificateDetails.CustomDeclaration>();
            }
            return this.customDeclaration;
        }

        /**
         * Gets the value of the registeredNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRegisteredNumber() {
            return registeredNumber;
        }

        /**
         * Sets the value of the registeredNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRegisteredNumber(String value) {
            this.registeredNumber = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="ImportCustomDeclareNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ImportCustomDeclareDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "importCustomDeclareNo",
            "importCustomDeclareDate"
        })
        public static class CustomDeclaration {

            @XmlElement(name = "ImportCustomDeclareNo", required = true)
            protected String importCustomDeclareNo;
            @XmlElement(name = "ImportCustomDeclareDate", required = true)
            protected String importCustomDeclareDate;

            /**
             * Gets the value of the importCustomDeclareNo property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getImportCustomDeclareNo() {
                return importCustomDeclareNo;
            }

            /**
             * Sets the value of the importCustomDeclareNo property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setImportCustomDeclareNo(String value) {
                this.importCustomDeclareNo = value;
            }

            /**
             * Gets the value of the importCustomDeclareDate property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getImportCustomDeclareDate() {
                return importCustomDeclareDate;
            }

            /**
             * Sets the value of the importCustomDeclareDate property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setImportCustomDeclareDate(String value) {
                this.importCustomDeclareDate = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="ImporterCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ImporterName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ImporterAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "importerCode",
            "importerName",
            "importerAddress"
        })
        public static class Importer {

            @XmlElement(name = "ImporterCode", required = true)
            protected String importerCode;
            @XmlElement(name = "ImporterName", required = true)
            protected String importerName;
            @XmlElement(name = "ImporterAddress", required = true)
            protected String importerAddress;

            /**
             * Gets the value of the importerCode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getImporterCode() {
                return importerCode;
            }

            /**
             * Sets the value of the importerCode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setImporterCode(String value) {
                this.importerCode = value;
            }

            /**
             * Gets the value of the importerName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getImporterName() {
                return importerName;
            }

            /**
             * Sets the value of the importerName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setImporterName(String value) {
                this.importerName = value;
            }

            /**
             * Gets the value of the importerAddress property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getImporterAddress() {
                return importerAddress;
            }

            /**
             * Sets the value of the importerAddress property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setImporterAddress(String value) {
                this.importerAddress = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="CountryCode" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "countryCode"
        })
        public static class ProductionCountry {

            @XmlElement(name = "CountryCode", required = true)
            protected List<String> countryCode;

            /**
             * Gets the value of the countryCode property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the countryCode property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getCountryCode().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * 
             * 
             */
            public List<String> getCountryCode() {
                if (countryCode == null) {
                    countryCode = new ArrayList<String>();
                }
                return this.countryCode;
            }

        }

    }

}
