/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.gt.dk.dao.motcua.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the MotCuaPhieuXuLyChinh service. Represents a row in the &quot;motcua_phieuxulychinh&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.dtt.gt.dk.dao.motcua.model.impl.MotCuaPhieuXuLyChinhModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.dtt.gt.dk.dao.motcua.model.impl.MotCuaPhieuXuLyChinhImpl}.
 * </p>
 *
 * @author win_64
 * @see MotCuaPhieuXuLyChinh
 * @see vn.dtt.gt.dk.dao.motcua.model.impl.MotCuaPhieuXuLyChinhImpl
 * @see vn.dtt.gt.dk.dao.motcua.model.impl.MotCuaPhieuXuLyChinhModelImpl
 * @generated
 */
public interface MotCuaPhieuXuLyChinhModel extends BaseModel<MotCuaPhieuXuLyChinh> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a mot cua phieu xu ly chinh model instance should use the {@link MotCuaPhieuXuLyChinh} interface instead.
	 */

	/**
	 * Returns the primary key of this mot cua phieu xu ly chinh.
	 *
	 * @return the primary key of this mot cua phieu xu ly chinh
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this mot cua phieu xu ly chinh.
	 *
	 * @param primaryKey the primary key of this mot cua phieu xu ly chinh
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this mot cua phieu xu ly chinh.
	 *
	 * @return the ID of this mot cua phieu xu ly chinh
	 */
	public long getId();

	/**
	 * Sets the ID of this mot cua phieu xu ly chinh.
	 *
	 * @param id the ID of this mot cua phieu xu ly chinh
	 */
	public void setId(long id);

	/**
	 * Returns the ho so thu tuc ID of this mot cua phieu xu ly chinh.
	 *
	 * @return the ho so thu tuc ID of this mot cua phieu xu ly chinh
	 */
	public long getHoSoThuTucId();

	/**
	 * Sets the ho so thu tuc ID of this mot cua phieu xu ly chinh.
	 *
	 * @param hoSoThuTucId the ho so thu tuc ID of this mot cua phieu xu ly chinh
	 */
	public void setHoSoThuTucId(long hoSoThuTucId);

	/**
	 * Returns the quy trinh thu tuc ID of this mot cua phieu xu ly chinh.
	 *
	 * @return the quy trinh thu tuc ID of this mot cua phieu xu ly chinh
	 */
	public long getQuyTrinhThuTucId();

	/**
	 * Sets the quy trinh thu tuc ID of this mot cua phieu xu ly chinh.
	 *
	 * @param quyTrinhThuTucId the quy trinh thu tuc ID of this mot cua phieu xu ly chinh
	 */
	public void setQuyTrinhThuTucId(long quyTrinhThuTucId);

	/**
	 * Returns the ten nguoi nop of this mot cua phieu xu ly chinh.
	 *
	 * @return the ten nguoi nop of this mot cua phieu xu ly chinh
	 */
	@AutoEscape
	public String getTenNguoiNop();

	/**
	 * Sets the ten nguoi nop of this mot cua phieu xu ly chinh.
	 *
	 * @param tenNguoiNop the ten nguoi nop of this mot cua phieu xu ly chinh
	 */
	public void setTenNguoiNop(String tenNguoiNop);

	/**
	 * Returns the cmnd nguoi nop of this mot cua phieu xu ly chinh.
	 *
	 * @return the cmnd nguoi nop of this mot cua phieu xu ly chinh
	 */
	@AutoEscape
	public String getCmndNguoiNop();

	/**
	 * Sets the cmnd nguoi nop of this mot cua phieu xu ly chinh.
	 *
	 * @param cmndNguoiNop the cmnd nguoi nop of this mot cua phieu xu ly chinh
	 */
	public void setCmndNguoiNop(String cmndNguoiNop);

	/**
	 * Returns the dia chi nguoi nop of this mot cua phieu xu ly chinh.
	 *
	 * @return the dia chi nguoi nop of this mot cua phieu xu ly chinh
	 */
	@AutoEscape
	public String getDiaChiNguoiNop();

	/**
	 * Sets the dia chi nguoi nop of this mot cua phieu xu ly chinh.
	 *
	 * @param diaChiNguoiNop the dia chi nguoi nop of this mot cua phieu xu ly chinh
	 */
	public void setDiaChiNguoiNop(String diaChiNguoiNop);

	/**
	 * Returns the so dtdd nguoi nop of this mot cua phieu xu ly chinh.
	 *
	 * @return the so dtdd nguoi nop of this mot cua phieu xu ly chinh
	 */
	@AutoEscape
	public String getSoDtddNguoiNop();

	/**
	 * Sets the so dtdd nguoi nop of this mot cua phieu xu ly chinh.
	 *
	 * @param soDtddNguoiNop the so dtdd nguoi nop of this mot cua phieu xu ly chinh
	 */
	public void setSoDtddNguoiNop(String soDtddNguoiNop);

	/**
	 * Returns the email nguoi nop of this mot cua phieu xu ly chinh.
	 *
	 * @return the email nguoi nop of this mot cua phieu xu ly chinh
	 */
	@AutoEscape
	public String getEmailNguoiNop();

	/**
	 * Sets the email nguoi nop of this mot cua phieu xu ly chinh.
	 *
	 * @param emailNguoiNop the email nguoi nop of this mot cua phieu xu ly chinh
	 */
	public void setEmailNguoiNop(String emailNguoiNop);

	/**
	 * Returns the ghi chu of this mot cua phieu xu ly chinh.
	 *
	 * @return the ghi chu of this mot cua phieu xu ly chinh
	 */
	@AutoEscape
	public String getGhiChu();

	/**
	 * Sets the ghi chu of this mot cua phieu xu ly chinh.
	 *
	 * @param ghiChu the ghi chu of this mot cua phieu xu ly chinh
	 */
	public void setGhiChu(String ghiChu);

	/**
	 * Returns the trang thai hien tai ID of this mot cua phieu xu ly chinh.
	 *
	 * @return the trang thai hien tai ID of this mot cua phieu xu ly chinh
	 */
	public long getTrangThaiHienTaiId();

	/**
	 * Sets the trang thai hien tai ID of this mot cua phieu xu ly chinh.
	 *
	 * @param trangThaiHienTaiId the trang thai hien tai ID of this mot cua phieu xu ly chinh
	 */
	public void setTrangThaiHienTaiId(long trangThaiHienTaiId);

	/**
	 * Returns the het ho so con of this mot cua phieu xu ly chinh.
	 *
	 * @return the het ho so con of this mot cua phieu xu ly chinh
	 */
	public long getHetHoSoCon();

	/**
	 * Sets the het ho so con of this mot cua phieu xu ly chinh.
	 *
	 * @param hetHoSoCon the het ho so con of this mot cua phieu xu ly chinh
	 */
	public void setHetHoSoCon(long hetHoSoCon);

	/**
	 * Returns the chiem quyen xu ly of this mot cua phieu xu ly chinh.
	 *
	 * @return the chiem quyen xu ly of this mot cua phieu xu ly chinh
	 */
	public long getChiemQuyenXuLy();

	/**
	 * Sets the chiem quyen xu ly of this mot cua phieu xu ly chinh.
	 *
	 * @param chiemQuyenXuLy the chiem quyen xu ly of this mot cua phieu xu ly chinh
	 */
	public void setChiemQuyenXuLy(long chiemQuyenXuLy);

	/**
	 * Returns the ngay tao phieu of this mot cua phieu xu ly chinh.
	 *
	 * @return the ngay tao phieu of this mot cua phieu xu ly chinh
	 */
	public Date getNgayTaoPhieu();

	/**
	 * Sets the ngay tao phieu of this mot cua phieu xu ly chinh.
	 *
	 * @param ngayTaoPhieu the ngay tao phieu of this mot cua phieu xu ly chinh
	 */
	public void setNgayTaoPhieu(Date ngayTaoPhieu);

	/**
	 * Returns the nguoi tao phieu of this mot cua phieu xu ly chinh.
	 *
	 * @return the nguoi tao phieu of this mot cua phieu xu ly chinh
	 */
	public long getNguoiTaoPhieu();

	/**
	 * Sets the nguoi tao phieu of this mot cua phieu xu ly chinh.
	 *
	 * @param nguoiTaoPhieu the nguoi tao phieu of this mot cua phieu xu ly chinh
	 */
	public void setNguoiTaoPhieu(long nguoiTaoPhieu);

	/**
	 * Returns the so dtcd nguoi nop of this mot cua phieu xu ly chinh.
	 *
	 * @return the so dtcd nguoi nop of this mot cua phieu xu ly chinh
	 */
	@AutoEscape
	public String getSoDtcdNguoiNop();

	/**
	 * Sets the so dtcd nguoi nop of this mot cua phieu xu ly chinh.
	 *
	 * @param soDtcdNguoiNop the so dtcd nguoi nop of this mot cua phieu xu ly chinh
	 */
	public void setSoDtcdNguoiNop(String soDtcdNguoiNop);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		vn.dtt.gt.dk.dao.motcua.model.MotCuaPhieuXuLyChinh motCuaPhieuXuLyChinh);

	@Override
	public int hashCode();

	@Override
	public CacheModel<vn.dtt.gt.dk.dao.motcua.model.MotCuaPhieuXuLyChinh> toCacheModel();

	@Override
	public vn.dtt.gt.dk.dao.motcua.model.MotCuaPhieuXuLyChinh toEscapedModel();

	@Override
	public vn.dtt.gt.dk.dao.motcua.model.MotCuaPhieuXuLyChinh toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}