/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.gt.dk.dao.motcua.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the MotCuaNotification service. Represents a row in the &quot;motcua_notification&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.dtt.gt.dk.dao.motcua.model.impl.MotCuaNotificationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.dtt.gt.dk.dao.motcua.model.impl.MotCuaNotificationImpl}.
 * </p>
 *
 * @author win_64
 * @see MotCuaNotification
 * @see vn.dtt.gt.dk.dao.motcua.model.impl.MotCuaNotificationImpl
 * @see vn.dtt.gt.dk.dao.motcua.model.impl.MotCuaNotificationModelImpl
 * @generated
 */
public interface MotCuaNotificationModel extends BaseModel<MotCuaNotification> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a mot cua notification model instance should use the {@link MotCuaNotification} interface instead.
	 */

	/**
	 * Returns the primary key of this mot cua notification.
	 *
	 * @return the primary key of this mot cua notification
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this mot cua notification.
	 *
	 * @param primaryKey the primary key of this mot cua notification
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this mot cua notification.
	 *
	 * @return the ID of this mot cua notification
	 */
	public long getId();

	/**
	 * Sets the ID of this mot cua notification.
	 *
	 * @param id the ID of this mot cua notification
	 */
	public void setId(long id);

	/**
	 * Returns the dossierid of this mot cua notification.
	 *
	 * @return the dossierid of this mot cua notification
	 */
	public long getDossierid();

	/**
	 * Sets the dossierid of this mot cua notification.
	 *
	 * @param dossierid the dossierid of this mot cua notification
	 */
	public void setDossierid(long dossierid);

	/**
	 * Returns the organization of this mot cua notification.
	 *
	 * @return the organization of this mot cua notification
	 */
	@AutoEscape
	public String getOrganization();

	/**
	 * Sets the organization of this mot cua notification.
	 *
	 * @param organization the organization of this mot cua notification
	 */
	public void setOrganization(String organization);

	/**
	 * Returns the division of this mot cua notification.
	 *
	 * @return the division of this mot cua notification
	 */
	@AutoEscape
	public String getDivision();

	/**
	 * Sets the division of this mot cua notification.
	 *
	 * @param division the division of this mot cua notification
	 */
	public void setDivision(String division);

	/**
	 * Returns the officer name of this mot cua notification.
	 *
	 * @return the officer name of this mot cua notification
	 */
	@AutoEscape
	public String getOfficerName();

	/**
	 * Sets the officer name of this mot cua notification.
	 *
	 * @param officerName the officer name of this mot cua notification
	 */
	public void setOfficerName(String officerName);

	/**
	 * Returns the message i d of this mot cua notification.
	 *
	 * @return the message i d of this mot cua notification
	 */
	@AutoEscape
	public String getMessageID();

	/**
	 * Sets the message i d of this mot cua notification.
	 *
	 * @param messageID the message i d of this mot cua notification
	 */
	public void setMessageID(String messageID);

	/**
	 * Returns the message type of this mot cua notification.
	 *
	 * @return the message type of this mot cua notification
	 */
	public long getMessageType();

	/**
	 * Sets the message type of this mot cua notification.
	 *
	 * @param messageType the message type of this mot cua notification
	 */
	public void setMessageType(long messageType);

	/**
	 * Returns the phieuxulyphu ID of this mot cua notification.
	 *
	 * @return the phieuxulyphu ID of this mot cua notification
	 */
	public long getPhieuxulyphuId();

	/**
	 * Sets the phieuxulyphu ID of this mot cua notification.
	 *
	 * @param phieuxulyphuId the phieuxulyphu ID of this mot cua notification
	 */
	public void setPhieuxulyphuId(long phieuxulyphuId);

	/**
	 * Returns the response of this mot cua notification.
	 *
	 * @return the response of this mot cua notification
	 */
	@AutoEscape
	public String getResponse();

	/**
	 * Sets the response of this mot cua notification.
	 *
	 * @param response the response of this mot cua notification
	 */
	public void setResponse(String response);

	/**
	 * Returns the response time of this mot cua notification.
	 *
	 * @return the response time of this mot cua notification
	 */
	public Date getResponseTime();

	/**
	 * Sets the response time of this mot cua notification.
	 *
	 * @param responseTime the response time of this mot cua notification
	 */
	public void setResponseTime(Date responseTime);

	/**
	 * Returns the request content of this mot cua notification.
	 *
	 * @return the request content of this mot cua notification
	 */
	@AutoEscape
	public String getRequestContent();

	/**
	 * Sets the request content of this mot cua notification.
	 *
	 * @param requestContent the request content of this mot cua notification
	 */
	public void setRequestContent(String requestContent);

	/**
	 * Returns the request time of this mot cua notification.
	 *
	 * @return the request time of this mot cua notification
	 */
	public Date getRequestTime();

	/**
	 * Sets the request time of this mot cua notification.
	 *
	 * @param requestTime the request time of this mot cua notification
	 */
	public void setRequestTime(Date requestTime);

	/**
	 * Returns the request sender of this mot cua notification.
	 *
	 * @return the request sender of this mot cua notification
	 */
	@AutoEscape
	public String getRequestSender();

	/**
	 * Sets the request sender of this mot cua notification.
	 *
	 * @param requestSender the request sender of this mot cua notification
	 */
	public void setRequestSender(String requestSender);

	/**
	 * Returns the is reply of this mot cua notification.
	 *
	 * @return the is reply of this mot cua notification
	 */
	public long getIsReply();

	/**
	 * Sets the is reply of this mot cua notification.
	 *
	 * @param isReply the is reply of this mot cua notification
	 */
	public void setIsReply(long isReply);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		vn.dtt.gt.dk.dao.motcua.model.MotCuaNotification motCuaNotification);

	@Override
	public int hashCode();

	@Override
	public CacheModel<vn.dtt.gt.dk.dao.motcua.model.MotCuaNotification> toCacheModel();

	@Override
	public vn.dtt.gt.dk.dao.motcua.model.MotCuaNotification toEscapedModel();

	@Override
	public vn.dtt.gt.dk.dao.motcua.model.MotCuaNotification toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}