/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.gt.dk.dao.motcua.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the MotCuaPhieuXuLyPhu service. Represents a row in the &quot;motcua_phieuxulyphu&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.dtt.gt.dk.dao.motcua.model.impl.MotCuaPhieuXuLyPhuModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.dtt.gt.dk.dao.motcua.model.impl.MotCuaPhieuXuLyPhuImpl}.
 * </p>
 *
 * @author win_64
 * @see MotCuaPhieuXuLyPhu
 * @see vn.dtt.gt.dk.dao.motcua.model.impl.MotCuaPhieuXuLyPhuImpl
 * @see vn.dtt.gt.dk.dao.motcua.model.impl.MotCuaPhieuXuLyPhuModelImpl
 * @generated
 */
public interface MotCuaPhieuXuLyPhuModel extends BaseModel<MotCuaPhieuXuLyPhu> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a mot cua phieu xu ly phu model instance should use the {@link MotCuaPhieuXuLyPhu} interface instead.
	 */

	/**
	 * Returns the primary key of this mot cua phieu xu ly phu.
	 *
	 * @return the primary key of this mot cua phieu xu ly phu
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this mot cua phieu xu ly phu.
	 *
	 * @param primaryKey the primary key of this mot cua phieu xu ly phu
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this mot cua phieu xu ly phu.
	 *
	 * @return the ID of this mot cua phieu xu ly phu
	 */
	public long getId();

	/**
	 * Sets the ID of this mot cua phieu xu ly phu.
	 *
	 * @param id the ID of this mot cua phieu xu ly phu
	 */
	public void setId(long id);

	/**
	 * Returns the phieu xu ly chinh ID of this mot cua phieu xu ly phu.
	 *
	 * @return the phieu xu ly chinh ID of this mot cua phieu xu ly phu
	 */
	public long getPhieuXuLyChinhId();

	/**
	 * Sets the phieu xu ly chinh ID of this mot cua phieu xu ly phu.
	 *
	 * @param phieuXuLyChinhId the phieu xu ly chinh ID of this mot cua phieu xu ly phu
	 */
	public void setPhieuXuLyChinhId(long phieuXuLyChinhId);

	/**
	 * Returns the trich yeu noi dung of this mot cua phieu xu ly phu.
	 *
	 * @return the trich yeu noi dung of this mot cua phieu xu ly phu
	 */
	@AutoEscape
	public String getTrichYeuNoiDung();

	/**
	 * Sets the trich yeu noi dung of this mot cua phieu xu ly phu.
	 *
	 * @param trichYeuNoiDung the trich yeu noi dung of this mot cua phieu xu ly phu
	 */
	public void setTrichYeuNoiDung(String trichYeuNoiDung);

	/**
	 * Returns the ghi chu of this mot cua phieu xu ly phu.
	 *
	 * @return the ghi chu of this mot cua phieu xu ly phu
	 */
	@AutoEscape
	public String getGhiChu();

	/**
	 * Sets the ghi chu of this mot cua phieu xu ly phu.
	 *
	 * @param ghiChu the ghi chu of this mot cua phieu xu ly phu
	 */
	public void setGhiChu(String ghiChu);

	/**
	 * Returns the trang thai hien tai ID of this mot cua phieu xu ly phu.
	 *
	 * @return the trang thai hien tai ID of this mot cua phieu xu ly phu
	 */
	public long getTrangThaiHienTaiId();

	/**
	 * Sets the trang thai hien tai ID of this mot cua phieu xu ly phu.
	 *
	 * @param trangThaiHienTaiId the trang thai hien tai ID of this mot cua phieu xu ly phu
	 */
	public void setTrangThaiHienTaiId(long trangThaiHienTaiId);

	/**
	 * Returns the noi dung ho so ID of this mot cua phieu xu ly phu.
	 *
	 * @return the noi dung ho so ID of this mot cua phieu xu ly phu
	 */
	public long getNoiDungHoSoId();

	/**
	 * Sets the noi dung ho so ID of this mot cua phieu xu ly phu.
	 *
	 * @param noiDungHoSoId the noi dung ho so ID of this mot cua phieu xu ly phu
	 */
	public void setNoiDungHoSoId(long noiDungHoSoId);

	/**
	 * Returns the chiem quyen xu ly of this mot cua phieu xu ly phu.
	 *
	 * @return the chiem quyen xu ly of this mot cua phieu xu ly phu
	 */
	public long getChiemQuyenXuLy();

	/**
	 * Sets the chiem quyen xu ly of this mot cua phieu xu ly phu.
	 *
	 * @param chiemQuyenXuLy the chiem quyen xu ly of this mot cua phieu xu ly phu
	 */
	public void setChiemQuyenXuLy(long chiemQuyenXuLy);

	/**
	 * Returns the ngay tao phieu of this mot cua phieu xu ly phu.
	 *
	 * @return the ngay tao phieu of this mot cua phieu xu ly phu
	 */
	public Date getNgayTaoPhieu();

	/**
	 * Sets the ngay tao phieu of this mot cua phieu xu ly phu.
	 *
	 * @param ngayTaoPhieu the ngay tao phieu of this mot cua phieu xu ly phu
	 */
	public void setNgayTaoPhieu(Date ngayTaoPhieu);

	/**
	 * Returns the nguoi tao phieu of this mot cua phieu xu ly phu.
	 *
	 * @return the nguoi tao phieu of this mot cua phieu xu ly phu
	 */
	public long getNguoiTaoPhieu();

	/**
	 * Sets the nguoi tao phieu of this mot cua phieu xu ly phu.
	 *
	 * @param nguoiTaoPhieu the nguoi tao phieu of this mot cua phieu xu ly phu
	 */
	public void setNguoiTaoPhieu(long nguoiTaoPhieu);

	/**
	 * Returns the nhom phieu xu ly of this mot cua phieu xu ly phu.
	 *
	 * @return the nhom phieu xu ly of this mot cua phieu xu ly phu
	 */
	@AutoEscape
	public String getNhomPhieuXuLy();

	/**
	 * Sets the nhom phieu xu ly of this mot cua phieu xu ly phu.
	 *
	 * @param nhomPhieuXuLy the nhom phieu xu ly of this mot cua phieu xu ly phu
	 */
	public void setNhomPhieuXuLy(String nhomPhieuXuLy);

	/**
	 * Returns the phan nhom ho so ID of this mot cua phieu xu ly phu.
	 *
	 * @return the phan nhom ho so ID of this mot cua phieu xu ly phu
	 */
	public long getPhanNhomHoSoId();

	/**
	 * Sets the phan nhom ho so ID of this mot cua phieu xu ly phu.
	 *
	 * @param phanNhomHoSoId the phan nhom ho so ID of this mot cua phieu xu ly phu
	 */
	public void setPhanNhomHoSoId(long phanNhomHoSoId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(MotCuaPhieuXuLyPhu motCuaPhieuXuLyPhu);

	@Override
	public int hashCode();

	@Override
	public CacheModel<MotCuaPhieuXuLyPhu> toCacheModel();

	@Override
	public MotCuaPhieuXuLyPhu toEscapedModel();

	@Override
	public MotCuaPhieuXuLyPhu toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}