//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.22 at 05:48:47 AM ICT 
//


package vn.dtt.gt.dk.nsw.fac;

import javax.xml.bind.annotation.XmlRegistry;
import vn.dtt.gt.dk.nsw.model.ConfirmCertificateEndorsement;

/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the vn package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ConfirmCertificateEndorsementFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: vn
     * 
     */
    public ConfirmCertificateEndorsementFactory() {
    }

    /**
     * Create an instance of {@link ConfirmCertificateEndorsement }
     * 
     */
    public ConfirmCertificateEndorsement createConfirmCertificateEndorsement() {
        return new ConfirmCertificateEndorsement();
    }

    /**
     * Create an instance of {@link ConfirmCertificateEndorsement.SpecificationList }
     * 
     */
    public ConfirmCertificateEndorsement.SpecificationList createConfirmCertificateEndorsementSpecificationList() {
        return new ConfirmCertificateEndorsement.SpecificationList();
    }

    /**
     * Create an instance of {@link ConfirmCertificateEndorsement.Confirmation }
     * 
     */
    public ConfirmCertificateEndorsement.Confirmation createConfirmCertificateEndorsementConfirmation() {
        return new ConfirmCertificateEndorsement.Confirmation();
    }

    /**
     * Create an instance of {@link ConfirmCertificateEndorsement.Importer }
     * 
     */
    public ConfirmCertificateEndorsement.Importer createConfirmCertificateEndorsementImporter() {
        return new ConfirmCertificateEndorsement.Importer();
    }

    /**
     * Create an instance of {@link ConfirmCertificateEndorsement.ProductionCountry }
     * 
     */
    public ConfirmCertificateEndorsement.ProductionCountry createConfirmCertificateEndorsementProductionCountry() {
        return new ConfirmCertificateEndorsement.ProductionCountry();
    }

    /**
     * Create an instance of {@link ConfirmCertificateEndorsement.CustomDeclaration }
     * 
     */
    public ConfirmCertificateEndorsement.CustomDeclaration createConfirmCertificateEndorsementCustomDeclaration() {
        return new ConfirmCertificateEndorsement.CustomDeclaration();
    }

    /**
     * Create an instance of {@link ConfirmCertificateEndorsement.SafetyTestReport }
     * 
     */
    public ConfirmCertificateEndorsement.SafetyTestReport createConfirmCertificateEndorsementSafetyTestReport() {
        return new ConfirmCertificateEndorsement.SafetyTestReport();
    }

    /**
     * Create an instance of {@link ConfirmCertificateEndorsement.EmissionTestReport }
     * 
     */
    public ConfirmCertificateEndorsement.EmissionTestReport createConfirmCertificateEndorsementEmissionTestReport() {
        return new ConfirmCertificateEndorsement.EmissionTestReport();
    }

    /**
     * Create an instance of {@link ConfirmCertificateEndorsement.COPReport }
     * 
     */
    public ConfirmCertificateEndorsement.COPReport createConfirmCertificateEndorsementCOPReport() {
        return new ConfirmCertificateEndorsement.COPReport();
    }

    /**
     * Create an instance of {@link ConfirmCertificateEndorsement.Circular }
     * 
     */
    public ConfirmCertificateEndorsement.Circular createConfirmCertificateEndorsementCircular() {
        return new ConfirmCertificateEndorsement.Circular();
    }

    /**
     * Create an instance of {@link ConfirmCertificateEndorsement.InspectorSign }
     * 
     */
    public ConfirmCertificateEndorsement.InspectorSign createConfirmCertificateEndorsementInspectorSign() {
        return new ConfirmCertificateEndorsement.InspectorSign();
    }

    /**
     * Create an instance of {@link ConfirmCertificateEndorsement.AttachedFile }
     * 
     */
    public ConfirmCertificateEndorsement.AttachedFile createConfirmCertificateEndorsementAttachedFile() {
        return new ConfirmCertificateEndorsement.AttachedFile();
    }

    /**
     * Create an instance of {@link ConfirmCertificateEndorsement.SpecificationList.SpecItem }
     * 
     */
    public ConfirmCertificateEndorsement.SpecificationList.SpecItem createConfirmCertificateEndorsementSpecificationListSpecItem() {
        return new ConfirmCertificateEndorsement.SpecificationList.SpecItem();
    }

}
