//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.22 at 05:48:10 AM ICT 
//


package vn.dtt.gt.dk.nsw.fac;

import javax.xml.bind.annotation.XmlRegistry;
import vn.dtt.gt.dk.nsw.model.NoticeOfViolation;

/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the vn package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class NoticeOfViolationFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: vn
     * 
     */
    public NoticeOfViolationFactory() {
    }

    /**
     * Create an instance of {@link NoticeOfViolation }
     * 
     */
    public NoticeOfViolation createNoticeOfViolation() {
        return new NoticeOfViolation();
    }

    /**
     * Create an instance of {@link NoticeOfViolation.Importer }
     * 
     */
    public NoticeOfViolation.Importer createNoticeOfViolationImporter() {
        return new NoticeOfViolation.Importer();
    }

    /**
     * Create an instance of {@link NoticeOfViolation.ProductionCountry }
     * 
     */
    public NoticeOfViolation.ProductionCountry createNoticeOfViolationProductionCountry() {
        return new NoticeOfViolation.ProductionCountry();
    }

    /**
     * Create an instance of {@link NoticeOfViolation.CustomDeclaration }
     * 
     */
    public NoticeOfViolation.CustomDeclaration createNoticeOfViolationCustomDeclaration() {
        return new NoticeOfViolation.CustomDeclaration();
    }

    /**
     * Create an instance of {@link NoticeOfViolation.TestReport }
     * 
     */
    public NoticeOfViolation.TestReport createNoticeOfViolationTestReport() {
        return new NoticeOfViolation.TestReport();
    }

    /**
     * Create an instance of {@link NoticeOfViolation.InspectorSign }
     * 
     */
    public NoticeOfViolation.InspectorSign createNoticeOfViolationInspectorSign() {
        return new NoticeOfViolation.InspectorSign();
    }

    /**
     * Create an instance of {@link NoticeOfViolation.AttachedFile }
     * 
     */
    public NoticeOfViolation.AttachedFile createNoticeOfViolationAttachedFile() {
        return new NoticeOfViolation.AttachedFile();
    }

    /**
     * Create an instance of {@link NoticeOfViolation.ImportedVehicle }
     * 
     */
    public NoticeOfViolation.ImportedVehicle createNoticeOfViolationImportedVehicle() {
        return new NoticeOfViolation.ImportedVehicle();
    }

}
