/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.gt.dk.dao.motcua.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import vn.dtt.gt.dk.dao.motcua.model.MotCuaPhieuXuLyPhu;
import vn.dtt.gt.dk.dao.motcua.model.MotCuaPhieuXuLyPhuModel;
import vn.dtt.gt.dk.dao.motcua.model.MotCuaPhieuXuLyPhuSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the MotCuaPhieuXuLyPhu service. Represents a row in the &quot;motcua_phieuxulyphu&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link vn.dtt.gt.dk.dao.motcua.model.MotCuaPhieuXuLyPhuModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MotCuaPhieuXuLyPhuImpl}.
 * </p>
 *
 * @author win_64
 * @see MotCuaPhieuXuLyPhuImpl
 * @see vn.dtt.gt.dk.dao.motcua.model.MotCuaPhieuXuLyPhu
 * @see vn.dtt.gt.dk.dao.motcua.model.MotCuaPhieuXuLyPhuModel
 * @generated
 */
@JSON(strict = true)
public class MotCuaPhieuXuLyPhuModelImpl extends BaseModelImpl<MotCuaPhieuXuLyPhu>
	implements MotCuaPhieuXuLyPhuModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a mot cua phieu xu ly phu model instance should use the {@link vn.dtt.gt.dk.dao.motcua.model.MotCuaPhieuXuLyPhu} interface instead.
	 */
	public static final String TABLE_NAME = "motcua_phieuxulyphu";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id", Types.BIGINT },
			{ "phieuxulychinhid", Types.BIGINT },
			{ "trichyeunoidung", Types.VARCHAR },
			{ "ghichu", Types.VARCHAR },
			{ "trangthaihientaiid", Types.BIGINT },
			{ "noidunghosoid", Types.BIGINT },
			{ "chiemquyenxuly", Types.BIGINT },
			{ "ngaytaophieu", Types.TIMESTAMP },
			{ "nguoitaophieu", Types.BIGINT },
			{ "nhomphieuxuly", Types.VARCHAR },
			{ "phannhomhosoid", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table motcua_phieuxulyphu (id LONG not null primary key,phieuxulychinhid LONG,trichyeunoidung VARCHAR(75) null,ghichu VARCHAR(75) null,trangthaihientaiid LONG,noidunghosoid LONG,chiemquyenxuly LONG,ngaytaophieu DATE null,nguoitaophieu LONG,nhomphieuxuly VARCHAR(75) null,phannhomhosoid LONG)";
	public static final String TABLE_SQL_DROP = "drop table motcua_phieuxulyphu";
	public static final String ORDER_BY_JPQL = " ORDER BY motCuaPhieuXuLyPhu.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY motcua_phieuxulyphu.id ASC";
	public static final String DATA_SOURCE = "tthcDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.vn.dtt.gt.dk.dao.motcua.model.MotCuaPhieuXuLyPhu"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.vn.dtt.gt.dk.dao.motcua.model.MotCuaPhieuXuLyPhu"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.vn.dtt.gt.dk.dao.motcua.model.MotCuaPhieuXuLyPhu"),
			true);
	public static long NHOMPHIEUXULY_COLUMN_BITMASK = 1L;
	public static long NOIDUNGHOSOID_COLUMN_BITMASK = 2L;
	public static long PHANNHOMHOSOID_COLUMN_BITMASK = 4L;
	public static long PHIEUXULYCHINHID_COLUMN_BITMASK = 8L;
	public static long TRANGTHAIHIENTAIID_COLUMN_BITMASK = 16L;
	public static long ID_COLUMN_BITMASK = 32L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static MotCuaPhieuXuLyPhu toModel(MotCuaPhieuXuLyPhuSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		MotCuaPhieuXuLyPhu model = new MotCuaPhieuXuLyPhuImpl();

		model.setId(soapModel.getId());
		model.setPhieuXuLyChinhId(soapModel.getPhieuXuLyChinhId());
		model.setTrichYeuNoiDung(soapModel.getTrichYeuNoiDung());
		model.setGhiChu(soapModel.getGhiChu());
		model.setTrangThaiHienTaiId(soapModel.getTrangThaiHienTaiId());
		model.setNoiDungHoSoId(soapModel.getNoiDungHoSoId());
		model.setChiemQuyenXuLy(soapModel.getChiemQuyenXuLy());
		model.setNgayTaoPhieu(soapModel.getNgayTaoPhieu());
		model.setNguoiTaoPhieu(soapModel.getNguoiTaoPhieu());
		model.setNhomPhieuXuLy(soapModel.getNhomPhieuXuLy());
		model.setPhanNhomHoSoId(soapModel.getPhanNhomHoSoId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<MotCuaPhieuXuLyPhu> toModels(
		MotCuaPhieuXuLyPhuSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<MotCuaPhieuXuLyPhu> models = new ArrayList<MotCuaPhieuXuLyPhu>(soapModels.length);

		for (MotCuaPhieuXuLyPhuSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.vn.dtt.gt.dk.dao.motcua.model.MotCuaPhieuXuLyPhu"));

	public MotCuaPhieuXuLyPhuModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return MotCuaPhieuXuLyPhu.class;
	}

	@Override
	public String getModelClassName() {
		return MotCuaPhieuXuLyPhu.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("phieuXuLyChinhId", getPhieuXuLyChinhId());
		attributes.put("trichYeuNoiDung", getTrichYeuNoiDung());
		attributes.put("ghiChu", getGhiChu());
		attributes.put("trangThaiHienTaiId", getTrangThaiHienTaiId());
		attributes.put("noiDungHoSoId", getNoiDungHoSoId());
		attributes.put("chiemQuyenXuLy", getChiemQuyenXuLy());
		attributes.put("ngayTaoPhieu", getNgayTaoPhieu());
		attributes.put("nguoiTaoPhieu", getNguoiTaoPhieu());
		attributes.put("nhomPhieuXuLy", getNhomPhieuXuLy());
		attributes.put("phanNhomHoSoId", getPhanNhomHoSoId());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id = (Long)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		Long phieuXuLyChinhId = (Long)attributes.get("phieuXuLyChinhId");

		if (phieuXuLyChinhId != null) {
			setPhieuXuLyChinhId(phieuXuLyChinhId);
		}

		String trichYeuNoiDung = (String)attributes.get("trichYeuNoiDung");

		if (trichYeuNoiDung != null) {
			setTrichYeuNoiDung(trichYeuNoiDung);
		}

		String ghiChu = (String)attributes.get("ghiChu");

		if (ghiChu != null) {
			setGhiChu(ghiChu);
		}

		Long trangThaiHienTaiId = (Long)attributes.get("trangThaiHienTaiId");

		if (trangThaiHienTaiId != null) {
			setTrangThaiHienTaiId(trangThaiHienTaiId);
		}

		Long noiDungHoSoId = (Long)attributes.get("noiDungHoSoId");

		if (noiDungHoSoId != null) {
			setNoiDungHoSoId(noiDungHoSoId);
		}

		Long chiemQuyenXuLy = (Long)attributes.get("chiemQuyenXuLy");

		if (chiemQuyenXuLy != null) {
			setChiemQuyenXuLy(chiemQuyenXuLy);
		}

		Date ngayTaoPhieu = (Date)attributes.get("ngayTaoPhieu");

		if (ngayTaoPhieu != null) {
			setNgayTaoPhieu(ngayTaoPhieu);
		}

		Long nguoiTaoPhieu = (Long)attributes.get("nguoiTaoPhieu");

		if (nguoiTaoPhieu != null) {
			setNguoiTaoPhieu(nguoiTaoPhieu);
		}

		String nhomPhieuXuLy = (String)attributes.get("nhomPhieuXuLy");

		if (nhomPhieuXuLy != null) {
			setNhomPhieuXuLy(nhomPhieuXuLy);
		}

		Long phanNhomHoSoId = (Long)attributes.get("phanNhomHoSoId");

		if (phanNhomHoSoId != null) {
			setPhanNhomHoSoId(phanNhomHoSoId);
		}
	}

	@JSON
	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		_columnBitmask = -1L;

		_id = id;
	}

	@JSON
	@Override
	public long getPhieuXuLyChinhId() {
		return _phieuXuLyChinhId;
	}

	@Override
	public void setPhieuXuLyChinhId(long phieuXuLyChinhId) {
		_columnBitmask |= PHIEUXULYCHINHID_COLUMN_BITMASK;

		if (!_setOriginalPhieuXuLyChinhId) {
			_setOriginalPhieuXuLyChinhId = true;

			_originalPhieuXuLyChinhId = _phieuXuLyChinhId;
		}

		_phieuXuLyChinhId = phieuXuLyChinhId;
	}

	public long getOriginalPhieuXuLyChinhId() {
		return _originalPhieuXuLyChinhId;
	}

	@JSON
	@Override
	public String getTrichYeuNoiDung() {
		if (_trichYeuNoiDung == null) {
			return StringPool.BLANK;
		}
		else {
			return _trichYeuNoiDung;
		}
	}

	@Override
	public void setTrichYeuNoiDung(String trichYeuNoiDung) {
		_trichYeuNoiDung = trichYeuNoiDung;
	}

	@JSON
	@Override
	public String getGhiChu() {
		if (_ghiChu == null) {
			return StringPool.BLANK;
		}
		else {
			return _ghiChu;
		}
	}

	@Override
	public void setGhiChu(String ghiChu) {
		_ghiChu = ghiChu;
	}

	@JSON
	@Override
	public long getTrangThaiHienTaiId() {
		return _trangThaiHienTaiId;
	}

	@Override
	public void setTrangThaiHienTaiId(long trangThaiHienTaiId) {
		_columnBitmask |= TRANGTHAIHIENTAIID_COLUMN_BITMASK;

		if (!_setOriginalTrangThaiHienTaiId) {
			_setOriginalTrangThaiHienTaiId = true;

			_originalTrangThaiHienTaiId = _trangThaiHienTaiId;
		}

		_trangThaiHienTaiId = trangThaiHienTaiId;
	}

	public long getOriginalTrangThaiHienTaiId() {
		return _originalTrangThaiHienTaiId;
	}

	@JSON
	@Override
	public long getNoiDungHoSoId() {
		return _noiDungHoSoId;
	}

	@Override
	public void setNoiDungHoSoId(long noiDungHoSoId) {
		_columnBitmask |= NOIDUNGHOSOID_COLUMN_BITMASK;

		if (!_setOriginalNoiDungHoSoId) {
			_setOriginalNoiDungHoSoId = true;

			_originalNoiDungHoSoId = _noiDungHoSoId;
		}

		_noiDungHoSoId = noiDungHoSoId;
	}

	public long getOriginalNoiDungHoSoId() {
		return _originalNoiDungHoSoId;
	}

	@JSON
	@Override
	public long getChiemQuyenXuLy() {
		return _chiemQuyenXuLy;
	}

	@Override
	public void setChiemQuyenXuLy(long chiemQuyenXuLy) {
		_chiemQuyenXuLy = chiemQuyenXuLy;
	}

	@JSON
	@Override
	public Date getNgayTaoPhieu() {
		return _ngayTaoPhieu;
	}

	@Override
	public void setNgayTaoPhieu(Date ngayTaoPhieu) {
		_ngayTaoPhieu = ngayTaoPhieu;
	}

	@JSON
	@Override
	public long getNguoiTaoPhieu() {
		return _nguoiTaoPhieu;
	}

	@Override
	public void setNguoiTaoPhieu(long nguoiTaoPhieu) {
		_nguoiTaoPhieu = nguoiTaoPhieu;
	}

	@JSON
	@Override
	public String getNhomPhieuXuLy() {
		if (_nhomPhieuXuLy == null) {
			return StringPool.BLANK;
		}
		else {
			return _nhomPhieuXuLy;
		}
	}

	@Override
	public void setNhomPhieuXuLy(String nhomPhieuXuLy) {
		_columnBitmask |= NHOMPHIEUXULY_COLUMN_BITMASK;

		if (_originalNhomPhieuXuLy == null) {
			_originalNhomPhieuXuLy = _nhomPhieuXuLy;
		}

		_nhomPhieuXuLy = nhomPhieuXuLy;
	}

	public String getOriginalNhomPhieuXuLy() {
		return GetterUtil.getString(_originalNhomPhieuXuLy);
	}

	@JSON
	@Override
	public long getPhanNhomHoSoId() {
		return _phanNhomHoSoId;
	}

	@Override
	public void setPhanNhomHoSoId(long phanNhomHoSoId) {
		_columnBitmask |= PHANNHOMHOSOID_COLUMN_BITMASK;

		if (!_setOriginalPhanNhomHoSoId) {
			_setOriginalPhanNhomHoSoId = true;

			_originalPhanNhomHoSoId = _phanNhomHoSoId;
		}

		_phanNhomHoSoId = phanNhomHoSoId;
	}

	public long getOriginalPhanNhomHoSoId() {
		return _originalPhanNhomHoSoId;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			MotCuaPhieuXuLyPhu.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public MotCuaPhieuXuLyPhu toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (MotCuaPhieuXuLyPhu)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		MotCuaPhieuXuLyPhuImpl motCuaPhieuXuLyPhuImpl = new MotCuaPhieuXuLyPhuImpl();

		motCuaPhieuXuLyPhuImpl.setId(getId());
		motCuaPhieuXuLyPhuImpl.setPhieuXuLyChinhId(getPhieuXuLyChinhId());
		motCuaPhieuXuLyPhuImpl.setTrichYeuNoiDung(getTrichYeuNoiDung());
		motCuaPhieuXuLyPhuImpl.setGhiChu(getGhiChu());
		motCuaPhieuXuLyPhuImpl.setTrangThaiHienTaiId(getTrangThaiHienTaiId());
		motCuaPhieuXuLyPhuImpl.setNoiDungHoSoId(getNoiDungHoSoId());
		motCuaPhieuXuLyPhuImpl.setChiemQuyenXuLy(getChiemQuyenXuLy());
		motCuaPhieuXuLyPhuImpl.setNgayTaoPhieu(getNgayTaoPhieu());
		motCuaPhieuXuLyPhuImpl.setNguoiTaoPhieu(getNguoiTaoPhieu());
		motCuaPhieuXuLyPhuImpl.setNhomPhieuXuLy(getNhomPhieuXuLy());
		motCuaPhieuXuLyPhuImpl.setPhanNhomHoSoId(getPhanNhomHoSoId());

		motCuaPhieuXuLyPhuImpl.resetOriginalValues();

		return motCuaPhieuXuLyPhuImpl;
	}

	@Override
	public int compareTo(MotCuaPhieuXuLyPhu motCuaPhieuXuLyPhu) {
		int value = 0;

		if (getId() < motCuaPhieuXuLyPhu.getId()) {
			value = -1;
		}
		else if (getId() > motCuaPhieuXuLyPhu.getId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof MotCuaPhieuXuLyPhu)) {
			return false;
		}

		MotCuaPhieuXuLyPhu motCuaPhieuXuLyPhu = (MotCuaPhieuXuLyPhu)obj;

		long primaryKey = motCuaPhieuXuLyPhu.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		MotCuaPhieuXuLyPhuModelImpl motCuaPhieuXuLyPhuModelImpl = this;

		motCuaPhieuXuLyPhuModelImpl._originalPhieuXuLyChinhId = motCuaPhieuXuLyPhuModelImpl._phieuXuLyChinhId;

		motCuaPhieuXuLyPhuModelImpl._setOriginalPhieuXuLyChinhId = false;

		motCuaPhieuXuLyPhuModelImpl._originalTrangThaiHienTaiId = motCuaPhieuXuLyPhuModelImpl._trangThaiHienTaiId;

		motCuaPhieuXuLyPhuModelImpl._setOriginalTrangThaiHienTaiId = false;

		motCuaPhieuXuLyPhuModelImpl._originalNoiDungHoSoId = motCuaPhieuXuLyPhuModelImpl._noiDungHoSoId;

		motCuaPhieuXuLyPhuModelImpl._setOriginalNoiDungHoSoId = false;

		motCuaPhieuXuLyPhuModelImpl._originalNhomPhieuXuLy = motCuaPhieuXuLyPhuModelImpl._nhomPhieuXuLy;

		motCuaPhieuXuLyPhuModelImpl._originalPhanNhomHoSoId = motCuaPhieuXuLyPhuModelImpl._phanNhomHoSoId;

		motCuaPhieuXuLyPhuModelImpl._setOriginalPhanNhomHoSoId = false;

		motCuaPhieuXuLyPhuModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<MotCuaPhieuXuLyPhu> toCacheModel() {
		MotCuaPhieuXuLyPhuCacheModel motCuaPhieuXuLyPhuCacheModel = new MotCuaPhieuXuLyPhuCacheModel();

		motCuaPhieuXuLyPhuCacheModel.id = getId();

		motCuaPhieuXuLyPhuCacheModel.phieuXuLyChinhId = getPhieuXuLyChinhId();

		motCuaPhieuXuLyPhuCacheModel.trichYeuNoiDung = getTrichYeuNoiDung();

		String trichYeuNoiDung = motCuaPhieuXuLyPhuCacheModel.trichYeuNoiDung;

		if ((trichYeuNoiDung != null) && (trichYeuNoiDung.length() == 0)) {
			motCuaPhieuXuLyPhuCacheModel.trichYeuNoiDung = null;
		}

		motCuaPhieuXuLyPhuCacheModel.ghiChu = getGhiChu();

		String ghiChu = motCuaPhieuXuLyPhuCacheModel.ghiChu;

		if ((ghiChu != null) && (ghiChu.length() == 0)) {
			motCuaPhieuXuLyPhuCacheModel.ghiChu = null;
		}

		motCuaPhieuXuLyPhuCacheModel.trangThaiHienTaiId = getTrangThaiHienTaiId();

		motCuaPhieuXuLyPhuCacheModel.noiDungHoSoId = getNoiDungHoSoId();

		motCuaPhieuXuLyPhuCacheModel.chiemQuyenXuLy = getChiemQuyenXuLy();

		Date ngayTaoPhieu = getNgayTaoPhieu();

		if (ngayTaoPhieu != null) {
			motCuaPhieuXuLyPhuCacheModel.ngayTaoPhieu = ngayTaoPhieu.getTime();
		}
		else {
			motCuaPhieuXuLyPhuCacheModel.ngayTaoPhieu = Long.MIN_VALUE;
		}

		motCuaPhieuXuLyPhuCacheModel.nguoiTaoPhieu = getNguoiTaoPhieu();

		motCuaPhieuXuLyPhuCacheModel.nhomPhieuXuLy = getNhomPhieuXuLy();

		String nhomPhieuXuLy = motCuaPhieuXuLyPhuCacheModel.nhomPhieuXuLy;

		if ((nhomPhieuXuLy != null) && (nhomPhieuXuLy.length() == 0)) {
			motCuaPhieuXuLyPhuCacheModel.nhomPhieuXuLy = null;
		}

		motCuaPhieuXuLyPhuCacheModel.phanNhomHoSoId = getPhanNhomHoSoId();

		return motCuaPhieuXuLyPhuCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(23);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", phieuXuLyChinhId=");
		sb.append(getPhieuXuLyChinhId());
		sb.append(", trichYeuNoiDung=");
		sb.append(getTrichYeuNoiDung());
		sb.append(", ghiChu=");
		sb.append(getGhiChu());
		sb.append(", trangThaiHienTaiId=");
		sb.append(getTrangThaiHienTaiId());
		sb.append(", noiDungHoSoId=");
		sb.append(getNoiDungHoSoId());
		sb.append(", chiemQuyenXuLy=");
		sb.append(getChiemQuyenXuLy());
		sb.append(", ngayTaoPhieu=");
		sb.append(getNgayTaoPhieu());
		sb.append(", nguoiTaoPhieu=");
		sb.append(getNguoiTaoPhieu());
		sb.append(", nhomPhieuXuLy=");
		sb.append(getNhomPhieuXuLy());
		sb.append(", phanNhomHoSoId=");
		sb.append(getPhanNhomHoSoId());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(37);

		sb.append("<model><model-name>");
		sb.append("vn.dtt.gt.dk.dao.motcua.model.MotCuaPhieuXuLyPhu");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>phieuXuLyChinhId</column-name><column-value><![CDATA[");
		sb.append(getPhieuXuLyChinhId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>trichYeuNoiDung</column-name><column-value><![CDATA[");
		sb.append(getTrichYeuNoiDung());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ghiChu</column-name><column-value><![CDATA[");
		sb.append(getGhiChu());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>trangThaiHienTaiId</column-name><column-value><![CDATA[");
		sb.append(getTrangThaiHienTaiId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>noiDungHoSoId</column-name><column-value><![CDATA[");
		sb.append(getNoiDungHoSoId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>chiemQuyenXuLy</column-name><column-value><![CDATA[");
		sb.append(getChiemQuyenXuLy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayTaoPhieu</column-name><column-value><![CDATA[");
		sb.append(getNgayTaoPhieu());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nguoiTaoPhieu</column-name><column-value><![CDATA[");
		sb.append(getNguoiTaoPhieu());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nhomPhieuXuLy</column-name><column-value><![CDATA[");
		sb.append(getNhomPhieuXuLy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>phanNhomHoSoId</column-name><column-value><![CDATA[");
		sb.append(getPhanNhomHoSoId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = MotCuaPhieuXuLyPhu.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			MotCuaPhieuXuLyPhu.class
		};
	private long _id;
	private long _phieuXuLyChinhId;
	private long _originalPhieuXuLyChinhId;
	private boolean _setOriginalPhieuXuLyChinhId;
	private String _trichYeuNoiDung;
	private String _ghiChu;
	private long _trangThaiHienTaiId;
	private long _originalTrangThaiHienTaiId;
	private boolean _setOriginalTrangThaiHienTaiId;
	private long _noiDungHoSoId;
	private long _originalNoiDungHoSoId;
	private boolean _setOriginalNoiDungHoSoId;
	private long _chiemQuyenXuLy;
	private Date _ngayTaoPhieu;
	private long _nguoiTaoPhieu;
	private String _nhomPhieuXuLy;
	private String _originalNhomPhieuXuLy;
	private long _phanNhomHoSoId;
	private long _originalPhanNhomHoSoId;
	private boolean _setOriginalPhanNhomHoSoId;
	private long _columnBitmask;
	private MotCuaPhieuXuLyPhu _escapedModel;
}