/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.gt.dk.dao.motcua.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import vn.dtt.gt.dk.dao.motcua.model.MotCuaQuyTrinhThuTuc;
import vn.dtt.gt.dk.dao.motcua.model.MotCuaQuyTrinhThuTucModel;
import vn.dtt.gt.dk.dao.motcua.model.MotCuaQuyTrinhThuTucSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the MotCuaQuyTrinhThuTuc service. Represents a row in the &quot;motcua_quytrinhthutuc&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link vn.dtt.gt.dk.dao.motcua.model.MotCuaQuyTrinhThuTucModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MotCuaQuyTrinhThuTucImpl}.
 * </p>
 *
 * @author win_64
 * @see MotCuaQuyTrinhThuTucImpl
 * @see vn.dtt.gt.dk.dao.motcua.model.MotCuaQuyTrinhThuTuc
 * @see vn.dtt.gt.dk.dao.motcua.model.MotCuaQuyTrinhThuTucModel
 * @generated
 */
@JSON(strict = true)
public class MotCuaQuyTrinhThuTucModelImpl extends BaseModelImpl<MotCuaQuyTrinhThuTuc>
	implements MotCuaQuyTrinhThuTucModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a mot cua quy trinh thu tuc model instance should use the {@link vn.dtt.gt.dk.dao.motcua.model.MotCuaQuyTrinhThuTuc} interface instead.
	 */
	public static final String TABLE_NAME = "motcua_quytrinhthutuc";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id", Types.BIGINT },
			{ "thutuchanhchinhid", Types.BIGINT },
			{ "maquytrinh", Types.VARCHAR },
			{ "tochucxuly", Types.BIGINT },
			{ "songayxuly", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table motcua_quytrinhthutuc (id LONG not null primary key,thutuchanhchinhid LONG,maquytrinh VARCHAR(75) null,tochucxuly LONG,songayxuly LONG)";
	public static final String TABLE_SQL_DROP = "drop table motcua_quytrinhthutuc";
	public static final String ORDER_BY_JPQL = " ORDER BY motCuaQuyTrinhThuTuc.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY motcua_quytrinhthutuc.id ASC";
	public static final String DATA_SOURCE = "tthcDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.vn.dtt.gt.dk.dao.motcua.model.MotCuaQuyTrinhThuTuc"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.vn.dtt.gt.dk.dao.motcua.model.MotCuaQuyTrinhThuTuc"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.vn.dtt.gt.dk.dao.motcua.model.MotCuaQuyTrinhThuTuc"),
			true);
	public static long THUTUCHANHCHINHID_COLUMN_BITMASK = 1L;
	public static long TOCHUCXULY_COLUMN_BITMASK = 2L;
	public static long ID_COLUMN_BITMASK = 4L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static MotCuaQuyTrinhThuTuc toModel(
		MotCuaQuyTrinhThuTucSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		MotCuaQuyTrinhThuTuc model = new MotCuaQuyTrinhThuTucImpl();

		model.setId(soapModel.getId());
		model.setThuTucHanhChinhId(soapModel.getThuTucHanhChinhId());
		model.setMaQuyTrinh(soapModel.getMaQuyTrinh());
		model.setToChucXuLy(soapModel.getToChucXuLy());
		model.setSoNgayXuLy(soapModel.getSoNgayXuLy());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<MotCuaQuyTrinhThuTuc> toModels(
		MotCuaQuyTrinhThuTucSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<MotCuaQuyTrinhThuTuc> models = new ArrayList<MotCuaQuyTrinhThuTuc>(soapModels.length);

		for (MotCuaQuyTrinhThuTucSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.vn.dtt.gt.dk.dao.motcua.model.MotCuaQuyTrinhThuTuc"));

	public MotCuaQuyTrinhThuTucModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return MotCuaQuyTrinhThuTuc.class;
	}

	@Override
	public String getModelClassName() {
		return MotCuaQuyTrinhThuTuc.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("thuTucHanhChinhId", getThuTucHanhChinhId());
		attributes.put("maQuyTrinh", getMaQuyTrinh());
		attributes.put("toChucXuLy", getToChucXuLy());
		attributes.put("soNgayXuLy", getSoNgayXuLy());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id = (Long)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		Long thuTucHanhChinhId = (Long)attributes.get("thuTucHanhChinhId");

		if (thuTucHanhChinhId != null) {
			setThuTucHanhChinhId(thuTucHanhChinhId);
		}

		String maQuyTrinh = (String)attributes.get("maQuyTrinh");

		if (maQuyTrinh != null) {
			setMaQuyTrinh(maQuyTrinh);
		}

		Long toChucXuLy = (Long)attributes.get("toChucXuLy");

		if (toChucXuLy != null) {
			setToChucXuLy(toChucXuLy);
		}

		Long soNgayXuLy = (Long)attributes.get("soNgayXuLy");

		if (soNgayXuLy != null) {
			setSoNgayXuLy(soNgayXuLy);
		}
	}

	@JSON
	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		_columnBitmask = -1L;

		_id = id;
	}

	@JSON
	@Override
	public long getThuTucHanhChinhId() {
		return _thuTucHanhChinhId;
	}

	@Override
	public void setThuTucHanhChinhId(long thuTucHanhChinhId) {
		_columnBitmask |= THUTUCHANHCHINHID_COLUMN_BITMASK;

		if (!_setOriginalThuTucHanhChinhId) {
			_setOriginalThuTucHanhChinhId = true;

			_originalThuTucHanhChinhId = _thuTucHanhChinhId;
		}

		_thuTucHanhChinhId = thuTucHanhChinhId;
	}

	public long getOriginalThuTucHanhChinhId() {
		return _originalThuTucHanhChinhId;
	}

	@JSON
	@Override
	public String getMaQuyTrinh() {
		if (_maQuyTrinh == null) {
			return StringPool.BLANK;
		}
		else {
			return _maQuyTrinh;
		}
	}

	@Override
	public void setMaQuyTrinh(String maQuyTrinh) {
		_maQuyTrinh = maQuyTrinh;
	}

	@JSON
	@Override
	public long getToChucXuLy() {
		return _toChucXuLy;
	}

	@Override
	public void setToChucXuLy(long toChucXuLy) {
		_columnBitmask |= TOCHUCXULY_COLUMN_BITMASK;

		if (!_setOriginalToChucXuLy) {
			_setOriginalToChucXuLy = true;

			_originalToChucXuLy = _toChucXuLy;
		}

		_toChucXuLy = toChucXuLy;
	}

	public long getOriginalToChucXuLy() {
		return _originalToChucXuLy;
	}

	@JSON
	@Override
	public long getSoNgayXuLy() {
		return _soNgayXuLy;
	}

	@Override
	public void setSoNgayXuLy(long soNgayXuLy) {
		_soNgayXuLy = soNgayXuLy;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			MotCuaQuyTrinhThuTuc.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public MotCuaQuyTrinhThuTuc toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (MotCuaQuyTrinhThuTuc)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		MotCuaQuyTrinhThuTucImpl motCuaQuyTrinhThuTucImpl = new MotCuaQuyTrinhThuTucImpl();

		motCuaQuyTrinhThuTucImpl.setId(getId());
		motCuaQuyTrinhThuTucImpl.setThuTucHanhChinhId(getThuTucHanhChinhId());
		motCuaQuyTrinhThuTucImpl.setMaQuyTrinh(getMaQuyTrinh());
		motCuaQuyTrinhThuTucImpl.setToChucXuLy(getToChucXuLy());
		motCuaQuyTrinhThuTucImpl.setSoNgayXuLy(getSoNgayXuLy());

		motCuaQuyTrinhThuTucImpl.resetOriginalValues();

		return motCuaQuyTrinhThuTucImpl;
	}

	@Override
	public int compareTo(MotCuaQuyTrinhThuTuc motCuaQuyTrinhThuTuc) {
		int value = 0;

		if (getId() < motCuaQuyTrinhThuTuc.getId()) {
			value = -1;
		}
		else if (getId() > motCuaQuyTrinhThuTuc.getId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof MotCuaQuyTrinhThuTuc)) {
			return false;
		}

		MotCuaQuyTrinhThuTuc motCuaQuyTrinhThuTuc = (MotCuaQuyTrinhThuTuc)obj;

		long primaryKey = motCuaQuyTrinhThuTuc.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		MotCuaQuyTrinhThuTucModelImpl motCuaQuyTrinhThuTucModelImpl = this;

		motCuaQuyTrinhThuTucModelImpl._originalThuTucHanhChinhId = motCuaQuyTrinhThuTucModelImpl._thuTucHanhChinhId;

		motCuaQuyTrinhThuTucModelImpl._setOriginalThuTucHanhChinhId = false;

		motCuaQuyTrinhThuTucModelImpl._originalToChucXuLy = motCuaQuyTrinhThuTucModelImpl._toChucXuLy;

		motCuaQuyTrinhThuTucModelImpl._setOriginalToChucXuLy = false;

		motCuaQuyTrinhThuTucModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<MotCuaQuyTrinhThuTuc> toCacheModel() {
		MotCuaQuyTrinhThuTucCacheModel motCuaQuyTrinhThuTucCacheModel = new MotCuaQuyTrinhThuTucCacheModel();

		motCuaQuyTrinhThuTucCacheModel.id = getId();

		motCuaQuyTrinhThuTucCacheModel.thuTucHanhChinhId = getThuTucHanhChinhId();

		motCuaQuyTrinhThuTucCacheModel.maQuyTrinh = getMaQuyTrinh();

		String maQuyTrinh = motCuaQuyTrinhThuTucCacheModel.maQuyTrinh;

		if ((maQuyTrinh != null) && (maQuyTrinh.length() == 0)) {
			motCuaQuyTrinhThuTucCacheModel.maQuyTrinh = null;
		}

		motCuaQuyTrinhThuTucCacheModel.toChucXuLy = getToChucXuLy();

		motCuaQuyTrinhThuTucCacheModel.soNgayXuLy = getSoNgayXuLy();

		return motCuaQuyTrinhThuTucCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(11);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", thuTucHanhChinhId=");
		sb.append(getThuTucHanhChinhId());
		sb.append(", maQuyTrinh=");
		sb.append(getMaQuyTrinh());
		sb.append(", toChucXuLy=");
		sb.append(getToChucXuLy());
		sb.append(", soNgayXuLy=");
		sb.append(getSoNgayXuLy());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(19);

		sb.append("<model><model-name>");
		sb.append("vn.dtt.gt.dk.dao.motcua.model.MotCuaQuyTrinhThuTuc");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>thuTucHanhChinhId</column-name><column-value><![CDATA[");
		sb.append(getThuTucHanhChinhId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>maQuyTrinh</column-name><column-value><![CDATA[");
		sb.append(getMaQuyTrinh());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>toChucXuLy</column-name><column-value><![CDATA[");
		sb.append(getToChucXuLy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>soNgayXuLy</column-name><column-value><![CDATA[");
		sb.append(getSoNgayXuLy());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = MotCuaQuyTrinhThuTuc.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			MotCuaQuyTrinhThuTuc.class
		};
	private long _id;
	private long _thuTucHanhChinhId;
	private long _originalThuTucHanhChinhId;
	private boolean _setOriginalThuTucHanhChinhId;
	private String _maQuyTrinh;
	private long _toChucXuLy;
	private long _originalToChucXuLy;
	private boolean _setOriginalToChucXuLy;
	private long _soNgayXuLy;
	private long _columnBitmask;
	private MotCuaQuyTrinhThuTuc _escapedModel;
}