/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.gt.dk.dao.motcua.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import vn.dtt.gt.dk.dao.motcua.model.MotCuaDienBienHoSo;
import vn.dtt.gt.dk.dao.motcua.model.MotCuaDienBienHoSoModel;
import vn.dtt.gt.dk.dao.motcua.model.MotCuaDienBienHoSoSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the MotCuaDienBienHoSo service. Represents a row in the &quot;motcua_dienbienhoso&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link vn.dtt.gt.dk.dao.motcua.model.MotCuaDienBienHoSoModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MotCuaDienBienHoSoImpl}.
 * </p>
 *
 * @author win_64
 * @see MotCuaDienBienHoSoImpl
 * @see vn.dtt.gt.dk.dao.motcua.model.MotCuaDienBienHoSo
 * @see vn.dtt.gt.dk.dao.motcua.model.MotCuaDienBienHoSoModel
 * @generated
 */
@JSON(strict = true)
public class MotCuaDienBienHoSoModelImpl extends BaseModelImpl<MotCuaDienBienHoSo>
	implements MotCuaDienBienHoSoModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a mot cua dien bien ho so model instance should use the {@link vn.dtt.gt.dk.dao.motcua.model.MotCuaDienBienHoSo} interface instead.
	 */
	public static final String TABLE_NAME = "motcua_dienbienhoso";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id", Types.BIGINT },
			{ "phieuxulychinhid", Types.BIGINT },
			{ "phieuxulyphuid", Types.BIGINT },
			{ "songayquahan", Types.INTEGER },
			{ "trangthaitruocid", Types.BIGINT },
			{ "trangthaisauid", Types.BIGINT },
			{ "ngayxuly", Types.TIMESTAMP },
			{ "nguoixuly", Types.BIGINT },
			{ "hanhdongxuly", Types.VARCHAR },
			{ "synchdate", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table motcua_dienbienhoso (id LONG not null primary key,phieuxulychinhid LONG,phieuxulyphuid LONG,songayquahan INTEGER,trangthaitruocid LONG,trangthaisauid LONG,ngayxuly DATE null,nguoixuly LONG,hanhdongxuly VARCHAR(75) null,synchdate DATE null)";
	public static final String TABLE_SQL_DROP = "drop table motcua_dienbienhoso";
	public static final String ORDER_BY_JPQL = " ORDER BY motCuaDienBienHoSo.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY motcua_dienbienhoso.id ASC";
	public static final String DATA_SOURCE = "tthcDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.vn.dtt.gt.dk.dao.motcua.model.MotCuaDienBienHoSo"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.vn.dtt.gt.dk.dao.motcua.model.MotCuaDienBienHoSo"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.vn.dtt.gt.dk.dao.motcua.model.MotCuaDienBienHoSo"),
			true);
	public static long NGUOIXULY_COLUMN_BITMASK = 1L;
	public static long PHIEUXULYCHINHID_COLUMN_BITMASK = 2L;
	public static long PHIEUXULYPHUID_COLUMN_BITMASK = 4L;
	public static long TRANGTHAISAUID_COLUMN_BITMASK = 8L;
	public static long TRANGTHAITRUOCID_COLUMN_BITMASK = 16L;
	public static long ID_COLUMN_BITMASK = 32L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static MotCuaDienBienHoSo toModel(MotCuaDienBienHoSoSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		MotCuaDienBienHoSo model = new MotCuaDienBienHoSoImpl();

		model.setId(soapModel.getId());
		model.setPhieuXuLyChinhId(soapModel.getPhieuXuLyChinhId());
		model.setPhieuXuLyPhuId(soapModel.getPhieuXuLyPhuId());
		model.setSoNgayQuaHan(soapModel.getSoNgayQuaHan());
		model.setTrangThaiTruocId(soapModel.getTrangThaiTruocId());
		model.setTrangThaiSauId(soapModel.getTrangThaiSauId());
		model.setNgayXuLy(soapModel.getNgayXuLy());
		model.setNguoiXuLy(soapModel.getNguoiXuLy());
		model.setHanhDongXuLy(soapModel.getHanhDongXuLy());
		model.setSynchDate(soapModel.getSynchDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<MotCuaDienBienHoSo> toModels(
		MotCuaDienBienHoSoSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<MotCuaDienBienHoSo> models = new ArrayList<MotCuaDienBienHoSo>(soapModels.length);

		for (MotCuaDienBienHoSoSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.vn.dtt.gt.dk.dao.motcua.model.MotCuaDienBienHoSo"));

	public MotCuaDienBienHoSoModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return MotCuaDienBienHoSo.class;
	}

	@Override
	public String getModelClassName() {
		return MotCuaDienBienHoSo.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("phieuXuLyChinhId", getPhieuXuLyChinhId());
		attributes.put("phieuXuLyPhuId", getPhieuXuLyPhuId());
		attributes.put("soNgayQuaHan", getSoNgayQuaHan());
		attributes.put("trangThaiTruocId", getTrangThaiTruocId());
		attributes.put("trangThaiSauId", getTrangThaiSauId());
		attributes.put("ngayXuLy", getNgayXuLy());
		attributes.put("nguoiXuLy", getNguoiXuLy());
		attributes.put("hanhDongXuLy", getHanhDongXuLy());
		attributes.put("SynchDate", getSynchDate());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id = (Long)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		Long phieuXuLyChinhId = (Long)attributes.get("phieuXuLyChinhId");

		if (phieuXuLyChinhId != null) {
			setPhieuXuLyChinhId(phieuXuLyChinhId);
		}

		Long phieuXuLyPhuId = (Long)attributes.get("phieuXuLyPhuId");

		if (phieuXuLyPhuId != null) {
			setPhieuXuLyPhuId(phieuXuLyPhuId);
		}

		Integer soNgayQuaHan = (Integer)attributes.get("soNgayQuaHan");

		if (soNgayQuaHan != null) {
			setSoNgayQuaHan(soNgayQuaHan);
		}

		Long trangThaiTruocId = (Long)attributes.get("trangThaiTruocId");

		if (trangThaiTruocId != null) {
			setTrangThaiTruocId(trangThaiTruocId);
		}

		Long trangThaiSauId = (Long)attributes.get("trangThaiSauId");

		if (trangThaiSauId != null) {
			setTrangThaiSauId(trangThaiSauId);
		}

		Date ngayXuLy = (Date)attributes.get("ngayXuLy");

		if (ngayXuLy != null) {
			setNgayXuLy(ngayXuLy);
		}

		Long nguoiXuLy = (Long)attributes.get("nguoiXuLy");

		if (nguoiXuLy != null) {
			setNguoiXuLy(nguoiXuLy);
		}

		String hanhDongXuLy = (String)attributes.get("hanhDongXuLy");

		if (hanhDongXuLy != null) {
			setHanhDongXuLy(hanhDongXuLy);
		}

		Date SynchDate = (Date)attributes.get("SynchDate");

		if (SynchDate != null) {
			setSynchDate(SynchDate);
		}
	}

	@JSON
	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		_columnBitmask = -1L;

		_id = id;
	}

	@JSON
	@Override
	public long getPhieuXuLyChinhId() {
		return _phieuXuLyChinhId;
	}

	@Override
	public void setPhieuXuLyChinhId(long phieuXuLyChinhId) {
		_columnBitmask |= PHIEUXULYCHINHID_COLUMN_BITMASK;

		if (!_setOriginalPhieuXuLyChinhId) {
			_setOriginalPhieuXuLyChinhId = true;

			_originalPhieuXuLyChinhId = _phieuXuLyChinhId;
		}

		_phieuXuLyChinhId = phieuXuLyChinhId;
	}

	public long getOriginalPhieuXuLyChinhId() {
		return _originalPhieuXuLyChinhId;
	}

	@JSON
	@Override
	public long getPhieuXuLyPhuId() {
		return _phieuXuLyPhuId;
	}

	@Override
	public void setPhieuXuLyPhuId(long phieuXuLyPhuId) {
		_columnBitmask |= PHIEUXULYPHUID_COLUMN_BITMASK;

		if (!_setOriginalPhieuXuLyPhuId) {
			_setOriginalPhieuXuLyPhuId = true;

			_originalPhieuXuLyPhuId = _phieuXuLyPhuId;
		}

		_phieuXuLyPhuId = phieuXuLyPhuId;
	}

	public long getOriginalPhieuXuLyPhuId() {
		return _originalPhieuXuLyPhuId;
	}

	@JSON
	@Override
	public int getSoNgayQuaHan() {
		return _soNgayQuaHan;
	}

	@Override
	public void setSoNgayQuaHan(int soNgayQuaHan) {
		_soNgayQuaHan = soNgayQuaHan;
	}

	@JSON
	@Override
	public long getTrangThaiTruocId() {
		return _trangThaiTruocId;
	}

	@Override
	public void setTrangThaiTruocId(long trangThaiTruocId) {
		_columnBitmask |= TRANGTHAITRUOCID_COLUMN_BITMASK;

		if (!_setOriginalTrangThaiTruocId) {
			_setOriginalTrangThaiTruocId = true;

			_originalTrangThaiTruocId = _trangThaiTruocId;
		}

		_trangThaiTruocId = trangThaiTruocId;
	}

	public long getOriginalTrangThaiTruocId() {
		return _originalTrangThaiTruocId;
	}

	@JSON
	@Override
	public long getTrangThaiSauId() {
		return _trangThaiSauId;
	}

	@Override
	public void setTrangThaiSauId(long trangThaiSauId) {
		_columnBitmask |= TRANGTHAISAUID_COLUMN_BITMASK;

		if (!_setOriginalTrangThaiSauId) {
			_setOriginalTrangThaiSauId = true;

			_originalTrangThaiSauId = _trangThaiSauId;
		}

		_trangThaiSauId = trangThaiSauId;
	}

	public long getOriginalTrangThaiSauId() {
		return _originalTrangThaiSauId;
	}

	@JSON
	@Override
	public Date getNgayXuLy() {
		return _ngayXuLy;
	}

	@Override
	public void setNgayXuLy(Date ngayXuLy) {
		_ngayXuLy = ngayXuLy;
	}

	@JSON
	@Override
	public long getNguoiXuLy() {
		return _nguoiXuLy;
	}

	@Override
	public void setNguoiXuLy(long nguoiXuLy) {
		_columnBitmask |= NGUOIXULY_COLUMN_BITMASK;

		if (!_setOriginalNguoiXuLy) {
			_setOriginalNguoiXuLy = true;

			_originalNguoiXuLy = _nguoiXuLy;
		}

		_nguoiXuLy = nguoiXuLy;
	}

	public long getOriginalNguoiXuLy() {
		return _originalNguoiXuLy;
	}

	@JSON
	@Override
	public String getHanhDongXuLy() {
		if (_hanhDongXuLy == null) {
			return StringPool.BLANK;
		}
		else {
			return _hanhDongXuLy;
		}
	}

	@Override
	public void setHanhDongXuLy(String hanhDongXuLy) {
		_hanhDongXuLy = hanhDongXuLy;
	}

	@JSON
	@Override
	public Date getSynchDate() {
		return _SynchDate;
	}

	@Override
	public void setSynchDate(Date SynchDate) {
		_SynchDate = SynchDate;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			MotCuaDienBienHoSo.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public MotCuaDienBienHoSo toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (MotCuaDienBienHoSo)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		MotCuaDienBienHoSoImpl motCuaDienBienHoSoImpl = new MotCuaDienBienHoSoImpl();

		motCuaDienBienHoSoImpl.setId(getId());
		motCuaDienBienHoSoImpl.setPhieuXuLyChinhId(getPhieuXuLyChinhId());
		motCuaDienBienHoSoImpl.setPhieuXuLyPhuId(getPhieuXuLyPhuId());
		motCuaDienBienHoSoImpl.setSoNgayQuaHan(getSoNgayQuaHan());
		motCuaDienBienHoSoImpl.setTrangThaiTruocId(getTrangThaiTruocId());
		motCuaDienBienHoSoImpl.setTrangThaiSauId(getTrangThaiSauId());
		motCuaDienBienHoSoImpl.setNgayXuLy(getNgayXuLy());
		motCuaDienBienHoSoImpl.setNguoiXuLy(getNguoiXuLy());
		motCuaDienBienHoSoImpl.setHanhDongXuLy(getHanhDongXuLy());
		motCuaDienBienHoSoImpl.setSynchDate(getSynchDate());

		motCuaDienBienHoSoImpl.resetOriginalValues();

		return motCuaDienBienHoSoImpl;
	}

	@Override
	public int compareTo(MotCuaDienBienHoSo motCuaDienBienHoSo) {
		int value = 0;

		if (getId() < motCuaDienBienHoSo.getId()) {
			value = -1;
		}
		else if (getId() > motCuaDienBienHoSo.getId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof MotCuaDienBienHoSo)) {
			return false;
		}

		MotCuaDienBienHoSo motCuaDienBienHoSo = (MotCuaDienBienHoSo)obj;

		long primaryKey = motCuaDienBienHoSo.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		MotCuaDienBienHoSoModelImpl motCuaDienBienHoSoModelImpl = this;

		motCuaDienBienHoSoModelImpl._originalPhieuXuLyChinhId = motCuaDienBienHoSoModelImpl._phieuXuLyChinhId;

		motCuaDienBienHoSoModelImpl._setOriginalPhieuXuLyChinhId = false;

		motCuaDienBienHoSoModelImpl._originalPhieuXuLyPhuId = motCuaDienBienHoSoModelImpl._phieuXuLyPhuId;

		motCuaDienBienHoSoModelImpl._setOriginalPhieuXuLyPhuId = false;

		motCuaDienBienHoSoModelImpl._originalTrangThaiTruocId = motCuaDienBienHoSoModelImpl._trangThaiTruocId;

		motCuaDienBienHoSoModelImpl._setOriginalTrangThaiTruocId = false;

		motCuaDienBienHoSoModelImpl._originalTrangThaiSauId = motCuaDienBienHoSoModelImpl._trangThaiSauId;

		motCuaDienBienHoSoModelImpl._setOriginalTrangThaiSauId = false;

		motCuaDienBienHoSoModelImpl._originalNguoiXuLy = motCuaDienBienHoSoModelImpl._nguoiXuLy;

		motCuaDienBienHoSoModelImpl._setOriginalNguoiXuLy = false;

		motCuaDienBienHoSoModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<MotCuaDienBienHoSo> toCacheModel() {
		MotCuaDienBienHoSoCacheModel motCuaDienBienHoSoCacheModel = new MotCuaDienBienHoSoCacheModel();

		motCuaDienBienHoSoCacheModel.id = getId();

		motCuaDienBienHoSoCacheModel.phieuXuLyChinhId = getPhieuXuLyChinhId();

		motCuaDienBienHoSoCacheModel.phieuXuLyPhuId = getPhieuXuLyPhuId();

		motCuaDienBienHoSoCacheModel.soNgayQuaHan = getSoNgayQuaHan();

		motCuaDienBienHoSoCacheModel.trangThaiTruocId = getTrangThaiTruocId();

		motCuaDienBienHoSoCacheModel.trangThaiSauId = getTrangThaiSauId();

		Date ngayXuLy = getNgayXuLy();

		if (ngayXuLy != null) {
			motCuaDienBienHoSoCacheModel.ngayXuLy = ngayXuLy.getTime();
		}
		else {
			motCuaDienBienHoSoCacheModel.ngayXuLy = Long.MIN_VALUE;
		}

		motCuaDienBienHoSoCacheModel.nguoiXuLy = getNguoiXuLy();

		motCuaDienBienHoSoCacheModel.hanhDongXuLy = getHanhDongXuLy();

		String hanhDongXuLy = motCuaDienBienHoSoCacheModel.hanhDongXuLy;

		if ((hanhDongXuLy != null) && (hanhDongXuLy.length() == 0)) {
			motCuaDienBienHoSoCacheModel.hanhDongXuLy = null;
		}

		Date SynchDate = getSynchDate();

		if (SynchDate != null) {
			motCuaDienBienHoSoCacheModel.SynchDate = SynchDate.getTime();
		}
		else {
			motCuaDienBienHoSoCacheModel.SynchDate = Long.MIN_VALUE;
		}

		return motCuaDienBienHoSoCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(21);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", phieuXuLyChinhId=");
		sb.append(getPhieuXuLyChinhId());
		sb.append(", phieuXuLyPhuId=");
		sb.append(getPhieuXuLyPhuId());
		sb.append(", soNgayQuaHan=");
		sb.append(getSoNgayQuaHan());
		sb.append(", trangThaiTruocId=");
		sb.append(getTrangThaiTruocId());
		sb.append(", trangThaiSauId=");
		sb.append(getTrangThaiSauId());
		sb.append(", ngayXuLy=");
		sb.append(getNgayXuLy());
		sb.append(", nguoiXuLy=");
		sb.append(getNguoiXuLy());
		sb.append(", hanhDongXuLy=");
		sb.append(getHanhDongXuLy());
		sb.append(", SynchDate=");
		sb.append(getSynchDate());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(34);

		sb.append("<model><model-name>");
		sb.append("vn.dtt.gt.dk.dao.motcua.model.MotCuaDienBienHoSo");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>phieuXuLyChinhId</column-name><column-value><![CDATA[");
		sb.append(getPhieuXuLyChinhId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>phieuXuLyPhuId</column-name><column-value><![CDATA[");
		sb.append(getPhieuXuLyPhuId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>soNgayQuaHan</column-name><column-value><![CDATA[");
		sb.append(getSoNgayQuaHan());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>trangThaiTruocId</column-name><column-value><![CDATA[");
		sb.append(getTrangThaiTruocId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>trangThaiSauId</column-name><column-value><![CDATA[");
		sb.append(getTrangThaiSauId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayXuLy</column-name><column-value><![CDATA[");
		sb.append(getNgayXuLy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nguoiXuLy</column-name><column-value><![CDATA[");
		sb.append(getNguoiXuLy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>hanhDongXuLy</column-name><column-value><![CDATA[");
		sb.append(getHanhDongXuLy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>SynchDate</column-name><column-value><![CDATA[");
		sb.append(getSynchDate());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = MotCuaDienBienHoSo.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			MotCuaDienBienHoSo.class
		};
	private long _id;
	private long _phieuXuLyChinhId;
	private long _originalPhieuXuLyChinhId;
	private boolean _setOriginalPhieuXuLyChinhId;
	private long _phieuXuLyPhuId;
	private long _originalPhieuXuLyPhuId;
	private boolean _setOriginalPhieuXuLyPhuId;
	private int _soNgayQuaHan;
	private long _trangThaiTruocId;
	private long _originalTrangThaiTruocId;
	private boolean _setOriginalTrangThaiTruocId;
	private long _trangThaiSauId;
	private long _originalTrangThaiSauId;
	private boolean _setOriginalTrangThaiSauId;
	private Date _ngayXuLy;
	private long _nguoiXuLy;
	private long _originalNguoiXuLy;
	private boolean _setOriginalNguoiXuLy;
	private String _hanhDongXuLy;
	private Date _SynchDate;
	private long _columnBitmask;
	private MotCuaDienBienHoSo _escapedModel;
}