/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.gt.dk.dao.motcua.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import vn.dtt.gt.dk.dao.motcua.model.PhieuXuLyChinhHoSoThuTuc;
import vn.dtt.gt.dk.dao.motcua.model.PhieuXuLyChinhHoSoThuTucModel;
import vn.dtt.gt.dk.dao.motcua.model.PhieuXuLyChinhHoSoThuTucSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the PhieuXuLyChinhHoSoThuTuc service. Represents a row in the &quot;view_phieuxulychinh_hosothutuc&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link vn.dtt.gt.dk.dao.motcua.model.PhieuXuLyChinhHoSoThuTucModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PhieuXuLyChinhHoSoThuTucImpl}.
 * </p>
 *
 * @author win_64
 * @see PhieuXuLyChinhHoSoThuTucImpl
 * @see vn.dtt.gt.dk.dao.motcua.model.PhieuXuLyChinhHoSoThuTuc
 * @see vn.dtt.gt.dk.dao.motcua.model.PhieuXuLyChinhHoSoThuTucModel
 * @generated
 */
@JSON(strict = true)
public class PhieuXuLyChinhHoSoThuTucModelImpl extends BaseModelImpl<PhieuXuLyChinhHoSoThuTuc>
	implements PhieuXuLyChinhHoSoThuTucModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a phieu xu ly chinh ho so thu tuc model instance should use the {@link vn.dtt.gt.dk.dao.motcua.model.PhieuXuLyChinhHoSoThuTuc} interface instead.
	 */
	public static final String TABLE_NAME = "view_phieuxulychinh_hosothutuc";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id", Types.BIGINT },
			{ "hosothutucid", Types.BIGINT },
			{ "quytrinhthutucid", Types.BIGINT },
			{ "tennguoinop", Types.VARCHAR },
			{ "cmndnguoinop", Types.VARCHAR },
			{ "diachinguoinop", Types.VARCHAR },
			{ "sodtddnguoinop", Types.VARCHAR },
			{ "emailnguoinop", Types.VARCHAR },
			{ "ghichu", Types.VARCHAR },
			{ "trangthaihientaiid", Types.BIGINT },
			{ "hethosocon", Types.BIGINT },
			{ "chiemquyenxuly", Types.BIGINT },
			{ "ngaytaophieu", Types.TIMESTAMP },
			{ "nguoitaophieu", Types.BIGINT },
			{ "sodtcdnguoinop", Types.VARCHAR },
			{ "masohoso", Types.VARCHAR },
			{ "mabiennhan", Types.VARCHAR },
			{ "thutuchanhchinhid", Types.BIGINT },
			{ "tenchuhoso", Types.VARCHAR },
			{ "ngayguihoso", Types.TIMESTAMP },
			{ "tendonvitiepnhan", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table view_phieuxulychinh_hosothutuc (id LONG not null primary key,hosothutucid LONG,quytrinhthutucid LONG,tennguoinop VARCHAR(75) null,cmndnguoinop VARCHAR(75) null,diachinguoinop VARCHAR(75) null,sodtddnguoinop VARCHAR(75) null,emailnguoinop VARCHAR(75) null,ghichu VARCHAR(75) null,trangthaihientaiid LONG,hethosocon LONG,chiemquyenxuly LONG,ngaytaophieu DATE null,nguoitaophieu LONG,sodtcdnguoinop VARCHAR(75) null,masohoso VARCHAR(75) null,mabiennhan VARCHAR(75) null,thutuchanhchinhid LONG,tenchuhoso VARCHAR(75) null,ngayguihoso DATE null,tendonvitiepnhan VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table view_phieuxulychinh_hosothutuc";
	public static final String ORDER_BY_JPQL = " ORDER BY phieuXuLyChinhHoSoThuTuc.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY view_phieuxulychinh_hosothutuc.id ASC";
	public static final String DATA_SOURCE = "tthcDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.vn.dtt.gt.dk.dao.motcua.model.PhieuXuLyChinhHoSoThuTuc"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.vn.dtt.gt.dk.dao.motcua.model.PhieuXuLyChinhHoSoThuTuc"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static PhieuXuLyChinhHoSoThuTuc toModel(
		PhieuXuLyChinhHoSoThuTucSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		PhieuXuLyChinhHoSoThuTuc model = new PhieuXuLyChinhHoSoThuTucImpl();

		model.setId(soapModel.getId());
		model.setHoSoThuTucId(soapModel.getHoSoThuTucId());
		model.setQuyTrinhThuTucId(soapModel.getQuyTrinhThuTucId());
		model.setTenNguoiNop(soapModel.getTenNguoiNop());
		model.setCmndNguoiNop(soapModel.getCmndNguoiNop());
		model.setDiaChiNguoiNop(soapModel.getDiaChiNguoiNop());
		model.setSoDtddNguoiNop(soapModel.getSoDtddNguoiNop());
		model.setEmailNguoiNop(soapModel.getEmailNguoiNop());
		model.setGhiChu(soapModel.getGhiChu());
		model.setTrangThaiHienTaiId(soapModel.getTrangThaiHienTaiId());
		model.setHetHoSoCon(soapModel.getHetHoSoCon());
		model.setChiemQuyenXuLy(soapModel.getChiemQuyenXuLy());
		model.setNgayTaoPhieu(soapModel.getNgayTaoPhieu());
		model.setNguoiTaoPhieu(soapModel.getNguoiTaoPhieu());
		model.setSoDtcdNguoiNop(soapModel.getSoDtcdNguoiNop());
		model.setMaSoHoSo(soapModel.getMaSoHoSo());
		model.setMaBienNhan(soapModel.getMaBienNhan());
		model.setThuTucHanhChinhId(soapModel.getThuTucHanhChinhId());
		model.setTenChuHoSo(soapModel.getTenChuHoSo());
		model.setNgayGuiHoSo(soapModel.getNgayGuiHoSo());
		model.setTenDonViTiepNhan(soapModel.getTenDonViTiepNhan());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<PhieuXuLyChinhHoSoThuTuc> toModels(
		PhieuXuLyChinhHoSoThuTucSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<PhieuXuLyChinhHoSoThuTuc> models = new ArrayList<PhieuXuLyChinhHoSoThuTuc>(soapModels.length);

		for (PhieuXuLyChinhHoSoThuTucSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.vn.dtt.gt.dk.dao.motcua.model.PhieuXuLyChinhHoSoThuTuc"));

	public PhieuXuLyChinhHoSoThuTucModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return PhieuXuLyChinhHoSoThuTuc.class;
	}

	@Override
	public String getModelClassName() {
		return PhieuXuLyChinhHoSoThuTuc.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("hoSoThuTucId", getHoSoThuTucId());
		attributes.put("quyTrinhThuTucId", getQuyTrinhThuTucId());
		attributes.put("tenNguoiNop", getTenNguoiNop());
		attributes.put("cmndNguoiNop", getCmndNguoiNop());
		attributes.put("diaChiNguoiNop", getDiaChiNguoiNop());
		attributes.put("soDtddNguoiNop", getSoDtddNguoiNop());
		attributes.put("emailNguoiNop", getEmailNguoiNop());
		attributes.put("ghiChu", getGhiChu());
		attributes.put("trangThaiHienTaiId", getTrangThaiHienTaiId());
		attributes.put("hetHoSoCon", getHetHoSoCon());
		attributes.put("chiemQuyenXuLy", getChiemQuyenXuLy());
		attributes.put("ngayTaoPhieu", getNgayTaoPhieu());
		attributes.put("nguoiTaoPhieu", getNguoiTaoPhieu());
		attributes.put("soDtcdNguoiNop", getSoDtcdNguoiNop());
		attributes.put("maSoHoSo", getMaSoHoSo());
		attributes.put("maBienNhan", getMaBienNhan());
		attributes.put("thuTucHanhChinhId", getThuTucHanhChinhId());
		attributes.put("tenChuHoSo", getTenChuHoSo());
		attributes.put("ngayGuiHoSo", getNgayGuiHoSo());
		attributes.put("tenDonViTiepNhan", getTenDonViTiepNhan());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id = (Long)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		Long hoSoThuTucId = (Long)attributes.get("hoSoThuTucId");

		if (hoSoThuTucId != null) {
			setHoSoThuTucId(hoSoThuTucId);
		}

		Long quyTrinhThuTucId = (Long)attributes.get("quyTrinhThuTucId");

		if (quyTrinhThuTucId != null) {
			setQuyTrinhThuTucId(quyTrinhThuTucId);
		}

		String tenNguoiNop = (String)attributes.get("tenNguoiNop");

		if (tenNguoiNop != null) {
			setTenNguoiNop(tenNguoiNop);
		}

		String cmndNguoiNop = (String)attributes.get("cmndNguoiNop");

		if (cmndNguoiNop != null) {
			setCmndNguoiNop(cmndNguoiNop);
		}

		String diaChiNguoiNop = (String)attributes.get("diaChiNguoiNop");

		if (diaChiNguoiNop != null) {
			setDiaChiNguoiNop(diaChiNguoiNop);
		}

		String soDtddNguoiNop = (String)attributes.get("soDtddNguoiNop");

		if (soDtddNguoiNop != null) {
			setSoDtddNguoiNop(soDtddNguoiNop);
		}

		String emailNguoiNop = (String)attributes.get("emailNguoiNop");

		if (emailNguoiNop != null) {
			setEmailNguoiNop(emailNguoiNop);
		}

		String ghiChu = (String)attributes.get("ghiChu");

		if (ghiChu != null) {
			setGhiChu(ghiChu);
		}

		Long trangThaiHienTaiId = (Long)attributes.get("trangThaiHienTaiId");

		if (trangThaiHienTaiId != null) {
			setTrangThaiHienTaiId(trangThaiHienTaiId);
		}

		Long hetHoSoCon = (Long)attributes.get("hetHoSoCon");

		if (hetHoSoCon != null) {
			setHetHoSoCon(hetHoSoCon);
		}

		Long chiemQuyenXuLy = (Long)attributes.get("chiemQuyenXuLy");

		if (chiemQuyenXuLy != null) {
			setChiemQuyenXuLy(chiemQuyenXuLy);
		}

		Date ngayTaoPhieu = (Date)attributes.get("ngayTaoPhieu");

		if (ngayTaoPhieu != null) {
			setNgayTaoPhieu(ngayTaoPhieu);
		}

		Long nguoiTaoPhieu = (Long)attributes.get("nguoiTaoPhieu");

		if (nguoiTaoPhieu != null) {
			setNguoiTaoPhieu(nguoiTaoPhieu);
		}

		String soDtcdNguoiNop = (String)attributes.get("soDtcdNguoiNop");

		if (soDtcdNguoiNop != null) {
			setSoDtcdNguoiNop(soDtcdNguoiNop);
		}

		String maSoHoSo = (String)attributes.get("maSoHoSo");

		if (maSoHoSo != null) {
			setMaSoHoSo(maSoHoSo);
		}

		String maBienNhan = (String)attributes.get("maBienNhan");

		if (maBienNhan != null) {
			setMaBienNhan(maBienNhan);
		}

		Long thuTucHanhChinhId = (Long)attributes.get("thuTucHanhChinhId");

		if (thuTucHanhChinhId != null) {
			setThuTucHanhChinhId(thuTucHanhChinhId);
		}

		String tenChuHoSo = (String)attributes.get("tenChuHoSo");

		if (tenChuHoSo != null) {
			setTenChuHoSo(tenChuHoSo);
		}

		Date ngayGuiHoSo = (Date)attributes.get("ngayGuiHoSo");

		if (ngayGuiHoSo != null) {
			setNgayGuiHoSo(ngayGuiHoSo);
		}

		String tenDonViTiepNhan = (String)attributes.get("tenDonViTiepNhan");

		if (tenDonViTiepNhan != null) {
			setTenDonViTiepNhan(tenDonViTiepNhan);
		}
	}

	@JSON
	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		_id = id;
	}

	@JSON
	@Override
	public long getHoSoThuTucId() {
		return _hoSoThuTucId;
	}

	@Override
	public void setHoSoThuTucId(long hoSoThuTucId) {
		_hoSoThuTucId = hoSoThuTucId;
	}

	@JSON
	@Override
	public long getQuyTrinhThuTucId() {
		return _quyTrinhThuTucId;
	}

	@Override
	public void setQuyTrinhThuTucId(long quyTrinhThuTucId) {
		_quyTrinhThuTucId = quyTrinhThuTucId;
	}

	@JSON
	@Override
	public String getTenNguoiNop() {
		if (_tenNguoiNop == null) {
			return StringPool.BLANK;
		}
		else {
			return _tenNguoiNop;
		}
	}

	@Override
	public void setTenNguoiNop(String tenNguoiNop) {
		_tenNguoiNop = tenNguoiNop;
	}

	@JSON
	@Override
	public String getCmndNguoiNop() {
		if (_cmndNguoiNop == null) {
			return StringPool.BLANK;
		}
		else {
			return _cmndNguoiNop;
		}
	}

	@Override
	public void setCmndNguoiNop(String cmndNguoiNop) {
		_cmndNguoiNop = cmndNguoiNop;
	}

	@JSON
	@Override
	public String getDiaChiNguoiNop() {
		if (_diaChiNguoiNop == null) {
			return StringPool.BLANK;
		}
		else {
			return _diaChiNguoiNop;
		}
	}

	@Override
	public void setDiaChiNguoiNop(String diaChiNguoiNop) {
		_diaChiNguoiNop = diaChiNguoiNop;
	}

	@JSON
	@Override
	public String getSoDtddNguoiNop() {
		if (_soDtddNguoiNop == null) {
			return StringPool.BLANK;
		}
		else {
			return _soDtddNguoiNop;
		}
	}

	@Override
	public void setSoDtddNguoiNop(String soDtddNguoiNop) {
		_soDtddNguoiNop = soDtddNguoiNop;
	}

	@JSON
	@Override
	public String getEmailNguoiNop() {
		if (_emailNguoiNop == null) {
			return StringPool.BLANK;
		}
		else {
			return _emailNguoiNop;
		}
	}

	@Override
	public void setEmailNguoiNop(String emailNguoiNop) {
		_emailNguoiNop = emailNguoiNop;
	}

	@JSON
	@Override
	public String getGhiChu() {
		if (_ghiChu == null) {
			return StringPool.BLANK;
		}
		else {
			return _ghiChu;
		}
	}

	@Override
	public void setGhiChu(String ghiChu) {
		_ghiChu = ghiChu;
	}

	@JSON
	@Override
	public long getTrangThaiHienTaiId() {
		return _trangThaiHienTaiId;
	}

	@Override
	public void setTrangThaiHienTaiId(long trangThaiHienTaiId) {
		_trangThaiHienTaiId = trangThaiHienTaiId;
	}

	@JSON
	@Override
	public long getHetHoSoCon() {
		return _hetHoSoCon;
	}

	@Override
	public void setHetHoSoCon(long hetHoSoCon) {
		_hetHoSoCon = hetHoSoCon;
	}

	@JSON
	@Override
	public long getChiemQuyenXuLy() {
		return _chiemQuyenXuLy;
	}

	@Override
	public void setChiemQuyenXuLy(long chiemQuyenXuLy) {
		_chiemQuyenXuLy = chiemQuyenXuLy;
	}

	@JSON
	@Override
	public Date getNgayTaoPhieu() {
		return _ngayTaoPhieu;
	}

	@Override
	public void setNgayTaoPhieu(Date ngayTaoPhieu) {
		_ngayTaoPhieu = ngayTaoPhieu;
	}

	@JSON
	@Override
	public long getNguoiTaoPhieu() {
		return _nguoiTaoPhieu;
	}

	@Override
	public void setNguoiTaoPhieu(long nguoiTaoPhieu) {
		_nguoiTaoPhieu = nguoiTaoPhieu;
	}

	@JSON
	@Override
	public String getSoDtcdNguoiNop() {
		if (_soDtcdNguoiNop == null) {
			return StringPool.BLANK;
		}
		else {
			return _soDtcdNguoiNop;
		}
	}

	@Override
	public void setSoDtcdNguoiNop(String soDtcdNguoiNop) {
		_soDtcdNguoiNop = soDtcdNguoiNop;
	}

	@JSON
	@Override
	public String getMaSoHoSo() {
		if (_maSoHoSo == null) {
			return StringPool.BLANK;
		}
		else {
			return _maSoHoSo;
		}
	}

	@Override
	public void setMaSoHoSo(String maSoHoSo) {
		_maSoHoSo = maSoHoSo;
	}

	@JSON
	@Override
	public String getMaBienNhan() {
		if (_maBienNhan == null) {
			return StringPool.BLANK;
		}
		else {
			return _maBienNhan;
		}
	}

	@Override
	public void setMaBienNhan(String maBienNhan) {
		_maBienNhan = maBienNhan;
	}

	@JSON
	@Override
	public long getThuTucHanhChinhId() {
		return _thuTucHanhChinhId;
	}

	@Override
	public void setThuTucHanhChinhId(long thuTucHanhChinhId) {
		_thuTucHanhChinhId = thuTucHanhChinhId;
	}

	@JSON
	@Override
	public String getTenChuHoSo() {
		if (_tenChuHoSo == null) {
			return StringPool.BLANK;
		}
		else {
			return _tenChuHoSo;
		}
	}

	@Override
	public void setTenChuHoSo(String tenChuHoSo) {
		_tenChuHoSo = tenChuHoSo;
	}

	@JSON
	@Override
	public Date getNgayGuiHoSo() {
		return _ngayGuiHoSo;
	}

	@Override
	public void setNgayGuiHoSo(Date ngayGuiHoSo) {
		_ngayGuiHoSo = ngayGuiHoSo;
	}

	@JSON
	@Override
	public String getTenDonViTiepNhan() {
		if (_tenDonViTiepNhan == null) {
			return StringPool.BLANK;
		}
		else {
			return _tenDonViTiepNhan;
		}
	}

	@Override
	public void setTenDonViTiepNhan(String tenDonViTiepNhan) {
		_tenDonViTiepNhan = tenDonViTiepNhan;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			PhieuXuLyChinhHoSoThuTuc.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public PhieuXuLyChinhHoSoThuTuc toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (PhieuXuLyChinhHoSoThuTuc)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		PhieuXuLyChinhHoSoThuTucImpl phieuXuLyChinhHoSoThuTucImpl = new PhieuXuLyChinhHoSoThuTucImpl();

		phieuXuLyChinhHoSoThuTucImpl.setId(getId());
		phieuXuLyChinhHoSoThuTucImpl.setHoSoThuTucId(getHoSoThuTucId());
		phieuXuLyChinhHoSoThuTucImpl.setQuyTrinhThuTucId(getQuyTrinhThuTucId());
		phieuXuLyChinhHoSoThuTucImpl.setTenNguoiNop(getTenNguoiNop());
		phieuXuLyChinhHoSoThuTucImpl.setCmndNguoiNop(getCmndNguoiNop());
		phieuXuLyChinhHoSoThuTucImpl.setDiaChiNguoiNop(getDiaChiNguoiNop());
		phieuXuLyChinhHoSoThuTucImpl.setSoDtddNguoiNop(getSoDtddNguoiNop());
		phieuXuLyChinhHoSoThuTucImpl.setEmailNguoiNop(getEmailNguoiNop());
		phieuXuLyChinhHoSoThuTucImpl.setGhiChu(getGhiChu());
		phieuXuLyChinhHoSoThuTucImpl.setTrangThaiHienTaiId(getTrangThaiHienTaiId());
		phieuXuLyChinhHoSoThuTucImpl.setHetHoSoCon(getHetHoSoCon());
		phieuXuLyChinhHoSoThuTucImpl.setChiemQuyenXuLy(getChiemQuyenXuLy());
		phieuXuLyChinhHoSoThuTucImpl.setNgayTaoPhieu(getNgayTaoPhieu());
		phieuXuLyChinhHoSoThuTucImpl.setNguoiTaoPhieu(getNguoiTaoPhieu());
		phieuXuLyChinhHoSoThuTucImpl.setSoDtcdNguoiNop(getSoDtcdNguoiNop());
		phieuXuLyChinhHoSoThuTucImpl.setMaSoHoSo(getMaSoHoSo());
		phieuXuLyChinhHoSoThuTucImpl.setMaBienNhan(getMaBienNhan());
		phieuXuLyChinhHoSoThuTucImpl.setThuTucHanhChinhId(getThuTucHanhChinhId());
		phieuXuLyChinhHoSoThuTucImpl.setTenChuHoSo(getTenChuHoSo());
		phieuXuLyChinhHoSoThuTucImpl.setNgayGuiHoSo(getNgayGuiHoSo());
		phieuXuLyChinhHoSoThuTucImpl.setTenDonViTiepNhan(getTenDonViTiepNhan());

		phieuXuLyChinhHoSoThuTucImpl.resetOriginalValues();

		return phieuXuLyChinhHoSoThuTucImpl;
	}

	@Override
	public int compareTo(PhieuXuLyChinhHoSoThuTuc phieuXuLyChinhHoSoThuTuc) {
		int value = 0;

		if (getId() < phieuXuLyChinhHoSoThuTuc.getId()) {
			value = -1;
		}
		else if (getId() > phieuXuLyChinhHoSoThuTuc.getId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof PhieuXuLyChinhHoSoThuTuc)) {
			return false;
		}

		PhieuXuLyChinhHoSoThuTuc phieuXuLyChinhHoSoThuTuc = (PhieuXuLyChinhHoSoThuTuc)obj;

		long primaryKey = phieuXuLyChinhHoSoThuTuc.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<PhieuXuLyChinhHoSoThuTuc> toCacheModel() {
		PhieuXuLyChinhHoSoThuTucCacheModel phieuXuLyChinhHoSoThuTucCacheModel = new PhieuXuLyChinhHoSoThuTucCacheModel();

		phieuXuLyChinhHoSoThuTucCacheModel.id = getId();

		phieuXuLyChinhHoSoThuTucCacheModel.hoSoThuTucId = getHoSoThuTucId();

		phieuXuLyChinhHoSoThuTucCacheModel.quyTrinhThuTucId = getQuyTrinhThuTucId();

		phieuXuLyChinhHoSoThuTucCacheModel.tenNguoiNop = getTenNguoiNop();

		String tenNguoiNop = phieuXuLyChinhHoSoThuTucCacheModel.tenNguoiNop;

		if ((tenNguoiNop != null) && (tenNguoiNop.length() == 0)) {
			phieuXuLyChinhHoSoThuTucCacheModel.tenNguoiNop = null;
		}

		phieuXuLyChinhHoSoThuTucCacheModel.cmndNguoiNop = getCmndNguoiNop();

		String cmndNguoiNop = phieuXuLyChinhHoSoThuTucCacheModel.cmndNguoiNop;

		if ((cmndNguoiNop != null) && (cmndNguoiNop.length() == 0)) {
			phieuXuLyChinhHoSoThuTucCacheModel.cmndNguoiNop = null;
		}

		phieuXuLyChinhHoSoThuTucCacheModel.diaChiNguoiNop = getDiaChiNguoiNop();

		String diaChiNguoiNop = phieuXuLyChinhHoSoThuTucCacheModel.diaChiNguoiNop;

		if ((diaChiNguoiNop != null) && (diaChiNguoiNop.length() == 0)) {
			phieuXuLyChinhHoSoThuTucCacheModel.diaChiNguoiNop = null;
		}

		phieuXuLyChinhHoSoThuTucCacheModel.soDtddNguoiNop = getSoDtddNguoiNop();

		String soDtddNguoiNop = phieuXuLyChinhHoSoThuTucCacheModel.soDtddNguoiNop;

		if ((soDtddNguoiNop != null) && (soDtddNguoiNop.length() == 0)) {
			phieuXuLyChinhHoSoThuTucCacheModel.soDtddNguoiNop = null;
		}

		phieuXuLyChinhHoSoThuTucCacheModel.emailNguoiNop = getEmailNguoiNop();

		String emailNguoiNop = phieuXuLyChinhHoSoThuTucCacheModel.emailNguoiNop;

		if ((emailNguoiNop != null) && (emailNguoiNop.length() == 0)) {
			phieuXuLyChinhHoSoThuTucCacheModel.emailNguoiNop = null;
		}

		phieuXuLyChinhHoSoThuTucCacheModel.ghiChu = getGhiChu();

		String ghiChu = phieuXuLyChinhHoSoThuTucCacheModel.ghiChu;

		if ((ghiChu != null) && (ghiChu.length() == 0)) {
			phieuXuLyChinhHoSoThuTucCacheModel.ghiChu = null;
		}

		phieuXuLyChinhHoSoThuTucCacheModel.trangThaiHienTaiId = getTrangThaiHienTaiId();

		phieuXuLyChinhHoSoThuTucCacheModel.hetHoSoCon = getHetHoSoCon();

		phieuXuLyChinhHoSoThuTucCacheModel.chiemQuyenXuLy = getChiemQuyenXuLy();

		Date ngayTaoPhieu = getNgayTaoPhieu();

		if (ngayTaoPhieu != null) {
			phieuXuLyChinhHoSoThuTucCacheModel.ngayTaoPhieu = ngayTaoPhieu.getTime();
		}
		else {
			phieuXuLyChinhHoSoThuTucCacheModel.ngayTaoPhieu = Long.MIN_VALUE;
		}

		phieuXuLyChinhHoSoThuTucCacheModel.nguoiTaoPhieu = getNguoiTaoPhieu();

		phieuXuLyChinhHoSoThuTucCacheModel.soDtcdNguoiNop = getSoDtcdNguoiNop();

		String soDtcdNguoiNop = phieuXuLyChinhHoSoThuTucCacheModel.soDtcdNguoiNop;

		if ((soDtcdNguoiNop != null) && (soDtcdNguoiNop.length() == 0)) {
			phieuXuLyChinhHoSoThuTucCacheModel.soDtcdNguoiNop = null;
		}

		phieuXuLyChinhHoSoThuTucCacheModel.maSoHoSo = getMaSoHoSo();

		String maSoHoSo = phieuXuLyChinhHoSoThuTucCacheModel.maSoHoSo;

		if ((maSoHoSo != null) && (maSoHoSo.length() == 0)) {
			phieuXuLyChinhHoSoThuTucCacheModel.maSoHoSo = null;
		}

		phieuXuLyChinhHoSoThuTucCacheModel.maBienNhan = getMaBienNhan();

		String maBienNhan = phieuXuLyChinhHoSoThuTucCacheModel.maBienNhan;

		if ((maBienNhan != null) && (maBienNhan.length() == 0)) {
			phieuXuLyChinhHoSoThuTucCacheModel.maBienNhan = null;
		}

		phieuXuLyChinhHoSoThuTucCacheModel.thuTucHanhChinhId = getThuTucHanhChinhId();

		phieuXuLyChinhHoSoThuTucCacheModel.tenChuHoSo = getTenChuHoSo();

		String tenChuHoSo = phieuXuLyChinhHoSoThuTucCacheModel.tenChuHoSo;

		if ((tenChuHoSo != null) && (tenChuHoSo.length() == 0)) {
			phieuXuLyChinhHoSoThuTucCacheModel.tenChuHoSo = null;
		}

		Date ngayGuiHoSo = getNgayGuiHoSo();

		if (ngayGuiHoSo != null) {
			phieuXuLyChinhHoSoThuTucCacheModel.ngayGuiHoSo = ngayGuiHoSo.getTime();
		}
		else {
			phieuXuLyChinhHoSoThuTucCacheModel.ngayGuiHoSo = Long.MIN_VALUE;
		}

		phieuXuLyChinhHoSoThuTucCacheModel.tenDonViTiepNhan = getTenDonViTiepNhan();

		String tenDonViTiepNhan = phieuXuLyChinhHoSoThuTucCacheModel.tenDonViTiepNhan;

		if ((tenDonViTiepNhan != null) && (tenDonViTiepNhan.length() == 0)) {
			phieuXuLyChinhHoSoThuTucCacheModel.tenDonViTiepNhan = null;
		}

		return phieuXuLyChinhHoSoThuTucCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(43);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", hoSoThuTucId=");
		sb.append(getHoSoThuTucId());
		sb.append(", quyTrinhThuTucId=");
		sb.append(getQuyTrinhThuTucId());
		sb.append(", tenNguoiNop=");
		sb.append(getTenNguoiNop());
		sb.append(", cmndNguoiNop=");
		sb.append(getCmndNguoiNop());
		sb.append(", diaChiNguoiNop=");
		sb.append(getDiaChiNguoiNop());
		sb.append(", soDtddNguoiNop=");
		sb.append(getSoDtddNguoiNop());
		sb.append(", emailNguoiNop=");
		sb.append(getEmailNguoiNop());
		sb.append(", ghiChu=");
		sb.append(getGhiChu());
		sb.append(", trangThaiHienTaiId=");
		sb.append(getTrangThaiHienTaiId());
		sb.append(", hetHoSoCon=");
		sb.append(getHetHoSoCon());
		sb.append(", chiemQuyenXuLy=");
		sb.append(getChiemQuyenXuLy());
		sb.append(", ngayTaoPhieu=");
		sb.append(getNgayTaoPhieu());
		sb.append(", nguoiTaoPhieu=");
		sb.append(getNguoiTaoPhieu());
		sb.append(", soDtcdNguoiNop=");
		sb.append(getSoDtcdNguoiNop());
		sb.append(", maSoHoSo=");
		sb.append(getMaSoHoSo());
		sb.append(", maBienNhan=");
		sb.append(getMaBienNhan());
		sb.append(", thuTucHanhChinhId=");
		sb.append(getThuTucHanhChinhId());
		sb.append(", tenChuHoSo=");
		sb.append(getTenChuHoSo());
		sb.append(", ngayGuiHoSo=");
		sb.append(getNgayGuiHoSo());
		sb.append(", tenDonViTiepNhan=");
		sb.append(getTenDonViTiepNhan());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(67);

		sb.append("<model><model-name>");
		sb.append("vn.dtt.gt.dk.dao.motcua.model.PhieuXuLyChinhHoSoThuTuc");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>hoSoThuTucId</column-name><column-value><![CDATA[");
		sb.append(getHoSoThuTucId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>quyTrinhThuTucId</column-name><column-value><![CDATA[");
		sb.append(getQuyTrinhThuTucId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tenNguoiNop</column-name><column-value><![CDATA[");
		sb.append(getTenNguoiNop());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>cmndNguoiNop</column-name><column-value><![CDATA[");
		sb.append(getCmndNguoiNop());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>diaChiNguoiNop</column-name><column-value><![CDATA[");
		sb.append(getDiaChiNguoiNop());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>soDtddNguoiNop</column-name><column-value><![CDATA[");
		sb.append(getSoDtddNguoiNop());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>emailNguoiNop</column-name><column-value><![CDATA[");
		sb.append(getEmailNguoiNop());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ghiChu</column-name><column-value><![CDATA[");
		sb.append(getGhiChu());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>trangThaiHienTaiId</column-name><column-value><![CDATA[");
		sb.append(getTrangThaiHienTaiId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>hetHoSoCon</column-name><column-value><![CDATA[");
		sb.append(getHetHoSoCon());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>chiemQuyenXuLy</column-name><column-value><![CDATA[");
		sb.append(getChiemQuyenXuLy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayTaoPhieu</column-name><column-value><![CDATA[");
		sb.append(getNgayTaoPhieu());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nguoiTaoPhieu</column-name><column-value><![CDATA[");
		sb.append(getNguoiTaoPhieu());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>soDtcdNguoiNop</column-name><column-value><![CDATA[");
		sb.append(getSoDtcdNguoiNop());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>maSoHoSo</column-name><column-value><![CDATA[");
		sb.append(getMaSoHoSo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>maBienNhan</column-name><column-value><![CDATA[");
		sb.append(getMaBienNhan());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>thuTucHanhChinhId</column-name><column-value><![CDATA[");
		sb.append(getThuTucHanhChinhId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tenChuHoSo</column-name><column-value><![CDATA[");
		sb.append(getTenChuHoSo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ngayGuiHoSo</column-name><column-value><![CDATA[");
		sb.append(getNgayGuiHoSo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tenDonViTiepNhan</column-name><column-value><![CDATA[");
		sb.append(getTenDonViTiepNhan());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = PhieuXuLyChinhHoSoThuTuc.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			PhieuXuLyChinhHoSoThuTuc.class
		};
	private long _id;
	private long _hoSoThuTucId;
	private long _quyTrinhThuTucId;
	private String _tenNguoiNop;
	private String _cmndNguoiNop;
	private String _diaChiNguoiNop;
	private String _soDtddNguoiNop;
	private String _emailNguoiNop;
	private String _ghiChu;
	private long _trangThaiHienTaiId;
	private long _hetHoSoCon;
	private long _chiemQuyenXuLy;
	private Date _ngayTaoPhieu;
	private long _nguoiTaoPhieu;
	private String _soDtcdNguoiNop;
	private String _maSoHoSo;
	private String _maBienNhan;
	private long _thuTucHanhChinhId;
	private String _tenChuHoSo;
	private Date _ngayGuiHoSo;
	private String _tenDonViTiepNhan;
	private PhieuXuLyChinhHoSoThuTuc _escapedModel;
}