/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.gt.dk.dao.nghiepvu.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ConfirmedInspection service. Represents a row in the &quot;vr_confirmedinspection&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.dtt.gt.dk.dao.nghiepvu.model.impl.ConfirmedInspectionModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.dtt.gt.dk.dao.nghiepvu.model.impl.ConfirmedInspectionImpl}.
 * </p>
 *
 * @author win_64
 * @see ConfirmedInspection
 * @see vn.dtt.gt.dk.dao.nghiepvu.model.impl.ConfirmedInspectionImpl
 * @see vn.dtt.gt.dk.dao.nghiepvu.model.impl.ConfirmedInspectionModelImpl
 * @generated
 */
public interface ConfirmedInspectionModel extends BaseModel<ConfirmedInspection> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a confirmed inspection model instance should use the {@link ConfirmedInspection} interface instead.
	 */

	/**
	 * Returns the primary key of this confirmed inspection.
	 *
	 * @return the primary key of this confirmed inspection
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this confirmed inspection.
	 *
	 * @param primaryKey the primary key of this confirmed inspection
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this confirmed inspection.
	 *
	 * @return the ID of this confirmed inspection
	 */
	public long getId();

	/**
	 * Sets the ID of this confirmed inspection.
	 *
	 * @param id the ID of this confirmed inspection
	 */
	public void setId(long id);

	/**
	 * Returns the registered inspection ID of this confirmed inspection.
	 *
	 * @return the registered inspection ID of this confirmed inspection
	 */
	public long getRegisteredInspectionId();

	/**
	 * Sets the registered inspection ID of this confirmed inspection.
	 *
	 * @param registeredInspectionId the registered inspection ID of this confirmed inspection
	 */
	public void setRegisteredInspectionId(long registeredInspectionId);

	/**
	 * Returns the customs declaration ID of this confirmed inspection.
	 *
	 * @return the customs declaration ID of this confirmed inspection
	 */
	public long getCustomsDeclarationId();

	/**
	 * Sets the customs declaration ID of this confirmed inspection.
	 *
	 * @param customsDeclarationId the customs declaration ID of this confirmed inspection
	 */
	public void setCustomsDeclarationId(long customsDeclarationId);

	/**
	 * Returns the confirmation code of this confirmed inspection.
	 *
	 * @return the confirmation code of this confirmed inspection
	 */
	public long getConfirmationCode();

	/**
	 * Sets the confirmation code of this confirmed inspection.
	 *
	 * @param confirmationCode the confirmation code of this confirmed inspection
	 */
	public void setConfirmationCode(long confirmationCode);

	/**
	 * Returns the attached file of this confirmed inspection.
	 *
	 * @return the attached file of this confirmed inspection
	 */
	public long getAttachedFile();

	/**
	 * Sets the attached file of this confirmed inspection.
	 *
	 * @param attachedFile the attached file of this confirmed inspection
	 */
	public void setAttachedFile(long attachedFile);

	/**
	 * Returns the inspection date of this confirmed inspection.
	 *
	 * @return the inspection date of this confirmed inspection
	 */
	public Date getInspectionDate();

	/**
	 * Sets the inspection date of this confirmed inspection.
	 *
	 * @param inspectionDate the inspection date of this confirmed inspection
	 */
	public void setInspectionDate(Date inspectionDate);

	/**
	 * Returns the inspection site of this confirmed inspection.
	 *
	 * @return the inspection site of this confirmed inspection
	 */
	@AutoEscape
	public String getInspectionSite();

	/**
	 * Sets the inspection site of this confirmed inspection.
	 *
	 * @param inspectionSite the inspection site of this confirmed inspection
	 */
	public void setInspectionSite(String inspectionSite);

	/**
	 * Returns the inspection district code of this confirmed inspection.
	 *
	 * @return the inspection district code of this confirmed inspection
	 */
	@AutoEscape
	public String getInspectionDistrictCode();

	/**
	 * Sets the inspection district code of this confirmed inspection.
	 *
	 * @param inspectionDistrictCode the inspection district code of this confirmed inspection
	 */
	public void setInspectionDistrictCode(String inspectionDistrictCode);

	/**
	 * Returns the inspection provincecode of this confirmed inspection.
	 *
	 * @return the inspection provincecode of this confirmed inspection
	 */
	@AutoEscape
	public String getInspectionProvincecode();

	/**
	 * Sets the inspection provincecode of this confirmed inspection.
	 *
	 * @param inspectionProvincecode the inspection provincecode of this confirmed inspection
	 */
	public void setInspectionProvincecode(String inspectionProvincecode);

	/**
	 * Returns the customs region of this confirmed inspection.
	 *
	 * @return the customs region of this confirmed inspection
	 */
	public long getCustomsRegion();

	/**
	 * Sets the customs region of this confirmed inspection.
	 *
	 * @param customsRegion the customs region of this confirmed inspection
	 */
	public void setCustomsRegion(long customsRegion);

	/**
	 * Returns the markas changed site of this confirmed inspection.
	 *
	 * @return the markas changed site of this confirmed inspection
	 */
	public long getMarkasChangedSite();

	/**
	 * Sets the markas changed site of this confirmed inspection.
	 *
	 * @param markasChangedSite the markas changed site of this confirmed inspection
	 */
	public void setMarkasChangedSite(long markasChangedSite);

	/**
	 * Returns the contact name of this confirmed inspection.
	 *
	 * @return the contact name of this confirmed inspection
	 */
	@AutoEscape
	public String getContactName();

	/**
	 * Sets the contact name of this confirmed inspection.
	 *
	 * @param contactName the contact name of this confirmed inspection
	 */
	public void setContactName(String contactName);

	/**
	 * Returns the contact phone of this confirmed inspection.
	 *
	 * @return the contact phone of this confirmed inspection
	 */
	@AutoEscape
	public String getContactPhone();

	/**
	 * Sets the contact phone of this confirmed inspection.
	 *
	 * @param contactPhone the contact phone of this confirmed inspection
	 */
	public void setContactPhone(String contactPhone);

	/**
	 * Returns the contact email of this confirmed inspection.
	 *
	 * @return the contact email of this confirmed inspection
	 */
	@AutoEscape
	public String getContactEmail();

	/**
	 * Sets the contact email of this confirmed inspection.
	 *
	 * @param contactEmail the contact email of this confirmed inspection
	 */
	public void setContactEmail(String contactEmail);

	/**
	 * Returns the sign name of this confirmed inspection.
	 *
	 * @return the sign name of this confirmed inspection
	 */
	@AutoEscape
	public String getSignName();

	/**
	 * Sets the sign name of this confirmed inspection.
	 *
	 * @param signName the sign name of this confirmed inspection
	 */
	public void setSignName(String signName);

	/**
	 * Returns the sign title of this confirmed inspection.
	 *
	 * @return the sign title of this confirmed inspection
	 */
	@AutoEscape
	public String getSignTitle();

	/**
	 * Sets the sign title of this confirmed inspection.
	 *
	 * @param signTitle the sign title of this confirmed inspection
	 */
	public void setSignTitle(String signTitle);

	/**
	 * Returns the sign place of this confirmed inspection.
	 *
	 * @return the sign place of this confirmed inspection
	 */
	@AutoEscape
	public String getSignPlace();

	/**
	 * Sets the sign place of this confirmed inspection.
	 *
	 * @param signPlace the sign place of this confirmed inspection
	 */
	public void setSignPlace(String signPlace);

	/**
	 * Returns the sign date of this confirmed inspection.
	 *
	 * @return the sign date of this confirmed inspection
	 */
	public Date getSignDate();

	/**
	 * Sets the sign date of this confirmed inspection.
	 *
	 * @param signDate the sign date of this confirmed inspection
	 */
	public void setSignDate(Date signDate);

	/**
	 * Returns the remarks of this confirmed inspection.
	 *
	 * @return the remarks of this confirmed inspection
	 */
	@AutoEscape
	public String getRemarks();

	/**
	 * Sets the remarks of this confirmed inspection.
	 *
	 * @param remarks the remarks of this confirmed inspection
	 */
	public void setRemarks(String remarks);

	/**
	 * Returns the corporation ID of this confirmed inspection.
	 *
	 * @return the corporation ID of this confirmed inspection
	 */
	@AutoEscape
	public String getCorporationId();

	/**
	 * Sets the corporation ID of this confirmed inspection.
	 *
	 * @param corporationId the corporation ID of this confirmed inspection
	 */
	public void setCorporationId(String corporationId);

	/**
	 * Returns the inspector ID of this confirmed inspection.
	 *
	 * @return the inspector ID of this confirmed inspection
	 */
	public long getInspectorId();

	/**
	 * Sets the inspector ID of this confirmed inspection.
	 *
	 * @param inspectorId the inspector ID of this confirmed inspection
	 */
	public void setInspectorId(long inspectorId);

	/**
	 * Returns the phieu xu ly phu ID of this confirmed inspection.
	 *
	 * @return the phieu xu ly phu ID of this confirmed inspection
	 */
	public long getPhieuXuLyPhuId();

	/**
	 * Sets the phieu xu ly phu ID of this confirmed inspection.
	 *
	 * @param phieuXuLyPhuId the phieu xu ly phu ID of this confirmed inspection
	 */
	public void setPhieuXuLyPhuId(long phieuXuLyPhuId);

	/**
	 * Returns the ho so thu tuc ID of this confirmed inspection.
	 *
	 * @return the ho so thu tuc ID of this confirmed inspection
	 */
	public long getHoSoThuTucId();

	/**
	 * Sets the ho so thu tuc ID of this confirmed inspection.
	 *
	 * @param hoSoThuTucId the ho so thu tuc ID of this confirmed inspection
	 */
	public void setHoSoThuTucId(long hoSoThuTucId);

	/**
	 * Returns the date from of this confirmed inspection.
	 *
	 * @return the date from of this confirmed inspection
	 */
	public Date getDateFrom();

	/**
	 * Sets the date from of this confirmed inspection.
	 *
	 * @param dateFrom the date from of this confirmed inspection
	 */
	public void setDateFrom(Date dateFrom);

	/**
	 * Returns the date to of this confirmed inspection.
	 *
	 * @return the date to of this confirmed inspection
	 */
	public Date getDateTo();

	/**
	 * Sets the date to of this confirmed inspection.
	 *
	 * @param dateTo the date to of this confirmed inspection
	 */
	public void setDateTo(Date dateTo);

	/**
	 * Returns the leader of this confirmed inspection.
	 *
	 * @return the leader of this confirmed inspection
	 */
	public int getLeader();

	/**
	 * Sets the leader of this confirmed inspection.
	 *
	 * @param leader the leader of this confirmed inspection
	 */
	public void setLeader(int leader);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ConfirmedInspection confirmedInspection);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ConfirmedInspection> toCacheModel();

	@Override
	public ConfirmedInspection toEscapedModel();

	@Override
	public ConfirmedInspection toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}