/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.gt.dk.dao.nghiepvu.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the EmissionTestRequirement service. Represents a row in the &quot;vr_emissiontestrequirement&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.dtt.gt.dk.dao.nghiepvu.model.impl.EmissionTestRequirementModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.dtt.gt.dk.dao.nghiepvu.model.impl.EmissionTestRequirementImpl}.
 * </p>
 *
 * @author win_64
 * @see EmissionTestRequirement
 * @see vn.dtt.gt.dk.dao.nghiepvu.model.impl.EmissionTestRequirementImpl
 * @see vn.dtt.gt.dk.dao.nghiepvu.model.impl.EmissionTestRequirementModelImpl
 * @generated
 */
public interface EmissionTestRequirementModel extends BaseModel<EmissionTestRequirement> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a emission test requirement model instance should use the {@link EmissionTestRequirement} interface instead.
	 */

	/**
	 * Returns the primary key of this emission test requirement.
	 *
	 * @return the primary key of this emission test requirement
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this emission test requirement.
	 *
	 * @param primaryKey the primary key of this emission test requirement
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this emission test requirement.
	 *
	 * @return the ID of this emission test requirement
	 */
	public long getId();

	/**
	 * Sets the ID of this emission test requirement.
	 *
	 * @param id the ID of this emission test requirement
	 */
	public void setId(long id);

	/**
	 * Returns the registered inspection ID of this emission test requirement.
	 *
	 * @return the registered inspection ID of this emission test requirement
	 */
	public long getRegisteredInspectionId();

	/**
	 * Sets the registered inspection ID of this emission test requirement.
	 *
	 * @param registeredInspectionId the registered inspection ID of this emission test requirement
	 */
	public void setRegisteredInspectionId(long registeredInspectionId);

	/**
	 * Returns the inspection record ID of this emission test requirement.
	 *
	 * @return the inspection record ID of this emission test requirement
	 */
	public long getInspectionRecordId();

	/**
	 * Sets the inspection record ID of this emission test requirement.
	 *
	 * @param inspectionRecordId the inspection record ID of this emission test requirement
	 */
	public void setInspectionRecordId(long inspectionRecordId);

	/**
	 * Returns the requirement number of this emission test requirement.
	 *
	 * @return the requirement number of this emission test requirement
	 */
	@AutoEscape
	public String getRequirementNumber();

	/**
	 * Sets the requirement number of this emission test requirement.
	 *
	 * @param requirementNumber the requirement number of this emission test requirement
	 */
	public void setRequirementNumber(String requirementNumber);

	/**
	 * Returns the content of request of this emission test requirement.
	 *
	 * @return the content of request of this emission test requirement
	 */
	@AutoEscape
	public String getContentOfRequest();

	/**
	 * Sets the content of request of this emission test requirement.
	 *
	 * @param contentOfRequest the content of request of this emission test requirement
	 */
	public void setContentOfRequest(String contentOfRequest);

	/**
	 * Returns the testing registered place of this emission test requirement.
	 *
	 * @return the testing registered place of this emission test requirement
	 */
	@AutoEscape
	public String getTestingRegisteredPlace();

	/**
	 * Sets the testing registered place of this emission test requirement.
	 *
	 * @param testingRegisteredPlace the testing registered place of this emission test requirement
	 */
	public void setTestingRegisteredPlace(String testingRegisteredPlace);

	/**
	 * Returns the testing registration of this emission test requirement.
	 *
	 * @return the testing registration of this emission test requirement
	 */
	@AutoEscape
	public String getTestingRegistration();

	/**
	 * Sets the testing registration of this emission test requirement.
	 *
	 * @param testingRegistration the testing registration of this emission test requirement
	 */
	public void setTestingRegistration(String testingRegistration);

	/**
	 * Returns the testing payment condition of this emission test requirement.
	 *
	 * @return the testing payment condition of this emission test requirement
	 */
	@AutoEscape
	public String getTestingPaymentCondition();

	/**
	 * Sets the testing payment condition of this emission test requirement.
	 *
	 * @param testingPaymentCondition the testing payment condition of this emission test requirement
	 */
	public void setTestingPaymentCondition(String testingPaymentCondition);

	/**
	 * Returns the remarks of this emission test requirement.
	 *
	 * @return the remarks of this emission test requirement
	 */
	@AutoEscape
	public String getRemarks();

	/**
	 * Sets the remarks of this emission test requirement.
	 *
	 * @param remarks the remarks of this emission test requirement
	 */
	public void setRemarks(String remarks);

	/**
	 * Returns the corporation ID of this emission test requirement.
	 *
	 * @return the corporation ID of this emission test requirement
	 */
	@AutoEscape
	public String getCorporationId();

	/**
	 * Sets the corporation ID of this emission test requirement.
	 *
	 * @param corporationId the corporation ID of this emission test requirement
	 */
	public void setCorporationId(String corporationId);

	/**
	 * Returns the sign name of this emission test requirement.
	 *
	 * @return the sign name of this emission test requirement
	 */
	@AutoEscape
	public String getSignName();

	/**
	 * Sets the sign name of this emission test requirement.
	 *
	 * @param signName the sign name of this emission test requirement
	 */
	public void setSignName(String signName);

	/**
	 * Returns the sign title of this emission test requirement.
	 *
	 * @return the sign title of this emission test requirement
	 */
	@AutoEscape
	public String getSignTitle();

	/**
	 * Sets the sign title of this emission test requirement.
	 *
	 * @param signTitle the sign title of this emission test requirement
	 */
	public void setSignTitle(String signTitle);

	/**
	 * Returns the sign place of this emission test requirement.
	 *
	 * @return the sign place of this emission test requirement
	 */
	@AutoEscape
	public String getSignPlace();

	/**
	 * Sets the sign place of this emission test requirement.
	 *
	 * @param signPlace the sign place of this emission test requirement
	 */
	public void setSignPlace(String signPlace);

	/**
	 * Returns the sign date of this emission test requirement.
	 *
	 * @return the sign date of this emission test requirement
	 */
	public Date getSignDate();

	/**
	 * Sets the sign date of this emission test requirement.
	 *
	 * @param signDate the sign date of this emission test requirement
	 */
	public void setSignDate(Date signDate);

	/**
	 * Returns the phieu xu ly phu ID of this emission test requirement.
	 *
	 * @return the phieu xu ly phu ID of this emission test requirement
	 */
	public long getPhieuXuLyPhuId();

	/**
	 * Sets the phieu xu ly phu ID of this emission test requirement.
	 *
	 * @param phieuXuLyPhuId the phieu xu ly phu ID of this emission test requirement
	 */
	public void setPhieuXuLyPhuId(long phieuXuLyPhuId);

	/**
	 * Returns the attached file of this emission test requirement.
	 *
	 * @return the attached file of this emission test requirement
	 */
	public long getAttachedFile();

	/**
	 * Sets the attached file of this emission test requirement.
	 *
	 * @param attachedFile the attached file of this emission test requirement
	 */
	public void setAttachedFile(long attachedFile);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		vn.dtt.gt.dk.dao.nghiepvu.model.EmissionTestRequirement emissionTestRequirement);

	@Override
	public int hashCode();

	@Override
	public CacheModel<vn.dtt.gt.dk.dao.nghiepvu.model.EmissionTestRequirement> toCacheModel();

	@Override
	public vn.dtt.gt.dk.dao.nghiepvu.model.EmissionTestRequirement toEscapedModel();

	@Override
	public vn.dtt.gt.dk.dao.nghiepvu.model.EmissionTestRequirement toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}