//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.21 at 04:13:57 PM ICT 
//


package vn.dtt.gt.dk.nsw;

import javax.xml.bind.annotation.XmlRegistry;

import vn.dtt.gt.dk.nsw.model.ConfirmationStatusOfQuanlityConformity;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the vn package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: vn
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ConfirmationStatusOfQuanlityConformity }
     * 
     */
    public ConfirmationStatusOfQuanlityConformity createConfirmationStatusOfQuanlityConformity() {
        return new ConfirmationStatusOfQuanlityConformity();
    }

    /**
     * Create an instance of {@link ConfirmationStatusOfQuanlityConformity.SpecificationList }
     * 
     */
    public ConfirmationStatusOfQuanlityConformity.SpecificationList createConfirmationStatusOfQuanlityConformitySpecificationList() {
        return new ConfirmationStatusOfQuanlityConformity.SpecificationList();
    }

    /**
     * Create an instance of {@link ConfirmationStatusOfQuanlityConformity.Importer }
     * 
     */
    public ConfirmationStatusOfQuanlityConformity.Importer createConfirmationStatusOfQuanlityConformityImporter() {
        return new ConfirmationStatusOfQuanlityConformity.Importer();
    }

    /**
     * Create an instance of {@link ConfirmationStatusOfQuanlityConformity.ProductionCountry }
     * 
     */
    public ConfirmationStatusOfQuanlityConformity.ProductionCountry createConfirmationStatusOfQuanlityConformityProductionCountry() {
        return new ConfirmationStatusOfQuanlityConformity.ProductionCountry();
    }

    /**
     * Create an instance of {@link ConfirmationStatusOfQuanlityConformity.CustomDeclaration }
     * 
     */
    public ConfirmationStatusOfQuanlityConformity.CustomDeclaration createConfirmationStatusOfQuanlityConformityCustomDeclaration() {
        return new ConfirmationStatusOfQuanlityConformity.CustomDeclaration();
    }

    /**
     * Create an instance of {@link ConfirmationStatusOfQuanlityConformity.SafetyTestReport }
     * 
     */
    public ConfirmationStatusOfQuanlityConformity.SafetyTestReport createConfirmationStatusOfQuanlityConformitySafetyTestReport() {
        return new ConfirmationStatusOfQuanlityConformity.SafetyTestReport();
    }

    /**
     * Create an instance of {@link ConfirmationStatusOfQuanlityConformity.EmissionTestReport }
     * 
     */
    public ConfirmationStatusOfQuanlityConformity.EmissionTestReport createConfirmationStatusOfQuanlityConformityEmissionTestReport() {
        return new ConfirmationStatusOfQuanlityConformity.EmissionTestReport();
    }

    /**
     * Create an instance of {@link ConfirmationStatusOfQuanlityConformity.COPReport }
     * 
     */
    public ConfirmationStatusOfQuanlityConformity.COPReport createConfirmationStatusOfQuanlityConformityCOPReport() {
        return new ConfirmationStatusOfQuanlityConformity.COPReport();
    }

    /**
     * Create an instance of {@link ConfirmationStatusOfQuanlityConformity.Circular }
     * 
     */
    public ConfirmationStatusOfQuanlityConformity.Circular createConfirmationStatusOfQuanlityConformityCircular() {
        return new ConfirmationStatusOfQuanlityConformity.Circular();
    }

    /**
     * Create an instance of {@link ConfirmationStatusOfQuanlityConformity.InspectorSign }
     * 
     */
    public ConfirmationStatusOfQuanlityConformity.InspectorSign createConfirmationStatusOfQuanlityConformityInspectorSign() {
        return new ConfirmationStatusOfQuanlityConformity.InspectorSign();
    }

    /**
     * Create an instance of {@link ConfirmationStatusOfQuanlityConformity.AttachedFile }
     * 
     */
    public ConfirmationStatusOfQuanlityConformity.AttachedFile createConfirmationStatusOfQuanlityConformityAttachedFile() {
        return new ConfirmationStatusOfQuanlityConformity.AttachedFile();
    }

    /**
     * Create an instance of {@link ConfirmationStatusOfQuanlityConformity.SpecificationList.SpecItem }
     * 
     */
    public ConfirmationStatusOfQuanlityConformity.SpecificationList.SpecItem createConfirmationStatusOfQuanlityConformitySpecificationListSpecItem() {
        return new ConfirmationStatusOfQuanlityConformity.SpecificationList.SpecItem();
    }

}
