/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.gt.dk.dao.nghiepvu.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the CertificateCircular service. Represents a row in the &quot;vr_certificatecircular&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.dtt.gt.dk.dao.nghiepvu.model.impl.CertificateCircularModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.dtt.gt.dk.dao.nghiepvu.model.impl.CertificateCircularImpl}.
 * </p>
 *
 * @author huymq
 * @see CertificateCircular
 * @see vn.dtt.gt.dk.dao.nghiepvu.model.impl.CertificateCircularImpl
 * @see vn.dtt.gt.dk.dao.nghiepvu.model.impl.CertificateCircularModelImpl
 * @generated
 */
public interface CertificateCircularModel extends BaseModel<CertificateCircular> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a certificate circular model instance should use the {@link CertificateCircular} interface instead.
	 */

	/**
	 * Returns the primary key of this certificate circular.
	 *
	 * @return the primary key of this certificate circular
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this certificate circular.
	 *
	 * @param primaryKey the primary key of this certificate circular
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this certificate circular.
	 *
	 * @return the ID of this certificate circular
	 */
	public long getId();

	/**
	 * Sets the ID of this certificate circular.
	 *
	 * @param id the ID of this certificate circular
	 */
	public void setId(long id);

	/**
	 * Returns the certificate record ID of this certificate circular.
	 *
	 * @return the certificate record ID of this certificate circular
	 */
	public long getCertificateRecordId();

	/**
	 * Sets the certificate record ID of this certificate circular.
	 *
	 * @param certificateRecordId the certificate record ID of this certificate circular
	 */
	public void setCertificateRecordId(long certificateRecordId);

	/**
	 * Returns the sequence no of this certificate circular.
	 *
	 * @return the sequence no of this certificate circular
	 */
	public long getSequenceNo();

	/**
	 * Sets the sequence no of this certificate circular.
	 *
	 * @param sequenceNo the sequence no of this certificate circular
	 */
	public void setSequenceNo(long sequenceNo);

	/**
	 * Returns the circular no of this certificate circular.
	 *
	 * @return the circular no of this certificate circular
	 */
	@AutoEscape
	public String getCircularNo();

	/**
	 * Sets the circular no of this certificate circular.
	 *
	 * @param circularNo the circular no of this certificate circular
	 */
	public void setCircularNo(String circularNo);

	/**
	 * Returns the circular date of this certificate circular.
	 *
	 * @return the circular date of this certificate circular
	 */
	public Date getCircularDate();

	/**
	 * Sets the circular date of this certificate circular.
	 *
	 * @param circularDate the circular date of this certificate circular
	 */
	public void setCircularDate(Date circularDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(CertificateCircular certificateCircular);

	@Override
	public int hashCode();

	@Override
	public CacheModel<CertificateCircular> toCacheModel();

	@Override
	public CertificateCircular toEscapedModel();

	@Override
	public CertificateCircular toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}