/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.gt.dk.dao.nghiepvu.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the CopReport service. Represents a row in the &quot;vr_copreport&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.dtt.gt.dk.dao.nghiepvu.model.impl.CopReportModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.dtt.gt.dk.dao.nghiepvu.model.impl.CopReportImpl}.
 * </p>
 *
 * @author huymq
 * @see CopReport
 * @see vn.dtt.gt.dk.dao.nghiepvu.model.impl.CopReportImpl
 * @see vn.dtt.gt.dk.dao.nghiepvu.model.impl.CopReportModelImpl
 * @generated
 */
public interface CopReportModel extends BaseModel<CopReport> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a cop report model instance should use the {@link CopReport} interface instead.
	 */

	/**
	 * Returns the primary key of this cop report.
	 *
	 * @return the primary key of this cop report
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this cop report.
	 *
	 * @param primaryKey the primary key of this cop report
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this cop report.
	 *
	 * @return the ID of this cop report
	 */
	public long getId();

	/**
	 * Sets the ID of this cop report.
	 *
	 * @param id the ID of this cop report
	 */
	public void setId(long id);

	/**
	 * Returns the registered inspection ID of this cop report.
	 *
	 * @return the registered inspection ID of this cop report
	 */
	public long getRegisteredInspectionId();

	/**
	 * Sets the registered inspection ID of this cop report.
	 *
	 * @param registeredInspectionId the registered inspection ID of this cop report
	 */
	public void setRegisteredInspectionId(long registeredInspectionId);

	/**
	 * Returns the report number of this cop report.
	 *
	 * @return the report number of this cop report
	 */
	@AutoEscape
	public String getReportNumber();

	/**
	 * Sets the report number of this cop report.
	 *
	 * @param reportNumber the report number of this cop report
	 */
	public void setReportNumber(String reportNumber);

	/**
	 * Returns the corporation ID of this cop report.
	 *
	 * @return the corporation ID of this cop report
	 */
	@AutoEscape
	public String getCorporationId();

	/**
	 * Sets the corporation ID of this cop report.
	 *
	 * @param corporationId the corporation ID of this cop report
	 */
	public void setCorporationId(String corporationId);

	/**
	 * Returns the sign name of this cop report.
	 *
	 * @return the sign name of this cop report
	 */
	@AutoEscape
	public String getSignName();

	/**
	 * Sets the sign name of this cop report.
	 *
	 * @param signName the sign name of this cop report
	 */
	public void setSignName(String signName);

	/**
	 * Returns the sign title of this cop report.
	 *
	 * @return the sign title of this cop report
	 */
	@AutoEscape
	public String getSignTitle();

	/**
	 * Sets the sign title of this cop report.
	 *
	 * @param signTitle the sign title of this cop report
	 */
	public void setSignTitle(String signTitle);

	/**
	 * Returns the sign place of this cop report.
	 *
	 * @return the sign place of this cop report
	 */
	@AutoEscape
	public String getSignPlace();

	/**
	 * Sets the sign place of this cop report.
	 *
	 * @param signPlace the sign place of this cop report
	 */
	public void setSignPlace(String signPlace);

	/**
	 * Returns the sign date of this cop report.
	 *
	 * @return the sign date of this cop report
	 */
	public Date getSignDate();

	/**
	 * Sets the sign date of this cop report.
	 *
	 * @param signDate the sign date of this cop report
	 */
	public void setSignDate(Date signDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(CopReport copReport);

	@Override
	public int hashCode();

	@Override
	public CacheModel<CopReport> toCacheModel();

	@Override
	public CopReport toEscapedModel();

	@Override
	public CopReport toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}