/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.gt.dk.dao.nghiepvu.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the IssueTracking service. Represents a row in the &quot;vr_assessmentissuetracking&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.dtt.gt.dk.dao.nghiepvu.model.impl.IssueTrackingModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.dtt.gt.dk.dao.nghiepvu.model.impl.IssueTrackingImpl}.
 * </p>
 *
 * @author win_64
 * @see IssueTracking
 * @see vn.dtt.gt.dk.dao.nghiepvu.model.impl.IssueTrackingImpl
 * @see vn.dtt.gt.dk.dao.nghiepvu.model.impl.IssueTrackingModelImpl
 * @generated
 */
public interface IssueTrackingModel extends BaseModel<IssueTracking> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a issue tracking model instance should use the {@link IssueTracking} interface instead.
	 */

	/**
	 * Returns the primary key of this issue tracking.
	 *
	 * @return the primary key of this issue tracking
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this issue tracking.
	 *
	 * @param primaryKey the primary key of this issue tracking
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this issue tracking.
	 *
	 * @return the ID of this issue tracking
	 */
	public long getId();

	/**
	 * Sets the ID of this issue tracking.
	 *
	 * @param id the ID of this issue tracking
	 */
	public void setId(long id);

	/**
	 * Returns the importercode of this issue tracking.
	 *
	 * @return the importercode of this issue tracking
	 */
	@AutoEscape
	public String getImportercode();

	/**
	 * Sets the importercode of this issue tracking.
	 *
	 * @param importercode the importercode of this issue tracking
	 */
	public void setImportercode(String importercode);

	/**
	 * Returns the importername of this issue tracking.
	 *
	 * @return the importername of this issue tracking
	 */
	@AutoEscape
	public String getImportername();

	/**
	 * Sets the importername of this issue tracking.
	 *
	 * @param importername the importername of this issue tracking
	 */
	public void setImportername(String importername);

	/**
	 * Returns the registerednumber of this issue tracking.
	 *
	 * @return the registerednumber of this issue tracking
	 */
	@AutoEscape
	public String getRegisterednumber();

	/**
	 * Sets the registerednumber of this issue tracking.
	 *
	 * @param registerednumber the registerednumber of this issue tracking
	 */
	public void setRegisterednumber(String registerednumber);

	/**
	 * Returns the inspectionrecordno of this issue tracking.
	 *
	 * @return the inspectionrecordno of this issue tracking
	 */
	@AutoEscape
	public String getInspectionrecordno();

	/**
	 * Sets the inspectionrecordno of this issue tracking.
	 *
	 * @param inspectionrecordno the inspectionrecordno of this issue tracking
	 */
	public void setInspectionrecordno(String inspectionrecordno);

	/**
	 * Returns the inspection record date of this issue tracking.
	 *
	 * @return the inspection record date of this issue tracking
	 */
	public Date getInspectionRecordDate();

	/**
	 * Sets the inspection record date of this issue tracking.
	 *
	 * @param inspectionRecordDate the inspection record date of this issue tracking
	 */
	public void setInspectionRecordDate(Date inspectionRecordDate);

	/**
	 * Returns the corporation ID of this issue tracking.
	 *
	 * @return the corporation ID of this issue tracking
	 */
	@AutoEscape
	public String getCorporationId();

	/**
	 * Sets the corporation ID of this issue tracking.
	 *
	 * @param corporationId the corporation ID of this issue tracking
	 */
	public void setCorporationId(String corporationId);

	/**
	 * Returns the inspector ID of this issue tracking.
	 *
	 * @return the inspector ID of this issue tracking
	 */
	public long getInspectorId();

	/**
	 * Sets the inspector ID of this issue tracking.
	 *
	 * @param inspectorId the inspector ID of this issue tracking
	 */
	public void setInspectorId(long inspectorId);

	/**
	 * Returns the vehicle class of this issue tracking.
	 *
	 * @return the vehicle class of this issue tracking
	 */
	@AutoEscape
	public String getVehicleClass();

	/**
	 * Sets the vehicle class of this issue tracking.
	 *
	 * @param vehicleClass the vehicle class of this issue tracking
	 */
	public void setVehicleClass(String vehicleClass);

	/**
	 * Returns the productcode of this issue tracking.
	 *
	 * @return the productcode of this issue tracking
	 */
	@AutoEscape
	public String getProductcode();

	/**
	 * Sets the productcode of this issue tracking.
	 *
	 * @param productcode the productcode of this issue tracking
	 */
	public void setProductcode(String productcode);

	/**
	 * Returns the productname of this issue tracking.
	 *
	 * @return the productname of this issue tracking
	 */
	@AutoEscape
	public String getProductname();

	/**
	 * Sets the productname of this issue tracking.
	 *
	 * @param productname the productname of this issue tracking
	 */
	public void setProductname(String productname);

	/**
	 * Returns the totalvehicle of this issue tracking.
	 *
	 * @return the totalvehicle of this issue tracking
	 */
	public long getTotalvehicle();

	/**
	 * Sets the totalvehicle of this issue tracking.
	 *
	 * @param totalvehicle the totalvehicle of this issue tracking
	 */
	public void setTotalvehicle(long totalvehicle);

	/**
	 * Returns the code number of this issue tracking.
	 *
	 * @return the code number of this issue tracking
	 */
	public long getCodeNumber();

	/**
	 * Sets the code number of this issue tracking.
	 *
	 * @param codeNumber the code number of this issue tracking
	 */
	public void setCodeNumber(long codeNumber);

	/**
	 * Returns the chassis number of this issue tracking.
	 *
	 * @return the chassis number of this issue tracking
	 */
	@AutoEscape
	public String getChassisNumber();

	/**
	 * Sets the chassis number of this issue tracking.
	 *
	 * @param chassisNumber the chassis number of this issue tracking
	 */
	public void setChassisNumber(String chassisNumber);

	/**
	 * Returns the engine number of this issue tracking.
	 *
	 * @return the engine number of this issue tracking
	 */
	@AutoEscape
	public String getEngineNumber();

	/**
	 * Sets the engine number of this issue tracking.
	 *
	 * @param engineNumber the engine number of this issue tracking
	 */
	public void setEngineNumber(String engineNumber);

	/**
	 * Returns the importedorassembled of this issue tracking.
	 *
	 * @return the importedorassembled of this issue tracking
	 */
	@AutoEscape
	public String getImportedorassembled();

	/**
	 * Sets the importedorassembled of this issue tracking.
	 *
	 * @param importedorassembled the importedorassembled of this issue tracking
	 */
	public void setImportedorassembled(String importedorassembled);

	/**
	 * Returns the issuetrackingfromcustomer of this issue tracking.
	 *
	 * @return the issuetrackingfromcustomer of this issue tracking
	 */
	@AutoEscape
	public String getIssuetrackingfromcustomer();

	/**
	 * Sets the issuetrackingfromcustomer of this issue tracking.
	 *
	 * @param issuetrackingfromcustomer the issuetrackingfromcustomer of this issue tracking
	 */
	public void setIssuetrackingfromcustomer(String issuetrackingfromcustomer);

	/**
	 * Returns the issuetrackingbycorporation of this issue tracking.
	 *
	 * @return the issuetrackingbycorporation of this issue tracking
	 */
	@AutoEscape
	public String getIssuetrackingbycorporation();

	/**
	 * Sets the issuetrackingbycorporation of this issue tracking.
	 *
	 * @param issuetrackingbycorporation the issuetrackingbycorporation of this issue tracking
	 */
	public void setIssuetrackingbycorporation(String issuetrackingbycorporation);

	/**
	 * Returns the issuetrackingbyimportedgroup of this issue tracking.
	 *
	 * @return the issuetrackingbyimportedgroup of this issue tracking
	 */
	@AutoEscape
	public String getIssuetrackingbyimportedgroup();

	/**
	 * Sets the issuetrackingbyimportedgroup of this issue tracking.
	 *
	 * @param issuetrackingbyimportedgroup the issuetrackingbyimportedgroup of this issue tracking
	 */
	public void setIssuetrackingbyimportedgroup(
		String issuetrackingbyimportedgroup);

	/**
	 * Returns the issuediscovery of this issue tracking.
	 *
	 * @return the issuediscovery of this issue tracking
	 */
	public long getIssuediscovery();

	/**
	 * Sets the issuediscovery of this issue tracking.
	 *
	 * @param issuediscovery the issuediscovery of this issue tracking
	 */
	public void setIssuediscovery(long issuediscovery);

	/**
	 * Returns the issuedescription of this issue tracking.
	 *
	 * @return the issuedescription of this issue tracking
	 */
	@AutoEscape
	public String getIssuedescription();

	/**
	 * Sets the issuedescription of this issue tracking.
	 *
	 * @param issuedescription the issuedescription of this issue tracking
	 */
	public void setIssuedescription(String issuedescription);

	/**
	 * Returns the issue v a q1reason of this issue tracking.
	 *
	 * @return the issue v a q1reason of this issue tracking
	 */
	@AutoEscape
	public String getIssueVAQ1reason();

	/**
	 * Sets the issue v a q1reason of this issue tracking.
	 *
	 * @param issueVAQ1reason the issue v a q1reason of this issue tracking
	 */
	public void setIssueVAQ1reason(String issueVAQ1reason);

	/**
	 * Returns the issue v a q2troubleshooting of this issue tracking.
	 *
	 * @return the issue v a q2troubleshooting of this issue tracking
	 */
	@AutoEscape
	public String getIssueVAQ2troubleshooting();

	/**
	 * Sets the issue v a q2troubleshooting of this issue tracking.
	 *
	 * @param issueVAQ2troubleshooting the issue v a q2troubleshooting of this issue tracking
	 */
	public void setIssueVAQ2troubleshooting(String issueVAQ2troubleshooting);

	/**
	 * Returns the issue v a q3longtermsolution of this issue tracking.
	 *
	 * @return the issue v a q3longtermsolution of this issue tracking
	 */
	@AutoEscape
	public String getIssueVAQ3longtermsolution();

	/**
	 * Sets the issue v a q3longtermsolution of this issue tracking.
	 *
	 * @param issueVAQ3longtermsolution the issue v a q3longtermsolution of this issue tracking
	 */
	public void setIssueVAQ3longtermsolution(String issueVAQ3longtermsolution);

	/**
	 * Returns the issue v a q4precaution of this issue tracking.
	 *
	 * @return the issue v a q4precaution of this issue tracking
	 */
	@AutoEscape
	public String getIssueVAQ4precaution();

	/**
	 * Sets the issue v a q4precaution of this issue tracking.
	 *
	 * @param issueVAQ4precaution the issue v a q4precaution of this issue tracking
	 */
	public void setIssueVAQ4precaution(String issueVAQ4precaution);

	/**
	 * Returns the creator of this issue tracking.
	 *
	 * @return the creator of this issue tracking
	 */
	@AutoEscape
	public String getCreator();

	/**
	 * Sets the creator of this issue tracking.
	 *
	 * @param creator the creator of this issue tracking
	 */
	public void setCreator(String creator);

	/**
	 * Returns the createddate of this issue tracking.
	 *
	 * @return the createddate of this issue tracking
	 */
	public Date getCreateddate();

	/**
	 * Sets the createddate of this issue tracking.
	 *
	 * @param createddate the createddate of this issue tracking
	 */
	public void setCreateddate(Date createddate);

	/**
	 * Returns the markupissue v a q4 of this issue tracking.
	 *
	 * @return the markupissue v a q4 of this issue tracking
	 */
	public int getMarkupissueVAQ4();

	/**
	 * Sets the markupissue v a q4 of this issue tracking.
	 *
	 * @param markupissueVAQ4 the markupissue v a q4 of this issue tracking
	 */
	public void setMarkupissueVAQ4(int markupissueVAQ4);

	/**
	 * Returns the maker v a q4 of this issue tracking.
	 *
	 * @return the maker v a q4 of this issue tracking
	 */
	@AutoEscape
	public String getMakerVAQ4();

	/**
	 * Sets the maker v a q4 of this issue tracking.
	 *
	 * @param makerVAQ4 the maker v a q4 of this issue tracking
	 */
	public void setMakerVAQ4(String makerVAQ4);

	/**
	 * Returns the checker v a q4 of this issue tracking.
	 *
	 * @return the checker v a q4 of this issue tracking
	 */
	@AutoEscape
	public String getCheckerVAQ4();

	/**
	 * Sets the checker v a q4 of this issue tracking.
	 *
	 * @param checkerVAQ4 the checker v a q4 of this issue tracking
	 */
	public void setCheckerVAQ4(String checkerVAQ4);

	/**
	 * Returns the approver v a q4 of this issue tracking.
	 *
	 * @return the approver v a q4 of this issue tracking
	 */
	@AutoEscape
	public String getApproverVAQ4();

	/**
	 * Sets the approver v a q4 of this issue tracking.
	 *
	 * @param approverVAQ4 the approver v a q4 of this issue tracking
	 */
	public void setApproverVAQ4(String approverVAQ4);

	/**
	 * Returns the maker v a q4modified of this issue tracking.
	 *
	 * @return the maker v a q4modified of this issue tracking
	 */
	public Date getMakerVAQ4modified();

	/**
	 * Sets the maker v a q4modified of this issue tracking.
	 *
	 * @param makerVAQ4modified the maker v a q4modified of this issue tracking
	 */
	public void setMakerVAQ4modified(Date makerVAQ4modified);

	/**
	 * Returns the checker v a q4modified of this issue tracking.
	 *
	 * @return the checker v a q4modified of this issue tracking
	 */
	public Date getCheckerVAQ4modified();

	/**
	 * Sets the checker v a q4modified of this issue tracking.
	 *
	 * @param checkerVAQ4modified the checker v a q4modified of this issue tracking
	 */
	public void setCheckerVAQ4modified(Date checkerVAQ4modified);

	/**
	 * Returns the approver v a q4modified of this issue tracking.
	 *
	 * @return the approver v a q4modified of this issue tracking
	 */
	public Date getApproverVAQ4modified();

	/**
	 * Sets the approver v a q4modified of this issue tracking.
	 *
	 * @param approverVAQ4modified the approver v a q4modified of this issue tracking
	 */
	public void setApproverVAQ4modified(Date approverVAQ4modified);

	/**
	 * Returns the markupissue v a q1 of this issue tracking.
	 *
	 * @return the markupissue v a q1 of this issue tracking
	 */
	public int getMarkupissueVAQ1();

	/**
	 * Sets the markupissue v a q1 of this issue tracking.
	 *
	 * @param markupissueVAQ1 the markupissue v a q1 of this issue tracking
	 */
	public void setMarkupissueVAQ1(int markupissueVAQ1);

	/**
	 * Returns the maker v a q1 of this issue tracking.
	 *
	 * @return the maker v a q1 of this issue tracking
	 */
	@AutoEscape
	public String getMakerVAQ1();

	/**
	 * Sets the maker v a q1 of this issue tracking.
	 *
	 * @param makerVAQ1 the maker v a q1 of this issue tracking
	 */
	public void setMakerVAQ1(String makerVAQ1);

	/**
	 * Returns the checker v a q1 of this issue tracking.
	 *
	 * @return the checker v a q1 of this issue tracking
	 */
	@AutoEscape
	public String getCheckerVAQ1();

	/**
	 * Sets the checker v a q1 of this issue tracking.
	 *
	 * @param checkerVAQ1 the checker v a q1 of this issue tracking
	 */
	public void setCheckerVAQ1(String checkerVAQ1);

	/**
	 * Returns the maker v a q1modified of this issue tracking.
	 *
	 * @return the maker v a q1modified of this issue tracking
	 */
	public Date getMakerVAQ1modified();

	/**
	 * Sets the maker v a q1modified of this issue tracking.
	 *
	 * @param makerVAQ1modified the maker v a q1modified of this issue tracking
	 */
	public void setMakerVAQ1modified(Date makerVAQ1modified);

	/**
	 * Returns the checker v a q1modified of this issue tracking.
	 *
	 * @return the checker v a q1modified of this issue tracking
	 */
	public Date getCheckerVAQ1modified();

	/**
	 * Sets the checker v a q1modified of this issue tracking.
	 *
	 * @param checkerVAQ1modified the checker v a q1modified of this issue tracking
	 */
	public void setCheckerVAQ1modified(Date checkerVAQ1modified);

	/**
	 * Returns the markupissue v a q2 of this issue tracking.
	 *
	 * @return the markupissue v a q2 of this issue tracking
	 */
	public int getMarkupissueVAQ2();

	/**
	 * Sets the markupissue v a q2 of this issue tracking.
	 *
	 * @param markupissueVAQ2 the markupissue v a q2 of this issue tracking
	 */
	public void setMarkupissueVAQ2(int markupissueVAQ2);

	/**
	 * Returns the maker v a q2 of this issue tracking.
	 *
	 * @return the maker v a q2 of this issue tracking
	 */
	@AutoEscape
	public String getMakerVAQ2();

	/**
	 * Sets the maker v a q2 of this issue tracking.
	 *
	 * @param makerVAQ2 the maker v a q2 of this issue tracking
	 */
	public void setMakerVAQ2(String makerVAQ2);

	/**
	 * Returns the checker v a q2 of this issue tracking.
	 *
	 * @return the checker v a q2 of this issue tracking
	 */
	@AutoEscape
	public String getCheckerVAQ2();

	/**
	 * Sets the checker v a q2 of this issue tracking.
	 *
	 * @param checkerVAQ2 the checker v a q2 of this issue tracking
	 */
	public void setCheckerVAQ2(String checkerVAQ2);

	/**
	 * Returns the maker v a q2modified of this issue tracking.
	 *
	 * @return the maker v a q2modified of this issue tracking
	 */
	public Date getMakerVAQ2modified();

	/**
	 * Sets the maker v a q2modified of this issue tracking.
	 *
	 * @param makerVAQ2modified the maker v a q2modified of this issue tracking
	 */
	public void setMakerVAQ2modified(Date makerVAQ2modified);

	/**
	 * Returns the checker v a q2modified of this issue tracking.
	 *
	 * @return the checker v a q2modified of this issue tracking
	 */
	public Date getCheckerVAQ2modified();

	/**
	 * Sets the checker v a q2modified of this issue tracking.
	 *
	 * @param checkerVAQ2modified the checker v a q2modified of this issue tracking
	 */
	public void setCheckerVAQ2modified(Date checkerVAQ2modified);

	/**
	 * Returns the markupissue v a q3 of this issue tracking.
	 *
	 * @return the markupissue v a q3 of this issue tracking
	 */
	public int getMarkupissueVAQ3();

	/**
	 * Sets the markupissue v a q3 of this issue tracking.
	 *
	 * @param markupissueVAQ3 the markupissue v a q3 of this issue tracking
	 */
	public void setMarkupissueVAQ3(int markupissueVAQ3);

	/**
	 * Returns the maker v a q3 of this issue tracking.
	 *
	 * @return the maker v a q3 of this issue tracking
	 */
	@AutoEscape
	public String getMakerVAQ3();

	/**
	 * Sets the maker v a q3 of this issue tracking.
	 *
	 * @param makerVAQ3 the maker v a q3 of this issue tracking
	 */
	public void setMakerVAQ3(String makerVAQ3);

	/**
	 * Returns the checker v a q3 of this issue tracking.
	 *
	 * @return the checker v a q3 of this issue tracking
	 */
	@AutoEscape
	public String getCheckerVAQ3();

	/**
	 * Sets the checker v a q3 of this issue tracking.
	 *
	 * @param checkerVAQ3 the checker v a q3 of this issue tracking
	 */
	public void setCheckerVAQ3(String checkerVAQ3);

	/**
	 * Returns the approver v a q3 of this issue tracking.
	 *
	 * @return the approver v a q3 of this issue tracking
	 */
	@AutoEscape
	public String getApproverVAQ3();

	/**
	 * Sets the approver v a q3 of this issue tracking.
	 *
	 * @param approverVAQ3 the approver v a q3 of this issue tracking
	 */
	public void setApproverVAQ3(String approverVAQ3);

	/**
	 * Returns the maker v a q3modified of this issue tracking.
	 *
	 * @return the maker v a q3modified of this issue tracking
	 */
	public Date getMakerVAQ3modified();

	/**
	 * Sets the maker v a q3modified of this issue tracking.
	 *
	 * @param makerVAQ3modified the maker v a q3modified of this issue tracking
	 */
	public void setMakerVAQ3modified(Date makerVAQ3modified);

	/**
	 * Returns the checker v a q3modified of this issue tracking.
	 *
	 * @return the checker v a q3modified of this issue tracking
	 */
	public Date getCheckerVAQ3modified();

	/**
	 * Sets the checker v a q3modified of this issue tracking.
	 *
	 * @param checkerVAQ3modified the checker v a q3modified of this issue tracking
	 */
	public void setCheckerVAQ3modified(Date checkerVAQ3modified);

	/**
	 * Returns the approver v a q3modified of this issue tracking.
	 *
	 * @return the approver v a q3modified of this issue tracking
	 */
	public Date getApproverVAQ3modified();

	/**
	 * Sets the approver v a q3modified of this issue tracking.
	 *
	 * @param approverVAQ3modified the approver v a q3modified of this issue tracking
	 */
	public void setApproverVAQ3modified(Date approverVAQ3modified);

	/**
	 * Returns the defect status of this issue tracking.
	 *
	 * @return the defect status of this issue tracking
	 */
	public int getDefectStatus();

	/**
	 * Sets the defect status of this issue tracking.
	 *
	 * @param defectStatus the defect status of this issue tracking
	 */
	public void setDefectStatus(int defectStatus);

	/**
	 * Returns the synchdate of this issue tracking.
	 *
	 * @return the synchdate of this issue tracking
	 */
	public Date getSynchdate();

	/**
	 * Sets the synchdate of this issue tracking.
	 *
	 * @param synchdate the synchdate of this issue tracking
	 */
	public void setSynchdate(Date synchdate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		vn.dtt.gt.dk.dao.nghiepvu.model.IssueTracking issueTracking);

	@Override
	public int hashCode();

	@Override
	public CacheModel<vn.dtt.gt.dk.dao.nghiepvu.model.IssueTracking> toCacheModel();

	@Override
	public vn.dtt.gt.dk.dao.nghiepvu.model.IssueTracking toEscapedModel();

	@Override
	public vn.dtt.gt.dk.dao.nghiepvu.model.IssueTracking toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}