/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.gt.dk.dao.nghiepvu.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ProductionCountry service. Represents a row in the &quot;vr_productioncountry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.dtt.gt.dk.dao.nghiepvu.model.impl.ProductionCountryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.dtt.gt.dk.dao.nghiepvu.model.impl.ProductionCountryImpl}.
 * </p>
 *
 * @author win_64
 * @see ProductionCountry
 * @see vn.dtt.gt.dk.dao.nghiepvu.model.impl.ProductionCountryImpl
 * @see vn.dtt.gt.dk.dao.nghiepvu.model.impl.ProductionCountryModelImpl
 * @generated
 */
public interface ProductionCountryModel extends BaseModel<ProductionCountry> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a production country model instance should use the {@link ProductionCountry} interface instead.
	 */

	/**
	 * Returns the primary key of this production country.
	 *
	 * @return the primary key of this production country
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this production country.
	 *
	 * @param primaryKey the primary key of this production country
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this production country.
	 *
	 * @return the ID of this production country
	 */
	public long getId();

	/**
	 * Sets the ID of this production country.
	 *
	 * @param id the ID of this production country
	 */
	public void setId(long id);

	/**
	 * Returns the vehicle group ID of this production country.
	 *
	 * @return the vehicle group ID of this production country
	 */
	public long getVehicleGroupId();

	/**
	 * Sets the vehicle group ID of this production country.
	 *
	 * @param vehicleGroupId the vehicle group ID of this production country
	 */
	public void setVehicleGroupId(long vehicleGroupId);

	/**
	 * Returns the country code of this production country.
	 *
	 * @return the country code of this production country
	 */
	@AutoEscape
	public String getCountryCode();

	/**
	 * Sets the country code of this production country.
	 *
	 * @param countryCode the country code of this production country
	 */
	public void setCountryCode(String countryCode);

	/**
	 * Returns the synch date of this production country.
	 *
	 * @return the synch date of this production country
	 */
	public Date getSynchDate();

	/**
	 * Sets the synch date of this production country.
	 *
	 * @param SynchDate the synch date of this production country
	 */
	public void setSynchDate(Date SynchDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ProductionCountry productionCountry);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ProductionCountry> toCacheModel();

	@Override
	public ProductionCountry toEscapedModel();

	@Override
	public ProductionCountry toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}