/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.gt.dk.dao.nghiepvu.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the THONGSOCHUNGCHIDONGCO service. Represents a row in the &quot;thongsochungchi_dongco&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.dtt.gt.dk.dao.nghiepvu.model.impl.THONGSOCHUNGCHIDONGCOModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.dtt.gt.dk.dao.nghiepvu.model.impl.THONGSOCHUNGCHIDONGCOImpl}.
 * </p>
 *
 * @author win_64
 * @see THONGSOCHUNGCHIDONGCO
 * @see vn.dtt.gt.dk.dao.nghiepvu.model.impl.THONGSOCHUNGCHIDONGCOImpl
 * @see vn.dtt.gt.dk.dao.nghiepvu.model.impl.THONGSOCHUNGCHIDONGCOModelImpl
 * @generated
 */
public interface THONGSOCHUNGCHIDONGCOModel extends BaseModel<THONGSOCHUNGCHIDONGCO> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a t h o n g s o c h u n g c h i d o n g c o model instance should use the {@link THONGSOCHUNGCHIDONGCO} interface instead.
	 */

	/**
	 * Returns the primary key of this t h o n g s o c h u n g c h i d o n g c o.
	 *
	 * @return the primary key of this t h o n g s o c h u n g c h i d o n g c o
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this t h o n g s o c h u n g c h i d o n g c o.
	 *
	 * @param primaryKey the primary key of this t h o n g s o c h u n g c h i d o n g c o
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this t h o n g s o c h u n g c h i d o n g c o.
	 *
	 * @return the ID of this t h o n g s o c h u n g c h i d o n g c o
	 */
	public long getId();

	/**
	 * Sets the ID of this t h o n g s o c h u n g c h i d o n g c o.
	 *
	 * @param id the ID of this t h o n g s o c h u n g c h i d o n g c o
	 */
	public void setId(long id);

	/**
	 * Returns the ho so thu tuc ID of this t h o n g s o c h u n g c h i d o n g c o.
	 *
	 * @return the ho so thu tuc ID of this t h o n g s o c h u n g c h i d o n g c o
	 */
	public long getHoSoThuTucId();

	/**
	 * Sets the ho so thu tuc ID of this t h o n g s o c h u n g c h i d o n g c o.
	 *
	 * @param hoSoThuTucId the ho so thu tuc ID of this t h o n g s o c h u n g c h i d o n g c o
	 */
	public void setHoSoThuTucId(long hoSoThuTucId);

	/**
	 * Returns the certificate record ID of this t h o n g s o c h u n g c h i d o n g c o.
	 *
	 * @return the certificate record ID of this t h o n g s o c h u n g c h i d o n g c o
	 */
	public long getCertificateRecordId();

	/**
	 * Sets the certificate record ID of this t h o n g s o c h u n g c h i d o n g c o.
	 *
	 * @param certificateRecordId the certificate record ID of this t h o n g s o c h u n g c h i d o n g c o
	 */
	public void setCertificateRecordId(long certificateRecordId);

	/**
	 * Returns the vehicle group ID of this t h o n g s o c h u n g c h i d o n g c o.
	 *
	 * @return the vehicle group ID of this t h o n g s o c h u n g c h i d o n g c o
	 */
	public long getVehicleGroupId();

	/**
	 * Sets the vehicle group ID of this t h o n g s o c h u n g c h i d o n g c o.
	 *
	 * @param vehicleGroupId the vehicle group ID of this t h o n g s o c h u n g c h i d o n g c o
	 */
	public void setVehicleGroupId(long vehicleGroupId);

	/**
	 * Returns the synch date of this t h o n g s o c h u n g c h i d o n g c o.
	 *
	 * @return the synch date of this t h o n g s o c h u n g c h i d o n g c o
	 */
	public Date getSynchDate();

	/**
	 * Sets the synch date of this t h o n g s o c h u n g c h i d o n g c o.
	 *
	 * @param SynchDate the synch date of this t h o n g s o c h u n g c h i d o n g c o
	 */
	public void setSynchDate(Date SynchDate);

	/**
	 * Returns the d c x0007 of this t h o n g s o c h u n g c h i d o n g c o.
	 *
	 * @return the d c x0007 of this t h o n g s o c h u n g c h i d o n g c o
	 */
	@AutoEscape
	public String getDCX0007();

	/**
	 * Sets the d c x0007 of this t h o n g s o c h u n g c h i d o n g c o.
	 *
	 * @param DCX0007 the d c x0007 of this t h o n g s o c h u n g c h i d o n g c o
	 */
	public void setDCX0007(String DCX0007);

	/**
	 * Returns the d c x0008 of this t h o n g s o c h u n g c h i d o n g c o.
	 *
	 * @return the d c x0008 of this t h o n g s o c h u n g c h i d o n g c o
	 */
	@AutoEscape
	public String getDCX0008();

	/**
	 * Sets the d c x0008 of this t h o n g s o c h u n g c h i d o n g c o.
	 *
	 * @param DCX0008 the d c x0008 of this t h o n g s o c h u n g c h i d o n g c o
	 */
	public void setDCX0008(String DCX0008);

	/**
	 * Returns the d c x0010 of this t h o n g s o c h u n g c h i d o n g c o.
	 *
	 * @return the d c x0010 of this t h o n g s o c h u n g c h i d o n g c o
	 */
	@AutoEscape
	public String getDCX0010();

	/**
	 * Sets the d c x0010 of this t h o n g s o c h u n g c h i d o n g c o.
	 *
	 * @param DCX0010 the d c x0010 of this t h o n g s o c h u n g c h i d o n g c o
	 */
	public void setDCX0010(String DCX0010);

	/**
	 * Returns the d c x0011 of this t h o n g s o c h u n g c h i d o n g c o.
	 *
	 * @return the d c x0011 of this t h o n g s o c h u n g c h i d o n g c o
	 */
	@AutoEscape
	public String getDCX0011();

	/**
	 * Sets the d c x0011 of this t h o n g s o c h u n g c h i d o n g c o.
	 *
	 * @param DCX0011 the d c x0011 of this t h o n g s o c h u n g c h i d o n g c o
	 */
	public void setDCX0011(String DCX0011);

	/**
	 * Returns the d c x0012 of this t h o n g s o c h u n g c h i d o n g c o.
	 *
	 * @return the d c x0012 of this t h o n g s o c h u n g c h i d o n g c o
	 */
	@AutoEscape
	public String getDCX0012();

	/**
	 * Sets the d c x0012 of this t h o n g s o c h u n g c h i d o n g c o.
	 *
	 * @param DCX0012 the d c x0012 of this t h o n g s o c h u n g c h i d o n g c o
	 */
	public void setDCX0012(String DCX0012);

	/**
	 * Returns the d c x1012 of this t h o n g s o c h u n g c h i d o n g c o.
	 *
	 * @return the d c x1012 of this t h o n g s o c h u n g c h i d o n g c o
	 */
	@AutoEscape
	public String getDCX1012();

	/**
	 * Sets the d c x1012 of this t h o n g s o c h u n g c h i d o n g c o.
	 *
	 * @param DCX1012 the d c x1012 of this t h o n g s o c h u n g c h i d o n g c o
	 */
	public void setDCX1012(String DCX1012);

	/**
	 * Returns the d c x0013 of this t h o n g s o c h u n g c h i d o n g c o.
	 *
	 * @return the d c x0013 of this t h o n g s o c h u n g c h i d o n g c o
	 */
	@AutoEscape
	public String getDCX0013();

	/**
	 * Sets the d c x0013 of this t h o n g s o c h u n g c h i d o n g c o.
	 *
	 * @param DCX0013 the d c x0013 of this t h o n g s o c h u n g c h i d o n g c o
	 */
	public void setDCX0013(String DCX0013);

	/**
	 * Returns the d c x1013 of this t h o n g s o c h u n g c h i d o n g c o.
	 *
	 * @return the d c x1013 of this t h o n g s o c h u n g c h i d o n g c o
	 */
	@AutoEscape
	public String getDCX1013();

	/**
	 * Sets the d c x1013 of this t h o n g s o c h u n g c h i d o n g c o.
	 *
	 * @param DCX1013 the d c x1013 of this t h o n g s o c h u n g c h i d o n g c o
	 */
	public void setDCX1013(String DCX1013);

	/**
	 * Returns the d c x0014 of this t h o n g s o c h u n g c h i d o n g c o.
	 *
	 * @return the d c x0014 of this t h o n g s o c h u n g c h i d o n g c o
	 */
	@AutoEscape
	public String getDCX0014();

	/**
	 * Sets the d c x0014 of this t h o n g s o c h u n g c h i d o n g c o.
	 *
	 * @param DCX0014 the d c x0014 of this t h o n g s o c h u n g c h i d o n g c o
	 */
	public void setDCX0014(String DCX0014);

	/**
	 * Returns the d c x0015 of this t h o n g s o c h u n g c h i d o n g c o.
	 *
	 * @return the d c x0015 of this t h o n g s o c h u n g c h i d o n g c o
	 */
	@AutoEscape
	public String getDCX0015();

	/**
	 * Sets the d c x0015 of this t h o n g s o c h u n g c h i d o n g c o.
	 *
	 * @param DCX0015 the d c x0015 of this t h o n g s o c h u n g c h i d o n g c o
	 */
	public void setDCX0015(String DCX0015);

	/**
	 * Returns the d c x0016 of this t h o n g s o c h u n g c h i d o n g c o.
	 *
	 * @return the d c x0016 of this t h o n g s o c h u n g c h i d o n g c o
	 */
	@AutoEscape
	public String getDCX0016();

	/**
	 * Sets the d c x0016 of this t h o n g s o c h u n g c h i d o n g c o.
	 *
	 * @param DCX0016 the d c x0016 of this t h o n g s o c h u n g c h i d o n g c o
	 */
	public void setDCX0016(String DCX0016);

	/**
	 * Returns the d c x0017 of this t h o n g s o c h u n g c h i d o n g c o.
	 *
	 * @return the d c x0017 of this t h o n g s o c h u n g c h i d o n g c o
	 */
	@AutoEscape
	public String getDCX0017();

	/**
	 * Sets the d c x0017 of this t h o n g s o c h u n g c h i d o n g c o.
	 *
	 * @param DCX0017 the d c x0017 of this t h o n g s o c h u n g c h i d o n g c o
	 */
	public void setDCX0017(String DCX0017);

	/**
	 * Returns the d c x0018 of this t h o n g s o c h u n g c h i d o n g c o.
	 *
	 * @return the d c x0018 of this t h o n g s o c h u n g c h i d o n g c o
	 */
	@AutoEscape
	public String getDCX0018();

	/**
	 * Sets the d c x0018 of this t h o n g s o c h u n g c h i d o n g c o.
	 *
	 * @param DCX0018 the d c x0018 of this t h o n g s o c h u n g c h i d o n g c o
	 */
	public void setDCX0018(String DCX0018);

	/**
	 * Returns the d c x0019 of this t h o n g s o c h u n g c h i d o n g c o.
	 *
	 * @return the d c x0019 of this t h o n g s o c h u n g c h i d o n g c o
	 */
	@AutoEscape
	public String getDCX0019();

	/**
	 * Sets the d c x0019 of this t h o n g s o c h u n g c h i d o n g c o.
	 *
	 * @param DCX0019 the d c x0019 of this t h o n g s o c h u n g c h i d o n g c o
	 */
	public void setDCX0019(String DCX0019);

	/**
	 * Returns the d c x0021 of this t h o n g s o c h u n g c h i d o n g c o.
	 *
	 * @return the d c x0021 of this t h o n g s o c h u n g c h i d o n g c o
	 */
	@AutoEscape
	public String getDCX0021();

	/**
	 * Sets the d c x0021 of this t h o n g s o c h u n g c h i d o n g c o.
	 *
	 * @param DCX0021 the d c x0021 of this t h o n g s o c h u n g c h i d o n g c o
	 */
	public void setDCX0021(String DCX0021);

	/**
	 * Returns the d c x0022 of this t h o n g s o c h u n g c h i d o n g c o.
	 *
	 * @return the d c x0022 of this t h o n g s o c h u n g c h i d o n g c o
	 */
	@AutoEscape
	public String getDCX0022();

	/**
	 * Sets the d c x0022 of this t h o n g s o c h u n g c h i d o n g c o.
	 *
	 * @param DCX0022 the d c x0022 of this t h o n g s o c h u n g c h i d o n g c o
	 */
	public void setDCX0022(String DCX0022);

	/**
	 * Returns the d c x0023 of this t h o n g s o c h u n g c h i d o n g c o.
	 *
	 * @return the d c x0023 of this t h o n g s o c h u n g c h i d o n g c o
	 */
	@AutoEscape
	public String getDCX0023();

	/**
	 * Sets the d c x0023 of this t h o n g s o c h u n g c h i d o n g c o.
	 *
	 * @param DCX0023 the d c x0023 of this t h o n g s o c h u n g c h i d o n g c o
	 */
	public void setDCX0023(String DCX0023);

	/**
	 * Returns the d c x0024 of this t h o n g s o c h u n g c h i d o n g c o.
	 *
	 * @return the d c x0024 of this t h o n g s o c h u n g c h i d o n g c o
	 */
	@AutoEscape
	public String getDCX0024();

	/**
	 * Sets the d c x0024 of this t h o n g s o c h u n g c h i d o n g c o.
	 *
	 * @param DCX0024 the d c x0024 of this t h o n g s o c h u n g c h i d o n g c o
	 */
	public void setDCX0024(String DCX0024);

	/**
	 * Returns the d c x0006 of this t h o n g s o c h u n g c h i d o n g c o.
	 *
	 * @return the d c x0006 of this t h o n g s o c h u n g c h i d o n g c o
	 */
	@AutoEscape
	public String getDCX0006();

	/**
	 * Sets the d c x0006 of this t h o n g s o c h u n g c h i d o n g c o.
	 *
	 * @param DCX0006 the d c x0006 of this t h o n g s o c h u n g c h i d o n g c o
	 */
	public void setDCX0006(String DCX0006);

	/**
	 * Returns the d c x0025 of this t h o n g s o c h u n g c h i d o n g c o.
	 *
	 * @return the d c x0025 of this t h o n g s o c h u n g c h i d o n g c o
	 */
	@AutoEscape
	public String getDCX0025();

	/**
	 * Sets the d c x0025 of this t h o n g s o c h u n g c h i d o n g c o.
	 *
	 * @param DCX0025 the d c x0025 of this t h o n g s o c h u n g c h i d o n g c o
	 */
	public void setDCX0025(String DCX0025);

	/**
	 * Returns the d c x0026 of this t h o n g s o c h u n g c h i d o n g c o.
	 *
	 * @return the d c x0026 of this t h o n g s o c h u n g c h i d o n g c o
	 */
	@AutoEscape
	public String getDCX0026();

	/**
	 * Sets the d c x0026 of this t h o n g s o c h u n g c h i d o n g c o.
	 *
	 * @param DCX0026 the d c x0026 of this t h o n g s o c h u n g c h i d o n g c o
	 */
	public void setDCX0026(String DCX0026);

	/**
	 * Returns the d c x0027 of this t h o n g s o c h u n g c h i d o n g c o.
	 *
	 * @return the d c x0027 of this t h o n g s o c h u n g c h i d o n g c o
	 */
	@AutoEscape
	public String getDCX0027();

	/**
	 * Sets the d c x0027 of this t h o n g s o c h u n g c h i d o n g c o.
	 *
	 * @param DCX0027 the d c x0027 of this t h o n g s o c h u n g c h i d o n g c o
	 */
	public void setDCX0027(String DCX0027);

	/**
	 * Returns the d c x0028 of this t h o n g s o c h u n g c h i d o n g c o.
	 *
	 * @return the d c x0028 of this t h o n g s o c h u n g c h i d o n g c o
	 */
	@AutoEscape
	public String getDCX0028();

	/**
	 * Sets the d c x0028 of this t h o n g s o c h u n g c h i d o n g c o.
	 *
	 * @param DCX0028 the d c x0028 of this t h o n g s o c h u n g c h i d o n g c o
	 */
	public void setDCX0028(String DCX0028);

	/**
	 * Returns the d c x0029 of this t h o n g s o c h u n g c h i d o n g c o.
	 *
	 * @return the d c x0029 of this t h o n g s o c h u n g c h i d o n g c o
	 */
	@AutoEscape
	public String getDCX0029();

	/**
	 * Sets the d c x0029 of this t h o n g s o c h u n g c h i d o n g c o.
	 *
	 * @param DCX0029 the d c x0029 of this t h o n g s o c h u n g c h i d o n g c o
	 */
	public void setDCX0029(String DCX0029);

	/**
	 * Returns the d c x0030 of this t h o n g s o c h u n g c h i d o n g c o.
	 *
	 * @return the d c x0030 of this t h o n g s o c h u n g c h i d o n g c o
	 */
	@AutoEscape
	public String getDCX0030();

	/**
	 * Sets the d c x0030 of this t h o n g s o c h u n g c h i d o n g c o.
	 *
	 * @param DCX0030 the d c x0030 of this t h o n g s o c h u n g c h i d o n g c o
	 */
	public void setDCX0030(String DCX0030);

	/**
	 * Returns the d c x0031 of this t h o n g s o c h u n g c h i d o n g c o.
	 *
	 * @return the d c x0031 of this t h o n g s o c h u n g c h i d o n g c o
	 */
	@AutoEscape
	public String getDCX0031();

	/**
	 * Sets the d c x0031 of this t h o n g s o c h u n g c h i d o n g c o.
	 *
	 * @param DCX0031 the d c x0031 of this t h o n g s o c h u n g c h i d o n g c o
	 */
	public void setDCX0031(String DCX0031);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(THONGSOCHUNGCHIDONGCO thongsochungchidongco);

	@Override
	public int hashCode();

	@Override
	public CacheModel<THONGSOCHUNGCHIDONGCO> toCacheModel();

	@Override
	public THONGSOCHUNGCHIDONGCO toEscapedModel();

	@Override
	public THONGSOCHUNGCHIDONGCO toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}