/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.gt.dk.dao.nghiepvu.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the THONGSOCHUNGCHIXECOGIOI service. Represents a row in the &quot;thongsochungchi_xecogioi&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.dtt.gt.dk.dao.nghiepvu.model.impl.THONGSOCHUNGCHIXECOGIOIModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.dtt.gt.dk.dao.nghiepvu.model.impl.THONGSOCHUNGCHIXECOGIOIImpl}.
 * </p>
 *
 * @author win_64
 * @see THONGSOCHUNGCHIXECOGIOI
 * @see vn.dtt.gt.dk.dao.nghiepvu.model.impl.THONGSOCHUNGCHIXECOGIOIImpl
 * @see vn.dtt.gt.dk.dao.nghiepvu.model.impl.THONGSOCHUNGCHIXECOGIOIModelImpl
 * @generated
 */
public interface THONGSOCHUNGCHIXECOGIOIModel extends BaseModel<THONGSOCHUNGCHIXECOGIOI> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a t h o n g s o c h u n g c h i x e c o g i o i model instance should use the {@link THONGSOCHUNGCHIXECOGIOI} interface instead.
	 */

	/**
	 * Returns the primary key of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the primary key of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param primaryKey the primary key of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the ID of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public long getId();

	/**
	 * Sets the ID of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param id the ID of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setId(long id);

	/**
	 * Returns the ho so thu tuc ID of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the ho so thu tuc ID of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public long getHoSoThuTucId();

	/**
	 * Sets the ho so thu tuc ID of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param hoSoThuTucId the ho so thu tuc ID of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setHoSoThuTucId(long hoSoThuTucId);

	/**
	 * Returns the certificate record ID of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the certificate record ID of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public long getCertificateRecordId();

	/**
	 * Sets the certificate record ID of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param certificateRecordId the certificate record ID of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setCertificateRecordId(long certificateRecordId);

	/**
	 * Returns the vehicle group ID of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the vehicle group ID of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public long getVehicleGroupId();

	/**
	 * Sets the vehicle group ID of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param vehicleGroupId the vehicle group ID of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setVehicleGroupId(long vehicleGroupId);

	/**
	 * Returns the synch date of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the synch date of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public Date getSynchDate();

	/**
	 * Sets the synch date of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param SynchDate the synch date of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setSynchDate(Date SynchDate);

	/**
	 * Returns the x c g0009 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0009 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0009();

	/**
	 * Sets the x c g0009 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0009 the x c g0009 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0009(String XCG0009);

	/**
	 * Returns the x c g0010 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0010 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0010();

	/**
	 * Sets the x c g0010 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0010 the x c g0010 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0010(String XCG0010);

	/**
	 * Returns the x c g0011 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0011 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0011();

	/**
	 * Sets the x c g0011 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0011 the x c g0011 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0011(String XCG0011);

	/**
	 * Returns the x c g0012 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0012 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0012();

	/**
	 * Sets the x c g0012 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0012 the x c g0012 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0012(String XCG0012);

	/**
	 * Returns the x c g0013 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0013 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0013();

	/**
	 * Sets the x c g0013 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0013 the x c g0013 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0013(String XCG0013);

	/**
	 * Returns the x c g0014 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0014 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0014();

	/**
	 * Sets the x c g0014 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0014 the x c g0014 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0014(String XCG0014);

	/**
	 * Returns the x c g0015 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0015 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0015();

	/**
	 * Sets the x c g0015 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0015 the x c g0015 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0015(String XCG0015);

	/**
	 * Returns the x c g0016 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0016 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0016();

	/**
	 * Sets the x c g0016 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0016 the x c g0016 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0016(String XCG0016);

	/**
	 * Returns the x c g0017 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0017 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0017();

	/**
	 * Sets the x c g0017 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0017 the x c g0017 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0017(String XCG0017);

	/**
	 * Returns the x c g0018 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0018 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0018();

	/**
	 * Sets the x c g0018 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0018 the x c g0018 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0018(String XCG0018);

	/**
	 * Returns the x c g0019 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0019 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0019();

	/**
	 * Sets the x c g0019 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0019 the x c g0019 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0019(String XCG0019);

	/**
	 * Returns the x c g0020 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0020 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0020();

	/**
	 * Sets the x c g0020 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0020 the x c g0020 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0020(String XCG0020);

	/**
	 * Returns the x c g0021 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0021 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0021();

	/**
	 * Sets the x c g0021 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0021 the x c g0021 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0021(String XCG0021);

	/**
	 * Returns the x c g1021 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g1021 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG1021();

	/**
	 * Sets the x c g1021 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG1021 the x c g1021 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG1021(String XCG1021);

	/**
	 * Returns the x c g1121 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g1121 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG1121();

	/**
	 * Sets the x c g1121 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG1121 the x c g1121 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG1121(String XCG1121);

	/**
	 * Returns the x c g0022 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0022 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0022();

	/**
	 * Sets the x c g0022 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0022 the x c g0022 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0022(String XCG0022);

	/**
	 * Returns the x c g1022 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g1022 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG1022();

	/**
	 * Sets the x c g1022 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG1022 the x c g1022 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG1022(String XCG1022);

	/**
	 * Returns the x c g1122 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g1122 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG1122();

	/**
	 * Sets the x c g1122 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG1122 the x c g1122 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG1122(String XCG1122);

	/**
	 * Returns the x c g0023 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0023 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0023();

	/**
	 * Sets the x c g0023 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0023 the x c g0023 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0023(String XCG0023);

	/**
	 * Returns the x c g1023 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g1023 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG1023();

	/**
	 * Sets the x c g1023 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG1023 the x c g1023 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG1023(String XCG1023);

	/**
	 * Returns the x c g1123 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g1123 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG1123();

	/**
	 * Sets the x c g1123 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG1123 the x c g1123 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG1123(String XCG1123);

	/**
	 * Returns the x c g0024 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0024 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0024();

	/**
	 * Sets the x c g0024 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0024 the x c g0024 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0024(String XCG0024);

	/**
	 * Returns the x c g1024 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g1024 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG1024();

	/**
	 * Sets the x c g1024 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG1024 the x c g1024 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG1024(String XCG1024);

	/**
	 * Returns the x c g1124 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g1124 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG1124();

	/**
	 * Sets the x c g1124 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG1124 the x c g1124 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG1124(String XCG1124);

	/**
	 * Returns the x c g0025 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0025 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0025();

	/**
	 * Sets the x c g0025 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0025 the x c g0025 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0025(String XCG0025);

	/**
	 * Returns the x c g1025 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g1025 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG1025();

	/**
	 * Sets the x c g1025 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG1025 the x c g1025 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG1025(String XCG1025);

	/**
	 * Returns the x c g1125 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g1125 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG1125();

	/**
	 * Sets the x c g1125 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG1125 the x c g1125 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG1125(String XCG1125);

	/**
	 * Returns the x c g0026 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0026 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0026();

	/**
	 * Sets the x c g0026 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0026 the x c g0026 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0026(String XCG0026);

	/**
	 * Returns the x c g1026 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g1026 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG1026();

	/**
	 * Sets the x c g1026 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG1026 the x c g1026 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG1026(String XCG1026);

	/**
	 * Returns the x c g1126 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g1126 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG1126();

	/**
	 * Sets the x c g1126 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG1126 the x c g1126 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG1126(String XCG1126);

	/**
	 * Returns the x c g0027 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0027 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0027();

	/**
	 * Sets the x c g0027 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0027 the x c g0027 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0027(String XCG0027);

	/**
	 * Returns the x c g1027 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g1027 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG1027();

	/**
	 * Sets the x c g1027 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG1027 the x c g1027 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG1027(String XCG1027);

	/**
	 * Returns the x c g1127 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g1127 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG1127();

	/**
	 * Sets the x c g1127 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG1127 the x c g1127 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG1127(String XCG1127);

	/**
	 * Returns the x c g0028 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0028 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0028();

	/**
	 * Sets the x c g0028 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0028 the x c g0028 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0028(String XCG0028);

	/**
	 * Returns the x c g1028 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g1028 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG1028();

	/**
	 * Sets the x c g1028 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG1028 the x c g1028 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG1028(String XCG1028);

	/**
	 * Returns the x c g1128 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g1128 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG1128();

	/**
	 * Sets the x c g1128 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG1128 the x c g1128 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG1128(String XCG1128);

	/**
	 * Returns the x c g0029 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0029 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0029();

	/**
	 * Sets the x c g0029 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0029 the x c g0029 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0029(String XCG0029);

	/**
	 * Returns the x c g1029 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g1029 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG1029();

	/**
	 * Sets the x c g1029 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG1029 the x c g1029 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG1029(String XCG1029);

	/**
	 * Returns the x c g1129 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g1129 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG1129();

	/**
	 * Sets the x c g1129 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG1129 the x c g1129 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG1129(String XCG1129);

	/**
	 * Returns the x c g0030 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0030 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0030();

	/**
	 * Sets the x c g0030 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0030 the x c g0030 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0030(String XCG0030);

	/**
	 * Returns the x c g1030 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g1030 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG1030();

	/**
	 * Sets the x c g1030 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG1030 the x c g1030 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG1030(String XCG1030);

	/**
	 * Returns the x c g1130 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g1130 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG1130();

	/**
	 * Sets the x c g1130 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG1130 the x c g1130 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG1130(String XCG1130);

	/**
	 * Returns the x c g0031 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0031 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0031();

	/**
	 * Sets the x c g0031 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0031 the x c g0031 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0031(String XCG0031);

	/**
	 * Returns the x c g1031 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g1031 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG1031();

	/**
	 * Sets the x c g1031 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG1031 the x c g1031 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG1031(String XCG1031);

	/**
	 * Returns the x c g1131 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g1131 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG1131();

	/**
	 * Sets the x c g1131 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG1131 the x c g1131 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG1131(String XCG1131);

	/**
	 * Returns the x c g0032 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0032 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0032();

	/**
	 * Sets the x c g0032 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0032 the x c g0032 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0032(String XCG0032);

	/**
	 * Returns the x c g1032 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g1032 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG1032();

	/**
	 * Sets the x c g1032 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG1032 the x c g1032 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG1032(String XCG1032);

	/**
	 * Returns the x c g1132 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g1132 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG1132();

	/**
	 * Sets the x c g1132 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG1132 the x c g1132 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG1132(String XCG1132);

	/**
	 * Returns the x c g0033 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0033 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0033();

	/**
	 * Sets the x c g0033 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0033 the x c g0033 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0033(String XCG0033);

	/**
	 * Returns the x c g1033 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g1033 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG1033();

	/**
	 * Sets the x c g1033 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG1033 the x c g1033 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG1033(String XCG1033);

	/**
	 * Returns the x c g1133 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g1133 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG1133();

	/**
	 * Sets the x c g1133 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG1133 the x c g1133 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG1133(String XCG1133);

	/**
	 * Returns the x c g0034 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0034 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0034();

	/**
	 * Sets the x c g0034 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0034 the x c g0034 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0034(String XCG0034);

	/**
	 * Returns the x c g1034 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g1034 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG1034();

	/**
	 * Sets the x c g1034 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG1034 the x c g1034 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG1034(String XCG1034);

	/**
	 * Returns the x c g1134 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g1134 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG1134();

	/**
	 * Sets the x c g1134 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG1134 the x c g1134 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG1134(String XCG1134);

	/**
	 * Returns the x c g0035 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0035 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0035();

	/**
	 * Sets the x c g0035 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0035 the x c g0035 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0035(String XCG0035);

	/**
	 * Returns the x c g1035 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g1035 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG1035();

	/**
	 * Sets the x c g1035 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG1035 the x c g1035 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG1035(String XCG1035);

	/**
	 * Returns the x c g1135 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g1135 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG1135();

	/**
	 * Sets the x c g1135 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG1135 the x c g1135 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG1135(String XCG1135);

	/**
	 * Returns the x c g0036 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0036 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0036();

	/**
	 * Sets the x c g0036 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0036 the x c g0036 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0036(String XCG0036);

	/**
	 * Returns the x c g1036 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g1036 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG1036();

	/**
	 * Sets the x c g1036 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG1036 the x c g1036 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG1036(String XCG1036);

	/**
	 * Returns the x c g1136 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g1136 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG1136();

	/**
	 * Sets the x c g1136 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG1136 the x c g1136 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG1136(String XCG1136);

	/**
	 * Returns the x c g0037 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0037 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0037();

	/**
	 * Sets the x c g0037 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0037 the x c g0037 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0037(String XCG0037);

	/**
	 * Returns the x c g1037 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g1037 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG1037();

	/**
	 * Sets the x c g1037 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG1037 the x c g1037 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG1037(String XCG1037);

	/**
	 * Returns the x c g1137 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g1137 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG1137();

	/**
	 * Sets the x c g1137 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG1137 the x c g1137 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG1137(String XCG1137);

	/**
	 * Returns the x c g0038 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0038 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0038();

	/**
	 * Sets the x c g0038 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0038 the x c g0038 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0038(String XCG0038);

	/**
	 * Returns the x c g1038 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g1038 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG1038();

	/**
	 * Sets the x c g1038 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG1038 the x c g1038 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG1038(String XCG1038);

	/**
	 * Returns the x c g1138 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g1138 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG1138();

	/**
	 * Sets the x c g1138 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG1138 the x c g1138 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG1138(String XCG1138);

	/**
	 * Returns the x c g0039 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0039 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0039();

	/**
	 * Sets the x c g0039 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0039 the x c g0039 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0039(String XCG0039);

	/**
	 * Returns the x c g1039 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g1039 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG1039();

	/**
	 * Sets the x c g1039 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG1039 the x c g1039 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG1039(String XCG1039);

	/**
	 * Returns the x c g1139 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g1139 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG1139();

	/**
	 * Sets the x c g1139 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG1139 the x c g1139 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG1139(String XCG1139);

	/**
	 * Returns the x c g0040 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0040 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0040();

	/**
	 * Sets the x c g0040 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0040 the x c g0040 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0040(String XCG0040);

	/**
	 * Returns the x c g1040 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g1040 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG1040();

	/**
	 * Sets the x c g1040 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG1040 the x c g1040 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG1040(String XCG1040);

	/**
	 * Returns the x c g1140 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g1140 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG1140();

	/**
	 * Sets the x c g1140 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG1140 the x c g1140 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG1140(String XCG1140);

	/**
	 * Returns the x c g0041 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0041 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0041();

	/**
	 * Sets the x c g0041 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0041 the x c g0041 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0041(String XCG0041);

	/**
	 * Returns the x c g1041 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g1041 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG1041();

	/**
	 * Sets the x c g1041 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG1041 the x c g1041 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG1041(String XCG1041);

	/**
	 * Returns the x c g1141 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g1141 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG1141();

	/**
	 * Sets the x c g1141 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG1141 the x c g1141 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG1141(String XCG1141);

	/**
	 * Returns the x c g0042 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0042 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0042();

	/**
	 * Sets the x c g0042 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0042 the x c g0042 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0042(String XCG0042);

	/**
	 * Returns the x c g1042 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g1042 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG1042();

	/**
	 * Sets the x c g1042 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG1042 the x c g1042 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG1042(String XCG1042);

	/**
	 * Returns the x c g1142 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g1142 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG1142();

	/**
	 * Sets the x c g1142 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG1142 the x c g1142 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG1142(String XCG1142);

	/**
	 * Returns the x c g0043 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0043 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0043();

	/**
	 * Sets the x c g0043 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0043 the x c g0043 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0043(String XCG0043);

	/**
	 * Returns the x c g1043 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g1043 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG1043();

	/**
	 * Sets the x c g1043 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG1043 the x c g1043 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG1043(String XCG1043);

	/**
	 * Returns the x c g1143 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g1143 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG1143();

	/**
	 * Sets the x c g1143 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG1143 the x c g1143 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG1143(String XCG1143);

	/**
	 * Returns the x c g0044 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0044 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0044();

	/**
	 * Sets the x c g0044 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0044 the x c g0044 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0044(String XCG0044);

	/**
	 * Returns the x c g1044 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g1044 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG1044();

	/**
	 * Sets the x c g1044 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG1044 the x c g1044 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG1044(String XCG1044);

	/**
	 * Returns the x c g1144 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g1144 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG1144();

	/**
	 * Sets the x c g1144 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG1144 the x c g1144 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG1144(String XCG1144);

	/**
	 * Returns the x c g0045 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0045 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0045();

	/**
	 * Sets the x c g0045 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0045 the x c g0045 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0045(String XCG0045);

	/**
	 * Returns the x c g0046 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0046 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0046();

	/**
	 * Sets the x c g0046 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0046 the x c g0046 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0046(String XCG0046);

	/**
	 * Returns the x c g1047 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g1047 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG1047();

	/**
	 * Sets the x c g1047 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG1047 the x c g1047 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG1047(String XCG1047);

	/**
	 * Returns the x c g0047 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0047 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0047();

	/**
	 * Sets the x c g0047 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0047 the x c g0047 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0047(String XCG0047);

	/**
	 * Returns the x c g0048 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0048 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0048();

	/**
	 * Sets the x c g0048 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0048 the x c g0048 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0048(String XCG0048);

	/**
	 * Returns the x c g0049 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0049 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0049();

	/**
	 * Sets the x c g0049 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0049 the x c g0049 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0049(String XCG0049);

	/**
	 * Returns the x c g0050 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0050 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0050();

	/**
	 * Sets the x c g0050 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0050 the x c g0050 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0050(String XCG0050);

	/**
	 * Returns the x c g0051 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0051 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0051();

	/**
	 * Sets the x c g0051 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0051 the x c g0051 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0051(String XCG0051);

	/**
	 * Returns the x c g0052 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0052 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0052();

	/**
	 * Sets the x c g0052 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0052 the x c g0052 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0052(String XCG0052);

	/**
	 * Returns the x c g0053 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0053 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0053();

	/**
	 * Sets the x c g0053 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0053 the x c g0053 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0053(String XCG0053);

	/**
	 * Returns the x c g0054 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0054 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0054();

	/**
	 * Sets the x c g0054 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0054 the x c g0054 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0054(String XCG0054);

	/**
	 * Returns the x c g1054 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g1054 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG1054();

	/**
	 * Sets the x c g1054 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG1054 the x c g1054 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG1054(String XCG1054);

	/**
	 * Returns the x c g1154 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g1154 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG1154();

	/**
	 * Sets the x c g1154 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG1154 the x c g1154 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG1154(String XCG1154);

	/**
	 * Returns the x c g1254 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g1254 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG1254();

	/**
	 * Sets the x c g1254 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG1254 the x c g1254 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG1254(String XCG1254);

	/**
	 * Returns the x c g1354 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g1354 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG1354();

	/**
	 * Sets the x c g1354 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG1354 the x c g1354 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG1354(String XCG1354);

	/**
	 * Returns the x c g1454 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g1454 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG1454();

	/**
	 * Sets the x c g1454 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG1454 the x c g1454 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG1454(String XCG1454);

	/**
	 * Returns the x c g1554 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g1554 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG1554();

	/**
	 * Sets the x c g1554 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG1554 the x c g1554 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG1554(String XCG1554);

	/**
	 * Returns the x c g1654 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g1654 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG1654();

	/**
	 * Sets the x c g1654 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG1654 the x c g1654 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG1654(String XCG1654);

	/**
	 * Returns the x c g1754 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g1754 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG1754();

	/**
	 * Sets the x c g1754 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG1754 the x c g1754 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG1754(String XCG1754);

	/**
	 * Returns the x c g0055 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0055 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0055();

	/**
	 * Sets the x c g0055 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0055 the x c g0055 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0055(String XCG0055);

	/**
	 * Returns the x c g0056 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0056 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0056();

	/**
	 * Sets the x c g0056 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0056 the x c g0056 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0056(String XCG0056);

	/**
	 * Returns the x c g0057 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0057 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0057();

	/**
	 * Sets the x c g0057 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0057 the x c g0057 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0057(String XCG0057);

	/**
	 * Returns the x c g0058 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0058 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0058();

	/**
	 * Sets the x c g0058 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0058 the x c g0058 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0058(String XCG0058);

	/**
	 * Returns the x c g0059 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0059 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0059();

	/**
	 * Sets the x c g0059 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0059 the x c g0059 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0059(String XCG0059);

	/**
	 * Returns the x c g1059 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g1059 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG1059();

	/**
	 * Sets the x c g1059 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG1059 the x c g1059 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG1059(String XCG1059);

	/**
	 * Returns the x c g0060 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0060 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0060();

	/**
	 * Sets the x c g0060 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0060 the x c g0060 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0060(String XCG0060);

	/**
	 * Returns the x c g0061 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0061 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0061();

	/**
	 * Sets the x c g0061 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0061 the x c g0061 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0061(String XCG0061);

	/**
	 * Returns the x c g0062 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0062 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0062();

	/**
	 * Sets the x c g0062 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0062 the x c g0062 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0062(String XCG0062);

	/**
	 * Returns the x c g0063 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0063 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0063();

	/**
	 * Sets the x c g0063 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0063 the x c g0063 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0063(String XCG0063);

	/**
	 * Returns the x c g0064 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0064 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0064();

	/**
	 * Sets the x c g0064 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0064 the x c g0064 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0064(String XCG0064);

	/**
	 * Returns the x c g0065 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0065 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0065();

	/**
	 * Sets the x c g0065 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0065 the x c g0065 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0065(String XCG0065);

	/**
	 * Returns the x c g0066 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0066 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0066();

	/**
	 * Sets the x c g0066 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0066 the x c g0066 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0066(String XCG0066);

	/**
	 * Returns the x c g1066 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g1066 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG1066();

	/**
	 * Sets the x c g1066 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG1066 the x c g1066 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG1066(String XCG1066);

	/**
	 * Returns the x c g0067 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0067 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0067();

	/**
	 * Sets the x c g0067 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0067 the x c g0067 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0067(String XCG0067);

	/**
	 * Returns the x c g0068 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0068 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0068();

	/**
	 * Sets the x c g0068 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0068 the x c g0068 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0068(String XCG0068);

	/**
	 * Returns the x c g0069 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0069 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0069();

	/**
	 * Sets the x c g0069 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0069 the x c g0069 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0069(String XCG0069);

	/**
	 * Returns the x c g0070 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0070 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0070();

	/**
	 * Sets the x c g0070 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0070 the x c g0070 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0070(String XCG0070);

	/**
	 * Returns the x c g0071 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0071 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0071();

	/**
	 * Sets the x c g0071 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0071 the x c g0071 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0071(String XCG0071);

	/**
	 * Returns the x c g0072 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0072 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0072();

	/**
	 * Sets the x c g0072 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0072 the x c g0072 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0072(String XCG0072);

	/**
	 * Returns the x c g1072 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g1072 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG1072();

	/**
	 * Sets the x c g1072 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG1072 the x c g1072 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG1072(String XCG1072);

	/**
	 * Returns the x c g0073 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0073 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0073();

	/**
	 * Sets the x c g0073 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0073 the x c g0073 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0073(String XCG0073);

	/**
	 * Returns the x c g0074 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0074 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0074();

	/**
	 * Sets the x c g0074 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0074 the x c g0074 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0074(String XCG0074);

	/**
	 * Returns the x c g0075 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0075 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0075();

	/**
	 * Sets the x c g0075 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0075 the x c g0075 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0075(String XCG0075);

	/**
	 * Returns the x c g0076 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0076 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0076();

	/**
	 * Sets the x c g0076 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0076 the x c g0076 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0076(String XCG0076);

	/**
	 * Returns the x c g0077 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0077 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0077();

	/**
	 * Sets the x c g0077 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0077 the x c g0077 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0077(String XCG0077);

	/**
	 * Returns the x c g1077 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g1077 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG1077();

	/**
	 * Sets the x c g1077 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG1077 the x c g1077 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG1077(String XCG1077);

	/**
	 * Returns the x c g0078 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0078 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0078();

	/**
	 * Sets the x c g0078 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0078 the x c g0078 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0078(String XCG0078);

	/**
	 * Returns the x c g1078 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g1078 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG1078();

	/**
	 * Sets the x c g1078 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG1078 the x c g1078 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG1078(String XCG1078);

	/**
	 * Returns the x c g0079 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0079 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0079();

	/**
	 * Sets the x c g0079 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0079 the x c g0079 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0079(String XCG0079);

	/**
	 * Returns the x c g0080 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0080 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0080();

	/**
	 * Sets the x c g0080 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0080 the x c g0080 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0080(String XCG0080);

	/**
	 * Returns the x c g1080 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g1080 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG1080();

	/**
	 * Sets the x c g1080 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG1080 the x c g1080 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG1080(String XCG1080);

	/**
	 * Returns the x c g0081 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0081 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0081();

	/**
	 * Sets the x c g0081 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0081 the x c g0081 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0081(String XCG0081);

	/**
	 * Returns the x c g0082 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0082 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0082();

	/**
	 * Sets the x c g0082 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0082 the x c g0082 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0082(String XCG0082);

	/**
	 * Returns the x c g0083 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0083 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0083();

	/**
	 * Sets the x c g0083 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0083 the x c g0083 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0083(String XCG0083);

	/**
	 * Returns the x c g0084 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0084 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0084();

	/**
	 * Sets the x c g0084 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0084 the x c g0084 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0084(String XCG0084);

	/**
	 * Returns the x c g0085 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0085 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0085();

	/**
	 * Sets the x c g0085 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0085 the x c g0085 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0085(String XCG0085);

	/**
	 * Returns the x c g1085 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g1085 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG1085();

	/**
	 * Sets the x c g1085 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG1085 the x c g1085 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG1085(String XCG1085);

	/**
	 * Returns the x c g0086 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0086 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0086();

	/**
	 * Sets the x c g0086 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0086 the x c g0086 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0086(String XCG0086);

	/**
	 * Returns the x c g1086 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g1086 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG1086();

	/**
	 * Sets the x c g1086 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG1086 the x c g1086 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG1086(String XCG1086);

	/**
	 * Returns the x c g0087 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0087 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0087();

	/**
	 * Sets the x c g0087 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0087 the x c g0087 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0087(String XCG0087);

	/**
	 * Returns the x c g0088 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0088 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0088();

	/**
	 * Sets the x c g0088 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0088 the x c g0088 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0088(String XCG0088);

	/**
	 * Returns the x c g1088 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g1088 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG1088();

	/**
	 * Sets the x c g1088 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG1088 the x c g1088 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG1088(String XCG1088);

	/**
	 * Returns the x c g0089 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0089 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0089();

	/**
	 * Sets the x c g0089 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0089 the x c g0089 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0089(String XCG0089);

	/**
	 * Returns the x c g0090 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0090 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0090();

	/**
	 * Sets the x c g0090 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0090 the x c g0090 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0090(String XCG0090);

	/**
	 * Returns the x c g0091 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0091 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0091();

	/**
	 * Sets the x c g0091 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0091 the x c g0091 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0091(String XCG0091);

	/**
	 * Returns the x c g0092 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0092 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0092();

	/**
	 * Sets the x c g0092 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0092 the x c g0092 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0092(String XCG0092);

	/**
	 * Returns the x c g0093 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0093 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0093();

	/**
	 * Sets the x c g0093 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0093 the x c g0093 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0093(String XCG0093);

	/**
	 * Returns the x c g0094 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0094 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0094();

	/**
	 * Sets the x c g0094 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0094 the x c g0094 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0094(String XCG0094);

	/**
	 * Returns the x c g0095 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0095 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0095();

	/**
	 * Sets the x c g0095 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0095 the x c g0095 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0095(String XCG0095);

	/**
	 * Returns the x c g0096 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0096 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0096();

	/**
	 * Sets the x c g0096 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0096 the x c g0096 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0096(String XCG0096);

	/**
	 * Returns the x c g0097 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0097 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0097();

	/**
	 * Sets the x c g0097 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0097 the x c g0097 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0097(String XCG0097);

	/**
	 * Returns the x c g1097 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g1097 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG1097();

	/**
	 * Sets the x c g1097 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG1097 the x c g1097 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG1097(String XCG1097);

	/**
	 * Returns the x c g0098 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0098 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0098();

	/**
	 * Sets the x c g0098 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0098 the x c g0098 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0098(String XCG0098);

	/**
	 * Returns the x c g0099 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0099 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0099();

	/**
	 * Sets the x c g0099 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0099 the x c g0099 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0099(String XCG0099);

	/**
	 * Returns the x c g0100 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0100 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0100();

	/**
	 * Sets the x c g0100 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0100 the x c g0100 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0100(String XCG0100);

	/**
	 * Returns the x c g0101 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0101 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0101();

	/**
	 * Sets the x c g0101 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0101 the x c g0101 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0101(String XCG0101);

	/**
	 * Returns the x c g0102 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0102 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0102();

	/**
	 * Sets the x c g0102 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0102 the x c g0102 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0102(String XCG0102);

	/**
	 * Returns the x c g0103 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0103 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0103();

	/**
	 * Sets the x c g0103 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0103 the x c g0103 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0103(String XCG0103);

	/**
	 * Returns the x c g0104 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0104 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0104();

	/**
	 * Sets the x c g0104 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0104 the x c g0104 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0104(String XCG0104);

	/**
	 * Returns the x c g0105 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0105 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0105();

	/**
	 * Sets the x c g0105 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0105 the x c g0105 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0105(String XCG0105);

	/**
	 * Returns the x c g0106 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0106 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0106();

	/**
	 * Sets the x c g0106 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0106 the x c g0106 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0106(String XCG0106);

	/**
	 * Returns the x c g0107 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0107 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0107();

	/**
	 * Sets the x c g0107 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0107 the x c g0107 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0107(String XCG0107);

	/**
	 * Returns the x c g0108 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0108 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0108();

	/**
	 * Sets the x c g0108 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0108 the x c g0108 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0108(String XCG0108);

	/**
	 * Returns the x c g0109 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0109 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0109();

	/**
	 * Sets the x c g0109 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0109 the x c g0109 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0109(String XCG0109);

	/**
	 * Returns the x c g0110 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0110 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0110();

	/**
	 * Sets the x c g0110 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0110 the x c g0110 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0110(String XCG0110);

	/**
	 * Returns the x c g0111 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0111 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0111();

	/**
	 * Sets the x c g0111 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0111 the x c g0111 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0111(String XCG0111);

	/**
	 * Returns the x c g0112 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0112 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0112();

	/**
	 * Sets the x c g0112 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0112 the x c g0112 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0112(String XCG0112);

	/**
	 * Returns the x c g0113 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0113 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0113();

	/**
	 * Sets the x c g0113 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0113 the x c g0113 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0113(String XCG0113);

	/**
	 * Returns the x c g0114 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0114 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0114();

	/**
	 * Sets the x c g0114 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0114 the x c g0114 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0114(String XCG0114);

	/**
	 * Returns the x c g0115 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0115 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0115();

	/**
	 * Sets the x c g0115 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0115 the x c g0115 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0115(String XCG0115);

	/**
	 * Returns the x c g0116 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0116 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0116();

	/**
	 * Sets the x c g0116 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0116 the x c g0116 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0116(String XCG0116);

	/**
	 * Returns the x c g0117 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0117 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0117();

	/**
	 * Sets the x c g0117 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0117 the x c g0117 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0117(String XCG0117);

	/**
	 * Returns the x c g0118 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0118 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0118();

	/**
	 * Sets the x c g0118 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0118 the x c g0118 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0118(String XCG0118);

	/**
	 * Returns the x c g0119 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0119 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0119();

	/**
	 * Sets the x c g0119 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0119 the x c g0119 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0119(String XCG0119);

	/**
	 * Returns the x c g0120 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0120 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0120();

	/**
	 * Sets the x c g0120 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0120 the x c g0120 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0120(String XCG0120);

	/**
	 * Returns the x c g0121 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0121 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0121();

	/**
	 * Sets the x c g0121 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0121 the x c g0121 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0121(String XCG0121);

	/**
	 * Returns the x c g0122 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0122 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0122();

	/**
	 * Sets the x c g0122 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0122 the x c g0122 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0122(String XCG0122);

	/**
	 * Returns the x c g0123 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0123 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0123();

	/**
	 * Sets the x c g0123 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0123 the x c g0123 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0123(String XCG0123);

	/**
	 * Returns the x c g0124 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0124 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0124();

	/**
	 * Sets the x c g0124 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0124 the x c g0124 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0124(String XCG0124);

	/**
	 * Returns the x c g0125 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0125 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0125();

	/**
	 * Sets the x c g0125 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0125 the x c g0125 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0125(String XCG0125);

	/**
	 * Returns the x c g0126 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0126 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0126();

	/**
	 * Sets the x c g0126 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0126 the x c g0126 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0126(String XCG0126);

	/**
	 * Returns the x c g0127 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0127 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0127();

	/**
	 * Sets the x c g0127 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0127 the x c g0127 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0127(String XCG0127);

	/**
	 * Returns the x c g0128 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0128 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0128();

	/**
	 * Sets the x c g0128 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0128 the x c g0128 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0128(String XCG0128);

	/**
	 * Returns the x c g0238 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0238 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0238();

	/**
	 * Sets the x c g0238 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0238 the x c g0238 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0238(String XCG0238);

	/**
	 * Returns the x c g0239 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0239 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0239();

	/**
	 * Sets the x c g0239 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0239 the x c g0239 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0239(String XCG0239);

	/**
	 * Returns the x c g0240 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0240 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0240();

	/**
	 * Sets the x c g0240 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0240 the x c g0240 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0240(String XCG0240);

	/**
	 * Returns the x c g0241 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @return the x c g0241 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	@AutoEscape
	public String getXCG0241();

	/**
	 * Sets the x c g0241 of this t h o n g s o c h u n g c h i x e c o g i o i.
	 *
	 * @param XCG0241 the x c g0241 of this t h o n g s o c h u n g c h i x e c o g i o i
	 */
	public void setXCG0241(String XCG0241);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		vn.dtt.gt.dk.dao.nghiepvu.model.THONGSOCHUNGCHIXECOGIOI thongsochungchixecogioi);

	@Override
	public int hashCode();

	@Override
	public CacheModel<vn.dtt.gt.dk.dao.nghiepvu.model.THONGSOCHUNGCHIXECOGIOI> toCacheModel();

	@Override
	public vn.dtt.gt.dk.dao.nghiepvu.model.THONGSOCHUNGCHIXECOGIOI toEscapedModel();

	@Override
	public vn.dtt.gt.dk.dao.nghiepvu.model.THONGSOCHUNGCHIXECOGIOI toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}