/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dtt.gt.dk.dao.nghiepvu.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the VehicleCertificate service. Represents a row in the &quot;vr_vehicle_certificate&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.dtt.gt.dk.dao.nghiepvu.model.impl.VehicleCertificateModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.dtt.gt.dk.dao.nghiepvu.model.impl.VehicleCertificateImpl}.
 * </p>
 *
 * @author win_64
 * @see VehicleCertificate
 * @see vn.dtt.gt.dk.dao.nghiepvu.model.impl.VehicleCertificateImpl
 * @see vn.dtt.gt.dk.dao.nghiepvu.model.impl.VehicleCertificateModelImpl
 * @generated
 */
public interface VehicleCertificateModel extends BaseModel<VehicleCertificate> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a vehicle certificate model instance should use the {@link VehicleCertificate} interface instead.
	 */

	/**
	 * Returns the primary key of this vehicle certificate.
	 *
	 * @return the primary key of this vehicle certificate
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this vehicle certificate.
	 *
	 * @param primaryKey the primary key of this vehicle certificate
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this vehicle certificate.
	 *
	 * @return the ID of this vehicle certificate
	 */
	public long getId();

	/**
	 * Sets the ID of this vehicle certificate.
	 *
	 * @param id the ID of this vehicle certificate
	 */
	public void setId(long id);

	/**
	 * Returns the mt gateway of this vehicle certificate.
	 *
	 * @return the mt gateway of this vehicle certificate
	 */
	public long getMtGateway();

	/**
	 * Sets the mt gateway of this vehicle certificate.
	 *
	 * @param mtGateway the mt gateway of this vehicle certificate
	 */
	public void setMtGateway(long mtGateway);

	/**
	 * Returns the ho so thu tuc ID of this vehicle certificate.
	 *
	 * @return the ho so thu tuc ID of this vehicle certificate
	 */
	public long getHoSoThuTucId();

	/**
	 * Sets the ho so thu tuc ID of this vehicle certificate.
	 *
	 * @param hoSoThuTucId the ho so thu tuc ID of this vehicle certificate
	 */
	public void setHoSoThuTucId(long hoSoThuTucId);

	/**
	 * Returns the sequence no of this vehicle certificate.
	 *
	 * @return the sequence no of this vehicle certificate
	 */
	public long getSequenceNo();

	/**
	 * Sets the sequence no of this vehicle certificate.
	 *
	 * @param sequenceNo the sequence no of this vehicle certificate
	 */
	public void setSequenceNo(long sequenceNo);

	/**
	 * Returns the vehicle recordid of this vehicle certificate.
	 *
	 * @return the vehicle recordid of this vehicle certificate
	 */
	public long getVehicleRecordid();

	/**
	 * Sets the vehicle recordid of this vehicle certificate.
	 *
	 * @param vehicleRecordid the vehicle recordid of this vehicle certificate
	 */
	public void setVehicleRecordid(long vehicleRecordid);

	/**
	 * Returns the draft certificateid of this vehicle certificate.
	 *
	 * @return the draft certificateid of this vehicle certificate
	 */
	public long getDraftCertificateid();

	/**
	 * Sets the draft certificateid of this vehicle certificate.
	 *
	 * @param draftCertificateid the draft certificateid of this vehicle certificate
	 */
	public void setDraftCertificateid(long draftCertificateid);

	/**
	 * Returns the certificate recordid of this vehicle certificate.
	 *
	 * @return the certificate recordid of this vehicle certificate
	 */
	public long getCertificateRecordid();

	/**
	 * Sets the certificate recordid of this vehicle certificate.
	 *
	 * @param certificateRecordid the certificate recordid of this vehicle certificate
	 */
	public void setCertificateRecordid(long certificateRecordid);

	/**
	 * Returns the debit note ID of this vehicle certificate.
	 *
	 * @return the debit note ID of this vehicle certificate
	 */
	public long getDebitNoteId();

	/**
	 * Sets the debit note ID of this vehicle certificate.
	 *
	 * @param debitNoteId the debit note ID of this vehicle certificate
	 */
	public void setDebitNoteId(long debitNoteId);

	/**
	 * Returns the vehicle group ID of this vehicle certificate.
	 *
	 * @return the vehicle group ID of this vehicle certificate
	 */
	public long getVehicleGroupId();

	/**
	 * Sets the vehicle group ID of this vehicle certificate.
	 *
	 * @param vehicleGroupId the vehicle group ID of this vehicle certificate
	 */
	public void setVehicleGroupId(long vehicleGroupId);

	/**
	 * Returns the vehicle class of this vehicle certificate.
	 *
	 * @return the vehicle class of this vehicle certificate
	 */
	@AutoEscape
	public String getVehicleClass();

	/**
	 * Sets the vehicle class of this vehicle certificate.
	 *
	 * @param vehicleClass the vehicle class of this vehicle certificate
	 */
	public void setVehicleClass(String vehicleClass);

	/**
	 * Returns the technical spec code of this vehicle certificate.
	 *
	 * @return the technical spec code of this vehicle certificate
	 */
	@AutoEscape
	public String getTechnicalSpecCode();

	/**
	 * Sets the technical spec code of this vehicle certificate.
	 *
	 * @param technicalSpecCode the technical spec code of this vehicle certificate
	 */
	public void setTechnicalSpecCode(String technicalSpecCode);

	/**
	 * Returns the reference certificate no of this vehicle certificate.
	 *
	 * @return the reference certificate no of this vehicle certificate
	 */
	@AutoEscape
	public String getReferenceCertificateNo();

	/**
	 * Sets the reference certificate no of this vehicle certificate.
	 *
	 * @param referenceCertificateNo the reference certificate no of this vehicle certificate
	 */
	public void setReferenceCertificateNo(String referenceCertificateNo);

	/**
	 * Returns the safetytestreport no of this vehicle certificate.
	 *
	 * @return the safetytestreport no of this vehicle certificate
	 */
	@AutoEscape
	public String getSafetytestreportNo();

	/**
	 * Sets the safetytestreport no of this vehicle certificate.
	 *
	 * @param safetytestreportNo the safetytestreport no of this vehicle certificate
	 */
	public void setSafetytestreportNo(String safetytestreportNo);

	/**
	 * Returns the emissiontestreport no of this vehicle certificate.
	 *
	 * @return the emissiontestreport no of this vehicle certificate
	 */
	@AutoEscape
	public String getEmissiontestreportNo();

	/**
	 * Sets the emissiontestreport no of this vehicle certificate.
	 *
	 * @param emissiontestreportNo the emissiontestreport no of this vehicle certificate
	 */
	public void setEmissiontestreportNo(String emissiontestreportNo);

	/**
	 * Returns the copreport no of this vehicle certificate.
	 *
	 * @return the copreport no of this vehicle certificate
	 */
	@AutoEscape
	public String getCopreportNo();

	/**
	 * Sets the copreport no of this vehicle certificate.
	 *
	 * @param copreportNo the copreport no of this vehicle certificate
	 */
	public void setCopreportNo(String copreportNo);

	/**
	 * Returns the controlreport no of this vehicle certificate.
	 *
	 * @return the controlreport no of this vehicle certificate
	 */
	@AutoEscape
	public String getControlreportNo();

	/**
	 * Sets the controlreport no of this vehicle certificate.
	 *
	 * @param controlreportNo the controlreport no of this vehicle certificate
	 */
	public void setControlreportNo(String controlreportNo);

	/**
	 * Returns the vehicletype description of this vehicle certificate.
	 *
	 * @return the vehicletype description of this vehicle certificate
	 */
	@AutoEscape
	public String getVehicletypeDescription();

	/**
	 * Sets the vehicletype description of this vehicle certificate.
	 *
	 * @param vehicletypeDescription the vehicletype description of this vehicle certificate
	 */
	public void setVehicletypeDescription(String vehicletypeDescription);

	/**
	 * Returns the vehicle type of this vehicle certificate.
	 *
	 * @return the vehicle type of this vehicle certificate
	 */
	@AutoEscape
	public String getVehicleType();

	/**
	 * Sets the vehicle type of this vehicle certificate.
	 *
	 * @param vehicleType the vehicle type of this vehicle certificate
	 */
	public void setVehicleType(String vehicleType);

	/**
	 * Returns the enginetype description of this vehicle certificate.
	 *
	 * @return the enginetype description of this vehicle certificate
	 */
	@AutoEscape
	public String getEnginetypeDescription();

	/**
	 * Sets the enginetype description of this vehicle certificate.
	 *
	 * @param enginetypeDescription the enginetype description of this vehicle certificate
	 */
	public void setEnginetypeDescription(String enginetypeDescription);

	/**
	 * Returns the engine type of this vehicle certificate.
	 *
	 * @return the engine type of this vehicle certificate
	 */
	@AutoEscape
	public String getEngineType();

	/**
	 * Sets the engine type of this vehicle certificate.
	 *
	 * @param engineType the engine type of this vehicle certificate
	 */
	public void setEngineType(String engineType);

	/**
	 * Returns the mark as vehicle of this vehicle certificate.
	 *
	 * @return the mark as vehicle of this vehicle certificate
	 */
	public int getMarkAsVehicle();

	/**
	 * Sets the mark as vehicle of this vehicle certificate.
	 *
	 * @param markAsVehicle the mark as vehicle of this vehicle certificate
	 */
	public void setMarkAsVehicle(int markAsVehicle);

	/**
	 * Returns the trademark description of this vehicle certificate.
	 *
	 * @return the trademark description of this vehicle certificate
	 */
	@AutoEscape
	public String getTrademarkDescription();

	/**
	 * Sets the trademark description of this vehicle certificate.
	 *
	 * @param trademarkDescription the trademark description of this vehicle certificate
	 */
	public void setTrademarkDescription(String trademarkDescription);

	/**
	 * Returns the trade mark of this vehicle certificate.
	 *
	 * @return the trade mark of this vehicle certificate
	 */
	@AutoEscape
	public String getTradeMark();

	/**
	 * Sets the trade mark of this vehicle certificate.
	 *
	 * @param tradeMark the trade mark of this vehicle certificate
	 */
	public void setTradeMark(String tradeMark);

	/**
	 * Returns the commercial name of this vehicle certificate.
	 *
	 * @return the commercial name of this vehicle certificate
	 */
	@AutoEscape
	public String getCommercialName();

	/**
	 * Sets the commercial name of this vehicle certificate.
	 *
	 * @param commercialName the commercial name of this vehicle certificate
	 */
	public void setCommercialName(String commercialName);

	/**
	 * Returns the model code of this vehicle certificate.
	 *
	 * @return the model code of this vehicle certificate
	 */
	@AutoEscape
	public String getModelCode();

	/**
	 * Sets the model code of this vehicle certificate.
	 *
	 * @param modelCode the model code of this vehicle certificate
	 */
	public void setModelCode(String modelCode);

	/**
	 * Returns the production plant of this vehicle certificate.
	 *
	 * @return the production plant of this vehicle certificate
	 */
	@AutoEscape
	public String getProductionPlant();

	/**
	 * Sets the production plant of this vehicle certificate.
	 *
	 * @param productionPlant the production plant of this vehicle certificate
	 */
	public void setProductionPlant(String productionPlant);

	/**
	 * Returns the address of production plant of this vehicle certificate.
	 *
	 * @return the address of production plant of this vehicle certificate
	 */
	@AutoEscape
	public String getAddressOfProductionPlant();

	/**
	 * Sets the address of production plant of this vehicle certificate.
	 *
	 * @param addressOfProductionPlant the address of production plant of this vehicle certificate
	 */
	public void setAddressOfProductionPlant(String addressOfProductionPlant);

	/**
	 * Returns the emission standard of this vehicle certificate.
	 *
	 * @return the emission standard of this vehicle certificate
	 */
	@AutoEscape
	public String getEmissionStandard();

	/**
	 * Sets the emission standard of this vehicle certificate.
	 *
	 * @param emissionStandard the emission standard of this vehicle certificate
	 */
	public void setEmissionStandard(String emissionStandard);

	/**
	 * Returns the code number of this vehicle certificate.
	 *
	 * @return the code number of this vehicle certificate
	 */
	public long getCodeNumber();

	/**
	 * Sets the code number of this vehicle certificate.
	 *
	 * @param codeNumber the code number of this vehicle certificate
	 */
	public void setCodeNumber(long codeNumber);

	/**
	 * Returns the chassis number of this vehicle certificate.
	 *
	 * @return the chassis number of this vehicle certificate
	 */
	@AutoEscape
	public String getChassisNumber();

	/**
	 * Sets the chassis number of this vehicle certificate.
	 *
	 * @param chassisNumber the chassis number of this vehicle certificate
	 */
	public void setChassisNumber(String chassisNumber);

	/**
	 * Returns the engine number of this vehicle certificate.
	 *
	 * @return the engine number of this vehicle certificate
	 */
	@AutoEscape
	public String getEngineNumber();

	/**
	 * Sets the engine number of this vehicle certificate.
	 *
	 * @param engineNumber the engine number of this vehicle certificate
	 */
	public void setEngineNumber(String engineNumber);

	/**
	 * Returns the production year of this vehicle certificate.
	 *
	 * @return the production year of this vehicle certificate
	 */
	@AutoEscape
	public String getProductionYear();

	/**
	 * Sets the production year of this vehicle certificate.
	 *
	 * @param productionYear the production year of this vehicle certificate
	 */
	public void setProductionYear(String productionYear);

	/**
	 * Returns the country code of this vehicle certificate.
	 *
	 * @return the country code of this vehicle certificate
	 */
	@AutoEscape
	public String getCountryCode();

	/**
	 * Sets the country code of this vehicle certificate.
	 *
	 * @param countryCode the country code of this vehicle certificate
	 */
	public void setCountryCode(String countryCode);

	/**
	 * Returns the country name of this vehicle certificate.
	 *
	 * @return the country name of this vehicle certificate
	 */
	@AutoEscape
	public String getCountryName();

	/**
	 * Sets the country name of this vehicle certificate.
	 *
	 * @param countryName the country name of this vehicle certificate
	 */
	public void setCountryName(String countryName);

	/**
	 * Returns the current status of this vehicle certificate.
	 *
	 * @return the current status of this vehicle certificate
	 */
	@AutoEscape
	public String getCurrentStatus();

	/**
	 * Sets the current status of this vehicle certificate.
	 *
	 * @param currentStatus the current status of this vehicle certificate
	 */
	public void setCurrentStatus(String currentStatus);

	/**
	 * Returns the vehicle engine usage of this vehicle certificate.
	 *
	 * @return the vehicle engine usage of this vehicle certificate
	 */
	@AutoEscape
	public String getVehicleEngineUsage();

	/**
	 * Sets the vehicle engine usage of this vehicle certificate.
	 *
	 * @param vehicleEngineUsage the vehicle engine usage of this vehicle certificate
	 */
	public void setVehicleEngineUsage(String vehicleEngineUsage);

	/**
	 * Returns the vehicle color of this vehicle certificate.
	 *
	 * @return the vehicle color of this vehicle certificate
	 */
	@AutoEscape
	public String getVehicleColor();

	/**
	 * Sets the vehicle color of this vehicle certificate.
	 *
	 * @param vehicleColor the vehicle color of this vehicle certificate
	 */
	public void setVehicleColor(String vehicleColor);

	/**
	 * Returns the unit price of this vehicle certificate.
	 *
	 * @return the unit price of this vehicle certificate
	 */
	public double getUnitPrice();

	/**
	 * Sets the unit price of this vehicle certificate.
	 *
	 * @param unitPrice the unit price of this vehicle certificate
	 */
	public void setUnitPrice(double unitPrice);

	/**
	 * Returns the currency of this vehicle certificate.
	 *
	 * @return the currency of this vehicle certificate
	 */
	@AutoEscape
	public String getCurrency();

	/**
	 * Sets the currency of this vehicle certificate.
	 *
	 * @param currency the currency of this vehicle certificate
	 */
	public void setCurrency(String currency);

	/**
	 * Returns the remarks of this vehicle certificate.
	 *
	 * @return the remarks of this vehicle certificate
	 */
	@AutoEscape
	public String getRemarks();

	/**
	 * Sets the remarks of this vehicle certificate.
	 *
	 * @param remarks the remarks of this vehicle certificate
	 */
	public void setRemarks(String remarks);

	/**
	 * Returns the mark up status of this vehicle certificate.
	 *
	 * @return the mark up status of this vehicle certificate
	 */
	public long getMarkUpStatus();

	/**
	 * Sets the mark up status of this vehicle certificate.
	 *
	 * @param markUpStatus the mark up status of this vehicle certificate
	 */
	public void setMarkUpStatus(long markUpStatus);

	/**
	 * Returns the mark as sample of this vehicle certificate.
	 *
	 * @return the mark as sample of this vehicle certificate
	 */
	public int getMarkAsSample();

	/**
	 * Sets the mark as sample of this vehicle certificate.
	 *
	 * @param markAsSample the mark as sample of this vehicle certificate
	 */
	public void setMarkAsSample(int markAsSample);

	/**
	 * Returns the vehicleengine status of this vehicle certificate.
	 *
	 * @return the vehicleengine status of this vehicle certificate
	 */
	public long getVehicleengineStatus();

	/**
	 * Sets the vehicleengine status of this vehicle certificate.
	 *
	 * @param vehicleengineStatus the vehicleengine status of this vehicle certificate
	 */
	public void setVehicleengineStatus(long vehicleengineStatus);

	/**
	 * Returns the vehicleengine folder of this vehicle certificate.
	 *
	 * @return the vehicleengine folder of this vehicle certificate
	 */
	public long getVehicleengineFolder();

	/**
	 * Sets the vehicleengine folder of this vehicle certificate.
	 *
	 * @param vehicleengineFolder the vehicleengine folder of this vehicle certificate
	 */
	public void setVehicleengineFolder(long vehicleengineFolder);

	/**
	 * Returns the vehicle group initial ID of this vehicle certificate.
	 *
	 * @return the vehicle group initial ID of this vehicle certificate
	 */
	public long getVehicleGroupInitialId();

	/**
	 * Sets the vehicle group initial ID of this vehicle certificate.
	 *
	 * @param vehicleGroupInitialId the vehicle group initial ID of this vehicle certificate
	 */
	public void setVehicleGroupInitialId(long vehicleGroupInitialId);

	/**
	 * Returns the registered inspection ID of this vehicle certificate.
	 *
	 * @return the registered inspection ID of this vehicle certificate
	 */
	public long getRegisteredInspectionId();

	/**
	 * Sets the registered inspection ID of this vehicle certificate.
	 *
	 * @param registeredInspectionId the registered inspection ID of this vehicle certificate
	 */
	public void setRegisteredInspectionId(long registeredInspectionId);

	/**
	 * Returns the registered number of this vehicle certificate.
	 *
	 * @return the registered number of this vehicle certificate
	 */
	@AutoEscape
	public String getRegisteredNumber();

	/**
	 * Sets the registered number of this vehicle certificate.
	 *
	 * @param registeredNumber the registered number of this vehicle certificate
	 */
	public void setRegisteredNumber(String registeredNumber);

	/**
	 * Returns the importer code of this vehicle certificate.
	 *
	 * @return the importer code of this vehicle certificate
	 */
	@AutoEscape
	public String getImporterCode();

	/**
	 * Sets the importer code of this vehicle certificate.
	 *
	 * @param importerCode the importer code of this vehicle certificate
	 */
	public void setImporterCode(String importerCode);

	/**
	 * Returns the importer name of this vehicle certificate.
	 *
	 * @return the importer name of this vehicle certificate
	 */
	@AutoEscape
	public String getImporterName();

	/**
	 * Sets the importer name of this vehicle certificate.
	 *
	 * @param importerName the importer name of this vehicle certificate
	 */
	public void setImporterName(String importerName);

	/**
	 * Returns the importer address of this vehicle certificate.
	 *
	 * @return the importer address of this vehicle certificate
	 */
	@AutoEscape
	public String getImporterAddress();

	/**
	 * Sets the importer address of this vehicle certificate.
	 *
	 * @param importerAddress the importer address of this vehicle certificate
	 */
	public void setImporterAddress(String importerAddress);

	/**
	 * Returns the representative of this vehicle certificate.
	 *
	 * @return the representative of this vehicle certificate
	 */
	@AutoEscape
	public String getRepresentative();

	/**
	 * Sets the representative of this vehicle certificate.
	 *
	 * @param representative the representative of this vehicle certificate
	 */
	public void setRepresentative(String representative);

	/**
	 * Returns the phone of this vehicle certificate.
	 *
	 * @return the phone of this vehicle certificate
	 */
	@AutoEscape
	public String getPhone();

	/**
	 * Sets the phone of this vehicle certificate.
	 *
	 * @param phone the phone of this vehicle certificate
	 */
	public void setPhone(String phone);

	/**
	 * Returns the fax of this vehicle certificate.
	 *
	 * @return the fax of this vehicle certificate
	 */
	@AutoEscape
	public String getFax();

	/**
	 * Sets the fax of this vehicle certificate.
	 *
	 * @param fax the fax of this vehicle certificate
	 */
	public void setFax(String fax);

	/**
	 * Returns the email of this vehicle certificate.
	 *
	 * @return the email of this vehicle certificate
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this vehicle certificate.
	 *
	 * @param email the email of this vehicle certificate
	 */
	public void setEmail(String email);

	/**
	 * Returns the inspection date of this vehicle certificate.
	 *
	 * @return the inspection date of this vehicle certificate
	 */
	public Date getInspectionDate();

	/**
	 * Sets the inspection date of this vehicle certificate.
	 *
	 * @param inspectionDate the inspection date of this vehicle certificate
	 */
	public void setInspectionDate(Date inspectionDate);

	/**
	 * Returns the inspection site of this vehicle certificate.
	 *
	 * @return the inspection site of this vehicle certificate
	 */
	@AutoEscape
	public String getInspectionSite();

	/**
	 * Sets the inspection site of this vehicle certificate.
	 *
	 * @param inspectionSite the inspection site of this vehicle certificate
	 */
	public void setInspectionSite(String inspectionSite);

	/**
	 * Returns the inspection district code of this vehicle certificate.
	 *
	 * @return the inspection district code of this vehicle certificate
	 */
	@AutoEscape
	public String getInspectionDistrictCode();

	/**
	 * Sets the inspection district code of this vehicle certificate.
	 *
	 * @param inspectionDistrictCode the inspection district code of this vehicle certificate
	 */
	public void setInspectionDistrictCode(String inspectionDistrictCode);

	/**
	 * Returns the inspection province code of this vehicle certificate.
	 *
	 * @return the inspection province code of this vehicle certificate
	 */
	@AutoEscape
	public String getInspectionProvinceCode();

	/**
	 * Sets the inspection province code of this vehicle certificate.
	 *
	 * @param inspectionProvinceCode the inspection province code of this vehicle certificate
	 */
	public void setInspectionProvinceCode(String inspectionProvinceCode);

	/**
	 * Returns the inspection district of this vehicle certificate.
	 *
	 * @return the inspection district of this vehicle certificate
	 */
	@AutoEscape
	public String getInspectionDistrict();

	/**
	 * Sets the inspection district of this vehicle certificate.
	 *
	 * @param inspectionDistrict the inspection district of this vehicle certificate
	 */
	public void setInspectionDistrict(String inspectionDistrict);

	/**
	 * Returns the inspection province of this vehicle certificate.
	 *
	 * @return the inspection province of this vehicle certificate
	 */
	@AutoEscape
	public String getInspectionProvince();

	/**
	 * Sets the inspection province of this vehicle certificate.
	 *
	 * @param inspectionProvince the inspection province of this vehicle certificate
	 */
	public void setInspectionProvince(String inspectionProvince);

	/**
	 * Returns the confirmed inspection ID of this vehicle certificate.
	 *
	 * @return the confirmed inspection ID of this vehicle certificate
	 */
	public long getConfirmedInspectionId();

	/**
	 * Sets the confirmed inspection ID of this vehicle certificate.
	 *
	 * @param confirmedInspectionId the confirmed inspection ID of this vehicle certificate
	 */
	public void setConfirmedInspectionId(long confirmedInspectionId);

	/**
	 * Returns the inspection record ID of this vehicle certificate.
	 *
	 * @return the inspection record ID of this vehicle certificate
	 */
	public long getInspectionRecordId();

	/**
	 * Sets the inspection record ID of this vehicle certificate.
	 *
	 * @param inspectionRecordId the inspection record ID of this vehicle certificate
	 */
	public void setInspectionRecordId(long inspectionRecordId);

	/**
	 * Returns the inspection record no of this vehicle certificate.
	 *
	 * @return the inspection record no of this vehicle certificate
	 */
	@AutoEscape
	public String getInspectionRecordNo();

	/**
	 * Sets the inspection record no of this vehicle certificate.
	 *
	 * @param inspectionRecordNo the inspection record no of this vehicle certificate
	 */
	public void setInspectionRecordNo(String inspectionRecordNo);

	/**
	 * Returns the inspection date from of this vehicle certificate.
	 *
	 * @return the inspection date from of this vehicle certificate
	 */
	public Date getInspectionDateFrom();

	/**
	 * Sets the inspection date from of this vehicle certificate.
	 *
	 * @param inspectionDateFrom the inspection date from of this vehicle certificate
	 */
	public void setInspectionDateFrom(Date inspectionDateFrom);

	/**
	 * Returns the inspection date to of this vehicle certificate.
	 *
	 * @return the inspection date to of this vehicle certificate
	 */
	public Date getInspectionDateTo();

	/**
	 * Sets the inspection date to of this vehicle certificate.
	 *
	 * @param inspectionDateTo the inspection date to of this vehicle certificate
	 */
	public void setInspectionDateTo(Date inspectionDateTo);

	/**
	 * Returns the inspection mode of this vehicle certificate.
	 *
	 * @return the inspection mode of this vehicle certificate
	 */
	public long getInspectionMode();

	/**
	 * Sets the inspection mode of this vehicle certificate.
	 *
	 * @param inspectionMode the inspection mode of this vehicle certificate
	 */
	public void setInspectionMode(long inspectionMode);

	/**
	 * Returns the inspection mode description of this vehicle certificate.
	 *
	 * @return the inspection mode description of this vehicle certificate
	 */
	@AutoEscape
	public String getInspectionModeDescription();

	/**
	 * Sets the inspection mode description of this vehicle certificate.
	 *
	 * @param inspectionModeDescription the inspection mode description of this vehicle certificate
	 */
	public void setInspectionModeDescription(String inspectionModeDescription);

	/**
	 * Returns the confirmed result of this vehicle certificate.
	 *
	 * @return the confirmed result of this vehicle certificate
	 */
	public long getConfirmedResult();

	/**
	 * Sets the confirmed result of this vehicle certificate.
	 *
	 * @param confirmedResult the confirmed result of this vehicle certificate
	 */
	public void setConfirmedResult(long confirmedResult);

	/**
	 * Returns the confirmed result description of this vehicle certificate.
	 *
	 * @return the confirmed result description of this vehicle certificate
	 */
	@AutoEscape
	public String getConfirmedResultDescription();

	/**
	 * Sets the confirmed result description of this vehicle certificate.
	 *
	 * @param confirmedResultDescription the confirmed result description of this vehicle certificate
	 */
	public void setConfirmedResultDescription(String confirmedResultDescription);

	/**
	 * Returns the import custom declare date of this vehicle certificate.
	 *
	 * @return the import custom declare date of this vehicle certificate
	 */
	public Date getImportCustomDeclareDate();

	/**
	 * Sets the import custom declare date of this vehicle certificate.
	 *
	 * @param importCustomDeclareDate the import custom declare date of this vehicle certificate
	 */
	public void setImportCustomDeclareDate(Date importCustomDeclareDate);

	/**
	 * Returns the import custom declare no of this vehicle certificate.
	 *
	 * @return the import custom declare no of this vehicle certificate
	 */
	@AutoEscape
	public String getImportCustomDeclareNo();

	/**
	 * Sets the import custom declare no of this vehicle certificate.
	 *
	 * @param importCustomDeclareNo the import custom declare no of this vehicle certificate
	 */
	public void setImportCustomDeclareNo(String importCustomDeclareNo);

	/**
	 * Returns the corporation code of this vehicle certificate.
	 *
	 * @return the corporation code of this vehicle certificate
	 */
	@AutoEscape
	public String getCorporationCode();

	/**
	 * Sets the corporation code of this vehicle certificate.
	 *
	 * @param corporationCode the corporation code of this vehicle certificate
	 */
	public void setCorporationCode(String corporationCode);

	/**
	 * Returns the corporation name of this vehicle certificate.
	 *
	 * @return the corporation name of this vehicle certificate
	 */
	@AutoEscape
	public String getCorporationName();

	/**
	 * Sets the corporation name of this vehicle certificate.
	 *
	 * @param corporationName the corporation name of this vehicle certificate
	 */
	public void setCorporationName(String corporationName);

	/**
	 * Returns the inspector contact code of this vehicle certificate.
	 *
	 * @return the inspector contact code of this vehicle certificate
	 */
	@AutoEscape
	public String getInspectorContactCode();

	/**
	 * Sets the inspector contact code of this vehicle certificate.
	 *
	 * @param inspectorContactCode the inspector contact code of this vehicle certificate
	 */
	public void setInspectorContactCode(String inspectorContactCode);

	/**
	 * Returns the inspector name of this vehicle certificate.
	 *
	 * @return the inspector name of this vehicle certificate
	 */
	@AutoEscape
	public String getInspectorName();

	/**
	 * Sets the inspector name of this vehicle certificate.
	 *
	 * @param inspectorName the inspector name of this vehicle certificate
	 */
	public void setInspectorName(String inspectorName);

	/**
	 * Returns the certificate type of this vehicle certificate.
	 *
	 * @return the certificate type of this vehicle certificate
	 */
	public long getCertificateType();

	/**
	 * Sets the certificate type of this vehicle certificate.
	 *
	 * @param certificateType the certificate type of this vehicle certificate
	 */
	public void setCertificateType(long certificateType);

	/**
	 * Returns the certificate number of this vehicle certificate.
	 *
	 * @return the certificate number of this vehicle certificate
	 */
	@AutoEscape
	public String getCertificateNumber();

	/**
	 * Sets the certificate number of this vehicle certificate.
	 *
	 * @param certificateNumber the certificate number of this vehicle certificate
	 */
	public void setCertificateNumber(String certificateNumber);

	/**
	 * Returns the oldcertificate number of this vehicle certificate.
	 *
	 * @return the oldcertificate number of this vehicle certificate
	 */
	@AutoEscape
	public String getOldcertificateNumber();

	/**
	 * Sets the oldcertificate number of this vehicle certificate.
	 *
	 * @param oldcertificateNumber the oldcertificate number of this vehicle certificate
	 */
	public void setOldcertificateNumber(String oldcertificateNumber);

	/**
	 * Returns the sign date of this vehicle certificate.
	 *
	 * @return the sign date of this vehicle certificate
	 */
	public Date getSignDate();

	/**
	 * Sets the sign date of this vehicle certificate.
	 *
	 * @param signDate the sign date of this vehicle certificate
	 */
	public void setSignDate(Date signDate);

	/**
	 * Returns the stamp status of this vehicle certificate.
	 *
	 * @return the stamp status of this vehicle certificate
	 */
	public long getStampStatus();

	/**
	 * Sets the stamp status of this vehicle certificate.
	 *
	 * @param stampStatus the stamp status of this vehicle certificate
	 */
	public void setStampStatus(long stampStatus);

	/**
	 * Returns the certificate status of this vehicle certificate.
	 *
	 * @return the certificate status of this vehicle certificate
	 */
	@AutoEscape
	public String getCertificateStatus();

	/**
	 * Sets the certificate status of this vehicle certificate.
	 *
	 * @param certificateStatus the certificate status of this vehicle certificate
	 */
	public void setCertificateStatus(String certificateStatus);

	/**
	 * Returns the digital issued of this vehicle certificate.
	 *
	 * @return the digital issued of this vehicle certificate
	 */
	public long getDigitalIssued();

	/**
	 * Sets the digital issued of this vehicle certificate.
	 *
	 * @param digitalIssued the digital issued of this vehicle certificate
	 */
	public void setDigitalIssued(long digitalIssued);

	/**
	 * Returns the markup safe test of this vehicle certificate.
	 *
	 * @return the markup safe test of this vehicle certificate
	 */
	public long getMarkupSafeTest();

	/**
	 * Sets the markup safe test of this vehicle certificate.
	 *
	 * @param markupSafeTest the markup safe test of this vehicle certificate
	 */
	public void setMarkupSafeTest(long markupSafeTest);

	/**
	 * Returns the markup emission test of this vehicle certificate.
	 *
	 * @return the markup emission test of this vehicle certificate
	 */
	public long getMarkupEmissionTest();

	/**
	 * Sets the markup emission test of this vehicle certificate.
	 *
	 * @param markupEmissionTest the markup emission test of this vehicle certificate
	 */
	public void setMarkupEmissionTest(long markupEmissionTest);

	/**
	 * Returns the markup control of this vehicle certificate.
	 *
	 * @return the markup control of this vehicle certificate
	 */
	public long getMarkupControl();

	/**
	 * Sets the markup control of this vehicle certificate.
	 *
	 * @param markupControl the markup control of this vehicle certificate
	 */
	public void setMarkupControl(long markupControl);

	/**
	 * Returns the attached file of this vehicle certificate.
	 *
	 * @return the attached file of this vehicle certificate
	 */
	public long getAttachedFile();

	/**
	 * Sets the attached file of this vehicle certificate.
	 *
	 * @param attachedFile the attached file of this vehicle certificate
	 */
	public void setAttachedFile(long attachedFile);

	/**
	 * Returns the inspector organization of this vehicle certificate.
	 *
	 * @return the inspector organization of this vehicle certificate
	 */
	@AutoEscape
	public String getInspectorOrganization();

	/**
	 * Sets the inspector organization of this vehicle certificate.
	 *
	 * @param inspectorOrganization the inspector organization of this vehicle certificate
	 */
	public void setInspectorOrganization(String inspectorOrganization);

	/**
	 * Returns the inspector division of this vehicle certificate.
	 *
	 * @return the inspector division of this vehicle certificate
	 */
	@AutoEscape
	public String getInspectorDivision();

	/**
	 * Sets the inspector division of this vehicle certificate.
	 *
	 * @param inspectorDivision the inspector division of this vehicle certificate
	 */
	public void setInspectorDivision(String inspectorDivision);

	/**
	 * Returns the inspector sign name of this vehicle certificate.
	 *
	 * @return the inspector sign name of this vehicle certificate
	 */
	@AutoEscape
	public String getInspectorSignName();

	/**
	 * Sets the inspector sign name of this vehicle certificate.
	 *
	 * @param inspectorSignName the inspector sign name of this vehicle certificate
	 */
	public void setInspectorSignName(String inspectorSignName);

	/**
	 * Returns the inspector sign title of this vehicle certificate.
	 *
	 * @return the inspector sign title of this vehicle certificate
	 */
	@AutoEscape
	public String getInspectorSignTitle();

	/**
	 * Sets the inspector sign title of this vehicle certificate.
	 *
	 * @param inspectorSignTitle the inspector sign title of this vehicle certificate
	 */
	public void setInspectorSignTitle(String inspectorSignTitle);

	/**
	 * Returns the inspector sign place of this vehicle certificate.
	 *
	 * @return the inspector sign place of this vehicle certificate
	 */
	@AutoEscape
	public String getInspectorSignPlace();

	/**
	 * Sets the inspector sign place of this vehicle certificate.
	 *
	 * @param inspectorSignPlace the inspector sign place of this vehicle certificate
	 */
	public void setInspectorSignPlace(String inspectorSignPlace);

	/**
	 * Returns the inspector sign date of this vehicle certificate.
	 *
	 * @return the inspector sign date of this vehicle certificate
	 */
	public Date getInspectorSignDate();

	/**
	 * Sets the inspector sign date of this vehicle certificate.
	 *
	 * @param inspectorSignDate the inspector sign date of this vehicle certificate
	 */
	public void setInspectorSignDate(Date inspectorSignDate);

	/**
	 * Returns the dossier date of this vehicle certificate.
	 *
	 * @return the dossier date of this vehicle certificate
	 */
	public Date getDossierDate();

	/**
	 * Sets the dossier date of this vehicle certificate.
	 *
	 * @param dossierDate the dossier date of this vehicle certificate
	 */
	public void setDossierDate(Date dossierDate);

	/**
	 * Returns the filedangkykiemtra ID of this vehicle certificate.
	 *
	 * @return the filedangkykiemtra ID of this vehicle certificate
	 */
	public long getFiledangkykiemtraId();

	/**
	 * Sets the filedangkykiemtra ID of this vehicle certificate.
	 *
	 * @param filedangkykiemtraId the filedangkykiemtra ID of this vehicle certificate
	 */
	public void setFiledangkykiemtraId(long filedangkykiemtraId);

	/**
	 * Returns the filebienbankiemtra ID of this vehicle certificate.
	 *
	 * @return the filebienbankiemtra ID of this vehicle certificate
	 */
	public long getFilebienbankiemtraId();

	/**
	 * Sets the filebienbankiemtra ID of this vehicle certificate.
	 *
	 * @param filebienbankiemtraId the filebienbankiemtra ID of this vehicle certificate
	 */
	public void setFilebienbankiemtraId(long filebienbankiemtraId);

	/**
	 * Returns the filechungchi ID of this vehicle certificate.
	 *
	 * @return the filechungchi ID of this vehicle certificate
	 */
	public long getFilechungchiId();

	/**
	 * Sets the filechungchi ID of this vehicle certificate.
	 *
	 * @param filechungchiId the filechungchi ID of this vehicle certificate
	 */
	public void setFilechungchiId(long filechungchiId);

	/**
	 * Returns the filebaocaotnantoan ID of this vehicle certificate.
	 *
	 * @return the filebaocaotnantoan ID of this vehicle certificate
	 */
	public long getFilebaocaotnantoanId();

	/**
	 * Sets the filebaocaotnantoan ID of this vehicle certificate.
	 *
	 * @param filebaocaotnantoanId the filebaocaotnantoan ID of this vehicle certificate
	 */
	public void setFilebaocaotnantoanId(long filebaocaotnantoanId);

	/**
	 * Returns the filebaocaotnkhithai ID of this vehicle certificate.
	 *
	 * @return the filebaocaotnkhithai ID of this vehicle certificate
	 */
	public long getFilebaocaotnkhithaiId();

	/**
	 * Sets the filebaocaotnkhithai ID of this vehicle certificate.
	 *
	 * @param filebaocaotnkhithaiId the filebaocaotnkhithai ID of this vehicle certificate
	 */
	public void setFilebaocaotnkhithaiId(long filebaocaotnkhithaiId);

	/**
	 * Returns the fileketluangiamdinh ID of this vehicle certificate.
	 *
	 * @return the fileketluangiamdinh ID of this vehicle certificate
	 */
	public long getFileketluangiamdinhId();

	/**
	 * Sets the fileketluangiamdinh ID of this vehicle certificate.
	 *
	 * @param fileketluangiamdinhId the fileketluangiamdinh ID of this vehicle certificate
	 */
	public void setFileketluangiamdinhId(long fileketluangiamdinhId);

	/**
	 * Returns the synch date of this vehicle certificate.
	 *
	 * @return the synch date of this vehicle certificate
	 */
	public Date getSynchDate();

	/**
	 * Sets the synch date of this vehicle certificate.
	 *
	 * @param SynchDate the synch date of this vehicle certificate
	 */
	public void setSynchDate(Date SynchDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(VehicleCertificate vehicleCertificate);

	@Override
	public int hashCode();

	@Override
	public CacheModel<VehicleCertificate> toCacheModel();

	@Override
	public VehicleCertificate toEscapedModel();

	@Override
	public VehicleCertificate toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}